### ISSUE TITLE
Don't automatically test indexers/notifications/download clients on update when previously tested

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1028]
If we know that it previously worked (when it was added), we should not try to test it.

If the thingy is added disabled we don't test it, but we should consider testing it on update if it wasn't previously tested successfully.

**Comment by Renegade605** [comment]
Maybe a good way to accomplish that is 1) If we haven't changed anything since we opened the settings or last hit test, don't test on save, and 2) If we DID change something before we hit save, but then the test fails, give us the option to force it to accept the change and save it anyway. This should cut down on unnecessary tests and give users who know what they're doing a way around the mandatory test without encouraging everyone to save without testing as you expressed concern about on the referenced issue.

(I've run into this problem when I went to adjust the notification time for Plex Home Theatre, but the client wasn't running at the time.)
