### ISSUE TITLE
Sonarr recognises the series folder but will not accept the files - fix needed

### ISSUE THREAD

**Issue by Woozy-one** [Sonarr/Sonarr#1040]
I have just installed and am setting up sonarr, I have quite a lot of TV shows which I have accumulated previously. Most have imported fine but some are not being recognised. This specific example is American Pickers, which Sonarr recognises but It will not accept the episodes I have. Is there a way to force it to see the episodes ?

**Comment by markus101** [comment]
Please use the forums for support.

This is likely die tobhow they are numbered, they need to be numbered in the same way Sonarr lists them, otherwise you will need to re-import the files form another location and have Sonarr sort them because they are numbered wrong (in the numbering scheme the release groups use).
