### ISSUE TITLE
Questions about how Sonarr is hosted

### ISSUE THREAD

**Issue by tidusjar** [Sonarr/Sonarr#1065]
Hello,

I am wondering if you could point me in the right direction to how Sonarr is being hosted without IIS being involved? I would like to do something similar in one of my projects.

Thanks.

**Comment by kayone** [comment]
We use Nancy and Owin as a server, take a look at https://github.com/NancyFx/Nancy/wiki/Hosting-nancy-with-owin#katana---httplistener-selfhost

current version of sonnar uses an older version of Owin since the new version requires .NET 4.5, but depending on your project you should consider using the latest version.
