### ISSUE TITLE
Better documentation for the API

### ISSUE THREAD

**Issue by ipsq** [Sonarr/Sonarr#1089]
[This article](https://github.com/Sonarr/Sonarr/wiki/Release-Push) is not well documented. Could this be clarified?

**Comment by markus101** [comment]
What information is missing?

**Comment by markus101** [comment]
If there is something we should add, please let us know.

**Comment by Dosk3n** [comment]
I agree that better API documentation is needed. Even if you provided demo api requests. I say this because currently I cant figure out how to make a call to the API using the api without the header. Your documentation says to use the API key in a query string but that is not enough as do you want us to put api?query=APIKEY or api/APIKEY/system/status or api//system/status/APIKEY . Neither works but after reading all the documentation I still have not found the answer while sickbeards api provides examples and took seconds to learn.

**Comment by Taloth** [comment]
Edited the wiki for ya: "using the apikey query string" to "using the &apikey= query string."

**Comment by Dosk3n** [comment]
Thank you Taloth. 

This has helped, I think if you added an example such as http://host:port/api/system/status?apikey=YOURAPIKEY then this would help people know the structure for all the api calls.

Thanks again though, got it working.
