### ISSUE TITLE
More renaming options

### ISSUE THREAD

**Issue by Toxic-Waste-** [Sonarr/Sonarr#1107]
Hi,

I was wondering if it would be possible to add more customization to the renaming options of Sonarr. I would like to keep the name intact (of the release group) and scrap all the other stuff. So basically an episode filename should look like this:

"Arrow.S04E11.720p.HDTV.x264-DIMENSION.mkv"

Sometimes releases get an extra attachment like [ettv] after the filename, or other things are added. Capitals might be different (X264 versus x264 f.e.). Is it possible that sonarr strips and changes those capticals?

If I use the options I get from Sonarr right now, I have noticed that for example, Sonarr changes the 720p.HDTV to HDTV.720p to give one example

I also noticed, when I download from usenet that give the files random strings as name, and I tell sonarr to rename to the original file, nothing changes, am I using it incorrectly?

So is it possible to add more customization or am I asking too much? :)

**Comment by markus101** [comment]
You can change the renaming Sonarr uses for different qualities on the quality settings page. You can also opt to use the file name or the release name when renaming if you want names that the release groups use, you'll need to play with the options that are available because the usenet release names will cause issues in some cases.

We're not looking to add further customization to naming at this time.
