### ISSUE TITLE
proxypass issue - loading or missing pictures

### ISSUE THREAD

**Issue by userdocs** [Sonarr/Sonarr#1117]
I successfully proxypass sonar in a linux environment using nginx and it appeared to work fine until:

I add some indexers and then a tv show. Now it won't load unless I use the URL:PORT format.

What i noticed about this issue is that there are two possible outcomes.

1: Sonarr background loads and the loading dots run left to right and the only other thing seen on screen is `Sonarr .ver` at the bottom.

If I tweak the proxypass

2: I get the central square of sonarr loading but none of the icons and menu pictures load.

Conclusion: I don't think the proxypass is the issue and that scenario 1 is actually the bug caused by adding an idexer + tv show. Scenario two is an incorrect proxypass. The proxypass works flawlessy to configure sonarr until a tvshow was added.

Is there a bug/conflict created that did no exist before adding an indexer + tv show?

**Comment by markus101** [comment]
Please use the forums for support.

A number of people have nginx configured as a reverse proxy for Sonarr without that issue, adding a series/indexer does not change how Sonarr loads the UI though.

**Comment by userdocs** [comment]
I think it was pretty stupid to close it that swiftly with no validation of the issue.

**Comment by markus101** [comment]
Until there is validation its a support issue, which we use the forums for.

**Comment by markus101** [comment]
Since you wanted validation, this config works perfectly, including adding an indexer and series.

```
server {
  listen       80 default_server;

  location / {
    proxy_pass        http://localhost:8989;
    proxy_set_header  Host localhost;

    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto $scheme;
  }
}
```

**Comment by userdocs** [comment]
except I have now confirmed it is a nginx + basic auth issue that does not occur when using the form method. the issue returns and persists using basic auth.

If you had asked some questions instead of reacting like someone hurt your feelings you might have got somewhere faster. I am not here to babysit your feelings.

**Comment by markus101** [comment]
I told you to use the forums for support, because thats where we do support and ask questions, try to figure out your setup, etc. Instead you decided my response was stupid, let me know that and didn't open a thread on the forums. Since I was genuinely curious and I ran some tests during my lunch break and concluded everything was working, gave you a cheeky response and moved on. Could it have been less cheeky, absolutely, would that have changed anything and made me ask questions, nope, thats what we use the forums for.

I enabled basic auth in Sonarr and retested using the same config as above and everything is working as expected.

In case 1 above it sounds like your proxy isn't passing the basic auth request to the browser, in case number 2 it sounds like the initial authentication response is passed back to Sonarr from nginx, but nothing else is (the series information loads because thats done through API key authentication). The issue lies with your nginx configuration, not Sonarr, if you post in the forums maybe someone can assist.
