### ISSUE TITLE
Integrate generic aggregated search capability

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#1128]
Just so the user can search for arbitrary text on the configured indexers (tv categories only) and send it to the download client.
Sonarr wouldn't have to associate it with a series/episode, it's just so the user doesn't have to go to each indexer's website.

**Comment by croon** [comment]
I noticed this being added to the 3.x milestone. I'm however unsure about the request:

Is this asking for a "front page" search functionality not associated with anything? "Sonarr wouldn't have to associate it with a series/episode"

Because if so, issue #1736 is asking for something else, namely Show X, episode Y manual search. When I can't find anything with manual search, I can input free text that I know will yield a result not normally associated with that episode (often the case with specials), and since I found it through that episode's manual/free text search that download would automatically be associated with that episode.

It would be tremendously useful over the current case of:

1) Going through several indexers manually to find the episode.
2) Download it.
3) Rename it to fit Sonarrs/theTVDB's convention.
4) Put it in a folder where Sonarr can pick it up.

New flow when regular auto/manual search fails:
1) Free text search "Show Y special 2017".
2) Click download on the correct match.
( 3) Sonarr handles it like a regular match.)

This is what I'm imagining would be a good implementation for me, but is this what the original request meant? I think this is what #1736 meant at least.

**Comment by master0044657** [comment]
Is someone working in this.? It would be an awsome feature

**Comment by xinseo** [comment]
Any progress on this? This would be extremely helpful for power users.

**Comment by CTalvio** [comment]
I want this so bad as I have several shows that do not have up to date info on alternate titles on thexem.de (some really old animes) and the fact that shows like Panty & Stocking get searched with the word "and" instead of "&" which screws with trackers that only accept exact search terms.

**Comment by Neolel** [comment]
I would like this as well. Just today, I have encountered a problem which could have been solved easily by having this exact feature.

**Comment by bakerboy448** [comment]
a simple +1 on the OP would suffice

comments indicating "me too" or "I want this too" and other not productive comments are extremely frowned upon

**Comment by louman** [comment]
Just like yours? Your comment has created two more useless comments so far ;)

**Comment by markus101** [comment]
No short term plans for this one.

**Comment by FazalAAli** [comment]
Would it be possible to add it to a long term roadmap if it is not possible in the short term? Clearly there is a huge need for this as it is not always possible to update the indexers or tv databases

**Comment by FazalAAli** [comment]
For anyone looking for a workaround, [NZBHydra2](https://github.com/theotherp/nzbhydra2) has support for reformatting search queries (going into the indexer) and reformatting results (out of indexer) as of version 4.7.0. It's an extra service you have to host, if you're not already, but the feature works great and is a necessity for foreign language viewers like me.

**Comment by AgeManning** [comment]
I know this issue is closed. But I think its a useful feature and implemented a version in #8132
