### ISSUE TITLE
Settings | Connect | Connections | Pushbullet - 'on rename' not selectable 

### ISSUE THREAD

**Issue by tmills1073** [Sonarr/Sonarr#1133]
In the Connect menu for Pushbullet, I am unable to select the option to trigger a notification on episode rename.  I'd rather have a notification when the processing is completed, as opposed to just downloaded.

**Comment by markus101** [comment]
On Rename is triggered when one or more existing files is renamed, On Download is triggered when the episode is imported (and renamed if applicable).

**Comment by tmills1073** [comment]
Thanks @markus101  - sorry I wasn't clear.  My issue is that the 'on rename' slider button is not selectable.  I can slide the other buttons, but not this specific one - it's greyed out.
 
![pushbullet01](https://cloud.githubusercontent.com/assets/15236550/12953070/ebb0f5c0-cfe6-11e5-953e-bb25f2a7431d.png)

**Comment by markus101** [comment]
You don't need to open another issue.

I knew what you were referring to. There is no need to enable On Rename since its only triggered when you manually rename files and is only useful for connections that update a library (Plex Media Server, Kodi, etc), `On Download` is triggered when processing is complete (after a file finishes downloading and is imported).
