### ISSUE TITLE
Unable to add existing show folder if it has brackets?

### ISSUE THREAD

**Issue by CyberMew** [Sonarr/Sonarr#1152]
Getting the following error: `Path is already configured as a root folder`
for `The Flash (2014)`

However, other shows don't have this problem. I press the `+` Add button and it disappears. Not for The Flash.

**Comment by Taloth** [comment]
Not sure how you jumped to the 'brackets' conclusion... But the problem is that the path has previously been used as 'root folder', probably by selecting it as folder during Import Existing.

Go to Series->Add Series->Import Existing, you'll see the root folders at the bottom. Ensure Flash isn't one of them.
Then go to Series->Series Editor, sort by Path, ensure Flash isn't one of em.
