### ISSUE TITLE
11.22.63 show not recognized after renaming

### ISSUE THREAD

**Issue by gac123** [Sonarr/Sonarr#1153]
let's say i would reencode files and rename those to reflect what it has been reencoded to
for this particular tv show called "11.22.63" Sonarr would recognize "11.22.63.S01E01.720p.HDTV.x264-DIMENSION[brassetv].mkv" but not "11.22.63.S01E01.720p.HDTV.x265.10bit.opus-DIMENSION[brassetv].mkv"

even though that file would be in the corresponding tv show folder, once it has this different, sonarr would mark it "episode missing from disk"
this would not be an issue with other shows, for example following are recognized:
filename - sonarr recog state
30.Rock.S01E01.Pilot.WEBDL-720p.x265.10bit.opus.mkv - WEBDL-720P
Billions.S01E03.720p.HDTV.x265.10bit.opus-AVS - HDTV-720P

thanks for your time!

**Comment by markus101** [comment]
Sonarr can't actually parse either of those titles properly, both are getting handled with the anime parser due to the `[brassetv]` at the end.

There isn't a quick solution to this besides renaming it to drop that, but something we'll be looking at improving with a major parsing overhaul.

https://github.com/Sonarr/Sonarr/issues/457
