### ISSUE TITLE
Add missing renaming tokens to UI

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1155]
There are probably more, but `{Quality Proper}` is missing.

If there are some we don't want to include (super advanced maybe?) then we should have a wiki page for them all.

**Comment by Taloth** [comment]
I vote for the wiki. Listing the all is overly complicated.

**Comment by thezoggy** [comment]
just have to be mindful of version changes that reflect in different tokens/actions.

**Comment by Toxic-Waste-** [comment]
Is it also possible to add a {Quality Repack}, as some groups use this instead of a proper and it changes the name of the file (which is not always handy when looking for subtitles for example..)

I have also noticed that the Release group is picked up wrong by the renamer at times, should I make a seperate ticket for that or does it fit here?

**Comment by thezoggy** [comment]
why not just use the original name if your trying to rely on that for sub searches? instead of trying to rebuild the original name out of tokens..

**Comment by markus101** [comment]
@Toxic-Waste- Sonarr doesn't treat them any differently internally, once its parsed it doesn't know whether its a repack or a proper so that can't be supported at this time. At the moment its not something we plan to support.

**Comment by Toxic-Waste-** [comment]
@thezoggy because it doesn't work for me, if they name is obfuscated, sonarr can't use the original name (or I am using it incorrectly), if there is any way to get the original scenename without all the other stuff, I'd love to hear it but I can't seem to get it to work

**Comment by markus101** [comment]
`{Original Title}` should do it, turning off renaming or using `{Original FileName}` will use the filename at the time of import, but `{Original Title}` will use the folder name/release name.

**Comment by Toxic-Waste-** [comment]
@markus101 I will try this one, thank you :) where exactly does he get the Original Title from? Is it the nzb name?

**Comment by markus101** [comment]
Yes, NZB name if available (using CDH to import).

**Comment by Toxic-Waste-** [comment]
@markus101 , I have been playing around with this setting and it does indeed use the nzb name. However I think I have found a bug, because when I put it on Original Title, and I put the "Rename Episode" to no, it still seems to rename it on import, is it supposed to? I use completed downloaded handling. If you want I can provide logs as proof

**Comment by markus101** [comment]
Actually we're using `Original Title` when renaming is off, which prefers the NZB/torrent name over the file name to deal with the obfuscated file names, if the indexer changes that for display purposes it would cause Sonarr to rename it.

**Comment by Toxic-Waste-** [comment]
@markus101 so when you use completed downloading handling, there is no way sonarr won't rename the file? I actually made a sabnzbd post processing script that names the files exactly how I like, just to see sonarr rename them on the import :p 

I know I'm a royal pain in the ass, but there are a couple of things sonarr renaming doesn't do, that I would like to see. I've also seen it miss on renames (taking Obfuscated as releasegroup for example, because it's the last word behind a hyphen in the filename I suppose) or lack of Repack and Real tags

**Comment by markus101** [comment]
`Original FIleName` will take the file name exactly as is and use it, if its obfuscated it will be obfuscated though.

**Comment by Toxic-Waste-** [comment]
will try that tonight, now I will shut up, thank you a lot @markus101

**Comment by markus101** [comment]
All naming options will be visible in the v3 UI.
