### ISSUE TITLE
Show Scene Numbering on Manual Search

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1156]
Right now we show the TVDB numbering at the top and search for something else, but we should let the user know what we're actually searching for.

**Comment by markus101** [comment]
Instead of simply showing the information the client is aware of we should create a `SearchCriteriaBuilder` and return that with the results, that way it would work for any search type including, standard, daily, anime or a full season (https://github.com/Sonarr/Sonarr/issues/266)

**Comment by lps-rocks** [comment]
I'm running across this more often - can this please be addressed since its over 2 years old? Realistically the user should be given the option to enable or disable scene numbering based on 

Typically Scene releases will use the (broken) scene numbering but P2P groups will use the correct episode number. This is becoming more common with WEB-DLs across more trackers as they embrace internal release groups and P2P groups.

**Comment by markus101** [comment]
This has been shown in Interactive search for a while, closing.
