### ISSUE TITLE
Automating Sonarr setup with chef - authentication/user storage questions

### ISSUE THREAD

**Issue by elijah** [Sonarr/Sonarr#1164]
Hi guys,

I'm working on automating my Sonarr setup with Chef - that's all working fine, but I have some questions.

Having set my authentication type to Forms - I discover that the storage of username and passwords was at some point moved into the nzbdrone.db sqlite3 database.  That's all well and good - very likely better for everyone.

What I don't know yet - and my C# is a little weak for reading the src directory and figuring out where to get this answer from - is what the crypto method is that was used to hash my password from the UI into storage in the Users table in sqlite.  I can dump the table and have found my user -- I see a triple that looks like it is probably a UUID, my username, and then (probably) a password hash.  :)

Alternately - 

If I just rip those out and store them as data - say, in chef attributes that I can then pass into a template - and use it to rebuild that table upon a reinstall - will that work?  Or is there some other reference to that data in the schema that would *keep* it from working?  

I know this sounds a tiny bit brittle, and is sort of a long way around to go to automate this - but I really, really, really despise hand work / manual reconfiguration when I need to rebuild something.  ;-)

Just asking for thoughts and opinions before I start hacking away at this. 

Looking forward to hearing from you!

best,
--e

[I just tried to sign the CLAhub agreement - service threw an error when I tried to sign.  I'll try again later..]

**Comment by markus101** [comment]
Currently the password is stored using a SHA256 Hash, but that could change and since its not an official API (expect that it could change at any time).

This isn't a scenario we support, but if you really want to do it you could setup a default database with the username and password set and have the database migration upgrade it if anything changes, since we'll likely rely on a migration to change the data instead of breaking it.

Of course you could always rely on backing up and restoring the database and config if you need to rebuild it and avoid manually entering the series/altering profiles, etc.
