### ISSUE TITLE
Sonarr using C:/VTRoot instead of D:/ location its supposed to.

### ISSUE THREAD

**Issue by Nuvelle** [Sonarr/Sonarr#1175]
In my series settings I have a path "D:\Media\". This is detected & used fine in the GUI.

When the file is downloaded & imported, it succeeds but is instead moved to a hidden folder on my C drive (C:\VTRoot\HarddiskVolume4\Media)

Is there any way to fix this behaviour? my D drive is a partition of the HDD, not a network drive or anything.

**Comment by markus101** [comment]
Please use the forums for support.

A quick search for VTRoot indicates it might be caused by Comodo Internet security: http://www.tomshardware.com/answers/id-2627315/games-installing-ssd-vtroot-location.html

Sonarr will move files to the path specific when the series was added (or later edited), you can review all the paths on the Series Editor.

**Comment by Nuvelle** [comment]
Thats the confusing part - all the paths show as D:\ (Import success and Series location) other than the actual save location, which is what led me to think it was a bug.

The server does indeed have Comodo so will investigate that, thank you!

**Comment by Nuvelle** [comment]
Just in case anyone else finds the same problem and sees this:

Comodo had put Sonarr into "sandboxed" mode. Telling it to ignore Sonarr, or trust the process/file fixed it. 

Just had to manually move the files to the correct folders and its all good now.
