### ISSUE TITLE
Support sending notifications via Join

### ISSUE THREAD

**Issue by bmcclure** [Sonarr/Sonarr#1197]
Join is a new alternative similar to Pushbullet in its functionality. It would be great if Sonarr supported sending notifications via Join.

http://joaoapps.com/join/

**Comment by markus101** [comment]
The API Docs we'd require to implement this didn't stand out on the site, if they don't have a public API (and the docs to go with it), we won't be able to support it.

**Comment by Nedlinin** [comment]
API now has some (admittedly basic) documentation available.

http://joaoapps.com/join/api/

**Comment by RELGG** [comment]
Found [this](https://www.reddit.com/r/sonarr/comments/4spkin/anyone_have_join_working_with_sonarr_yet/d5bc892?context=3)

**Comment by Nedlinin** [comment]
@RELGG nice find. This is going to be more important in a week's time with PushBullet opting to block automated pushes for non paying users.

**Comment by RELGG** [comment]
@Nedlinin got this today

> Hello, Pushbullet team here again.
Yesterday you received an email from us about changes we were planning to make regarding automated push activity. We received a lot of great feedback to that email and have concluded based on this feedback that there is a better way to address the growing push volume we're seeing. As a result, you can ignore our previous email. We will not be making changes that target specific services.
Instead of singling out specific services, we are now putting an upper bound of 500 API pushes per month for free Pushbullet accounts. API pushes do not include pushes from services like IFTTT or from Channels or from Pushbullet apps. They are specifically from the use of our public API.
This limit will affect far fewer users than our previous approach so we're very happy with that. This upper bound does not apply to Pro accounts.
Sorry for the lack of clarity to our previous email. I hope this email clears everything up.
Best,
Ryan
Cofounder, Pushbullet
PS: If you're curious about the feedback leading to this change, you can read it [Here](https://www.reddit.com/r/PushBullet/comments/4ullh7/august_1st_deadline_to_block_scriptedautomated/)

**Comment by jaywk** [comment]
Regardless of the updated Pushbullet team announcment, I 'd still love to have native support for the Join API.

**Comment by gregbendes** [comment]
+1

**Comment by markus101** [comment]
Merged in.
