### ISSUE TITLE
Prevent grabbing propers when existing grab meets requirements

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1208]
Right now a proper will be grabbed if the original release hasn't been imported even when Download Propers is false. For quality upgrades we respect the grab history/download client's queue, but we don't do these same checks for propers.

**Comment by fruitfrog** [comment]
Would like to give this a +1. Causing lots of GB of data being re-downloaded.

**Comment by WildOrangutan** [comment]
I somewhat agree. I think proper should be defined as a category in Settings>Quality section and not hidden in Media as advanced option.

**Comment by paolovador** [comment]
Hi,

I just noticed Money Heist episode 1 being downloaded twice, one of them being a proper version. It looks like the same problem but I'm not really sure because the proper version was downloaded first, then the "normal" one. If I understood this issue correctly shouldn't it be the other way around ? normal first, then proper as an upgrade ?
![Episode 1 History](https://user-images.githubusercontent.com/6412153/60800954-638e6500-a176-11e9-96d5-f36a54a44408.PNG)

It says in the logs that there was a problem sending the proper version to download client but I can see that it was added fine (and before the normal version) in qBitorrent:
![logs](https://user-images.githubusercontent.com/6412153/60800948-61c4a180-a176-11e9-99d1-15f887642816.PNG)
![qBitorrent](https://user-images.githubusercontent.com/6412153/60800962-64bf9200-a176-11e9-89a2-812c1169242b.PNG)

Thanks in advance for your help in explaining the situation

**Comment by markus101** [comment]
That is not the same problem this issue covers. Please use the forums for support and questions, we'll need to see debug logs to properly answer that question.
