### ISSUE TITLE
Unable to detect episode

### ISSUE THREAD

**Issue by CyberMew** [Sonarr/Sonarr#1214]
It says no file available for this episode. For example, ShowName/S04E08/040809.repack.mkv (dual episode)

it should be able to detect that the episode has been grabbed. Sickbeard has no issue detecting this (I just ported it over). If this is not an 'issue', is there anyway I can manually assign the file to it?

**Comment by markus101** [comment]
It looks like Sonarr detects it as Season 4 episode 8 due to the folder name. This is a pretty odd file name and isn't something Sonarr detects. Are all your files named like this?

Manual import would work (point it at the series folder) if no episodes were detected, but the folder will have broken that ability. Renaming it to something easier to parse (S04E08-E09 for example) will allow Sonarr to import automatically.
