### ISSUE TITLE
Sonarr cannot set uid and gid independently

### ISSUE THREAD

**Issue by xelra** [Sonarr/Sonarr#1220]
Trying to only apply gid, without setting uid is not possible in Sonarr. This makes it impossible to set gid, unless you're root, because setting uid is only possible as root. 

Users have to either try to set the same uid as the sonarr daemon or leave this feature blank in Sonarr and run their own permission inheritence by setting sticky bits. The former is only a workaround though and might not always be possible. For example when using remote mounts or any kind of mount with an idmap.

Sonarr needs to be able to set uid and gid independently of each other.

**Comment by markus101** [comment]
As far as I can tell this is not possible with mono:

https://github.com/mono/mono/blob/master/mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs#L4574-L4576

I don't see a way to set the group without setting the user, since its uint we can't pass null. Beyond finding a way to get the owner ID of the file (which I couldn't find) I don't see a feasible way to achieve this (directly calling chmod is not viable).

**Comment by xelra** [comment]
From [Mono.Unix.Native.Syscall.chown Method](http://docs.go-mono.com/?link=M%3aMono.Unix.Native.Syscall.chown):

"One of the owner or group id's may be left unchanged by specifying it as -1."

Despite it being uint.
