### ISSUE TITLE
Renaming {Release Group} to "Sonarr" instead of none if none found

### ISSUE THREAD

**Issue by ToXinE** [Sonarr/Sonarr#1229]
I wondered why this behavior. I want to rename episode file without any release group if there is none found in the file name : 

example:
With the following naming pattern: 
`{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Title} {Release Group} `

`Dexter - S01E12.avi` should be renamed to `Dexter - S01E12 - Born Free SDTV.avi` (and not 
`Dexter - S01E12 - Born Free SDTV Sonarr.avi`)

**Comment by Taloth** [comment]
hm, didn't notice this issue earlier.

1) It's by design, has to do with parsing back.
2) we won't change this logic, has to do with backward compat. otherwise ppl wll end up with erroneous trailing hyphens if they have "...{Quality Title]-{Release Group}".
3) I feel ya, coz I had the same issue. But here's the solution "{Series Title} - S{season:00}E{episode:00} - {Episode Title} {Quality Title}{ Release Group}". (Note the embedded prefix separator in the tag?)

Those special prefix/suffixes are kinda advanced so was never added to the wiki.

Btw, here's my format "{Series.CleanTitle}.S{season:00}E{episode:00}{.Episode.CleanTitle}{.Quality.Full}{.MediaInfo.Full}{-Release Group}" which is similar to the scene format.

**Comment by ToXinE** [comment]
Thank you. I'll try this embedded prefix separator in the tag to see if it suits my needs.
