### ISSUE TITLE
Allow read-only root folders

### ISSUE THREAD

**Issue by devcompl** [Sonarr/Sonarr#1239]
Given that each setup varies from person to person, I think it would be better if we could also add root folders with just read-only permissions.

Maybe add a popup warning user that sonarr will not use all of its features on that folder.

I've read on the forums that the only way now is to create symlinks. Obviously it would be best to have an official support for such folders.

**Comment by markus101** [comment]
Why would this be an advantage? If you don't want Sonarr to alter anything in a series, unmonitoring everything would have the same effect or not adding it to Sonarr at all.

**Comment by devcompl** [comment]
Well sonarr would still monitor the series and download new episodes automatically. 
You would just have to put them in manually.

There is no advantage here, it just allows people with strict permissions on their data to still use sonarr

**Comment by markus101** [comment]
> Well sonarr would still monitor the series and download new episodes automatically. 

You can achieve that by pointing Sonarr to empty folders and unmonitoring old episodes or preventing Sonarr from having write access to the folders and contents.

Playing devil's advocate, I assume this is because you don't want a program such as Sonarr altering files, but that would still be possible if there was a bug in Sonarr that failed to enforce the read-only setting.

This isn't something we're going to commit to implement at this time.
