### ISSUE TITLE
Exclude File Types

### ISSUE THREAD

**Issue by PartTimeLegend** [Sonarr/Sonarr#1243]
Is it possible to include functionality to exclude file types?

**Comment by markus101** [comment]
You can use release restrictions (On the Indexer Settings page) to exclude releases that contain (or don't contain) certain words. Specific file types can't be excluded because they aren't known until the download completes. If you want to exclude a particular file from being imported it will need to be removed before Sonarr can process it (post processing script in your download client might work for this).
