### ISSUE TITLE
Poor Auto-Search Prioritization

### ISSUE THREAD

**Issue by adz7** [Sonarr/Sonarr#1244]
So I've had a separate issue where I have noticed episodes not being Automatically being Searched.  I know you would need bug logs to figure that out but I digress (somethign a reboot will probably fix).

When I have manually tried to catchup I use Auto Search, this works however Sonarr grabs a shit copy of the episode even though there is a better release available.

For example Brooklyn Nine-Nine - 3x22 - Bureau:

Sonarr Auto Grabbed:

8.8 hours
Brooklyn Nine Nine S03E22 1080p WEB-DL 6CH HEVC x265-RMTeam[1080p][HEVC]	KickassTorrents	273.0 MB	 **28 / 11**	WEBDL-1080p

I feel like it should have grabbed the below release as it clearly has a larger filesize and heaps more seeders available, there is no way a 270MB file is actually 1920x1080 resolution:

12.7 hours
Brooklyn Nine-Nine S03E22 1080p WEB-DL DD5 1 H264-NTb[rartv]	KickassTorrents	847.3 MB	**156 / 51**	WEBDL-1080p

I just tested it for three other different episodes and the same result, it's grabbed sub 500MB file's even though one release even had a 1.7GB file available with 200+ seeds.

Any ideas?

**Comment by cryodream** [comment]
@adz7 it's x265, so it maybe very well be that small in size.

But on the topic - yes, I stopped using the auto search in sonarr, just because most of the time it grabs wrong (or rather not the ones I would pick manually) releases. Hence I got used t spending an additional minute or too and searching manually.

Also, Sonarr does not have separate between WED-DL and WEBRips, which gives the most trouble. Another reason, why I do not use auto search.

**Comment by markus101** [comment]
Improved ordering has been implemented in develop, which will prefer weigh seeders higher than size and should result in improved decision making.

**Comment by adz7** [comment]
Thanks Cryo & Mark, there you go learnt something new, x265 is going to save me a lot of HD space :D

**Comment by adz7** [comment]
And that thankyou is a sincere, wish we had this sort of support and level of dev for Couch Potata.  That project is essentially dust.  There is only one dev and all one moderator for the forums, they managed to break the Manual Post-Processing feature, got reported 2 months ago still no solution.  Fantastic to Sonarr still going strong :+1:

**Comment by adz7** [comment]
So i've researched it and it looks like 1080p x265 is better quality with much lower file sizes than x264 - @markus101  is there any way to preference x265 releases over x264?  I say preference because if no x265 release is available I'd still like x264 to be grabbed.

**Comment by markus101** [comment]
No, that would be https://github.com/Sonarr/Sonarr/issues/385

**Comment by gjedeer** [comment]
Has that code made it to release version? 

If yes then it's not working very well for my use case. I'd like to have the ability to have Auto-Search choose release strictly by the number of peers (because most popular release is much more likely to have translated subtitles, and I'd take SDTV with translated subtitles over 2160p with no subtitles). 

If you pointed at the source code file maybe I could implement that as a setting? The code base size is a bit intimidating...

**Comment by gjedeer** [comment]
Would it be as simple as swapping CompareQuality with ComparePeersIfTorrent here? https://github.com/Sonarr/Sonarr/blob/816cf608fcef07e375aa750a863d0a7365108981/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs#L21 (I'm not suggesting doing that as a default)

**Comment by markus101** [comment]
Yes the code went live some time ago.

Selecting a release based purely on the number of seeders wasn't the intention of that fix and not a use case we have plans to support at this time.

Simply swapping them or moving `ComparePeersIfTorrent` to the top wouldn't work properly if Usenet was the preferred protocol since they would compare equally, so such a change wouldn't fit well in all scenarios.

**Comment by gjedeer** [comment]
Just in case someone else stumbled onto this issue: I actually implemented that simple change in https://github.com/gjedeer/Sonarr and I'm running that build for ~3 months now. It works great for a torrent-only workload and almost always downloads popular releases for which foreign subtitles are easily available.
