### ISSUE TITLE
HDBits search bug

### ISSUE THREAD

**Issue by needo37** [Sonarr/Sonarr#1271]
When doing a search for a show HDBits does not return season packs. Only single episodes.

**Comment by Dahlgren** [comment]
Season packs are used when searching for an entire season or show, not for individual episode searches. Since many HDBits season packs are quite large per episode you might have to increase the max Size Limit for your desired quality in Sonarr settings for it to be chosen for download. Tested it with the current release just now and worked fine after adjusting the Size Limit to a higher value for BluRay qualities.

**Comment by anonaut** [comment]
May i ask why BTN returns season packs when searching for single episodes? Is this something BTN implemented? If not could we do the same for HDB?

**Comment by markus101** [comment]
It was done because BTN is strict in removing single episodes (besides the pilot). I'm not sure if HDBits does the same thing, but we don't have plans to do the same thing for other indexers.

In fact, closing this as it's covered by: https://github.com/Sonarr/Sonarr/issues/266
