### ISSUE TITLE
Sonarr missing multi-episode files

### ISSUE THREAD

**Issue by Terebi42** [Sonarr/Sonarr#1305]
season 2 of a show is on BTN,  series.php?id=33367

Most of the episodes are dual episodes, because they air together

Won't grab any of them, even via manual search.

**Comment by markus101** [comment]
The problem is with how the search API works, we ask for a releases for that series (by TVDB ID) and the season and episode in the format `S02E33`, but BTN is expecting us to look for `S02E33E34`, but the problem is Sonarr has no idea that its a double episode and most, but not all episodes in that series are double episodes so its a guess at best.

Its not just BTN that causes issues when searching for double episodes as Newznab indexers have similar problems (usually because they aren't parsed properly so it fails unless they are linked manually). RSS should have no issues picking these releases up since the release name can be parsed properly by Sonarr.

**Comment by Terebi42** [comment]
when you do a "find all missing season episdode" searches, does it do a search for each episode individually, or does it do a mass search for all episodes in the season that then sorts out into which files go into which episodes? If the latter, it should be able to catch them?

**Comment by markus101** [comment]
It depends, if there are multiple files missing it will do a season search, but with BTN those are season packs not individual episodes in the season so they aren't found, on Newznab indexers they are found though.
