### ISSUE TITLE
Provide option to override libsqlite3.so location

### ISSUE THREAD

**Issue by fadenb** [Sonarr/Sonarr#1325]
Hi,

when packaging Sonarr for NixOS I needed to tell Sonarr where to find libsqlite3.so during runtime.
I was able to do this by creating a file called `System.Data.SQLite.dll.config` in the application directory (in which I replace the path later on):
```xml
<configuration>
  <dllmap dll="sqlite3" target="libsqlite3.so" os="linux"/>
</configuration>
```

I think it will be useful to provide this file by default like it is done with `NzbDrone.Core.dll.config`.
I was unsure where to put the file in the source tree or otherwise I would have provided a PR with this requests :)

**Comment by markus101** [comment]
Any location in the PATH should work, you should be able to add another location to the PATH and it will be picked up automatically. If the file has an alternate name on your OS that what is being looked for you can use a symlink to remap it to the correct file name.

The reason for `NzbDrone.Core.dll.config` was because the library was looking for a DLL, for `System.Data.SQLite.dll.config` it already looks for the common name on the system.

**Comment by markus101** [comment]
Closing, but please let us know if there is anything else we should consider for this.
