### ISSUE TITLE
Help me understand why my quality was upgraded please

### ISSUE THREAD

**Issue by suprdave23** [Sonarr/Sonarr#1332]
I have an episode that seems to have been deleted for an upgrade when the quality was already configured with a cutoff that the original episode reached.

I have HD-720p profile configured so that "Bluray" quality is considered the worst, but is the cutoff. HDTV 720p is considered the best. My goal is once any 720p quality is downloaded it stops and never attempts to upgrade the quality. 

Attached are the logs, profile settings, and episode settings. Can someone please help me understand what I missed?

First thing I noticed was it picked up the same episode but named "part 2", so someone hosed up the episode naming (that really should have been episode 2, not "part 2" of episode 1). May or may not be relevant.

The very last log entry at the top was me forcefully making it redownload the proper episode.

Thanks in advance!

![masterchef](https://cloud.githubusercontent.com/assets/11187813/15937722/aa4724da-2e35-11e6-878d-7d344a9fcd1b.JPG)

![masterchef2](https://cloud.githubusercontent.com/assets/11187813/15937728/af10b17a-2e35-11e6-83bd-89256c52e70e.jpg)

![profile](https://cloud.githubusercontent.com/assets/11187813/15937730/b1c8696c-2e35-11e6-88ba-264fc08de418.JPG)

![masterchef3](https://cloud.githubusercontent.com/assets/11187813/15937732/b42ab2be-2e35-11e6-8556-0bc080b9538a.jpg)

**Comment by markus101** [comment]
Next time please use the forums for support.

Since there wasn't a grab event the issue is with the second file that was imported, labeled S07E01 part 2, that caused Sonarr to remove the existing file for S07E01 and import it as S07E01, there is probably a grab event for another episode maybe S07E02 that has the corresponding grab. Comes down to a file name in the release which is why Sonarr didn't grab it as an upgrade, but imported it (it will import equal or higher quality files automatically, to support the scenario where an equal quality release is grabbed manually to replace an existing file (less of an issue with manual import now available though).
