### ISSUE TITLE
Search All Missing not working consistently.

### ISSUE THREAD

**Issue by geekcroft** [Sonarr/Sonarr#1359]
Hi all,

So, I've been having an issue for I think a few weeks now but have only managed to figure out exactly what it is.

I have around 1100 missing episodes in my Wanted Tab. If I hit "Find all missing" it goes away and looks to be searching, however it generally doesnt ever return any results. Yet if I go into a series manually and do a manual search for an episode, I get results and can send them off to Sabnzdb. 

Utillising NZBGeek as my usenet indexer. 

I can get logs etc if needed. 

Is this just my indexer being iffy, or is it something internal to Sonarr?

**Comment by markus101** [comment]
Search all missing will search for a season worth of results if there is more than one episode missing for the season and series, which behaves the exact same as a season search from the series page (a series search performs a season search for each season in the series). You'd need to check debug logs to see if your indexer is returning the same results it gets in a manual search when you do a season search (assuming more than one episode is missing in that season), if it is then they are being rejected for some reason (manual search will show that reason) otherwise its your indexer causing issues. 

If you need us to assist further please open a thread on the forums, as we don't use Github issues for support.
