### ISSUE TITLE
rm -rf all hard links -> how to reimport without moving

### ISSUE THREAD

**Issue by anonaut** [Sonarr/Sonarr#1365]
hello,

yesterday i accidently rm -rf my hardlinks for anime and tv shows. the source files are still there (and in my rtorrent client with the sonarr label), but all the naming done by sonarr is gone. i tried manual importing but that moves the files (which i don't want because i want to seed them indefinetly). I also tried deleting a series in sonarr and readding it in the hope that the sonarr queue will pick it up but that didn't work.

is there any way to restart the postprocessing for files already processed?

**Comment by markus101** [comment]
> I also tried deleting a series in sonarr and readding it in the hope that the sonarr queue will pick it up but that didn't work.

That's should do it since that would cause Sonarr to lose track that it previously imported that completed download, but it would need to be in the correct category (label) and be named in a way that Sonarr can understand it properly. 

Another option would be to hardlink all the completed downloads to another folder folder (outside of Sonarr) and then have Sonarr scan that folder and move the files its able to process (Manual Import: import automatically should do it), any files left over could not be imported and you could use manual import to import them and select the correct series and episode.

The only other option that comes to mind would be to clear the import history from Sonarr (using a SQLite manager), that would be similar to removing and reading the series, but would only remove the import events so the hash is tracked through the grab event.

Good luck.
