### ISSUE TITLE
Nzbget Delete:SCAN

### ISSUE THREAD

**Issue by joshuader6** [Sonarr/Sonarr#1394]
Sometimes nzbget fails to parse an nzb file. 
This results in a status "Delete:SCAN" 
Sonarr doesn't pick that up as a failure atm.

**Comment by christianvaes** [comment]
I'm also having this issue can this be fixed please

**Comment by proxenus** [comment]
I am having the same issue. I think this may be related to this request:
https://github.com/Sonarr/Sonarr/issues/430

The new version of the API has 2 states added to DeleteStatus. SCAN is obviously what we're having a problem with. There is another new one: COPY.

from here: https://github.com/nzbget/nzbget/wiki/API-Method-%22history%22
DeleteStatus (string) - Indicates if the download was deleted:
NONE - not deleted;
MANUAL - the download was manually deleted by user;
HEALTH - the download was deleted by health check;
DUPE - the download was deleted by duplicate check;
BAD - v14.0 the download was marked as BAD by a queue-script during download;
SCAN - v16.0 the download was deleted because the nzb-file could not be parsed (malformed nzb-file);
COPY - v16.0 the download was deleted by duplicate check because an nzb-file with exactly same content exists in download queue or in history.
