### ISSUE TITLE
Multiple Drone Locations

### ISSUE THREAD

**Issue by Ragonz** [Sonarr/Sonarr#1413]
Feature Request

Ability to add additional drone locations so Sonarr can "find" episodes for multiple locations

**Comment by markus101** [comment]
I assume you mean Drone Factory, which is considered deprecated and will be removed as a setting in v3. You can use the API to tell Sonarr to look at a folder to import files or use Manual Import (on Wanted: Missing) to choose a folder.

Automated imports are best handled by Completed Download Handling, which is why Drone Factory is deprecated.
