### ISSUE TITLE
[Feature Request] Support to associate download client

### ISSUE THREAD

**Issue by saitoh183** [Sonarr/Sonarr#1427]
In CouchPotato there is a setting for each Download client that allows you to set the client to only be used for manual downloads. If this is not checked, then the client is also used for automatic downloads. Could this be a possibility in Sonarr? (but a bit more sophisticated)

For example, the lack of support for RARBG with Blackhole. If i have Deluge but i also Utorrent enable (used with blackhole), i could associate RARBG to use deluge as a client and workaround the blackhole issue. This also goes for when i select a torrent from a manual search.

**Comment by markus101** [comment]
> For example, the lack of support for RARBG with Blackhole.

That is because RARBG primarily uses magnet links, not torrent files, in the latest development versions Sonarr will download them to the blackhole as `.magnet` files which from my understanding is the same way that CP handles them.

Linking an indexer with a specific download client has already been requested: https://github.com/Sonarr/Sonarr/issues/1215 I don't see there being an option to make a download client only handle manual grabs being worth the implementation time vs linking indexers to clients if we opt to go that route.

**Comment by saitoh183** [comment]
Well sonarr just fail when I select a rarbg link manually. (little cloud icon goes red)  and i don't see any magnet link file being sent. Downloader only handling manual grabs is not really necessary if you have indexer association.

**Comment by markus101** [comment]
Are you running a recent develop release?

**Comment by saitoh183** [comment]
Version
2.0.0.4230
Mono Version
4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)
AppData directory
/home/svc-saitoh/.config/NzbDrone
Startup directory
/opt/NzbDrone

**Comment by markus101** [comment]
> 2.0.0.4230

That's master, so you won't have that change.

**Comment by saitoh183** [comment]
should i change to dev?

**Comment by markus101** [comment]
That change will make it to master eventually, if you don't need it right now wait for it.

**Comment by saitoh183** [comment]
ok...i guess i could give it a go
