### ISSUE TITLE
Trim search bar input

### ISSUE THREAD

**Issue by benjick** [Sonarr/Sonarr#1450]
![image](https://cloud.githubusercontent.com/assets/430872/18328758/91a1a43e-7550-11e6-8d52-f411121d2298.png)

vs

![image](https://cloud.githubusercontent.com/assets/430872/18328764/9a023b8e-7550-11e6-8dd2-58a0eaf88db4.png)

Spaces should be trimmed

**Comment by benjick** [comment]
Maybe I'll just send a PR for this if you want

**Comment by markus101** [comment]
:+1: yes, it should trim

**Comment by Taloth** [comment]
I don't think so. Imagine the follow series:
The Shield
The Shield of Aegis
Shielded

The search query 'shield' should return all, 'shield ' should at least omit 'Shielded', and arguably the first one too.

**Comment by benjick** [comment]
Why should it not return those three? Just add *of* if you want more specificy

**Comment by markus101** [comment]
Why should it return all three though? The space is significant in that it filters the suggestions further than if it wasn't there.

This isn't apples to apples (because google searches are a much more powerful beast), but the filtering of the series suggestions is somewhat similar to, If I enter `how do i make a` into a Google I start getting suggestions:

![image](https://cloud.githubusercontent.com/assets/413544/18901032/32a69938-84fc-11e6-92dd-e863e1853a5f.png)

If I hit space after the `a` the results filter down to:

![image](https://cloud.githubusercontent.com/assets/413544/18901065/80e71e10-84fc-11e6-88ba-7e63c3c8dff8.png)
(`how do i make an app` disappears)
