### ISSUE TITLE
macOS Sierra public beta

### ISSUE THREAD

**Issue by altryne** [Sonarr/Sonarr#1453]
Last upgrade (el cap) I remember having problems with sqllite drivers, almost destroying all my Sonarr history. 

Wanted to see if anyone installed Sonarr on macOS Sierra and can tell me if it works and I can install the Beta worry free?

**Comment by markus101** [comment]
There are a couple threads on the forums, one user had issues, though it's unclear whether it's Sonarr or something else causing issues. Another user had to reinstall Sonarr after upgrading, but otherwise it appears to be working.

https://forums.sonarr.tv/t/does-sonarr-work-with-sierra/11935
https://forums.sonarr.tv/t/blank-screen-after-upgrading-to-macos-sierra/12025/15
