### ISSUE TITLE
Join notifications need transparent icon as "smallicon"

### ISSUE THREAD

**Issue by Fixer2k** [Sonarr/Sonarr#1458]
Happy to see Join integration. Before native support I wrote my own php-script that made Sonarr send to Join.

For the Sonarr icon to show correctly in the notification area on Android, it has to be transparent. At the time it shows a white circle.

This is what I use:

This one as "icon" (API):
![256_color](https://cloud.githubusercontent.com/assets/22151176/18439012/f061c0e2-7903-11e6-826a-bd36d6288fcb.png)

and this one as "smallicon" (API):
![256_white_transp](https://cloud.githubusercontent.com/assets/22151176/18439019/f5400e52-7903-11e6-93ec-a3ea11c1482c.png)

I also made this one for "smallicon" but not using it:
![256_black_transp](https://cloud.githubusercontent.com/assets/22151176/18439121/61a2189c-7904-11e6-90b8-72c64384fba7.png)

**Comment by Nedlinin** [comment]
The image being used appears to be identical to your first example:
https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Notifications/Join/JoinProxy.cs#L70
https://cdn.rawgit.com/Sonarr/Sonarr/develop/Logo/256.png

I did not add in smallicon as the API docs said it would be used if set but if not that "icon" is used as long as it has transparency (which this one does).

**Comment by Fixer2k** [comment]
Ah, yes. It's the same. It won't work as smallicon, white circle. The circle in the default logo is not transparent but white and no details in the logo.

**Comment by Nedlinin** [comment]
Yep.  The logo actually contains that white circle.  I think it'd be up to the Join core team member if they are wanting to create one without the white circle but I'd consider that white part of the logo itself.  It is surrounded by transparency so the circle seems quite intentional.

If they decide to change the Join logo it is insanely trivial though (literally change the URL on the line I linked and you're done).

**Comment by Fixer2k** [comment]
Android won't allow colors in the notification area. I will use my own script for now.
