### ISSUE TITLE
Setting series as "monitored" not working as intended

### ISSUE THREAD

**Issue by ScuttleSE** [Sonarr/Sonarr#1491]
Pick any ongoing series with one season
Set both the season and the show as unmonitored
Go to Series editor, mark the show and set it to monitored
Show is monitored, but the season is still unmonitored

**Comment by markus101** [comment]
That's working as intended. The season doesn't immediately get monitored (or unmonitored) when you change the monitored status of the series. Unmonitoring a series will prevent _any_ episode from being automatically grab via RSS (searching for that episode would ignore that) and you can't toggle the monitored status of a season when the series is unmonitored (since it would have no effect).

**Comment by ScuttleSE** [comment]
Well, that generates a problem then

How can I find a show where the show is monitored, but the seasons aren't? The filtering options in series editor aren't granular enough.

**Comment by ScuttleSE** [comment]
Also...I don't really understand your reply.. 

"you can't toggle the monitored status of a season when the series is unmonitored (since it would have no effect)"

Sure, that I understand, but when I in series editor checks the series and choose "Monitored", why is it not changing status on the individual seasons/episodes in the series?

**Comment by markus101** [comment]
Because they are separate monitored statuses. If you only wanted the latest season of a series and had unmonitored the previous seasons and had unmonitored the series temporarily for some reason would you wouldn't want every previous season to suddenly become monitored (or unmonitored when you unmonitored it).

If you want to check whether individual seasons for series are unmonitored you can see that on the series details page, if you want to check them for all the seasons, the Season Pass page is the best place for that.
