### ISSUE TITLE
RSS feed - invalid character

### ISSUE THREAD

**Issue by manderss99** [Sonarr/Sonarr#1518]
I have problem with two of my rss feeds, I often gets error in sonarr log about invalid character.
often its 0x07, 0x010, presumably this is bc torrent descriptions fields are not properly encoded.

I have been in contact with the sites but there is either no response or a recommendation to change my client :(.

Would it be possible to make sonarr more tolerant about these kind of not perfect feeds?
These sites provide a valuable service so I really would like to be able to continue using them.

thanks

**Comment by markus101** [comment]
The contents of the RSS feed with invalid characters in it would be a good start so we can investigate the possibility of cleaning it up before processing.

**Comment by manderss99** [comment]
I have an example rss from alpharatio, however since it contains my authkey I dont want to put it up publicly. What should I do? (btw, the other indexer with problem is xspeeds)

**Comment by markus101** [comment]
You can filter out the authkey replace it with `private_authkey` or similar and post it. You can also PM it to me on the forums (same username), but you should filter it either way.

**Comment by manderss99** [comment]
attaching alpharatio rss output where sonarr complains about line 1512 (control characters).

[alpharatio.zip](https://github.com/Sonarr/Sonarr/files/618796/alpharatio.zip)

**Comment by markus101** [comment]
I was able fix the invalid character issue, but AlphaRatio's feed is beyond hope for Sonarr unless at a minimum they fix the title, since the title contains a bunch of other crap in it.

Title: `<title><![CDATA[TvHD 465989 465960 Good.Behavior.S01E03.PROPER.720p.HDTV.x264-KILLERS]]></title>`
Title that Sonarr could actually use: `<title>Good.Behavior.S01E03.PROPER.720p.HDTV.x264-KILLERS></title>`
