### ISSUE TITLE
Request: Show network logo on shows (plus small poster in table view)

### ISSUE THREAD

**Issue by just-Addict** [Sonarr/Sonarr#1531]
Hi there,

Loving Sonarr after having tried Sickbeard. Much more versatile. Much better backlog search.

Got a small request though. Would be nice if the network logo was shown (either as overlay or next to the number of downloaded episodes/next air-date in poster/overview list modes.

Also, and likewise it would be cool if both a small poster and again the network logo could be added to the table view. 

This makes it just that bit easier to see which network airs which show and just a tad easier to locate the show in table view (images are just a tad quicker recognized than reading shownames... )

Adding the network logo would be especially helpful since you can sort on Network, but only the table view makes any mention of which show airs on which network

**Comment by markus101** [comment]
We looked at uysing network logos some time ago, but the availability of them was quite poor and in some cases the quality was quite awful. The lack of consistent logos for all channels is a bit of a killer since a lack of a logo will stand out in a negative way. Unless these images are available somewhere I don't see this being something we'll support.

**Comment by markus101** [comment]
The docker image should be updated shortly (if it's not already). If you upgrade when it's available you should get line numbers in the error message that may help us narrow down where the issue is coming from.

**Comment by thezoggy** [comment]
using network logos is such a pain.. 

- upkeep with them in general (fixes/sizes/etc)
- longer page loads due to the fact that each one is a separate request for the webserver to serve up.. grouping them into one image then becomes a huge image/pain to upkeep
- using images then means you have to add logic to sort/filter that field using alt data.. the user loses the ctrl+f ability
- images mean when you want to change the ui.. you have to deal with their readability/size.. gets in the way of design process 
- bloating the size of install that much more

**Comment by markus101** [comment]
No plans for network logos or small posters in the table at this time.
