### ISSUE TITLE
Indexers unavailable due to failures

### ISSUE THREAD

**Issue by Titte95** [Sonarr/Sonarr#1537]
I've had this msg for a few days now

> Indexers unavailable due to failures: TRACKER

I've tried remove it in sonarr, and in jackett but it will come back with the msg after a half an hour or so.
Anyway to fix this?

**Comment by markus101** [comment]
The indexer has to exist in Sonarr for it to know it's unavailable. If the indexer periodically fails (multiple times in a row) Sonarr will stop using it and report that to you. If the connection between Sonarr and Jackett is good the issue is somewhere with Jackett and the connection to the indexer.

Do you have this issue with other indexers?
Have you looked at the logs to see why it's failing?

**Comment by Titte95** [comment]
I am using two indexers in sonarr, but the other one are just working fine :(

**Comment by Titte95** [comment]
I can easily find the torrents through jackett with the tracker

**Comment by markus101** [comment]
You'll need to look at the logs to see why it's failing.

**Comment by Titte95** [comment]
Can i post the logs here safetly?

**Comment by markus101** [comment]
They're going to be public, same as if you post them on the forums though...
