### ISSUE TITLE
Feature: Disable indexers are unavailable due to failures

### ISSUE THREAD

**Issue by greencopper** [Sonarr/Sonarr#1539]
It would be really nice if the option about "Indexers are unavailable due to failures" could be disabled.

I am running on VPN and currently it drops out intermittent which makes Sonarr unavailable for about 24 hours.

This isn't useful as in my case I actually need Sonarr to keep retrying to connect because the problem isn't with the indexer, but with my line.

An option to disable this functionality would be great.

**Comment by markus101** [comment]
How is it failing? There may be cases where we shouldn't be disabling the indexer when we can't connect or perhaps limiting the duration of the disabling, but I don't see there being an option to opt out of disabling. Testing indexers will also immediately retry the connection and remove the block if it succeeds.

**Comment by greencopper** [comment]
It's failing because the indexer gets disabled. However, in my case the indexer is working fine, it's my stupid connection I'm currently having trouble with, so I just need Sonarr to keep retrying the connection every 5 seconds or so. I don't want it to disable the indexer at all.

**Comment by markus101** [comment]
> It's failing because the indexer gets disabled.

No it's disabled because it failed. The logs will show exactly how it failed.

> I just need Sonarr to keep retrying the connection every 5 seconds or so

That's not how it works or would work, if it failed and wasn't disabled at best it would be retried the next time the RSS Sync ran.

> I don't want it to disable the indexer at all.

It can be disabled for a multitude of reasons, if it fails because the indexer is down it should be disabled, if it failed because the indexer has told Sonar you've exhausted your API hits for the day it should be disabled, otherwise you may end up getting banned entirely. If it's getting disabled for something else we can evaluate if that should not disable it, but there are no plans to opt out of disabling entirely.

**Comment by greencopper** [comment]
Ok, thanks, I guess I'm gonna have to hack it up myself then.

**Comment by thezoggy** [comment]
but sometimes sonarr needs to protect users from doing stupid things especially with the size of its user base. you dont want sonarr to ddos a site that is already having problems.. the adaptive throttling is a good thing. 

the true solution would be to fix the flaky vpn?

**Comment by markus101** [comment]
> If it fails because the indexer is down, it should not be disabled, but rather keep trying until the indexer is up again. 

Sonarr doesn't immediately block for a long period of time, it starts low and increases for every subsequent failure. A successful response stops escalating the block, but doesn't immediately clear it.

Like I said before we have no plans to add an option to opt out of it, it prevents people from flipping switches because things don't work and not understanding what they are doing and resulting in Sonarr getting banned (indexers have banned applications for abuse and will do so anytime they are hammering things).

Logs of the connection failing when the VPN might illuminate something we can do to prevent backing off in _some_ cases, but really if your VPN has prolonged issues that Sonarr is blocking connections for a day it definitely should be fixed or replaced.

**Comment by greencopper** [comment]
> but sometimes sonarr needs to protect users from doing stupid things

Users needs the freedom to decide how they want the application they are using to work. Not all users needs "hand-holding". This should be opt out.

Sure, I have a problem with my VPN, but this is not the issue, I could just as well be suffering from a bad Internet connection. But the point is: We need freedom! I want to be able to decide for myself how the application handles issues.

Having to clone or hack the application to prevent this is a waste of time.

**Comment by markus101** [comment]
Having to ask multiple times for actual information to try and help solve it is a waste of all our time. We need to know the actual problem (with actual logs, not "it doesn't work") in order. If you want us to help solve it, help us help you. Stop trying to convince us that we're doing it wrong and opting out is a valid solution, it's not, it may appear to be the issue here given your use case, but it is not the right solution.

If you want to give us logs to take a look at, we'll do it and determine _if_ we can do anything to prevent Sonarr from disabling indexers in that circumstance.

**Comment by Scruttbucket** [comment]
I just had the same issue multiple times after I restarted Sonarr due to database issues:
`NzbDroneErrorPipeline | Request Failed. POST /api/release: SABnzbd is disabled due to recent failues`

It happend due to earlier SQLLite errors so which is totally unrelated to DoSing a service and shouldn't disable the Pipeline:
`CommandExecutor | Error occurred while executing task CheckForFinishedDownload: unable to open database file unable to open database file`

So I would still like the option of disabling it myself or have it exclude disabling this after a restart or if it's from SQLLite (a local issue). 

As for the SQLLite issue itself, let's keep that out of scope of this issue (probably bad SQLLite and mono package availability/implementation on Synology), I'm working around it by restarting the sonarr service daily with a cron job, it's just that if I get the DB errors within 24h of uptime, it starts disabling my downloader.

**Comment by Elehiggle** [comment]
One workaround would be to call the testall function every 15 or so minutes:

/root/sonarrtestindexers.sh

```
#!/bin/bash

curl 'http://192.168.1.71:8989/api/v3/indexer/testall' -X POST -H 'Content-Length: 0' -H 'X-Api-Key: YOUR_API_KEY_HERE'
```

Put in crontab -e:

`*/15 * * * * /root/sonarrtestindexers.sh`

This is especially needed if you use Nzbhydra2. Sometimes Sonarr tries to download more items than a certain indexer in Hydra allows. That indexer returns "Wait 1440 minutes or risk being temporarily banned.", Sonarr locks the indexer for 24 hours and Sonarr is unusable. Unfortunately Sonarr has apparently no plans to add support for this (also according to the Nzbhydra2 dev which talked to the Sonarr devs), so that is your only way.

**Comment by thezoggy** [comment]
you should fix your underlying problem of why your indexer isnt reliable?

**Comment by Elehiggle** [comment]
> you should fix your underlying problem of why your indexer isnt reliable?

The indexer is reliable, but there are download limits on that indexer. I use Nzbhydra2 which aggregates all your indexers into one indexer only that you have to add in Sonarr. Sometimes a show is only available on one specific indexer which I use the free plan of. Sonarr tries to download more than is allowed and then locks the whole indexer for 24 hours, rendering whole Sonarr unusable since all indexers go through Hydra.

**Comment by thezoggy** [comment]
yet again, you should fix your problem with your indexer. 
low limits are done purposely to let people try and even state that shouldnt be used with automation as you will exceed it. pay for higher limits / dont use it with sonarr?

**Comment by Elehiggle** [comment]
We are not discussing the nature of indexers here and whether or not you should use them in Sonarr or not, the whole nature of Usenet nowadays is automation. These are valid concerns; and not only because there are indexers with no paid plans available, but still imposing daily limits.

**Comment by borderjs** [comment]
> One workaround would be to call the testall function every 15 or so minutes:
> 
> /root/sonarrtestindexers.sh
> 
> ```
> #!/bin/bash
> 
> curl 'http://192.168.1.71:8989/api/v3/indexer/testall' -X POST -H 'Content-Length: 0' -H 'X-Api-Key: YOUR_API_KEY_HERE'
> ```
> 
> Run
> `chmod +x /root/sonarrtestindexers.sh`
> 
> Put in crontab -e:
> `*/15 * * * * /root/sonarrtestindexers.sh`
> 

Hey Elehiggle, I tried this and says that api call isn't found.  Any ideas?  

Thanks

**Comment by Elehiggle** [comment]
> > One workaround would be to call the testall function every 15 or so minutes:
> > /root/sonarrtestindexers.sh
> > ```
> > #!/bin/bash
> > 
> > curl 'http://192.168.1.71:8989/api/v3/indexer/testall' -X POST -H 'Content-Length: 0' -H 'X-Api-Key: YOUR_API_KEY_HERE'
> > ```
> > 
> > 
> > Run
> > `chmod +x /root/sonarrtestindexers.sh`
> > Put in crontab -e:
> > `*/15 * * * * /root/sonarrtestindexers.sh`
> 
> Hey @Elehiggle, I tried this and says that api call isn't found. Any ideas?
> 
> Edit: I think I determined the issue, I do not have the alpha v3 so I guess it isn't in the original api. I also assume this command would not be in Radarr so would only solve half the issue.
> 
> Thanks

I don't think Radarr disables indexers. At least when I got an error, I did not see any indication in the logs that the indexer would be disabled. Also, I do not see any button to restore the indexer, like in Sonarr. 

Yes, I use the Sonarr Alpha. If the old Sonarr disables indexers and has a button to reactivate them, you can easily find out the appropriate URL and parameters by going to the site where the button is displayed, then do a rightclick anywhere, click Inspect and then go to the Network tab. If you press on the reactivate button, the correct API url will be shown. You can also copy the whole curl call there. This is on Chrome, but on Firefox its nearly the same.

**Comment by borderjs** [comment]
Radarr has disabled my indexers as well.  This only occurs since I started
using Hydra.  I just go into the indexer and retest it.  Following your
instructions, I was able to copy the curl command and execute it.  I
appreciate your help!
