### ISSUE TITLE
Episode numbering conflict 

### ISSUE THREAD

**Issue by tregota** [Sonarr/Sonarr#1549]
When a series has episode numbering where episode differs from absolute the search and download goes by the episode number but a scan disk where new episodes are found seem use the absolute number to match a video file to an episode.

So if a show has an eposode numbering where the absolute number is one lower than the episode number and you start of with some video files and scan them in, sonarr will skip one episode when starting to download the remaining.

Shouldn't both methods use the same episode number whether it be the absolute or not?

**Comment by markus101** [comment]
It depends how the file is named, if it only has the absolute number in the file name then that's all it can use to match it. Only series that are to set to Anime will actually use absolute numbering and http://thexem.de could be playing a roll in searching/matching if there are episodes remapped there.

Can you explain the issue further with a concrete example and screenshots?

**Comment by tregota** [comment]
Sure, I hope this image describes my problem sufficiently.

![numberingproblem](https://cloud.githubusercontent.com/assets/948240/20326600/cb070114-ab89-11e6-9829-b6a08b694b0d.jpg)

**Comment by markus101** [comment]
It's because the episodes are remapped on thexem.de because TheTVDB and the release groups are using different numbers, due to a disagreement whether an episode is a special or not: https://forums.thetvdb.com/viewtopic.php?t=32474

The remapping is here, which shifts everything up one episode to align with the first released episode being labeled S11E01, but is actually a special.
http://thexem.de/xem/show/3404

This has nothing to do with the absolute episode numbers, that's only included because it comes from thexem.de and this is expected behaviour given the discrepancy, as long as Sonarr is managing the grabbing and importing the files on disk will match the description of the episode, but the episode grabbed for episode 16 will be labeled episode 17 and episode 17 will be labeled episode 18 and so on.

**Comment by tregota** [comment]
@markus101 Alright thanks I see now why the numbering works as it does but the one thing that I still don't understand is if Sonarr adheres to the remapping when downloading then why not also when scanning the disk? Shouldn't it find episode 17 on the disk then look at the remapping and use it as episode 16?
Sorry for being so bothersome. ;)

**Comment by markus101** [comment]
When it's importing episodes from the download client it does, if it's already in the series folder it will not, those are treated as matching what Sonarr expects, otherwise if Sonarr lost track of them and rescanned them it would offset them all by one again every time that happened.

**Comment by tregota** [comment]
Oh! So it's because I don't have "Rename Episodes" turned on?

**Comment by markus101** [comment]
Ahh yes, that would do it. 👍 glad to hear we've found a solution.
