### ISSUE TITLE
Sonarr search pattern modify 

### ISSUE THREAD

**Issue by segator** [Sonarr/Sonarr#1556]
I am implementing some private spanish trackers in jackett.

I see that sonarr always find by :   tv show S01E03 (in spanish trackers we should find by 1x03 or 01x03

for the season pack sonarr use tv show S01  in spanish trackers we should find by tv show Temporada 1
or tv show T1.
it could be awesome if we can change the way of search.

**Comment by markus101** [comment]
Sonarr should be passing the season + episode number it's looking for to Jackett, not explicitly searching for `S01E03`, but that may depend on the capabilities Jackett reports to Sonarr, so you can override it there. As for `Temporada` or `T` instead of `Season` or `S` I'm not sure what we want to do with that, we'd probably want to limit the scope of that applying to series where Spanish is the selected language, but that's not something we could easily handle today. I'm not sure if that's something Jackett could translate before presenting it to Sonarr.

**Comment by segator** [comment]
Hi i just tried to format/replace the search sent by sonarr to jacket and now work fine for this tv shows that the name is the same in spanish.
it could be interesting that sonarr send the tv show name in the selected language.

The other problem that I see is that sonarr doesn't know how to handle torrent with season pack (all the episodes in a single torrent)

**Comment by markus101** [comment]
Sonarr doesn't actually know the series title in the language, it won't know that until https://github.com/Sonarr/Sonarr/issues/269is implemented.

We don't have plans to support search for alternate forms of season/episode numbers, there isn't really a good way to actually support that without confusing users or making multiple API calls, which is avoided with Tornab/Newznab queries because the season and episode number are sent, not the season and episode pattern, if Jackett isn't getting that information from Sonarr it needs to tell Sonarr it can support it and then Jacket handles it all.

> The other problem that I see is that sonarr doesn't know how to handle torrent with season pack (all the episodes in a single torrent)

It does, they just have to be well named, `Series Title S01` or `Series Title Season 1` are both valid, though that won't for cases where it's using a translated name for season.

**Comment by Asiier** [comment]
Sorry for replying to a closed issue... But I'm having the exact same problem as @segator but I cannot figure out how "overwrite the search term" that Sonarr passes to Jackett.
Should that be done in Sonarr? In Jackett?

I'd appreciate some help.

I tried to contact any of you guys by in other ways, but neither of you have any contact info on your profile.

**Comment by segator** [comment]
I switched to "medusa"  it have ugly interface but allow you more costumitzations
