### ISSUE TITLE
anime: support linked opening/ending (ordered chapters)

### ISSUE THREAD

**Issue by orbisvicis** [Sonarr/Sonarr#1557]
I currently drop linked openings/endings into the season folders, but Sonarr doesn't manage/delete them, so sometimes I forget about these leftover files.

**Comment by markus101** [comment]
Not entirely sure what you're referring to or how Sonarr should support them, can you elaborate?
When would they be deleted?

**Comment by orbisvicis** [comment]
I'm referring to [series such as this](https://anidb.net/perl-bin/animedb.pl?show=anime&aid=7729). A common release format is encode the opening and closing sequences into separate files, and then link them to the actual series. So that playing the first episode would show something like (mpv):

```
Playing: Steins;Gate.S01E01.Prologue.of.the.Beginning.and.Ending.Bluray-720p.mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 2: ./[WhyNot] Steins;Gate - NCED [BD 720p AAC][65D6B1FC].mkv
Match for source 1: ./[WhyNot] Steins;Gate - NCOP [BD 720p AAC][1B65071D].mkv
```

I'm not sure how Sonarr should support these files. Ideally, it would track the openings/endings just like individual episodes. While this release format is common, it is just as normal to find endings/openings encoded into the episodes files themselves. This would then become an issue with the anime database (xem?) sonarr uses. I think sonarr would still need to support matching filenames against endings/openings.

I currently manually copy these files into the Sonarr episode tree. This is annoying for two aspects:

1. No metadata is generated. [Sometimes this breaks Kodi, prevents it from listing the show](http://trac.kodi.tv/ticket/17086).
2. These files are not managed by Sonarr, so when I delete episodes (via the webui), the extra files will remain, consuming unnecessary space.

Perhaps as an interim solution, Sonarr could somehow warn or manage these non-managed video files.

**Comment by markus101** [comment]
> Ideally, it would track the openings/endings just like individual episodes.

They would need to be added to TheTVDB then (that's where Sonarr get's it's metadata from), but that would separate them as specials since they wouldn't be in the regular season order, which probably wouldn't play well with playing them properly.

> No metadata is generated. Sometimes this breaks Kodi, prevents it from listing the show.

Unless they are linked to an episode/special that's always going to be the case.

> These files are not managed by Sonarr, so when I delete episodes (via the webui), the extra files will remain, consuming unnecessary space.

Same thing here, without being explicitly tied to an episode/special Sonarr won't handle them. Based on the naming above I don't really see how Sonarr could handle them and know when to actually delete them since they aren't explicitly linked to an episode.

I think managing them would be manual, but could be handled through Sonarr once https://github.com/Sonarr/Sonarr/issues/286 is implemented.

**Comment by orbisvicis** [comment]
Just some thoughts, #286 is just as good:

> Based on the naming above I don't really see how Sonarr could handle them and know when to actually delete them 

The ordered chapter filename doesn't really matter, Sonarr can rename them however it wants. Sonarr already supports names such as:

```
[WhyNot] Steins;Gate - 12 [BD 720p AAC][65D6B1FC].mkv
```

Why not add support for the following:

```
[WhyNot] Steins;Gate - NCED [BD 720p AAC][65D6B1FC].mkv
[WhyNot] Steins;Gate - ED [BD 720p AAC][65D6B1FC].mkv
[WhyNot] Steins;Gate - NCOP [BD 720p AAC][65D6B1FC].mkv
[WhyNot] Steins;Gate - OP [BD 720p AAC][65D6B1FC].mkv
[WhyNot] Steins;Gate - OP1.a [BD 720p AAC][65D6B1FC].mkv
[WhyNot] Steins;Gate - OP1.av2 [BD 720p AAC][65D6B1FC].mkv
```

Then, don't depend on an external TV database. In the import section, explicitly allow importing openings/endings based on filename. Link them to all episodes, but don't generate metadata. Perhaps create a specific section (besides "Specials") such as "Openings/Endings" in the Series overview page. When no more files link to them, delete them. If the overview page is implemented, allow deleting them from there as well...

**Comment by xelra** [comment]
@orbisvicis The whole purpose of Sonarr is matching media files to tvdb. Having OPs and EDs would only be possible if Sonarr would fundamentally change at its core and allow for additional data sources, like for example anidb. OP and ED info is available there and you could make an anidb compliant library. Keep in mind though that anything else in your media center setup needs to be able to handle anidb compliant libraries then too though.

**Comment by markus101** [comment]
Sonarr supports them because it maps to a known episode in the external database, if you had `[WhyNot] Steins;Gate - 112 [BD 720p AAC][65D6B1FC].mkv` Sonarr would ignore it because it doesn't exist as a known episode.

Handling files that don't link to anything isn't something we want to do at this time, especially when you add in more complex options like automatically deleting them when a certain condition is met.

We've talked about anidb support before (https://github.com/Sonarr/Sonarr/issues/365), but it's not something we're focused on, but hopefully being able to handle extraneous files helps alleviate some of the issues here.

**Comment by Devian50** [comment]
I just found this issue trying to find some way to work around an issue I've been having. I manually downloaded an upgraded version of a season and it came with separated out NCOP and NCED files. The issue is that during manual import, Sonarr refuses to import the OP and ED files, meaning they also won't be copied to the final media library location. At the very least, I would like to be able to define OP/ED for the file in place of episode number so they would be kept together with the rest of their episodes.

Luckily, the way most anime at least does this is they use GUID linking for the separate files, which is completely unrelated to file name. This means it doesn't matter what Sonarr renames the files to, if it wants to rename them at all. The only issue is they need to be on the same drive, which can cause issues in systems like FreeNAS with ZFS datasets, or fully separate drives.

> The whole purpose of Sonarr is matching media files to tvdb.

I would imagine the auto-downloader portion is not related to matching media files to the TVDB. I believe this issue would relate to the auto-downloading and raw file management portion.

Please reconsider this issue, as it would be quite helpful for anyone dealing with higher quality encodes for Anime and such. I don't care about getting metadata, just that the files are neat and organized and none are left behind.
