### ISSUE TITLE
Init.d Autostart on Debian - Script Launching as root rather than nzbdrone user defined/created

### ISSUE THREAD

**Issue by schniederzero** [Sonarr/Sonarr#1560]
Hello Sonarr Team!

First of all, you're doing a great job with this software. It is amazing!

However, I have run into an issue with the Debian init.d startup script. I've copied the script from the wiki page [here](https://github.com/Sonarr/Sonarr/wiki/Autostart-on-Debian), but rather than starting up as the user nzbdrone, the service still starts as root. I've opened a topic on the Sonarr site and was provided some information from Markus, however that and a little of my own investigation hasn't turned up any answers.

Has anyone else run into this? This is persistent across two different Debian installs, meaning the script, and myself, are the common denominators here. 

Are there any debug logs I can pull? 

root 759 0.4 3.8 179980 119360 ? Sl 17:05 0:18 /usr/bin/mono /opt/NzbDrone/NzbDrone.exe

Valid user does exist:
nzbdrone:x:1001:1001:NzbDrone Sonarr Media:/opt/NzbDrone:/usr/sbin/nologin

I've given it a valid bash shell for testing, which made no different.
I've called --user, on top of your -c, in the init.d script per the man page examples, but it also made no difference. 

I'm relatively new to Debian (Jessie) and this is a learning process. I appreciate any help or direction that you can share. I will continue my own investigation and update if I find anything. 

Thanks!

**Comment by markus101** [comment]
The forums are the correct location for support and troubleshooting.

The issue lies outside of Sonarr and the init.d script was written by some one else. You should take a look at systemd as it should be included with Debian Jessie and is supposed to be used going forward (at least that is my understanding).

Forum thread for anyone else's benefit.
https://forums.sonarr.tv/t/is-nzbdrone-running-under-the-root-account-or-the-nzbdrone-user-defined-in-the-init-d-script/12808/4
