### ISSUE TITLE
Downloaded show two times

### ISSUE THREAD

**Issue by notexe** [Sonarr/Sonarr#1584]
Hi,

Sonarr just downloaded a proper release from a different release group. It shouldn't have needed the proper release, since the FLEET release was fine. So might be a bit of a bug I think.

Original: x264-FLEET
Redownload: PROPER.x264-KILLERS

\- Josh

**Comment by markus101** [comment]
> Sonarr just downloaded a proper release from a different release group

Propers are always from different release groups. Repacks come from the same release group.

It's not a bug the release was nuked for some reason, hence the proper. Sonarr doesn't know why the original release was nuked so it has no way of doing anything other than grabbing it because it was available.

**Comment by Taloth** [comment]
Nuked: missing.content.at.end_get.KILLERS.proper
