### ISSUE TITLE
Add customizing search pattern for season of tv shows

### ISSUE THREAD

**Issue by T-REX-XP** [Sonarr/Sonarr#1628]
Now we have search like this: "Taboo (2016) : S01"
but we need opportunity to set other search request which based on language of tracker. like this: "Табу / Taboo / Сезон: 1 / Серии: 1-2 из 8 "

thanks

**Comment by markus101** [comment]
Sonarr would first need to support other languages for metadata, since the name is also different (https://github.com/Sonarr/Sonarr/issues/269). We have an idea for a n aggregated search, similar to manual search that would be able to achieve this, but no current plans for full customization.

https://github.com/Sonarr/Sonarr/issues/1128
