### ISSUE TITLE
Specify deluge download directory

### ISSUE THREAD

**Issue by StrayanDropbear** [Sonarr/Sonarr#1638]
It would be nice to be able to set the download/complete directory for deluge torrents. this functionality is available on deluge itself.

**Comment by markus101** [comment]
What is the benefit of having Sonarr set these directories?

**Comment by StrayanDropbear** [comment]
Having the ability to split download/complete directories when using sonarr + couchpotato/radarr. It avoids them grabbing the wrong release.

**Comment by markus101** [comment]
Sonarr uses the label to determine if it is something it should import, when using Completed Download Handling, which you want to with torrents, Drone factory would cause the files to be moved.

**Comment by ewancoder** [comment]
I confirm that Sonarr can successfully download torrents through deluge and assign them a label, and deluge can manage these labels however you want.

My setup:
- in sonarr deluge settings category is set to "tv-sonarr"
- media management -> ignore deleted episodes is turned on
- use hardlinks instead of copy -> turned on
- download client -> remove turned on

In deluge:
- labels plugin enabled
- created "tv-sonarr" label with following settings
- queue: automanaged turned on, stop seed ratio at 2.00 turned on, remove at ratio **turned OFF** (sonarr will handle removal)

As a result, sonarr finds TV Shows, downloads them, renames, places in specific folders (label can be assigned to store data in specific folders) and when torrent is seeded at 2.0 ratio sonarr removes it (actually sonarr waits until deluge pauses download and then deletes related torrent and its data, but since we have hardlinked copy in separate renamed folder - all our data is safe).

Also, when you delete any episodes from you disk manually (if you have no space left) - sonarr will automatically unmonitor those episodes and will not try to download them again.

**Comment by StrayanDropbear** [comment]
Yes that feature works fine but for me not being able to set complete directories is a problem. I run scripts on the complete directory, I run them on "tvshows" but when i want to add a different torrent manually to deluge I need to manually specify the directory from Deluge. having the feature to change directory means i can just run scripts on the folder i know is only going to get tvshows from sonarr.

**Comment by Taloth** [comment]
I don't understand how that changes anything, since Sonarr sets the label, deluge sets the directory via the label. How would changing the directory by Sonarr directly change anything?
If you add something to Deluge manually, simply set the appropriate label and deluge will set the directory.

**Comment by asko85** [comment]
hey guys , i believe i have things set up correctly, but the final step just doesnt seem to be happening.
i have deluge download the episode to a folder "unsorted", and then move completed to "download/tv", sonarr is communicating with deluge and sending files successfully both have the label "tv". but at the end downloads stay in "unsorted"
