### ISSUE TITLE
trying to get free space of missing root dir

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#1639]
removed harddrive which was linked to a series, so on startup I got a health check that it didnt exists.. noticed tons of spam for it throwing:

```17-1-22 23:25:54.4|Warn|DiskSpaceService|Unable to get free space for: F:\

[v2.0.0.4545] System.IO.DirectoryNotFoundException: F:\
   at NzbDrone.Windows.Disk.DiskProvider.GetAvailableSpace(String path) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Windows\Disk\DiskProvider.cs:line 33
   at NzbDrone.Core.DiskSpace.DiskSpaceService.<GetDiskSpace>d__9.MoveNext() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DiskSpace\DiskSpaceService.cs:line 73
```

it knows it doesnt exist (health check), so why try and get the free space for it? should be smarter...

I removed the tv series that was linked to it, health check had to be manually ran to get it to remove the warning...  not sure if you want it to do a quick root dir check when removing series

**Comment by markus101** [comment]
Is that the full stack trace from the error?
Health checks are really only a front-end enhancement, the back end code doesn't track them to know that a root folder is missing and not doing something because of that and I don't really see that changing because they are separate things.

Running a health check on series removal or edit makes sense though (there are probably quite a few events we could tie into).

**Comment by thezoggy** [comment]
that is all that the logs show (info level)..
