### ISSUE TITLE
Disable folder creation

### ISSUE THREAD

**Issue by sdothum** [Sonarr/Sonarr#1670]
Is there any way to disable automatic folder creation by sonarr? I have to manage the folder nzbget drops episodes into anyway so would prefer sonarr not to create series folders there (the folder names I use don't contain blanks). Even if  I remove the folder sonarr creates, it recreates it the next time it issues an update. I suppose  I could just point sonarr to a folder different from the one nzbget manages and just ignore it -- hopefully, without consequence.

**Comment by markus101** [comment]
Please use the forums for support.

Sonarr doesn't create empty folders by default:

![image](https://cloud.githubusercontent.com/assets/413544/22858420/add9d7d8-f071-11e6-83eb-98dd911083ab.png)

(An advanced setting on the media management page that defaults to off).

>  I suppose I could just point sonarr to a folder different from the one nzbget manages and just ignore it -- hopefully, without consequence.

No more of an issue than things current are, since Sonarr will always treat files it hasn't seen on disk as missing.

**Comment by TGM** [comment]
Where is this option? Cannot see it in  Sonarr Ver. 2.0.0.5252
