### ISSUE TITLE
Multiple User Support

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1682]
Multiple users would allow user's to allow family members and friends to access Sonarr without giving them full access.

Role based access control would allow different roles to be assigned to each user that would give them different levels of access.

- Superuser - Master user, can add/remove users, alter any settings
- Admin - Master user, can add/remove users, alter settings (limited by Superuser)
- Show Manager - Can add new shows, but can't alter settings
- Read only - Can only view existing shows, can't edit or add series nor can they access settings

There could be more roles as well, making it flexible, but somewhat guided so it's not overwhelming and remains functional. Any other ideas around multiple users is welcomed, nothing is currently set in stone and this is only a proposal, it may not be something we end up implementing, but it's been something I've been thinking about.

**Comment by maxkoryukov** [comment]
What you think about some kind of **custom policies** ? I mean, it could not be sufficient to have only four predefined roles: `[Superuser, Admin , Show manager, Read Only]`.

I would like to suggest the following solution:

We could add **meta** options for each setting. I suggest to use these meta':

* visibility
* editable

If these meta-settings will depend on role (for *role1* - visible and editable, for *role2* - only visible), then the proposed system will have an ability to configure custom roles (and listed predefined roles too)

**Comment by markus101** [comment]
Yeah, I don't think there needs to be a limitation on which profiles exist, just some defaults to start it off.

I think there will need to be some limitations on things though, for sanity and ease of implementation, probably in some logical groups for settings outside of providers (download clients, indexers, etc) and the entire provider would be editable if you had edit rights. Going further than that would be to difficult to maintain and would likely lead to support issues all over the place, especially if new settings are added.

**Comment by maxkoryukov** [comment]
Previously I have implemented simple framework, there were implemented such things, like:

* boolean checker
* dropdown element
* text input
* number input
* combobox input
* switch (boolean with dependence subfields)
* ....

Each component have:
* property `readonly`
* property `visible`
* property `id`
* property `value`

Most properties are set outside the component, but each component should correctly handle all properties

**Comment by theCheek** [comment]
This is an excellent suggestion as I have multiple users requesting shows inside Plex which are sent to Sonarr, and they currently have no way of seeing the status of the downloads because I don't want to give them access to deluge or sabnzbd as they will probably break stuff. To have a user class who can only see the queue would solve this.

**Comment by gold007eye** [comment]
Another group that I think might be good would be "calendar only" access.  So for family and friends that you can let just see what's upcoming or past (which would also let them see if it's downloaded or not) so that it could be used more like a "Guest TV Guide".

**Comment by mbze430** [comment]
this would be a great feature to have. +1

**Comment by skandix** [comment]
need to say myself to have this kind of feature would just be awesome.

**Comment by E-v-o** [comment]
Please consider adding this, even starting out with extremely basic user settings would be great, mainly just locking users out of config/settings.

**Comment by glenngit** [comment]
Why is this not implemented yet?? 💯% required.

**Comment by theCheek** [comment]
@glenngit I'm sure the devs don't need such pointless comments. Remember this is a project we are all benefiting from for free. 

yes it would be a great feature, but I don't think its 100% required from a functionality point of you. One solution for a sort of 'read only' mode for users is to install HTPC Manager (https://github.com/styxit/HTPC-Manager) and enable Guest access. They can then use Sonarr (and radarr) functions such as adding stuff, but they can't get to the back end at all.

**Comment by marksie1988** [comment]
Would love this feature. I don't want my family changing settings etc. So I want to be able to create accounts with different settings.

**Comment by Kyrluckechuck** [comment]
Since this has been around so long and is still open, can we get clarification from anyone on the idealization team about what the requirements/constraints of a PR for this would be? 

What is the agreed-upon feature-set or limitations so that someone can help contribute a PR for this?

**Comment by robbiemcleod56** [comment]
+1 on this feature request. 
For those of you looking for a solution to this right now (and it's not exactly an easy solution, can only add shows, seems to prefer searching by each episode rather than whole seasons, and it also requires Plex or Emby to be installed,) would be to use Ombi. Took me a few hours to get fully set up but now people can just log in to Ombi's dashboard and request what they want. Works with Radarr and Lidarr as well.

**Comment by linedpaper** [comment]
Would love to see OIDC and OAUTH2 support in addition to LDAP and SAML already mentioned.  Currently using traefik-auth forwarding in front of this to provide OIDC, but it breaks 3rd party apps due to the pre-auth, would love to see it built in or be able to accept forwarded auth from a reverse proxy!

**Comment by yoanndelattre** [comment]
+1 Do we have any news on this feature ?

**Comment by bakerboy448** [comment]
when there is an update to share there will be an update shared

for `+1` simply thumbs up the OP; comments to such are unnecessary

**Comment by lknite** [comment]
OIDC should be prioritized over others, SAML can offer more options but oidc is currently the most popular and provides everything we need in this use case.  LDAP integration is old school at this point, instead users should setup an identity manager such as Keycloak, and use ldap behind keycloak as the source for user accounts.  Keycloak and other identity managers are able to use github, Google, ldap, behind the scene.

I'd suggest devs interested first get oidc working with something like harbor, so you know the oidc setup is good then add the ability to login to sonarr, you can add a "groups" claim, which with ldap can be active directory groups the user is a member of.  First can allow login if a user is able to login, then only allow access if user is a member of a group, then you can start thinking about what an admin account should be able to do vs a read-only account, and later maybe start granting more specific rights based on groups.

Just being able to login and only grant members of the "admin" group would be awesome so by default we aren't giving everyone access.

**Comment by lknite** [comment]
Put together a video for those who are considering whether or not to add OIDC to an application:

[OIDC for Contributors](https://youtu.be/E3fjncdkaOI)

**Comment by joshka** [comment]
+1 to OIDC rather than other options (greatest reach, least integration hassle).

I'm starting work on this and want to make sure I get some feedback and buyin before going too far. I recently slapped a PR for devcontainers in https://github.com/Sonarr/Sonarr/pull/6695 as a precursor to this.

SSO and multi-user are related, but sort of orthogonal, so I'm unsure whether to reopen https://github.com/Sonarr/Sonarr/issues/2477 and discuss the OIDC part there or continue here (choosing the latter, but will probably move to the former at some point).

This issue breaks down pretty naturally into the following parts:
1. Support multiple users (user1, user2)
2. Support users being specific roles (user, admin)
3. Support more advanced / specific roles (superadmin, guest)
4. Support logging in using sso (user1@sso)

The current state of play is that:
- the backend database, userrepository, and userservice all supports multiple users, but the frontend doesn't support adding extra users.
- The backend doesn't support roles.
- None of the pages support authorizing specific actions with roles.
- The backend doesn't support sso.

The order I think it makes sense to implement this is:
1. Add support for the `admin` role to db/repo
2. Assign the admin role to all existing users in an installation as part of a schema migration
3. Lock down the Settings pages to `admin` only
4. Add create / edit users function to the General tab
5. Add OIDC as an authentication method with config mentioned in above youtube vid at 8:42 (https://youtu.be/E3fjncdkaOI?si=9YQ7I1HN3RmSIIXk&t=522
6. Update auth policy and controllers to support oidc
7. More OIDC work to be expanded on

Some questions / clarifications
1. Are we fine with the initial implementation of this being just Admin/user? (I'm assuming yes, and we can iterate)
2. What other things in Sonarr should be admin only aside from just settings? (restart / shutdown probably)
3. Would it make sense to create a security settings page instead of putting user config into general?
4. Would it be fine to reopen https://github.com/Sonarr/Sonarr/issues/2477 to expand on the OIDC parts of this?
5. More OIDC questions to be moved to 2477 (roles -> group mapping, how to manage allowing users etc.)
6. Does enabling OIDC still keep forms login available (I'm assuming yes here too as if your SSO provider is down, then not being able to login to all your things is a problem)
7. How does work on Sonarr generally flow to the other *arrs - (I think this is the source and the others are downstream, but please correct me if I'm wrong on this)
8. When things move from single user to multi-user, obviously it becomes necessary to think about how to track who did what where. How much should change in the database / logging to handle this?

It's been a while since I've written any .NET (though I did it for a pretty decent amount of time ~2003-16). If anyone has some general tips for working with .NET in VSCode on a Mac, that would be great (I don't have a windows setup right now). I see there's some work to get up to .NET 8.0 in flight in https://github.com/Sonarr/Sonarr/pull/6580.

So far I've locally setup lldap and Authelia as an IdP and successfully run some basic OIDC PoC spikes in a test .NET project. Authelia is a pain to configure as it's all yaml base, so I might convert to using either Authentik or Keycloak as I suspect they may be easier to setup for the others testing this. Both seem heavier weight than Authelia however, so perhaps a nicely configured docker-compose file and supporting configs for authelia would be the right approach. If anyone has advice based on comparative experience across these IdPs that would be great.

Can I get an add on the development discord channel for handling any more real-time questions about this?

**Comment by markus101** [comment]
Another current state of play item since it falls in between a couple you listed

- The backend doesn't differentiate between users at the API level as it's all just single API to do everything, likely want to switch to JWTs there, with the ability for user's to have a separate API key for external services to access Sonarr on their behalf

Answers / Comments:
1. Just two roles to starts sound reasonable
2. Deleting series? Deleting files from a series? Perhaps a simpler approach for multiple users would be admins and read-only users, that way we avoid the web of "what can a user do/not do?" until we hash out roles / role permissions
3. I think so
4. Sure, I will re-open
5. 👍 
6. I think so, there are other security related things around that as well though, like always-on auth, but I think the first admin user always needs some sort of direct authentication
7. It depends, but a lot of things usually start in Sonarr then get pulled in downstream, sometimes they land in Radarr/Lidarr/Prowlarr and get backported, but that's less consistent (and sometimes has other hurdles)
8. I think we should be able to add that context to pretty much all logging and should track who did what within the DB as an audit log of sorts

Yes, I can add you, though a separate channel might make sense as well. What is you username on Discord?

**Comment by joshka** [comment]
> likely want to switch to JWTs there

It's probable that an opaque token is still fine for these use cases - just one per user or store the allowable actions in the db. If that doesn't work out for whatever reason, I'd consider PASETO over JWTs for the reasons noted in https://paseto.io/ and https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid - a minor point worth picking up later though.

> Perhaps a simpler approach for multiple users would be admins and read-only users
👍 

> I think the first admin user always needs some sort of direct authentication

There are some reasonable flows that can allow the OIDC setup to be the only way that authentication works, but it sounds like you're on the same page with me about doing what works for this.

On the Authelia / Authentik / Keycloak for testing thing, I was thinking about this more today and one big benefit of Authelia is the same as the downside - I can use a yaml file to define the user info for testing. That should makes the OIDC parts really easy to test.

**Comment by joshka** [comment]
Some brief notes based on taking a visit through the source to document the current state and make sure I cover the bits that need to change:

- On First Run, a default config file is created with `AuthenticationMethod` set to `None`.
- When the user visits the site, the AuthenticationRequiredModal is displayed which enforces that the user choose an auth method before continuing.
- Currently that provides Basic and Forms mode options and allows the user to enter a single username, password and a password confirmation
- The data for this form is loaded from the HostConfigController at api/config/host. The controller combines info from the config file as well as attempting to load a single user from the db if it exists (or just empty defaults otherwise)
- Clicking save puts the updates back to the api via api/config/host/1
- If the username and password are not empty (which is checked on the frontend), then the user is upserted into the db. If there is no current user, the user info is added (password is hashed), otherwise password for the single existing user is updated.

The same get from api/config/host and put to api/config/host/1 is done when the settings/general screen is loaded / saved.
- The component loaded is the GeneralSettings component which includes the SecuritySettings component

Note that currently in both places the username can be changed directly at the same time as the password.

<details><summary>Screenshots of current behavior</summary>
<p>

<img width="729" alt="image" src="https://github.com/Sonarr/Sonarr/assets/381361/062d62b7-8285-46f8-9f1a-ca3d6f56c885">

<img width="702" alt="image" src="https://github.com/Sonarr/Sonarr/assets/381361/2a90cdfa-f98e-41db-a790-1f0906a2d787">

</p>
</details> 

---

AuthenticationMethod = None triggers the first run mode
It's possible in a mutli-user setup, there could be more than 1 user in the db already when a user changes the config file to auth method = `None`. We can handle scenario either by adding the full user management (multiple users) to the auth required modal dialog.

---

The simplest implementation for this is to add all the users to the api calls instead of just a single user.
- change the API from a single username / password / confirmation property to a list of (id / username / password / confirmation)

The UI can be fairly simple here initially too. A list of users, click to edit, click to delete, click to add new. Prevent removing the last user in the list.

Backend will run through the list and compare against the db users and do the update/remove/adds (this list is likely small enough that doing a full load and compare is quick enough - no need to excessively complicate this)

**Comment by joshka** [comment]
I'm still working on this, just was on vacation for the last week or so.

**Comment by DevDema** [comment]
Any updates? This would be really cool to have

**Comment by joshka** [comment]
I got caught up with other things and let this drop. It's still on my someday list though.

**Comment by Alexk2309** [comment]
> I got caught up with other things and let this drop. It's still on my someday list though.

Hi, @joshka would it be okay for me to continue on your work? This looks very interesting and I would like to have a crack at it. Thanks!

**Comment by joshka** [comment]
Absolutely, go for it. Feel free to ping me on PRs if you want. You'll need some understanding of Redux (which was my barrier), done in the older style than is found in the current docs, and you'll need to come up with a design for both the new install / existing install code. It's possible that the right way to do this is to mark one user as a super admin or something like that that can never be removed. Also keep in mind a design that makes it feasible to do the OIDC side of this too.

**Comment by Alexk2309** [comment]
Hi everyone currently still working on this issue, I have gotten the basics done. 

I managed to add a new setting for 'users', which allows for the creation and deletion of users. I've also managed to integrate roles into different users as well. 

However, I'm stumped on how to restrict what endpoints depending on the roles of a user, and what UI not to render based on the user's roles.

After digging I've realized that the API key is what authorizes a user's access to certain endpoints. 

I'm not sure how to go about things, do guys think that multiple API keys should be made for each user and then their respective roles will determine their level of access for their Api-Key?

Or is there another way to go about things that I'm not seeing? Appreciate any help that comes my way.

Please also clarify if any of the points I've made above are wrong too 😄 

CC: @joshka , @markus101

**Comment by markus101** [comment]
At a minimum an API key per user would be required, then on the API side some sort of RBAC (Role Based Access Control) would need to be applied. Offhand I'm not sure how that would be best achieved though.

**Comment by Alexk2309** [comment]
Hi @marksie1988 cool, sounds good, I'll work on implementing a new API key for each user. Do you think it would be possible to get an invite to the discord server that way I can discuss the best way to tackle this problem?

Thanks!

**Comment by markus101** [comment]
🤔 you've pinged the wrong person. The discord server is public and linked from sonarr.tv

**Comment by markus101** [comment]
@thezak48 @bakerboy448 @Thirrian moving the discussion on private trackers here.

Given that this issue has been open for as long as it has it's more than a little frustrating to learn now that multi-user support would lead to them blocking access from Sonarr for "account sharing" without specifics on what leads to that decision.

Are there any specific functions that they are concerned about?
Would having a single admin user eliminate those concerns?
Would limiting specific functionality eliminate those concerns?

As of right now a single user could be shared by multiple users, giving them all admin access and all the concerns that go with that. The obvious answer is don't share credentials, but being able to provide limited to access would work towards doing that.

> none of these request apps or watchlist would provide direct access to hitting indexers / trackers.

In the PT sense, neither does Sonarr, most of that communication goes through Prowlarr and nothing restricts multiple instances of Sonarr/Radarr/etc from connecting to a single Prowlarr instances.

> I.e. request apps can require approval of requests so a user can't trigger 100 seasons being searched at once

Realistically Sonarr could do this as well, though at the same time, it'd be a lot of effort to gain something already available in another app.

**Comment by zakkarry** [comment]
I think given the risk associated with this, and the functionality being available in already accepted methods of requesting (notifiarr, *seerr, ombi, petio, etc etc) - providing this functionality seems like a risk that should be avoided.

What does this provide that is otherwise currently unavailable or unachievable with relative ease? 

If there is something, is that worth putting Sonarr at risk like this?

Given that there is work actively being done on the implementation (reviews, coding, etc) I think it would be best to actually pause things on moving this forward before you know that it wont result in negative consequences to the arr ecosystem as a whole (since this potentially could be pulled downstream at some point)

I get that you're asking for clarification from the trackers, but frankly I question whether getting a few opinions or OKs is truly going to be a sign that it is unanimously acceptable across the majority of the trackers, it is naive to think any tracker(s) speaks for all trackers, and hunting down admins for all of them does not mean that at any time in the future when potential abuse does become an issue with the users feature - that they wont change their mind suddenly and you will then be up shits creek with this having been implemented.

The fact that there is a question, at all, of the acceptance of this screams to me to tread lightly pursuing this actively, as the mere development of it amongst the lead developers says that you condone and support this, while many who run what we basically rely on might take dramatically different approaches and not be inclined to voice those objections to you at all.

It's very easy to lose trust, especially in the higher tier private trackers, and very hard if not impossible to be considered trustworthy again after this.

This scares me.

**Comment by bakerboy448** [comment]
I think another viewpoint here is - similar to how the External Auth method is buried - it makes it a little less easy for users to blatantly share +  keeps a slightly lower footprint overall..

**Comment by joshka** [comment]
What's the perceived downside to multiple users here? If you have an account on a service that has some sort of limit (API calls per month, ...), and your software uses that limit to its fullest, does it really matter if there's one user or several? How is the scenario of having a multi-user request app in front of Sonarr different from having a multi-user Sonarr app?

**Comment by zakkarry** [comment]
Private trackers explicitly say "Do not share your accounts" - and this does exactly that.

I'm not sure why you would be under the impression that this is anything but sharing accounts explicitly and natively, but it opens the entire native experience up to a lot of scrutiny and backlash. 

I'm not sure if you are unfamiliar with private trackers, but what you're implying after reading my post and many of the others implies you may be.

**Comment by joshka** [comment]
> I'm not sure if you are unfamiliar with private trackers, but what you're implying after reading my post and many of the others implies you may be.

I'm familiar (but don't use any). I was referring mainly to the usenet side when talking about API calls here. But the same thing applies to private trackers. There your resource is the leech ratio. So long as that's adhered to 🤷. Obviously you might claim that there's a financial side of this too, where multiple users would otherwise need multiple accounts.

> Private trackers explicitly say "Do not share your accounts" - and this does exactly that.

But so does using Overseer or any multi-user frontend to Sonarr / *arr product. Following the logic of your argument here, should Sonarr remove its own API keys altogether because they can be used by multiple users, and some of the services which are behind that might not want multi-user access? Sonarr doesn't directly download / interact with the tracker, that all happens with the downloader program of choice. Should the downloaders remove their api keys because they can be used by multiple coordinator services? If I point two Sonarr instances at the same downloader, should the downloader detect this and prevent it?

These all seem like points where:
- There's a policy that can't reasonably be enforced with a technological measure
- There are valid usages that don't conflict with the policy (none of the usenet indexers I use specifically call out that multiple people cannot use the api calls, neither does my usenet provider.

There is one thing I think I can see does make sense here, and that is that care should be taken to only allow the admin user to read / modify sensitive login info for external sites to avoid sharing of credentials (as opposed to the actual sharing of the service).

My main interest here is mostly in the OIDC based SSO side of this, rather than the multi-user side. I want proper user management so that I can chuck the user info into Keycloak and login once rather than once per service. Adding a well thought out multi-user concept is a (mostly) necessary part of this. (Technically this is possible to implement against a single user system, but it would be pretty janky to map a multi-user auth system to a single user system in a way that makes sense).

I'll ask the same question again. How does Sonarr supporting multiple users put a private tracker in a different situation than they are if there are multiple users accessing Sonarr from some program through Sonarr's API?

**Comment by CLHatch** [comment]
Technically it's not sharing accounts. Sharing accounts would be using one
account on multiple people's computers. This is one computer downloading.
Just multiple people telling your server what to download to your single
computer.

**Comment by zakkarry** [comment]
> Technically it's not sharing accounts. Sharing accounts would be using one
> account on multiple people's computers. This is one computer downloading.
> Just multiple people telling your server what to download to your single
> computer.

Sadly, this is only YOUR definition and desire of usage to have. There is no tracker of worth that has a no sharing rule that would say what amounts to "oh its all good share away just proxy your api calls through one source!"

There is also no means to enforce any household or family only rules. 

Both are ridiculous assertions to make in defense of this feature, and anyone who has been around the PT community at all should very much be aware of the pitfalls here. Trackers already deal with sharing of accounts, and from discussions I sought out with some staff, wont appreciate new means of doing so being this blatant.

**Comment by Alexk2309** [comment]
As the main contributor to this new feature, I would like to ask why these concerns weren't brought to light, many years ago. 

This issue has been up for about 7 years, how come none of these concerns weren't voiced earlier? Only when I started development on this issue, it becomes a problem. I practically spent my uni holidays working on this project, and it will be more than a bit frustrating for all my work to be scrapped. Especially because I was really passionate about this feature.

**Comment by zakkarry** [comment]
> As the main contributor to this new feature, I would like to ask why these concerns weren't brought to light, many years ago. 
> 
> This issue has been up for about 7 years, how come none of these concerns weren't voiced earlier? Only when I started development on this issue, it becomes a problem. I practically spent my entire uni holidays working on this project, and it will be more than a bit frustrating for all my work to be scrapped. Especially because I am very passionate about this feature. 
> 

I completely understand that, and frankly feel bad to the end for you. 

I will also add that if we're merging features based merely on not hurting a potential contributors feelings, thats flawed.

I think the reason this may notnhave been brought up is that the audience to issues on the repo is pretty limited. Particularly to the tracker staff who would be concerned with this. 

PRs get significantly more eyes, and thus, when you opened one... people noticed and now more has been discussed.

**Comment by wplinge** [comment]
A technically illiterate line in the sand drawn by outside parties isn't a great reason either.

**Comment by zakkarry** [comment]
> A technically illiterate line in the sand drawn by outside parties isn't a great reason either.

The people providing the majority of content at the top levels for the entire community are hardly baselessly making demands.

There are reasons, quite obvious ones if youbread the discussions. There are rules on PTs forna reason and this flagrantly disregards those rules.

Tell me how useful do you think Sonarr is without PTs available for a majority of the user base?

**Comment by joshka** [comment]
> Tell me how useful do you think Sonarr is without PTs available for a majority of the user base?

I have never used a PT with Sonarr (the last one I used closed down when Sonarr was very young). I find that Sonarr is quite useful without them though.

Can you post some of the specific PT rules that you're concerned about here?

Have you got any specific information (more than hypothetical) that you can share that suggests that tracker runners might be concerned about this change?

I'm also curious how you'd suggest soliciting their feedback on this issue (given they haven't chimed in on it in 7 years).

I wonder if anyone else finds it a little humorous that we're debating preventing certain technology implementations on policy terms when there's valid rationale for that technological implementation to exist that doesn't trigger the policy. There's a parallel of sorts with MPAA's position about breaking CSS on DVDs.

**Comment by v3DJG6GL** [comment]
I really don't think this is account sharing.

As some others have mentioned, other frontends like Jellyseerr and Overserr are in some ways the same principle as this PR. And I've never read on _any_ private tracker that such frontends are prohibited in any way.

Also, the one app that manages all logins for private trackers is Prowlarr, for example, not Sonarr/Radarr. And as far as I understand this feature, these credentials are not shared by Prowlarr with possible multiple Sonarr/Radarr users. Sonarr/Radarr only use Prowlarr's API to make queries. Grabs are still made via Prowlarr. No private tracker account is passed on to other users. As I said, this is exactly how Jellyseerr & Overserr have been doing it for a long time.

Furthemore, not all *arr users use private trackers. Some supposedly only use public trackers, as I did for a long time. And some may only use the Usenet part of this ecosystem. All these users are not affected by these concerns anyway.
_If_ this would really turn out to be a potential problem, an infobox could also be added to inform multiple users about these concerns.

**Comment by zakkarry** [comment]
I'm going to bow out of this discussion on here, because between users who are unfamiliar with PTs and users who believe that at least several high-level trackers don't associate this with account sharing - despite there being opinions voiced from those making these decisions as staff/devs on the PTs that they have these concerns (as well as other implications of rule violations I won't get into here at this point) - it's a little like arguing with a wall.

Your opinion of this feature, in this case, unfortunately, does not matter to PT staff.  If it does, go make your case to them. 

This puts the entire arr eco-system at risk. The fact that it is dismissed with "yea but i dont think so" as a reason/justification is laughable as a defense. This may enable the same end result as other request applications but goes about it in an entirely different way. 

Furthermore, API access does not equate to multiple users. 

To make an analogy - You can ask ChatGPT questions and get the responses, but that's not the same thing as getting access to ChatGPT's backend and models.

**Comment by joshka** [comment]
There is not a single user in this thread that has identified themselves as PT staff. There is not a single piece of evidence or any statement that there is such a specific opinion held. You're also stawmanning the arguments of those that don't have your perspective. You've talked in generalities and hyperbole about the problem, but don't seem to be willing to cite anything that backs your perspective. I've asked for that info a couple of times, and I'd be receptive to hearing it. You're the one in the inflexible position here.

Are you perhaps speaking as a PT admin that opposes this? If so speak for yourself and own your opinion. Lay out the argument about why this is a problem from the perspective of someone for whom it is a problem. If you're not, provide evidence that your opinions are what the PTs actually feel is problematic here.

Do these sound unreasonable asks to you?

**Comment by zakkarry** [comment]
I'm not at liberty to disclose anything I don't want to or think puts risk on any other parties. Those who are in charge of these decisions have made their opinions clear to the Sonarr team and those of us who develop projects for this community and sought them out, and it's obvious why no one would out themselves as PT staff here. 

Those of us with ties to PTs and the community at large have spoken to them. If you don't believe us, go ask the staff/devs yourself. It is not any of our job to give you logs or screenshots of our conversations. If they are in doubt, we as developers have ties to the staff in question and will verify them ourselves and pass the sentiments along to the parties who steer this, not the public at large. That's not how this works.

No one is required to give you evidence or provenance to substantiate anything. These are not my opinions, I'm merely echoing what has been said to myself and numerous others on the Sonarr development team and adjacent projects already.

Whether you believe it to be one person rambling in a GHI or not makes no difference to me in the least.

**Comment by strongy** [comment]
> I'm not at liberty to disclose anything I don't want to or think puts risk on any other parties. Those who are in charge of these decisions have made their opinions clear to the Sonarr team and those of us who develop projects for this community and sought them out, and it's obvious why no one would out themselves as PT staff here.
> 
> Those of us with ties to PTs and the community at large have spoken to them. If you don't believe us, go ask the staff/devs yourself. It is not any of our job to give you logs or screenshots of our conversations. If they are in doubt, we as developers have ties to the staff in question and will verify them ourselves and pass the sentiments along to the parties who steer this, not the public at large. That's not how this works.
> 
> No one is required to give you evidence or provenance to substantiate anything. These are not my opinions, I'm merely echoing what has been said to myself and numerous others on the Sonarr development team and adjacent projects already.
> 
> Whether you believe it to be one person rambling in a GHI or not makes no difference to me in the least.

no offense but these are exactly your opinions until you can prove they are not which you have not nor has anyone substantiated these claims

**Comment by zakkarry** [comment]
No, it's "the Sonarr dev team and adjacent projects (like the one I'm a part of among others) have spoken to the staff in question, and we all have gotten the same responses" - and we've also collectively discussed this as developers, you were, for obvious reasons I don't have to point out, not a part of these conversations. You've instead asked for PT staff to out themselves on GitHub and for first-hand conversations to be provided to you on a platter.

No offense, but if you can't tell you are not the ones who matter in this scenario. If you were, then you could either go speak to the staff yourself like many of us have, or you would have been a part of these conversations about the "feature" we've collectively had where this was all discussed at length.

The level of naivete and ignorance on display by users whose responses are akin to "nuh uh" and "I don't believe you" is astounding. 

I have no reason to lie about this, and this isn't some throwaway account on github. Check my GH profile. Multiple Arr team members have chimed in here as well, and you still think it's just fiction.

**Comment by strongy** [comment]
> No, it's "the Sonarr dev team and adjacent projects (like the one I'm a part of among others) have spoken to the staff in question, and we all have gotten the same responses" - and we've also collectively discussed this as developers, you were, for obvious reasons I don't have to point out, not a part of these conversations. You've instead asked for PT staff to out themselves on GitHub and for first-hand conversations to be provided to you on a platter.
> 
> No offense, but if you can't tell you are not the ones who matter in this scenario. If you were, then you could either go speak to the staff yourself like many of us have, or you would have been a part of these conversations about the "feature" we've collectively had where this was all discussed at length.
> 
> The level of naivete and ignorance on display by users whose responses are akin to "nuh uh" and "I don't believe you" is astounding.
> 
> I have no reason to lie about this, and this isn't some throwaway account on github. Check my GH profile. Multiple Arr team members have chimed in here as well, and you still think it's just fiction.

again since no actual developers have chimed in on this its just you and your opinion and no matter how you spin it, its still going to be that until they actually say something.

**Comment by zakkarry** [comment]
Poor @mynameisbogdan - I guess you and I aren't developers anymore!

Hilarious.

**Comment by thezak48** [comment]
> > No, it's "the Sonarr dev team and adjacent projects (like the one I'm a part of among others) have spoken to the staff in question, and we all have gotten the same responses" - and we've also collectively discussed this as developers, you were, for obvious reasons I don't have to point out, not a part of these conversations. You've instead asked for PT staff to out themselves on GitHub and for first-hand conversations to be provided to you on a platter.
> > No offense, but if you can't tell you are not the ones who matter in this scenario. If you were, then you could either go speak to the staff yourself like many of us have, or you would have been a part of these conversations about the "feature" we've collectively had where this was all discussed at length.
> > The level of naivete and ignorance on display by users whose responses are akin to "nuh uh" and "I don't believe you" is astounding.
> > I have no reason to lie about this, and this isn't some throwaway account on github. Check my GH profile. Multiple Arr team members have chimed in here as well, and you still think it's just fiction.
> 
> again since no actual sonarr developers have chimed in on this its just you and your opinion and no matter how you spin it, its still going to be that until they actually say something.

![image](https://github.com/user-attachments/assets/7873c9ba-d62b-4cf2-babf-a930eef79a05)
https://discord.com/channels/383686866005917708/383687854057979906/1282769042159046726 
Are you happy now?

**Comment by zakkarry** [comment]
No way! I wasn't lying? Who would have thought.

**Comment by bakerboy448** [comment]
- indexers are going to be shared and not unique per user

No great solution here. Users would be unable to utilize this feature if their sites prohibit it....sites likely to outright ban \*Arr

- even if the indexers are unique per user and users add multiple instances of the same indexer, sharing the same IP is also a big issue with not only PT but also usenet indexers.

This would get extremely complex...


- searching from the UI (same as [GET /api/v3/release](https://sonarr.tv/docs/api/#/Release/get_api_v3_release)) you can see the passkeys for native indexers and the apikey for Prowlarr/Jackett in the downloadUrl property.

This - IMO - is what would kill this feature and meets the literal criteria for account sharing. Fact: your creds are here. Fact: others have access. Fact: your account is shared.  Possible work around would be stripping most functionality away from any "multi-user" role.  Single admin role and some very limited view only.   Ultimately that wouldn't provide any significant benefit over the existing request apps that already are general not a problem.

- being able to download backups from the UI with others credentials saved in the sqlite sonarr.db. this would still be an issue even if you restrict this to only being able to see the backups from appdata since the credentials are saved in plain text in the indexer settings column.

Resolvable by disabling feature completely....and only allowing a single admin role to see the api key that can access the backup endpoints

**Comment by zakkarry** [comment]
> * indexers are going to be shared and not unique per user
> 
> 
> No great solution here. Users would be unable to utilize this feature if their sites prohibit it....sites likely to outright ban *Arr
> 
>     * even if the indexers are unique per user and users add multiple instances of the same indexer, sharing the same IP is also a big issue with not only PT but also usenet indexers.
> 
> 
> This would get extremely complex...
> 
>     * searching from the UI (same as [GET /api/v3/release](https://sonarr.tv/docs/api/#/Release/get_api_v3_release)) you can see the passkeys for native indexers and the apikey for Prowlarr/Jackett in the downloadUrl property.
> 
> 
> This - IMO - is what would kill this feature and meets the literal criteria for account sharing. Fact: your creds are here. Fact: others have access. Fact: your account is shared. Possible work around would be stripping most functionality away from any "multi-user" role. Single admin role and some very limited view only. Ultimately that wouldn't provide any significant benefit over the existing request apps that already are general not a problem.
> 
>     * being able to download backups from the UI with others credentials saved in the sqlite sonarr.db. this would still be an issue even if you restrict this to only being able to see the backups from appdata since the credentials are saved in plain text in the indexer settings column.
> 
> 
> Resolvable by disabling feature completely....and only allowing a single admin role to see the api key that can access the backup endpoints

So limit the entire interface to read only for any additional users, and remove a bunch of features.

lol...If user sharing is not the goal then this should be a great solution right?

What was the point again?

**Comment by markus101** [comment]
The concerns of PT admins aren't up for debate, they've voiced their concerns, we've listened and the unfortunate reality is any form of multi-user support directly within Sonarr will be seen as a method for account sharing leading to Sonarr and other arrs being banned. You may not agree with this and that'd fine, but it's not up for debate.

@joshka @Alexk2309 I know you've both put in some time and brainpower into this and I'm sorry that these discussions happened after you put effort into it. In order to make use of some of this, as I mentioned on Discord (quoted above) I'd like to see these efforts pivot towards supporting scope based API keys to allow restricted API access for those keys.

Some examples:

- iCal Integration - access to calendar endpoint only
- Recyclarr - access to profiles and CFs only
- Overseerr - access to add series and read settings only

Next steps:

- Closing/locking this GHI
- Locking discussions on the multi-user PR
- Opening a new GHI for scoped API keys

The first two will take effect immediately, the third will be done in the next few days.

Thanks everyone that was involved in these conversations on all fronts and again I'm sorry for the wasted efforts.
