### ISSUE TITLE
Pushbullet notifications on calendar downloads only

### ISSUE THREAD

**Issue by stevenolsen** [Sonarr/Sonarr#1706]
I find all notifications that are not related to new downloads, i.e. downloads not from today's shows are fairly useless and more often than not, initiated by the user.

For example, I'm currently upgrading quality from AVC to HEVC and the only way to do so fully is to remove all the old files and import the new ones. I end up getting 25+ notifications at once. With Pushbullet limiting API calls, limiting push notifications to new calendar entries would be ideal.

I thought this was fixed with the advent of "On Download", but this still includes manual imports. If that's not supposed to happen, then this is a bug.

**Comment by vertigo235** [comment]
Just curious but do you have "On Upgrade" enabled?

**Comment by markus101** [comment]
As Vertigo said, if these are upgrades, disable `On Upgrade` notifications and you won't be bothered.

`On Download` has been there since notifications have (`On Upgrade` is newer), but not notifying on Manual Import has it's own issue: https://github.com/Sonarr/Sonarr/issues/933

We don't have plans to restrict notifications to episodes that aired during a certain time frame at this time.
