### ISSUE TITLE
Newest version of Deluge not working with Sonarr

### ISSUE THREAD

**Issue by Sjark** [Sonarr/Sonarr#1738]
The newest version of Deluge (1.3.14) won't work with Sonarr.

When you hit "Test" on the configuration page you get the following error:
Unknown exception: HTTP request failed: [500:InternalServerError] [POST] at [http://127.0.0.1:8112/json]

I ran Deluge in debug, and the error is as follows:
`Invalid JSON request content-type: application/json-rpc`

I believe that this is due to the following commit in deluge:
[11e8957deaf0c76fdfbac62d99c8b6c61cfdddf9](https://github.com/deluge-torrent/deluge/commit/11e8957deaf0c76fdfbac62d99c8b6c61cfdddf9)

Content-Type on requests to deluge should be updated to "application/json"

**Comment by Taloth** [comment]
Tnx for looking into it.

Looks like it's a conflict between the original json-rpc over http spec, which explicitly allowed both app/json and app/json-rpc http://www.jsonrpc.org/historical/json-rpc-over-http.html#http-header.   
So it's a bit unfortunate that deluge decided to be _that_ strict about it, but I admire their desire to stick the IANA's standardized list of media types.   
It looks like back when they drafted json-rpc over http there was some disagreement on that. Either way, all of that is based on draft documents, nothing was ever finalized.

I'll look into it on our end, but it's a bit more involved since the code we use to do JsonRpc is used for other apis besides Deluge, so i'll have to check if the others are compatible.

**Comment by Sjark** [comment]
A quick way to fix it might be to add a variable called ContentType to the constructor of JsonRpcRequestBuilder that has a default value of "application/json-rpc", and just set that to "application/json" when deluge calls it.

**Comment by Taloth** [comment]
Tnx, but I finished testing the other apis, so it's good.
