### ISSUE TITLE
TVMaze as a metadata source

### ISSUE THREAD

**Issue by ptr727** [Sonarr/Sonarr#1752]
For reference see this forum thread:
https://forums.sonarr.tv/t/ability-to-match-a-show-with-tvmaze/9708

I would like the ability to configure the source of show metadata.
Specifically the ability to add a show by TVMaze ID, and to use TVMaze metadata.

This is not about which metadata provider is right, or the best, but the ability for me to choose a provider.
And, if TVDB was perfect, there would be no need to ask for this feature.

**Comment by Taloth** [comment]
We've talked about multiple metadata sources before and we will not be implementing them in the way you're requesting.

Preferring one provider over another doesn't matter, you still have scene vs p2p issues, a far more serious issue that's becoming problematic for more and more series.
To be able to do something like that reliably we need an architecture in place to track the source and revision used in a particular series folder, and we'd need TheXEM improvements to provide mappings. That's not going to happen anytime soon.

We do have plans to allow skyhook to use tvmaze info for upcoming series, since those are not allowed on tvdb. As well as tracking changes so that we can better maintain the series folder and handle TheXEM data changes better. Baby steps.

Either way, there are existing github issues regarding upcoming series, multiple metadata sources, dvdorder etc. I don't want a separate TvMaze issue.
