### ISSUE TITLE
[Feature Request] Separate Process path & Physical path

### ISSUE THREAD

**Issue by mechanimal82** [Sonarr/Sonarr#1762]
Note: Also suggested in the Radarr git

For example; people who store their media on a mapped drive to cloud storage mounted onto the local machine (e.g. VPS with Amazon Cloud Drive). I would like to be able to set a global setting to determine the 'Process path' which will be used to organise and rename (if left blank, use the physical path from the individual movie setting). This needs to be different to the individual file 'physical path' which would be on a mounted drive.

This enables the application to sort, organise & rename. Then a custom script push the file to cloud storage where the physical path would capture the file quality etc.

**Comment by markus101** [comment]
> I would like to be able to set a global setting to determine the 'Process path' which will be used to organise and rename (if left blank, use the physical path from the individual movie setting).

I assume you mean series, but a copy/paste from the GHI created for Radarr, but that scenario wouldn't work for Sonarr, Sonarr writes everything to the series folder and something like this would require Sonarr to allow multiple series folders and would be non-trivial to configure.

This sounds familiar to another recent request: https://github.com/Sonarr/Sonarr/issues/1693

I don't see this being implemented in Sonarr due to the complexity of doing so, but there are options to do it which would be transparent to Sonarr (as mentioned in that GHI).
