### ISSUE TITLE
API changes SABnzbd 2.0.0

### ISSUE THREAD

**Issue by Safihre** [Sonarr/Sonarr#1775]
For SABnzbd 2.0.0 I am cleaning up the `history` and `queue` API-calls, since they contained lots of double and non queue/history related info.
But I noticed that Sonarr get's annoyed then when doing connection test (regular behavior seems fine):
![image](https://cloud.githubusercontent.com/assets/5703454/24061199/bd04f0d0-0b56-11e7-81ac-c75068c407a9.png)

I see Sonarr does a total of 4 calls for the connection tests. I was wondering what info it needs? Why does it needs to know where the user's categories point to?

That information removed from the `history`/`queue` calls is and will stay be available in the call: `api?mode=fullstatus`. 
That one also does an IPv4 address lookup so this one is faster: `api?mode=fullstatus&skip_dashboard=1`

**Comment by Taloth** [comment]
The error you get has to do with some legacy code we don't really need anymore.
The api proxy still contains the logic to resolve the category paths for each category by using various pieces of information:
- `category.dir`
- `config.misc.complete_dir` (if category.dir is relative)
- `queue.my_home` (if complete_dir is relative, thus relative to the user's home)

I assume that `queue.my_home` has been removed, as is evident by relative path in the warning you posted. It only happens with a relative complete_dir.

We don't really need that code anymore, it was used historically for the introduction of the Completed Download Handling logic and/or Remote Path Mapping and was needed to prevent conflicts. At least, iirc. :smile:
I'll see about removing it, but I suppose we'll have to be ahead of the 2.0.0 release.

If you want to make other changes to the the api that is breaking, then we can support it, we'll just have to add a version check.

The other field we're using is `queue.paused`, in order to show all queued items as paused. If that's going away then we'll have to think of an alternative. But I suppose 'pause' does belong in the queue.

**Comment by Safihre** [comment]
Indeed the thing that I wanted to remove (haven't pushed it yet) was the `my_home` one. It's still there in `mode=fullstatus`, in case you need it.

But all the other info is indeed staying, paused status is very much queuey 😃

**Comment by Taloth** [comment]
I opted to rewrite it against mode=fullstatus using status.completedir, mainly because having the (category) output dir would allow some auto-complete helper in the Remote Path Mapping UI.

**Comment by Safihre** [comment]
@Taloth Was wondering what your normal release schedule is for the stable branch? I am always on the develop branch, but saw some users having this problem on the stable branch.
Just released `2.0.0RC2` so hoping to do the final next week or so (not really in a rush).

**Comment by Taloth** [comment]
@Safihre Whenever we feel it's stable, there isn't a schedule. But we had a report of manual search crashing on windows that could be related to a recent mediainfo update, so we gotta check that out first before we throw a release over the wall. Worst case we roll that mediainfo back.
But mostly we need to be sure the extrafiles (subtitle) import isn't puking for any develop user.

I'll ping you if we push a master out. If you get to final before then, lemme know and we'll arrange a master release. (Tnx for keeping an eye out, btw)

**Comment by Taloth** [comment]
On another note, do you have any kind of nntp emulator?

I've been putting together docker containers for various versions of our download clients in order to do more reliable integration tests, but I'd prefer to have some kind of mock usenet 'server' that can serve some stuff in an isolated network.

**Comment by Safihre** [comment]
@Taloth We don't, but NZBGet does: https://github.com/nzbget/nzbget/wiki/NServ-NNTP-Server

It works really well and really fast!

**Comment by Taloth** [comment]
Ok, awesome! I was fiddling with some convoluted unix app.

**Comment by Safihre** [comment]
More docs and examples: https://github.com/nzbget/nzbget/wiki/Performing-speed-tests

**Comment by Taloth** [comment]
@Safihre A new master release is out now. Those systems that are on automatic update will get it over the next 6h.

**Comment by Safihre** [comment]
Thanks for letting me know! Aiming for 2.0.0 by end of the weekend so that great news.
