### ISSUE TITLE
Web interface "crashes" under "load"

### ISSUE THREAD

**Issue by carpenike** [Sonarr/Sonarr#1789]
I believe I've sorted this out as it looks like the health checks that HAProxy was running caused the web interface to crash. Sonarr continued running and processing shows without issue but I couldn't get access to the web site until I restarted the docker container.

I disabled the HAProxy health checks and the web interface is much more stable now.

There were no events in the Sonarr logs indicating the web failure so my suspicion is that mono was silently crashing.

**Comment by markus101** [comment]
Which version of mono is running in the container?

**Comment by carpenike** [comment]
root@sonarr:/# mono -V
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

**Comment by markus101** [comment]
I was seeing this same issue (Sonarr was working, but the UI was dead) when running behind Synology's reverse proxy, I believe I was also on mono 4.2.3. I've since upgraded to mono 4.8.1 and I haven't seen it re-occur.

If you're still on 4.2.3 I'd recommend updating and seeing if it's still an issue. I'm going to close this issue, but if you're still seeing it with a newer mono version let us know and we can reopen/track it.
