### ISSUE TITLE
Disable tasks

### ISSUE THREAD

**Issue by kragebein** [Sonarr/Sonarr#1846]
Feature request: Be able to disable tasks. 

Tasks not imperative to the operation of Sonarr should have the option to be turned off by the user.

While trying to "debug" a scenario i'm having issues with, these tasks just run - and not beeing able to stop/pause them from happening is .. odd.

**Comment by markus101** [comment]
Housekeeping doesn't delete files, the Refresh Series task would have seen an episode missing/replaced with a better quality, which would have caused Sonarr to delete the linked extra files because it's no longer tracking the episode file, but the Refresh Series task is integral to Sonarr, so it's not something that could be disabled.

We do no have plans to allow tasks to be disabled.
