### ISSUE TITLE
Merge with other Sonarr-like projects.

### ISSUE THREAD

**Issue by gregorij89** [Sonarr/Sonarr#1873]
Hi,

firstly I want to thank you guys, Sonarr is a really good project and I like it so much. As you know, Sonarr has forks for doing another media related jobs (I know about Radarr - https://github.com/Radarr/Radarr and a newly created fork Lidarr - https://github.com/mattman86/Lidarr). I think it would be awesome to create some solid rock base from Sonarr, that will handle the UI, indexers, downloaders etc. and that will have some sort of code interface for media management functionality. In that scenario, shows management, movies management or music management is only some sort of plugin that is using the base. I think it will be easier to maintain and keep the original concept of Sonarr for all forks. Besides shows, movies and music I could imagine comics or e-books management, so it could be widely used.

What are you think about it? And what  @galli-leo or @mattman86 think about it? It could have a positive impact for all of us.

George

**Comment by Taloth** [comment]
That's not going to happen. Read up on how the Radarr fork began (it's actually not a fork, but a new product using the same original codebase): https://forums.sonarr.tv/t/sonarr-movie-support-discussion-planning/12753/38

The short of it is that we loath to provide a single tool for all those features. It's impossible to support (you don't want to know how many hours markus spends on providing user support for Sonarr alone).
From a user perspective tv, movies, e-books etc might appear to be 'the same thing', but it really isn't. The requirements are totally different, that would make it a 3-in-1 not 1 product with 3 features.

That said, the Sonarr team had ideas about providing some common modules once we start working on a .net core version of Sonarr. Which would allow the various products to use and maintain certain common modules together. But I don't see the reverse (common product with plugins) happen.

**Comment by gregorij89** [comment]
I know it is not the same thing, and I can imagine how time-consuming the whole project is. I am also an IT pro and I have some kind of programming skills, but I am not a professional programmer.

Maybe I am not express myself clearly. I am not suggesting to create one for all solution maintained by you and your team. I was suggesting to create some base framework on which others could create their projects - and maintain them including the user support. It doesn't matter if the whole concept will be like one big deployment with the ability to add functions, or others just use the framework and make their own deployments. I can imagine both. But I think I am not so far from the truth, that using the downloaders, indexers, handling web UI etc. is merely the same in all three projects. So why doing one thing three times? The business logic behind managing shows, movies etc. is a different story, and it is unique. And that is the point where should be the edge between the framework and the "plugin" itself. It is the "plugin" responsibility to parse names, identify duplicates, cut-offs, create DB logic for its work etc. For example, not so far ago, there was a change in Deluge API that broke the communication between Sonarr and Deluge. It was firstly repaired in Sonarr and Radarr team followed you with some little delay - but they´ve had to implement the patch again into their code (at least I guess). With the common framework, this job could be done just once. Are we clear now? 

You said clearly it's not going to happen, but as I read your comment, you actually agree with me - at least partially at the end, where you admit common modules with .NET core version of Sonarr. But it's basically what I am proposing. I know I am not a developer for any of these projects so I´ve only shared some idea I had when I was reading about a new Lidarr project.

Nevertheless, you and your team have my thanks because you are doing your job (or hobby :) ) well and many love your project.

George

**Comment by Taloth** [comment]
Yes, we're mostly talking about the same thing. But you mentioned 'plugins' into a common base, and I wanted to emphasis that it's absolutely not what we're thinking about. 
You don't 'plug' a website into php and call it 'php with website', you create the website on top of php and call it 'website'. Similarly, Sonarr uses Newtonsofts Json.Net library, we don't 'plug' Sonarr into Json.Net.   
But you do write custom modules for wordpress, and plug it into wordpress... and that's NOT what we want to do.   
I'd happily accept that it simply got lost in translation between IT pro and dev, and move on. :smile:

As for the Deluge API thing, they didn't have to redo the fix. Afaik they pull in changes from the Sonarr repository and cherrypick what's applicable to Radarr.  
https://github.com/Sonarr/Sonarr/commit/bbf2134fe15db754fb4c5fd7620d432032aa8a5a vs https://github.com/Radarr/Radarr/commit/73f0916fa035b1748be6a920e23e7c9562f855ab

**Comment by galli-leo** [comment]
@Taloth Correct. We usually get fixes that are applicable to Radarr and pull them in. And I totally agree. Merging will cause more headaches than it will solve. Especially with how we have massacred your code base 😬

**Comment by mattman86** [comment]
I actually thought about this a while ago. I used to work for a company that built out a webapp that did QA audits for hotels and restaurants. One issue was that we had to install the same app 100 times with only some minor changes in each instance. So, I worked for almost a year and a half to create a "common base set of features" that then could be referenced by every client. The issue we run into with the ****ar apps is that the relationships between the files are so intertwined that as we work toward a common bad, we eventually end up with 3 separate apps with only a few common files. In a business case, that would not be worth the time taken.

After I looked into it, I really just came up with the idea already done by causefx with Organizr.

**Comment by Taloth** [comment]
@galli-leo We were kinda happy with that, made sure it could never get merged back in side by side with tv support. Something we've been actively trying to avoid for 2+ years.
It allowed Radarr to focus entirely on their own feature set and us on ours. That's why I don't consider it a fork, but more a spin-off.

But as I said, I think having certain modules as shared libraries (either as nuget or submodules) would be better for the projects. Particularly NzbDrone.Common for large parts. It's something that's been on my mind, but I don't want to address it in the current code-base since it would cause more problems than it solves. .net core is an excellent candidate since it's already heavily modularized.
The downside of such modules is that the Sonarr team has been free to change things however way we like, creating internal api surfaces doesn't make that easier. At one point you gotta wonder if the benefits are worth it, but the modularization is going to happen for Sonarr either way, so we'll see how it plays out eventually.

**Comment by fonix232** [comment]
Couldn't this be solved via a provider pattern? So that there's a common core that handles downloads, media folders, indexers, et cetera, and then there are providers, that provide the functionality of the "Sonarr/Radarr/Lidarr only" features - much like how the indexers or download client handlers work.

This way the merge is not required, and people could focus on the core host and its capabilities, while others could work on the separate content providers (TV shows, movies, games, e-books, music, whatnot).
