### ISSUE TITLE
How do we use Torznab additional parameters?

### ISSUE THREAD

**Issue by sgtsquiggs** [Sonarr/Sonarr#1882]
Specifically, I am trying to limit my search to freeleech or neutral leech only. Referring to this PR that was merged a while back: https://github.com/Sonarr/Sonarr/pull/1464

I've tried `downloadvolumefactor=0` and `downloadvolumefactor:0` but I get `'Additional Parameters' is not in the correct format`. Can't seem to find this documented anywhere in issues/wiki/google.

**Comment by Taloth** [comment]
The parameters were added to the torznab specification to ensure a standardized means exists for the _indexer_ to convey tracker seeding requirements, but aren't a feature themselves. The information allows clients to implement a feature to adjust the seeding ratio limits in the client accordingly.

Atm Sonarr can't adjust the seeding ratio requirements, in theory it can do it for a couple of clients, but not all support it.
The second, prioritization is a different matter. I'd imagine that a lower seed requirement would be preferred, but the criteria of that precedence is a bit more complicated.
Sonarr has the following absolute prioritization:
- Quality, a higher quality trumps anything else.
- Protocol, if the user selected a preference in torrent vs usenet, that goes second.
- EpisodeCount, a season pack takes precedence over single episodes.
- Peers, releases are put in buckets using a logarithmic scale (1, 10, 100, 1000 peers)... and then sorted, more peers the better.
- Size, buckets by 200MB, smaller is preferred atm.

Torznab recognizes 4 tracker-related attributes:
- downloadvolumefactor, the lower the better. (How much credits you 'pay' for downloads)
- uploadvolumefactor, the higher the better. (How much credits you 'receive' for uploading)
- minimumratio, the lower the 'better'. (The higher the ratio has to be before you're allowed to stop seeding, I wouldn't prioritize on this)
- minimumseedtime, the lower the 'better'. (How long you have to seed for, I wouldn't prioritize on this either)

So where in the prioritization list does 'downloadvolumefactor' belong? Is it more important than peers? if no, then how effective will it be?

**Comment by sgtsquiggs** [comment]
I see. My use case is to search *only* freeleech. I was hoping for some super user parameter option I could set to tell the indexer to only return those results. My indexer is via jackett, which is returning all of these parameters.

**Comment by sgtsquiggs** [comment]
By return those results I mean let sonarr only use those matching my specified parameters.

**Comment by Taloth** [comment]
As mentioned, there isn't such capability. At best we could consider a feature to filter out stuff, but I don't see us implementing it since it's aimed as such a specific use-case.

**Comment by jake9000** [comment]
I think that there may have been a misunderstanding with this question. I was also interested in this feature since a tracker I like to use for filling out my backlog only enables freeleech for certain filesizes/categories and I didn't want sonarr to accidentally tank my buffer. 

The additional parameter field seems to just get tacked on to the end of the URL sent to Jackett, so you have to format it with that in mind. The basic structure is `&parameter=value`. if you want to have two parameters you'll need to do it like `&parameter1=value&parameter2=value` To make an torznab indexer that only returns freeleech files, use `&downloadvolumefactor=0`

nzbnab api docs are here: http://newznab.readthedocs.io/en/latest/misc/api/
Jackett's parameters are at the bottom of their api docs here: https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer

**Comment by Taloth** [comment]
Except that there is a big difference between query params supported by the indexer and the extended attributes in the results. The fact that Jackett may return those values in the results, doesn't automatically mean it can filter on them. Remember, Additional Parameters are sent to the indexer, so if Jackett can handle it, fine, but I suspect it does not.
