### ISSUE TITLE
Synology 6.1.1 Sonarr not starting after Synology restart

### ISSUE THREAD

**Issue by komainu85** [Sonarr/Sonarr#1885]
Ive installed the latest Sonarr from the Synology community feed. Sonarr starts up correctly after installation, however if I restart my Synology, then Sonarr refuses to startup.

If I go to package centre in Synology diskstation, and then click the run command on Sonarr after I restart my Synology nothing happens. Sonarr does not start.

Is there any logs I can provide to help narrow down the issue?

**Comment by Taloth** [comment]
> Provide a description of the feature request or bug, the more details the better.
**Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)**

Please use the forums for support questions. You can check the [log files](https://github.com/Sonarr/Sonarr/wiki/Log-Files) for any startup errors.

**Comment by Nakash23** [comment]
hello,

i have exactly the same problem.

Sonarr version:  2.0.0.4949
Mono version (from synocommunity):  4.6.2.7-8

Hello,
i installed on my synology up to date (6.1.3-15152 update 8) mono and sonarr (and radarr) from the synocommunity.
Everything works except some crashs some times from sonarr.
It happens when the synology restart.

Thanks a lot for your help.
