### ISSUE TITLE
Better "missing root folder" message to help find the problem faster

### ISSUE THREAD

**Issue by gjermshus** [Sonarr/Sonarr#1895]
When missing a root folder the Health Check tells you which root folder is missing.
But it does not tell you what series may be configured wrong or missing.
The error message should say something about which series this error propagates from, so it would be easier for the user to identify and correct.

**Comment by markus101** [comment]
> The error message should say something about which series this error propagates from, so it would be easier for the user to identify and correct.

What if it's 10, 100, 1000 series that are affected?
There may be some value if it's one or two series, but the more series the less valuable it becomes I think and listing every series wouldn't always be practical.

Is the problem not knowing where to go to find out which series were affected?
If you know the path and have a list of series and their paths is that sufficient to find and fix it?

**Comment by gjermshus** [comment]
I can see the potential overload of information here. 
My case was that of 80 series I didn't know where or how many I had forgot to change path. Only solution is to go through all the series one by one. (My solution was altering the sqlite database manually).

I think that more information regarding where the problem is, would be helpful towards correcting the issue faster. But I see the practicality of limit the message if its to many issues.

It may also be that the missing root folder message is cached so you have to either restart the application or what for the cache to clear to see if the error is fixed or not?

**Comment by kyse** [comment]
I also thought about this as well when looking at mounted as read only health check message.  Instead of doing a distinct on the list of series's mount path, I was thinking to show the warning per tv series so folks know what to edit/adjust in the series list if they wanted to change up the mount for a series.  But frankly if they are targeting a mount for series, I'd assume a mount would want to be rw, and a ro would be more of an error/diagnostics issue, so a single warning would suffice.  And as already pointed out, the fact I would end up with 100-1000 warning messages would suck.

It seems like a missing root folder would fall into the same concept to me.  If you're missing a root folder, you probably want to fix that missing root folder issue, and that's probably not something you particularly need to know each series to address?

One thought I was having though to offer this was add an expand to show detail css formatting to the warning, but I have't messed with the UI end of the code yet perhaps @markus101 could offer some thoughts on such an idea.

I believe it lists and allows you to sort by the path column on the edit series editor page.  Click on the checkbox/select the series you want to edit and adjust the root folder with the root folder dropdown field at the bottom of the page.

A nice suggestion from this thought, add a link to the warning bringing you to the series editor with the affected tv series already selected so one doesn't have to select 80 series out of 1000 before adjusting the root path.

**Comment by Taloth** [comment]
@gjermshus Series Editor.... would've saved you a whole lot of time.

![image](https://cloud.githubusercontent.com/assets/6383890/25713682/d549430c-30f5-11e7-845e-82fd95c68d76.png)

@kyse Yes, we plan to make health checks a bit more interactive at one point. Particularly useful for indexers that got temporarily disable due to issues.

@markus101 How about in v3 we allow specifying a topic in health check issues so the UI can show it in for example Series Editor as a banner box? I'd imagine we could connect health checks to 'solvers guides' or something like that that show up in the relevant pages.

**Comment by gjermshus** [comment]
@Taloth I have missed that one and that would be my solution. 
The solution to my problem was not the bring the root dir back. It was suppose to be gone but I had missed 5 series that I had not changed the path and my solution was either to a replace() query to the database or browse through all series one by one (since I didnt know about the series editor).

That said, Im not sure that I think "missing root folder" is good enough, since it only tells you what the problem is, not where it is or where to fix it. Since that information is well known by the system I still think that a more informative error message would be a good thing.

**Comment by kyse** [comment]
I'm being OCD and looking at adding an expandable cell backgrid extension to my local code atm.  Playing around with passing a collection such as offending series along with the health check model to the UI and allowing a dropdown cell via the extension to display the additional details such as series.  I can create a PR for it when I'm done if you're interested @Taloth?

**Comment by markus101** [comment]
@Taloth I added a link for indexers that goes to the settings page in v3: 
![image](https://cloud.githubusercontent.com/assets/413544/25717896/e528b1e6-30b8-11e7-8238-587e088e21f8.png)

Though it's tough to draw the line on that being a client or server side provided thing (ATM it's client side).

@kyse I don't think it's worth the effort, I don't think listing the series is the correct solution, but getting the user to the correct place to fix it. Listing the series would have still caused @gjermshus to manually edit 5 series instead of using the series editor to fix them up.

**Comment by kyse** [comment]
My thought is, if I can get familiar enough with the UI code, I can add on to my fun with the cell extension (which your probably right, its not needed), to pass the offending series into a call to the series editor to automatically check the offending series, perhaps with a header detailing the selected series root path is missing.  Effort wise, honestly I'm just messing around to get familiar with the libraries you guys are using, so that's on me.

**Comment by markus101** [comment]
Keep in mind backgrid and everything else backbone dies with v2, so becoming comfortable there won't help long term.

**Comment by Taloth** [comment]
@gjermshus 
>That said, Im not sure that I think "missing root folder" is good enough, **since it only tells you what the problem is, not where it is or where to fix it.** Since that information is well known by the system I still think that a more informative error message would be a good thing.

Except that the 'wiki' link in that health check warning links to the wiki, which mentions how to fix it. https://github.com/Sonarr/Sonarr/wiki/Health-Checks#series-folders
It tells you about the recent folder list, and about the series editor. It's not verbose and the TODO indicates that it could use some work. But it definitely explains the issue.
I already mentioned that the health check stuff could use some additional guidance. I've said enough.

@kyse Don't waste your time, feel free to play around, but integrating new UI functionality in v2 isn't worth it.

@markus101 Nice. The backend should provide a topic in the HealthCheck object, then I'm sure the UI router can handle generating the link. I think.

**Comment by markus101** [comment]
I've been treating the check name (`IndexerRssCheck`, `IndexerSearchCheck`) as the topic to direct it to the correct location, though the UI component is taking that and determining the link, not the router.

It's pretty low tech, but at worst there isn't a link shown if something in the UI and server don't align, which would still be the case with the router handling it in some way. The only limitation would be if there were different resolutions for different items in the same check, but so far that doesn't seem to be the case.

**Comment by markus101** [comment]
Closing this as we have it covered in the v3 work and will link to the series editor, in addition to the wiki link.
