### ISSUE TITLE
X509CertificateValidationPolicy error filling logs

### ISSUE THREAD

**Issue by edraven** [Sonarr/Sonarr#1902]
X509CertificateValidationPolicy	https://127.0.0.1:9090 uses the obsolete md5 hash in it's https certificate, if that is your certificate, please (re)create certificate with better algorithm as soon as possible.	3:09pm

**Comment by markus101** [comment]
That's because your certificate is old and should be fixed, Sonarr is telling you it's wrong so you can fix it.

https://sabnzbd.org/wiki/advanced/https

**Comment by MullinsN** [comment]
Are you saying to access to sonarr via HTTPS only? Or getting creating a certificate for the synology?

**Comment by MullinsN** [comment]
Ok the fix is/was actually quite simple in my case.

The error message is referring to something running on port 9090 on your NAS. In my case I was running SABnzbd on that port in SSL : 9090.

As mentioned early, by Markus, there is a certificate issue, so we need to generate a new one for SABnzbd. To do this go to (Make sure you have advanced settings ticked).

https://[Local IP Address]:9090/sabnzbd/config/general/

You may need to change the port, but for example in my case it's

https://192.119.1.20:9090/sabnzbd/config/general/

NOTE 1 - Now if you are in Chrome and you click on the certificate error, you can view the certificate, and in my case, there was a certificate created a long time ago, using the MD5 hash - hence the message from Sonarr.

NOTE 2 - In Sonarr clear the logs, if there is nothing in there you want to keep - http://[Local IP Address]/system/logs - It will be easier to spot that the change is successful,

Anyway halfway down the page on the config/general you will see a HTTPS Certificate and HTTPS key fields with server.cert and server.key respectively. 

Just click the refresh button, against the HTTPS Certificate (It will restart SABnzbd) and then the HTTPS Key (It will restart SABnzbd).

If you now view the certificate (In the Chrome taskbar) you will notice it has changed to an sha256R algorithm and the log should stop filling up with x509 errors (the version of SABnzbd I am running is 2.3.5) .

I am assuming that Sonarr improved it's security checks in the last year, and since I had installed SABnzbd many years back, the certificate I had was the one that was generated at install time, which is probably why an uninstall and reinstall also fixed the problem.

I hope that helps. I really did go around the houses on this.
