### ISSUE TITLE
Read-only options: Copy, Hardlink or Hardlink or copy

### ISSUE THREAD

**Issue by Magic815** [Sonarr/Sonarr#1906]
For the times when I am manual importing, I was thinking it would be nice to have a confirmation box of what type of transfer Sonarr will use prior to actually executing it.

In my case, if I am using manual import, it is for a torrent from a private tracker that I need to keep seeding. Because of this, I'm always going to want hardlink. I already have the setting 'Use Hardlinks instead of Copy.' However, in the event something goes wrong with hardlinking, it will resort to copy.

I'd prefer instead, that I would get a confirmation window saying that it will "copy due to hardlink failing," at which point I can cancel the transfer and dig into why hardlinks fail.

**Comment by markus101** [comment]
A confirmation wouldn't fit well with the overall process and would still leave automated imports open to falling back to a copy instead of a hardlink, which may not be expected.

@Taloth what do you think about expanding the read-only options to:

- Copy
- Hard link or copy
- Hard link

That way falling back to copy could be prevented if the user wants it and would be an easy way for a user to confirm hardlinking is working instead of having to check inode IDs or spelunking the logs.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
