### ISSUE TITLE
Lowering RSSSyncInterval minimum

### ISSUE THREAD

**Issue by pentaflake** [Sonarr/Sonarr#1918]
Is there any way the hard coded minimum can be adjusted to allow for lower values such as 5 minutes.

Edit: This is actually a bad idea as pointed out below, putting one implemention of the suggested solution here instead. 
https://github.com/Zymest/autodl-curl-sonarr

**Comment by Grimeton** [comment]
Hi,

```
# sqlite3 nzbdrone.db
sqlite> update ScheduledTasks set Interval=5 where TypeName='NzbDrone.Core.Indexers.RssSyncCommand';
sqlite > \q
#
```

Try this.

Cu

**Comment by pentaflake** [comment]
That did not take upon starting sonarr again it shows as 10 minutes still on the tasks page under system.

Rss Sync	10 minutes	May 11 2017 5:39pm	May 11 2017 5:49pm

**Comment by markus101** [comment]
`TaskManager` enforces a minimum of 10 minutes, though that's not the only place it's enforced as there is also validation when saving the setting.

5 minutes is aggressive for RSS and our concern with opening it up is people will needlessly set it to 5 minutes, burn through API calls and have indexers annoyed by it to the point where Sonarr is banned. Banning is pretty extreme, but it's been known to happen to some clients.

Quick grabbing at low intervals is really best left to something (an IRC bot for example) feeding Sonarr releases to see if they are wanted, using Sonarr's API: https://github.com/Sonarr/Sonarr/wiki/Release-Push instead of Sonarr checking an RSS feed frequently.

Which sites suggest a 5 minute interval for their RSS feed?

**Comment by pentaflake** [comment]
I can see the reasoning behind that then, better to leave it where it is. I will have to look into using the api calls to send releases to Sonarr instead, it actually seems like the more logical approach.

**Comment by Taloth** [comment]
>  more logical approach 

It's faster too, matter of seconds instead of minutes. But it hinges on the tracker having an IRC announce channel.

@markus101 How about leave the issue open to add the explanation to the UI?

**Comment by markus101** [comment]
Add an explanation why 10 minutes is the minimum or that using the release/push endpoint would be better for faster grabbing?

**Comment by Taloth** [comment]
Both, I suppose. I'd like people to get to the same realization that using the push api is so much better than settings rss to 5 min, to avoid the 'but I need' discussion.
