### ISSUE TITLE
HTTP Error - Res: [POST] http://localhost:9091/command/setCategory: 404.NotFound Close

### ISSUE THREAD

**Issue by neuman1812** [Sonarr/Sonarr#1919]
Warning appears after DownloadDecisionMaker ,  Does not appear to affect operation in anyway.  Category is still set.  

```
[Info] DownloadDecisionMaker: Processing 15 releases
May 11 17:16:45 raspberry mono[560]: [Warn] HttpClient: HTTP Error - Res: [POST] http://localhost:9091/command/setCategory: 404.NotFound
May 11 17:16:45 raspberry mono[560]: [Info] DownloadService: Report sent to qbit. Designated.Survivor.S01E20.720p.HDTV.x264-KILLERS[rartv]

```

Sonarr version :Sonarr Ver. 2.0.0.4689
Mono Version:
Mono JIT compiler version 4.8.1 (Stable 4.8.1.0/22a39d7 Wed Apr 12 12:47:01 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

Running on a Raspberry Pi 3, Ubuntu mate 16.04

**Comment by Grimeton** [comment]
Hi,

yeah that can't work.

- The path is wrong. It's /api/command
- The command type has to be part of the hash that is send to Sonarr via the POST request.
- The only thing you can "GET" there is via /api/command/{jobid}

cu

**Comment by markus101** [comment]
@Grimeton that's a request Sonarr is making to QBittorent, not one being sent to Sonarr. QBittorent has two different API commands (depending on the version) which will set the category the other a warning. Sonarr tries `setCategory` then `setLabel` if the first call fails.

Upgrading QBittorent will get rid of the warning.

From the code itself:

`// if setCategory fails due to method not being found, then try older setLabel command for qbittorent < v.3.3.5`

**Comment by neuman1812** [comment]
Thanks for the info.  Im running on a pi now so upgrading to the new version of qbittorrent is not possible. But since this doesn't affect the operation,  I'll just ignore it.
