### ISSUE TITLE
Remote Mappings Linux & Windows Misleading (UNC is required?)

### ISSUE THREAD

**Issue by davi1td** [Sonarr/Sonarr#1952]
Sonarr version (2.0.0.4784) Develop branch
Win10

I'm running Qbittorent on Linux, and my remote and local paths were correct(so i thought).
In my configuration it appears that indeed a windows UNC local path is required. That's fine but was very difficult to understand/troubleshoot because:
* When choosing the path it defaults to browsing through your drive letters i.e c: d: e: etc. and allows you to choose it.
* There were no errors in the logs, except that completed QB torrents are paused and nothing was acted on, moving files and removing from QB etc. 
The only way I figured it out was when I went to wanted/queue and the downloads in question were showing zero time left and chose manual import, it would just sit there w a  spinning wheel, because of the error that was produced. This showed up in the logs:
System.ArgumentException: value [/mnt/hgfs/mymedia ... is not a valid Windows path. paths must be a full path eg. C:\Windows
Two problems with this, the value it was referring as not valid was **wrong**, it wasn't the unix path that was wrong it was the windows drive letter that was wrong and needed to be UNC. 
My request is:
1) do not allow NON-UNC paths in the selector, update the help text to say as much
2) when it does error out, recommend using a \\UNCpath not c:\windows
3) Clearly this was having errors in the background originally before i tried manual import, but no error was ever reported in the logs.
Thanks! 
Sonarr Rocks!
-TD

**Comment by markus101** [comment]
> do not allow NON-UNC paths in the selector, update the help text to say as much

It doesn't need to be UNC, but it depends how Sonarr is running (Windows services cannot access mapped network drives, this is covered in the FAQ). We have an issue to to improve that: https://github.com/Sonarr/Sonarr/issues/979

> when it does error out, recommend using a \UNCpath not c:\windows

If the remote box is pushing files to the system Sonarr is running on then a local path is valid, but this is a generic message when the path doesn't match the operating system, we could recommend UNC in addition to a local path.

> Clearly this was having errors in the background originally before i tried manual import, but no error was ever reported in the logs.

Activity: Queue shows the reason why something wasn't imported if you hover over the icon on the left and the logs will log the problem, but may not continually spam the logs because it already knows it's failing (each download is tracked and stored while Sonarr is running).

**Comment by davi1td** [comment]
Is a physical drive letter still considered mapped? In my case it was a physical drive letter.
As for logs you're probably right, may have cleared / restarted logs and didn't see original error in them.
The biggest issue though is when you do get that error in the logs, regardless of the c:\windows part its saying the linux remote mount is wrong and suggesting c:\windows which leaves one wondering where exactly the problem is  ... maybe something like no mention of the correct side , linux in this case , reveal the configured windows path and mention are you running as a windows service? only UNC paths allowed....
Thanks for the quick response and a great app!
-TD

**Comment by markus101** [comment]
> Is a physical drive letter still considered mapped? In my case it was a physical drive letter.

A drive letter can be assigned to a physical drive or mapped to a network drive (Mapped Network Drive). `C:\` pointing to a local drive is physical, but `Z:\` pointed to a UNC path is not physical.

> The biggest issue though is when you do get that error in the logs, regardless of the c:\windows part its saying the linux remote mount is wrong and suggesting c:\windows which leaves one wondering where exactly the problem is ... maybe something like no mention of the correct side , linux in this case , reveal the configured windows path and mention are you running as a windows service? only UNC paths allowed....

If it's reporting that the path is wrong for the OS then the remote path mapping isn't being applied (wrong host or wrong remote path), since it hasn't translated it to a local path, which is shown in Activity: Queue Something like: `[/mnt/hgfs/mymedia] is not a valid local path. You may need a Remote Path Mapping.`.

**Comment by davi1td** [comment]
OK, just so we're clear, in my case drive J: is a physical drive.
The remote host and mapping are totally correct, reminder all I did to correct my issue was change the j:\mymedia to: \\mylocalhost\j$\mymedia ...
As for the /mnt/hgfs/mymedia ... it was never wrong or changed, all is working fine after changing j: to the UNC above.
Further I wrote a quick service testing the ability to access j: drive with local service:
Dim IsValidDir As Boolean = IO.Directory.Exists("J:\mymedia\CompletedDownloads\Sonarr") 
It returns true.
Does that make sense? Sorry if I wasn't clear ...
Thanks again

**Comment by markus101** [comment]
> The remote host and mapping are totally correct, reminder all I did to correct my issue was change the j:\mymedia to: \mylocalhost\j$\mymedia ...

That's definitely not required and not something we would suggest to try to solve it. I don't see a reason why it it was failing originally and suddenly works that way. I'd even say going back to `J:\` would be advisable and see if it breaks again, but I don't see how/why it would.

**Comment by davi1td** [comment]
I give up, I set it back to j:\... added a new show for test and it worked, so as you said, who knows how / why it did what it did before ... I guess we can just say if your're having a weird problem like this , set it to UNC go back later and change back to drive letter lol
Thanks for the support 👍
