### ISSUE TITLE
[Feature Request] Option to rename obfuscated video

### ISSUE THREAD

**Issue by Stibbons** [Sonarr/Sonarr#1966]
I prefer not having the filename renamed, it help to find the matching subtitle later. But when the folder has "Obfuscated" in it, the video file is something like `49ebce69fc7e106c6f0a0a83310a8552754a0737.mp4`. In this case it is possible to name it with the same name than the folder it has been extracted into from sabnzdb?

**Comment by markus101** [comment]
You can use `{Original Title}` as the renaming pattern and Sonarr will use the name the download client reports (when using completed download handling), which should be the same as the folder name instead the filename.

`Obfuscated` is not the only indication that it's been obfuscated, just one of the patterns used, we don't plan to contidionally rename using the folder name instead of the filename when renaming is off.
