### ISSUE TITLE
Sonarr doesn't hard link torrents. Automatically copies them even when Hard linking is enabled.

### ISSUE THREAD

**Issue by kalq** [Sonarr/Sonarr#1979]
I have both Sonarr and my rtorrent/rutorrent running in separate Docker containers. However for whatever reason after a torrent finishes it doesn't hard link the file. It copies it over. I've tried both multiple mounts for the media and download locations each and then setting up a Direct Path Mapping. I've also tried having the exact same mounts for the Sonnar and rtorrent containers that match the directory heirarchy of the actual storage. In both cases it only copies and doesn't hard link.

The logs don't show anything about any hard link attempts or even the copying.

**Comment by markus101** [comment]
If you're using using multiple mounts int he Sonarr container then it will only copy because you can't hardlink across mounts, that is a limitation of the system itself, not something Sonarr can overcome, regardless of how the data is structured on the host.

If you're using a single mount in the Sonarr docker container, please open a thread on the forums for support.
