### ISSUE TITLE
Fix 'IHttpProvider' is obsolete warnings

### ISSUE THREAD

**Issue by Neaox** [Sonarr/Sonarr#2008]
There are 30 obsolete warnings on the current `develop` branch which are variations of the following:
* 'HttpProvider' is obsolete: 'Use HttpProvider'
* 'IHttpProvider' is obsolete: 'Use IHttpClient'

**Comment by markus101** [comment]
They have been marked obsolete because they shouldn't be used going forward. A blanket issue to fix them all up isn't very helpful given they cover various parts of the app and would require testing everything that is changed by upgrading them. We'd much rather them be updated as those parts of the app are worked on.
