### ISSUE TITLE
How to use BTSync without the Drone Factory?

### ISSUE THREAD

**Issue by brimur** [Sonarr/Sonarr#2021]
Hi guys,

Given the following scenario how would a Sonarr user stop using Drone Factory and still maintain automation. 

1. Sonarr on Server A at some location
2. BT client on Server B at a different location
3. Server A (Sonarr) has only web/api access to Server B (BT Client) to send torrent. No file system access.
4. Downloaded files are moved back to Server A from Server B via some process
5. Files now exist on Server A but Sonarr cant "know" that as far as I can tell using Download Handling

Right now drone factory can watch the folder on Server A for when Server B moves the files there and can then allow Sonarr to process them. If drone factory is removed how would this be done using download handling, without the need for checking in every day and clicking Manual Import, which defeats the point of Sonarr.

Thanks

**Comment by Taloth** [comment]
The reason we don't want people to use the Drone Factory is because it's very easy to get it wrong and get partial files, partial imports and what not. We get a significant amount of support request from users that misuse it and don't even need it.
The _Periodic_ Drone Factory scan will be removed in v3 (we're at v2 now) and won't happen in any automatic update. So **don't panic**. This current warning is to move people away from it, and prevent new users from (mis)using it.

To get back to business:

'via some process', on which computer?

There are a few ways to tackle this, but it depends on how you currently handle the transfer. So I'm going to give you the general gist until I get some more details.

1) Remote Path mapping, this generally applies to any remote mount, but can also be used if you use a transfer method that's 'atomic', more on that later.
2) The Sonarr API, you can call the Sonarr API to have it import a specific directory and optionally specify the original download identifier so Sonarr knows which download it is about. This allows any external process to signal Sonarr that the download is ready to be imported.
3) Despite your mentioning 'no file system access' I'm still gonna say it, but isn't it possible to mount it via sshfs?

The goal is to ensure that the entire set of files appear in the directory at a whole (atomically). For example by transferring to a temp directory and then moving that directory to the import folder. That way Sonarr can't see partial files or incomplete directories.
A remote mount is preferable, but not mandatory. Not having a periodic scan forces you to move to a more event-driven approach, which is what we're trying to achieve here.

BTSync is somewhat of an tricky edge case, coz afaik it has no 'finished' event. In fact, it was one of the edge-cases mentioned in https://www.reddit.com/r/sonarr/comments/44lasw/why_the_drone_factory_is_bad_or_just_plain_evil/. So it kind of depends on how you do it right now.

**Comment by brimur** [comment]
So based on my setup I think option 2 could work since Server B can talk to Server A and the drone factory folder is local to Server A, but how would I script a call to the Sonarr API from Server B to grab the contents of the drone factory folder? Thanks

**Comment by Taloth** [comment]
HTTP POST with a json body: https://github.com/Sonarr/Sonarr/wiki/Command#downloadedepisodesscan

Something like
```
curl http://localhost:8989/api/command -X POST -d '{"name": "downloadedepisodesscan","path": "/serverA/var/temp/Download.S01E01","importMode":"Move","downloadClientId":"{infohash}"}' --header "X-Api-Key:MyKey"
```

It works per individual job/download, so you call it for every finished+transferred download in the download client.

**Comment by brimur** [comment]
Cool, that works. Thanks very much

**Comment by Peke** [comment]
Just wondering what about people that uses JDownloader or similar to Download files into Drone Factory folder?

Is there any JSON format HTTP POST to INITIATE GLOBAL Scan from Crone Job?
