### ISSUE TITLE
"Title slug is in use by another series with a similar name"

### ISSUE THREAD

**Issue by DivinityCycle** [Sonarr/Sonarr#2026]
I have not looked at the code to establish where / how this is working, but my Sonarr collection currently has a show called C.O.P.S. in it. When attempting to add a show called Cops, I get the error "Title slug is in use by another series with a similar name".

This implies to me that the slug is being generated by simply dropping non-alphanumeric & whitespace characters out, which is OK but then introduces the above situation where Sh.ow and Show cannot both exist in the same library with no way around this issue that I can see.

I'm not honestly too sure what best practices would be in this case, but maybe replacing non-alphanumeric characters with underscores in slug generation would be alright? In my case this would give me the slug "c_o_p_s_" which isn't pretty, but is functional. As far as I understand it, slugs aren't really user-facing anyways, so a slightly uglier version of a thing the user never see is still a thing the user never see right?

**Comment by markus101** [comment]
The slug is used in the URL when viewing series details and dashes are used to replace spaces, but periods in acronyms are not changed, they are just removed. I've pushed a change to skyhook to replace periods in acronyms with dashes so `C.O.P.S.` will become `c-o-p-s` and `Cops` will still be `cops` and any other acronyms in titles will follow a similar pattern `Chicago P.D.` will be `chicago-p-d` instead of `chicago-pd` (a minor change, but not worth the complexity to handle acronyms in the title vs the entire title being an acronym).

Refresh `C.O.P.S.` and it should be fixed up.

**Comment by Taloth** [comment]
markus, it will cause issues with the importer and parser anyway.

**Comment by markus101** [comment]
What will? The slug generation is separate from any title cleaning for importing.

**Comment by Taloth** [comment]
it is different, but fixing the slug will only allow him to add both shows. and then he'll have problems importing since title cleaning removes dots too.

**Comment by markus101** [comment]
Ahh right, There could be some weird behaviour with that and only having the one series as well since episodes would import as the series it knows about regardless of it being correct, but thanks for pointing that out.
