### ISSUE TITLE
[Feature Request] Recycling Bin Update Timestamp

### ISSUE THREAD

**Issue by ghultstrand** [Sonarr/Sonarr#2057]
I would like an option, like Change File Date, that will update the modified timestamp on the file sent to the Recycling Bin so I can run a cron to clean up files older than X days.

**Comment by markus101** [comment]
Sonarr does, but only when the OS is Windows as setting the last write time often fails when running under mono. Sonarr will also clean up files older than 7 days automatically, but that depends on being able to set the last write time.

Very similar to this mono bug: https://bugzilla.xamarin.com/show_bug.cgi?id=31945

I think we could probably do our best to set the time instead of avoiding it altogether though.
