### ISSUE TITLE
Anizb is no longer available

### ISSUE THREAD

**Issue by Kaminogoroshi** [Sonarr/Sonarr#2094]
I think it happened after last update but can't say for sure.
Here are the logs that i get.

I am running windows 10

https://pastebin.com/U4QS2eGa

**Comment by Kaminogoroshi** [comment]
So nzb-tortuga is also not available.
Here are the logs for tortuga.

https://pastebin.com/qFz6mYRd

**Comment by Stealthii** [comment]
You can add Anizb using the 'Fanzub' preset, and changing the URL to https://anizb.org/api/.

I've tested this and Anizb still works as an Indexer - try re-adding.

**Comment by Kaminogoroshi** [comment]
Yea it works for me also.
Thx for the reply, but does it the fanzub preset only search for anime only or not meaning if the parameter is set to 5070 or others also

**Comment by markus101** [comment]
The fact that anizb was working as a newznab indexer was a happy accident, but it doesn't actually support any newznab functionality that I can see (missing the `caps` functionality being a big part of it). That update did add some more validation when getting caps which is why it started working.

With Fanzub and anizb both being anime only there aren't any categories to choose from.
