### ISSUE TITLE
Unable to parse episodes from release name

### ISSUE THREAD

**Issue by vdefender** [Sonarr/Sonarr#2106]
Release rejected

> Unable to parse episodes from release name

Here is the name of the episode

> Frequency.S01E00.Epilogue.1080p.WEB.x264-TBS[rartv]

Oddly it's not showing up in the error logs. Do I need to set it to be more verbose?

**Comment by markus101** [comment]
One of two possible causes, [rarbg] causing it to be parsed with an absolute episode number or the fact that s01e00 isn't a valid episode and not matched.

Debug logs will show the processing on more details.

The first possible issue is part of issue https://github.com/Sonarr/Sonarr/issues/457 the second is just a bad release name for a special and likely will need to be grabbed manually (as happened s with a number of special due to their poor naming).

**Comment by Taloth** [comment]
@markus101 Except that we remove that suffix in https://github.com/Sonarr/Sonarr/blob/766520b851bbadf325a73139a1643c4d050db4a0/src/NzbDrone.Core/Parser/Parser.cs#L258. That leaves 'isn't a valid episode', which is correct: S01E00 doesn't exist, which is scene's way of mapping season specials. On tvdb it's S00E01. Which is covered by https://github.com/Sonarr/Sonarr/issues/1872.
