### ISSUE TITLE
Allow manual searches to have different priority.

### ISSUE THREAD

**Issue by fftux** [Sonarr/Sonarr#2108]
**Summary**
Currently the download client settings allow for a 'recent' (less than 14 days old) priority, and an 'older' priority.  It would be nice to also have a priority for manual searches, or to allow for user selectable priority when doing a manual search.  

**Use case**  
Recent is set to normal, older is set to low, and manual set to high.  Typically, when performing a manual search, it is because you just found out you are missing an episode.  This allows for you to do a manual search, and upon a match being found it will immediately jump to the top of the queue.  Otherwise recent episodes will have precedence over the backlog.

**Comment by markus101** [comment]
I can see some benefit to this, but the use case seems limited, by either having a lot of things already queued or the potential to have newer items queued before the download completes. There are probably other  reasons why you'd want to queue something at a higher or lower quality and if we add one, why not add them all, which could result in many different (possibly conflicting) options for quality.

If clients had anything close to standardized priority levels perhaps it could be chosen at time of grab, but they are all over the place and even that would probably lead to other priority options.

My initial thought for this is no, because it has a reasonable chance to snowball, but I'll let @Taloth weigh in as well.

**Comment by chopskxw** [comment]
Thanks.  I know it is a bit of a stretch, but it is something I deal with frequently.  I have less than great internet, so I usually always have things queued.  This would greatly help with lessening my need to manually manage a queue.  

I would suggest, if implemented, that by default it work just as today, but simply add the option to do an override for manual searches.  That way, it is not on unless users configure it to be.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
