### ISSUE TITLE
Repair Database startup option

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#2134]
Currently if the JSON in `IndexerStatus.LastRssSyncReleaseInfo` becomes corrupt RSS ceases to function properly (https://pastebin.com/GrkkHt78 - with mono 4.6.1). We could either have the parser handle that automatically and fall back to `NULL` or clear it during the housekeeping runs.

A similar issue came up recently on the forums/IRC with a `Series.Ratings` being corrupt. Never becoming corrupt in the first place would be better than having to fix it up afterwards, but at least things would keep working.

**Comment by Taloth** [comment]
These things are caused by database or memory corruption, when that happens Sonarr should just bail. The fact that it appears inside those fields is just a coin-toss. You could do 'null' but then you're just looking at the tip of the iceberg.

So when this happens, Sonarr should just panic and throw a 'database corrupt' exception and point at an dedicated wiki page.

While it might make sense to gracefully handle or repair the damage, it hides a far more severe issue and can create unpredictable behavior.
If you want to offer a tool to repair damage, then add a --repair mode that does a full integrity check on the database, checks those json fields and repair them where possible or clear them if they're just metadata. But I'd be opposed to doing that as part of the normal workflow in Sonarr.

**Comment by markus101** [comment]
Good points, I like the idea of a repair option so we can do something about it (if possible). Throwing a corrupt database with more information (ideally a way to surface that as a health result) would also be helpful to indicate to the user that there is a problem.

**Comment by markus101** [comment]
Having gone through a SQLite repair recently made me realize how out of scope this is, closing without places to revisit.
