### ISSUE TITLE
Season Alias (e.g., S05 vs S2017)

### ISSUE THREAD

**Issue by Webreaper** [Sonarr/Sonarr#2137]
I have a show (Child Genius UK) and the tracker I use is posting it as Season 5. The TVDB lists the seasons as years (so this year's is S2017). I submitted a naming correction, but it's been rejected as a numbering issue, not a naming issue. 

Is there a way to specify a Season Alias? I see this mentioned in previous Issues, but can't find it anywhere in the GUI, so presuming it's a feature that was dropped? What's the solution (other than managing the whole season myself manually, which is a PITA)?

**Comment by markus101** [comment]
TheXEM.de is the correct place for numbering issues, a difference in season or episode numbers is a numbering issue, a difference in different seasons using different names can properly be handled aliases applied to the season instead of the series, which we do handle via that the naming request form.

There are a few don't listed in when submitting a request via that form, which does direct numbering issues to thexem.de and for the future we prefer support/questions to be posted on the forums.

**Comment by Webreaper** [comment]
My question was less of a support issue, and more of a question of how we handle these cases in Sonarr and whether a feature is needed to allow end-users to actually be able to manage this themselves. I don't really understand your response - are you telling me that we _can_ support S05 => S2017 style aliases via the naming request form? If so, why did I get a "This is not a naming issue, it's a numbering issue" response, without it being added? You mention TheXEM.de - are end-users supposed to register and add maps themselves here? If so, it's a complicated and unwieldy solution, and could be better served by managing this directly in Sonarr.

**Comment by markus101** [comment]
> are you telling me that we can support S05 => S2017 style aliases via the naming request form?

No, that belongs on thexem.de I was referring to seasons where a different name is used (such as Aqua Teen Hunger Force).

> You mention TheXEM.de - are end-users supposed to register and add maps themselves here?

The best course of action is to reach out to them on IRC, one of the mods can set it up (if it makes sense and in this case I believe it does).

> If so, it's a complicated and unwieldy solution, and could be better served by managing this directly in Sonarr.

If it was part of Sonarr it'd still be quite complicated, your case is quite easy, but there are a lot more complicated requirements for other series where certain episodes are off because of a special or parts of seasons really belong to another season. thexem.de isn't a perfect solution, but it's the only viable option for this at the moment.

**Comment by Webreaper** [comment]
Okay. I'll just leave it for now; manually snatching and importing this particular series is far less hassle than TheXEM/IRC/etc.

I understand that there are far more complex edge cases (episode offsets etc) but having no simple way to set up a season name alias seems like a scenario that would be easy to support. It just seems a shame that Sonarr is so advanced in most respects, but something as useful as this management of outliers is implemented **so** much better in SickRage (for example).
