### ISSUE TITLE
Categories on qBittorrent are sometimes not set

### ISSUE THREAD

**Issue by zone117x** [Sonarr/Sonarr#2155]
It seems that maybe 1 out of 20 times the category does not get set when the torrent is added to qBittorrent. Seems to happen more often when there are several downloads already going. 

Is the category being set with a separate API call after the torrent gets added? If so maybe it needs a retry.

**Comment by markus101** [comment]
Typically this is due to the torrent failing to be sent to qbit (at least in Sonarr's eyes), the debug logs would be the best place to look at why Sonarr failed to set the category in a particular instance.

The category is set via a separate call, but if qbit returned a negative response to being sent the torrent or magent there isn't anything for Sonarr to retry.

**Comment by markus101** [comment]
If there is something concrete we can investigate in the logs let us know, but nothing actionable right now.
