### ISSUE TITLE
Daily shows are mixing dates

### ISSUE THREAD

**Issue by tomsommer** [Sonarr/Sonarr#2215]
Screenshot says it all, the parsing is mixing month and day randomly?

![image](https://user-images.githubusercontent.com/149171/31309222-0c2d54be-ab83-11e7-909c-28b4f05477c8.png)

**Comment by markus101** [comment]
It looks like both results are being returned by your indexer, but the wrong episodes are all rejected as they are for the wrong episode. Sonarr will process any results returned so it can determine which episode it belongs to.

**Comment by tomsommer** [comment]
Explain this then:

![image](https://user-images.githubusercontent.com/149171/31315905-94113d4c-ac22-11e7-9cc2-7f91e3888c63.png)

**Comment by markus101** [comment]
TheTVDB renumbered some episodes and added them the previous season, because Sonarr links the episodes by Season + Episode number when refreshing the series it kept the files associated to the episodes with the same episode numbers, which now have different dates.

The easiest way to fix this would be to move the episodes out of the series folder, rescan the series, then back in and re-scan the series (or move them to the proper season folder, if you're using season folders for that series).
