### ISSUE TITLE
Error notifications

### ISSUE THREAD

**Issue by Igglybuff** [Sonarr/Sonarr#2230]
Ideally the built-in options for what sort of notifications you want to deliver (currently grab/download/upgrade/rename) should be expanded to include error notifications too, particularly for cases where Sonarr fails to import a download from a download client due to `No files found are eligible for import in /oath/to/download` which is fairly common.

**Comment by markus101** [comment]
We have plans to notify on health check failures: https://github.com/Sonarr/Sonarr/issues/1798 and maybe import failures fall under that at some point, but we don't plan to alert on every possible error.  Failing to import because a file is missing should not be common, it'd be best to fix the underlying issues otherwise alerts are noise you're likely to end up disabling or ignoring.
