### ISSUE TITLE
[Feature Request] HDR Quality

### ISSUE THREAD

**Issue by Ashkaan** [Sonarr/Sonarr#2235]
HDR content is getting more popular (thankfully).  Is there any way to prioritize support as a feature?

It would probably need to look like this:

1) The addition of the HDR quality profile as an option and some search terms related on the backend, and
2) Support for multiple quality profiles.

We need Sonarr to be able to get and maintain both an HDR and regular version of each show so we can still watch our shows on non-HDR devices.  For example, I have Plex on my HDR TV to watch HDR content, but I also need a second non-HDR copy for Plex on my iPad.

**Comment by markus101** [comment]
1. I don't see HDR as being a separate quality, it's still the same source with different options, like 7.1 vs 5.1. Preferred words (https://github.com/Sonarr/Sonarr/issues/385) would help here, but wouldn't solve the wanting to have multiple files retained.
2. That's really more of multiple files per episode, than a separate profile. https://github.com/Sonarr/Sonarr/issues/312 exists for that, but not a priority for us to add

**Comment by Ashkaan** [comment]
Wait, that wouldn't work.  If a show has HDR as a preferred word, then it will only get the HDR version and I won't be able to play it on my iPad.

Don't you have this problem personally?  What's the solution?

**Comment by markus101** [comment]
There isn't really a workaround for this right now, since Sonarr can't have more than one file per episode. Two instances of Sonarr one requiring `HDR` would work, but not ideal since the files would also need to be stored separately. To achieve what you want both those issues would need to implemented, but how Sonarr would deal with multiple files of different/the same quality is a big question mark.

**Comment by Ashkaan** [comment]
I'm willing to compromise and store them in two locations.  I'll try two Instances.  Thank you.

**Comment by DavHau** [comment]
Years have passed and in the meantime HDR got maintream. Many new releases are in HDR now. Therefore i think this topic should finally get addressed.

>     1. I don't see HDR as being a separate quality, it's still the same source with different options, like 7.1 vs 5.1. Preferred words (#385) would help here, but wouldn't solve the wanting to have multiple files retained.
I disagree. HDR is one of the big milestones in video quality and not just some small option. The quality jump to HDR is probably bigger than the one from 1080p to 2160p. Since there are even profiles for WEBDL, Bluray, and HDTV even they have the same resolution, then definately HDR deserves it's own one, too. It differs from all those before very much. Many people don't see the difference between 1080p and 2160p but the shiny colours, contrast and brightness of HDR can be a different story.

BTW, I really don't see why the topic of having multiple files/qualities per episode is required for HDR.
Your media server should be able to downsample HDR for your devices as they downsample 2160p to 720p, too. And i also think in the meantime this should already be supported by plex/emby. If not, post an issue there ;)

I didn't look too much into your plans for v3. But in case the quality profiles work in any kind similar as in v2, then HDR should get some special attention as it is the main new milestone in video quality.

**Comment by Ashkaan** [comment]
@DavHau, you're absolutely right about the need for this.  One thing to keep in mind is that Plex Media Server only downsamples HDR to SDR in certain situations.  For example, it does not downsample when it has to transcode.  The Plex devs are way behind on this as Emby seems to do it.

It's a complicated issue because it's not really a "Quality" as Radarr defines it.  You can have a Bluray-2160p in SDR or HDR.  So doubling the number of qualities sounds awful.  It would make more sense for the Radarr team to rethink how this works so it's separated out.  For example, we would have 3x "Qualities" lists Resolution, Source, and Color Space.  Then, we can set preferences in each of those.  Even that idea has a glaring shortcoming.

I found that the best workaround right now is to add "Preferred Tags" of "HDR" and "HDR10Plus".

**Comment by nismanoku** [comment]
i also have a SDR television and have no problem with my shield TV (Plex) and oppo player playing any of the HDR content on it. May it be HDR10, HDR10+ or Dolby Vision (MP4). So maybe look into the shield as it may transcode the HDR to SDR as i can see that my plex server is direct playing to it, but don't know for sure.
