### ISSUE TITLE
Sonarr Repeatedly showing Missing Root Folder errors 

### ISSUE THREAD

**Issue by stuntguy3000** [Sonarr/Sonarr#2309]
This is a bit of a tough one.

In my environment, Sonarr runs on a laptop which connects to a network share which is **not always active**.

When with Sonarr service auto starting disabled, if Sonarr is opened before the network share is mapped I cannot get it to "find the root folder on the mapped drive" - This _includes_ restarting the service from Windows services and "Restart" within Sonarr itself.

This is extremly annoying and frankly I have no idea how to get around it.

I have verified the path it cannot find is always mapped and writable, because torrents are writing to it.

Please implement better health checks including automatic retries.

Thanks

**Comment by nuhll** [comment]
I guess you could simply slow the start of sonarr. There are many tuts on internet for it. (as workaround)

**Comment by markus101** [comment]
I think we could improve things here by re-checking things following a successful import since that should mean thing are operating properly. The health check could still show on start up for some time.

**Comment by Taloth** [comment]
@markus101 That's easy to do with [these attributes](https://github.com/Sonarr/Sonarr/blob/8cc02a9d9c271128800b069f6a7b8d87f0919d3f/src/NzbDrone.Core/HealthCheck/Checks/RootFolderCheck.cs#L8-L10).
But we could implement a `[CheckOn(typeof(SeriesScannedEvent/ImportedEvent), IfFailed=true)]` causing it only to recheck if the healthcheck failed previously. Instead of always. 
Or better yet, have the error detection during import / series scan that checks whether the root folder exists report an 'Issue' so we can track it.

Or... hehe... Move the actual diskprovider check away from the import logic into a separate 'Check'/'Verify'/'Condition'/something class that does the heavy lifting.
RootFolderCheck would simply invoke 'RootFolderPresentCondition' for all series, import would do the same but then for one series. The Condition would obviously just invoke diskProvider, but then also be able to handle the error/issue reporting.
So a `if (_rootFolderPresentCondition.IsSatified(series.RootFolder, ...))` statement. This would allow the Condition to tackle reporting the issues, and specify how critical it is.
It also means we could potentially deal with recurring issues (and thus repeated error log entries).
I can see how this would relate to the async import process for TransferProviders, since at any point during the import you can have a 'blocking issue', and with the proper infrastructure have it reported to the user.

**Comment by markus101** [comment]
Yeah, saw that attribute, I was worried about constantly checking, but I think a conditional on it will help.

Your second idea is inline with https://github.com/Sonarr/Sonarr/issues/677 I think.
