### ISSUE TITLE
Manual Import relative path sort

### ISSUE THREAD

**Issue by Delerium** [Sonarr/Sonarr#2313]
What is going on with the default sort order in manual import?  Just about every list of episodes that I manually import, I get a list with a few episodes sorted out of order. 

Example:
MythBusters S12E01 Star Wars Special.mp4
MythBusters S12E02 Moonshiner Myths.mp4
MythBusters S12E03 Hollywood Car Crash Cliches.mp4
MythBusters S12E04 Car Chase Chaos - Animal Antics.mp4
MythBusters S12E05 DO Try This at Home.mp4
MythBusters S12E06 Mythssion Impossible.mp4
MythBusters S12E07 Bullet Baloney.mp4
MythBusters S12E08 Supersonic Ping Pong - Ice Cannon.mp4
MythBusters S12E14 Traffic Tricks.mp4
MythBusters S12E15 Plane Boarding - Bite the Bullet.avi
Mythbusters S12E09 Fire in the Hole.mp4
Mythbusters S12E10 Household Disasters.mp4
Mythbusters S12E11 Commercial Myths.mp4
Mythbusters S12E12 Road Rage - Cliff Top Push Off - Wanted Car Flip - Two Wheel Wipe Out.mp4
Mythbusters S12E13 Laws of Attraction.mp4

At first I thought it might be sorting by extension first then alpha, but then episode 14 would be in the right place.  This gets frustrating if you are trying to import things that aren't being detected properly, and the manual import can't even show you the files in correct order.

**Comment by markus101** [comment]
Those the the complete relative paths including sub folders?

**Comment by Delerium** [comment]
Why was this closed?  All of those files are from the same exact folder.  This is not something that just happens once.  Just about every manual import from a single directory does this.

**Comment by markus101** [comment]
![image](https://user-images.githubusercontent.com/413544/33521012-e3dc9410-d77a-11e7-91cb-24b5e1e4e677.png)

Which leads you to the commit where this was fixed: https://github.com/Sonarr/Sonarr/commit/32309260b9b62ec1025d9c86db89a17953f5a6a5

The actual issue is MythBusters vs Mythbusters, when sorting those are not the same unless you're explicitly sorting ignoring the case or converting everything to a single case (which is what the fix does).

**Comment by Delerium** [comment]
gotcha. sorry, I didn't realize the message meant you committed a change.  Thanks for the fix!
