### ISSUE TITLE
[Telegram] Downloaded notification are not sent

### ISSUE THREAD

**Issue by welcoMattic** [Sonarr/Sonarr#2321]
## Bug Report

Downloaded notifications are not sent on Telegram
Grabbed one, yes.

### System Information/Logs

**Sonarr Version:** 2.0.0.5054

**Operating System:** Docker (on Ubuntu)

**.net Framework (Windows) or mono (macOS/Linux) Version:** 5.0.0

**Link to Log Files (debug or trace):** no logs/errors about notifications

**Browser (for UI bugs):**
Telegram configuration
![image](https://user-images.githubusercontent.com/773875/33715429-bd0d5578-db52-11e7-921c-7161c75e0d59.png)

**Comment by markus101** [comment]
Please open a thread on the forums for support, we'll need to see debug logs of a grab/import.

**Comment by welcoMattic** [comment]
That is the bug, there's no logs.

**Comment by markus101** [comment]
At the very least with debug logs you're going to get one of these messages:

When no tags are set: `No tags set for this notification.`
When tags are set and the grabbed/imported series has at least one tag that is the same: `Notification and series have one or more matching tags.`
When tags are set and the grabbed/imported series does not have any tags that are the same: `Telegram does not have any tags that match "The Series"'s tags"` (where "The Series" is the actual series title)

Since nothing is being sent I'd guess you're running into option 3. Make sure the series have those same tags (tags aren't used to filter notifications by something in the release name or filename).
