### ISSUE TITLE
With Jackett: Agents of S.H.I.E.L.D., not searching for "S.H.I.E.L.D.", only "SHIELD" and "S H I E L D"

### ISSUE THREAD

**Issue by Wyall** [Sonarr/Sonarr#2330]
Doing a manual search for a Agents of S.H.I.E.L.D. episode, Jackett's logs show that the searches are:
Marvels Agents of S H I E L D
Agents of SHIELD
Marvels Agents of SHIELD

This returns no results on my indexers (all tracker with jackett), they need some combination with "S.H.I.E.L.D." (testet with Jacketts direct search function in web interface). In the Radarr Discord somebody said that he/she doesn't have this problem with usenet.

For RSS it works, it seems like one of the indexers announces the releases there in a way that works with Sonarr, but the manual search afterwards doesn't work.

It seems to me that the problem is that either Sonarr doesn't look for S.H.I.E.L.D. (but not sure, as it worked with usenet), or the dots get lost on the way to Jackett?

**Comment by markus101** [comment]
Periods are always removed when searching, which works for most indexers, though depends how the indexer on the other end handles it.

> For RSS it works, it seems like one of the indexers announces the releases there in a way that works with Sonarr, but the manual search afterwards doesn't work.

RSS works because Sonarr knows they are the same thing when it processes the release.

Closing as this is covered by https://github.com/Sonarr/Sonarr/issues/2152 and similar to https://github.com/Sonarr/Sonarr/issues/1225
