### ISSUE TITLE
Season Folder check before import fails for nested folders

### ISSUE THREAD

**Issue by qweasdzxc787** [Sonarr/Sonarr#2338]
### System Information/Logs

**Sonarr Version:**
2.0.0.5085

**Operating System:**
Fedora 26

**.net Framework (Windows) or mono (macOS/Linux) Version:**
Mono version 4.8.0

**Link to Log Files (debug or trace):**
[sonarr.debug.21.txt](https://github.com/Sonarr/Sonarr/files/1560742/sonarr.debug.21.txt)

### What problem are you looking to solve?
Sonarr incorrectly imported and overwrote Game of Thrones episodes 01x01, 01x02, 01x03, 01x04, and 01x09 with Season 7 Extras. I had both extras and all seasons except 7 as un-monitored. Sonarr should not overwrite episodes that are un-monitored for any reason. See attached log.

**Comment by markus101** [comment]
Your logs don't appear to have anything to do with the issue, I don't see anything for GoT or any imports.

Unmonitoring only affects grabbing via RSS feeds and series/season searches. An automatic or manual search for a single episode will not reject results because it's unmonitored and will grab a release if it meets the required criteria. Unmonitoring also does not affect importing because that would make automatic and manual searches for unmonitored episodes pointless (if it wouldn't import it afterwards).

My best guess is the files were named in a way that Sonarr thought they were for season 1 (a special with an episode number only could do that), but without accurate logs it's only a guess.

We do not have plans to make importing check if the episode is monitored as that is not the intention of that flag.

**Comment by qweasdzxc787** [comment]
This is straight out of the log...did you not read it?

17-12-14 08:25:04.1|Debug|QualityParser|Trying to parse quality for Game.of.Thrones.S07.Extras.REPACK.1080p.BluRay.REMUX.AVC.TrueHD.5.1-EPSiLON
17-12-14 08:25:04.1|Debug|Parser|Quality parsed: Bluray-1080p v2
17-12-14 08:25:04.1|Debug|Parser|Release Group parsed: EPSiLON
17-12-14 08:25:04.1|Debug|UpgradeMediaFileService|Removing existing episode file: [49622] 01x09 - Baelor.mkv
17-12-14 08:25:04.1|Debug|RecycleBinProvider|Attempting to send '/storage/TV/TV/Game of Thrones/01x09 - Baelor.mkv' to recycling bin
17-12-14 08:25:04.1|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /storage/TV/TV/Game of Thrones/01x09 - Baelor.mkv
17-12-14 08:25:04.2|Debug|RecycleBinProvider|File has been permanently deleted: /storage/TV/TV/Game of Thrones/01x09 - Baelor.mkv
17-12-14 08:25:04.2|Debug|EpisodeService|Detaching episode 650 from file.
17-12-14 08:25:04.3|Debug|MediaInfoFormatter|Formatiting audio channels using 'AudioChannelPositions', with a value of: '3/2/0.1'
17-12-14 08:25:04.3|Debug|EpisodeFileMovingService|Copying episode file: /export/Finished/torrent/sonarr/Game.of.Thrones.S07.Extras.REPACK.1080p.BluRay.REMUX.AVC.TrueHD.5.1-EPSiLON/Featurettes/09 - Conquest & Rebellion - An Animated History of the Seven Kingdoms.mkv to /storage/TV/TV/Game of Thrones/01x09 - Baelor.mkv
17-12-14 08:25:04.3|Debug|DiskTransferService|Copy [/export/Finished/torrent/sonarr/Game.of.Thrones.S07.Extras.REPACK.1080p.BluRay.REMUX.AVC.TrueHD.5.1-EPSiLON/Featurettes/09 - Conquest & Rebellion - An Animated History of the Seven Kingdoms.mkv] > [/storage/TV/TV/Game of Thrones/01x09 - Baelor.mkv]
17-12-14 08:25:04.3|Debug|OtherExtraFileService|Deleting Extra from database for episode file: [49622] 01x09 - Baelor.mkv
17-12-14 08:25:04.3|Debug|MetadataFileService|Deleting Extra from database for episode file: [49622] 01x09 - Baelor.mkv
17-12-14 08:25:04.3|Debug|SubtitleFileService|Deleting Extra from database for episode file: [49622] 01x09 - Baelor.mkv
17-12-14 08:26:52.7|Debug|DiskProvider|Setting permissions: 644 on /storage/TV/TV/Game of Thrones/01x09 - Baelor.mkv
17-12-14 08:26:52.7|Debug|DiskProvider|User and Group for chown not configured, skipping chown.
17-12-14 08:26:52.7|Debug|EpisodeService|Linking [01x09 - Baelor.mkv] > [[650]Baelor]
17-12-14 08:26:58.0|Debug|TransmissionProxy|Transmission authentication succeeded.
17-12-14 08:26:58.2|Debug|Parser|Parsing string 'Game.of.Thrones.S07.Extras.REPACK.1080p.BluRay.REMUX.AVC.TrueHD.5.1-EPSiLON'
17-12-14 08:26:58.2|Debug|Parser|Episode Parsed. Game of Thrones - Season 07 
17-12-14 08:26:58.2|Debug|Parser|Language parsed: English
17-12-14 08:26:58.2|Debug|QualityParser|Trying to parse quality for Game.of.Thrones.S07.Extras.REPACK.1080p.BluRay.REMUX.AVC.TrueHD.5.1-EPSiLON
17-12-14 08:26:58.2|Debug|Parser|Quality parsed: Bluray-1080p v2
17-12-14 08:26:58.2|Debug|Parser|Release Group parsed: EPSiLON

It grabbed a S07 Extras release on it's own, downloaded it, and used it to replace S01 content (that was un-monitored). After having manually ripped S01 from Blu-rays myself, this is highly frustrating. Sonarr didn't even bother to check file sizes before overwriting them! (a 10GB file was replaced with a 2.7 GB file, regardless of content, that's just wrong). Fix this. Give us control of our content so we can decide if something needs replacing. When I mark something as un-monitored, I really intend that to be the case. Don't touch it!

**Comment by qweasdzxc787** [comment]
At the very least halt it from overwriting it, like it does when it downloads a release and it's the same size as the previous file (I've seen that many times). I had to go out of my way to restore content thanks to this bug. My only other option is to completely delete the series from Sonarr to ensure it doesn't get messed with.

**Comment by markus101** [comment]
> This is straight out of the log...did you not read it?

I searched for it, but it turns out it was only matching on exact matches, I see it now. I definitely didn't read it line by line hunting for it.

> It grabbed a S07 Extras release on it's own

Extras releases are filtered out and if the release name was `Game.of.Thrones.S07.Extras.REPACK.1080p.BluRay.REMUX.AVC.TrueHD.5.1-EPSiLON` (matching the folder name) it would have been. If your indexer had a different name then it could sneak through.

> and used it to replace S01 content

That shouldn't have happened, but I see why it did, it's due to the `Featurettes` subfolder, Sonarr checks the folder to see if it should restrict it to a specific season, but that didn't succeed since the parent folder wasn't the release name. We should also check the information Sonarr has from the download client in this case.

> Sonarr didn't even bother to check file sizes before overwriting them! (a 10GB file was replaced with a 2.7 GB file, regardless of content, that's just wrong)

Just checking the file sizes wouldn't work, if the user wanted to "upgrade" to a smaller release for archival purposes. Sonarr could check if it's a smaller size if the quality is the same, which should cover most cases adequately, if the quality couldn't be determined it could fall apart, but that's going to cause issues regardless.

> When I mark something as un-monitored, I really intend that to be the case. Don't touch it!

As I said, that's not the intended functionality of that flag and we do not have plans to change it's behaviour.

**Comment by Taloth** [comment]
So what's the grab event in the episode history?
