### ISSUE TITLE
Easy fix for foreign users

### ISSUE THREAD

**Issue by nuhll** [Sonarr/Sonarr#2339]
Hi, im using the latest sonarr version since some weeks now.

Much thanks so far. I love it!

But it could be better for foreign users.

Add just one thing for us NON English ppl, **let us add something to the title.**

BECAUSE all film on this world, which are not in english, have country added.

Seriesname S01E01-> if its english
Seriesname S01E01 **german** -> if its german
Seriesname S01E01 **italia** -> if its italia (i dont know how italian movies are named, but i think u get that part xD)

I would suggest to add one checkbox at:

Restrictions -> "must contain" -> e.g. -> "german" -> **checkbox** -> _"Do you want to add this to the search querrys_"?

Its that easy. At the moment its pretty much unusable (or lets say, it could be much better without effort) and torrent e.g. is complete broken for foreign users.

Please add this also for radarr. Its an easy fix and would help all NON english speaking ppl in the world 💃

**Comment by markus101** [comment]
Searching for `Serienname S01E01` should also include `Serienname S01E01 german` results, if it doesn't that's something with the indexer excluding it (either the indexer failing to return it or not returning it because it's in a different category). Sonarr also searches using TVDB, TVRage and TVMaze IDs if the indexer supports it.

I don't see a scenario where searching would be improved by this change, so not something we'll look into adding.

**Comment by nuhll** [comment]
The problem is if you have 1000 Serienname S01E01, you wont probably find the 1000-1050 which include Serienname S01E01. 

I cant believe you close this.

**Comment by Fish2** [comment]
Cant you just put German in the Indexer Restrictions ?

**Comment by nuhll** [comment]
Cant you just put german in the search querry? O.o (where is the downside?)

Ofc i changed everything what was possible to german, but you wont get ANY results for bittorrent. Because english is more common. 

And ofc i have "restriction" "must contain" "german" BUT that doesnt mean anything if the Serienname s01e01 is not returning anythign with "german" in it because its on page number 298349213

**Comment by markus101** [comment]
> The problem is if you have 1000 Serienname S01E01, you wont probably find the 1000-1050 which include Serienname S01E01 german

1000 results? I've never seen a search for a single episode come anywhere near 1000 legitimate results (only getting close when the indexer returns unrelated results).

>Also this is not only for language problems. If you enable MUST CONTAIN, it will ONLY ADD results if thats in the name, so please explain why it doesnt make sense to add it to the search querry... so the indexer give you results to something you say it MUST CONTAIN that. xD

If you have multiple must contain words, where at least one is required, then Sonarr would need to do a search for each one, which is a waste if one search will also contain them. If you have a concrete example where a search for a single episode returns more than 1000 results, please provide it.

I closed this because you didn't provide a reason why this was useful, you provided a solution instead of describing the actual problem you're trying to solve. Tell us what you want to solve, not only how you want us to fix it.

Off the top of my head there are several potential issues in the suggested approach:

- Multiple release restrictions with "add to search term" would be a problem since order would matter
- Searches by IDs wouldn't apply the restrictions
- Results with the required term later in the release name (ie. `Series.Title.S01E01.HDTV.x264.german` would be filtered out)
- Potential for making searches that only return duplicates of results you already have

**Comment by nuhll** [comment]
The problem is, that sometimes, on many results, the language you are looking for is so far behind, that the indexer is not finding it.

Thats the problem. :)

I cant provide anything conret, but i already saw it. 

"Multiple release restrictions with "add to search term" would be a problem since order would matter"
I would ignore that problem. If yu want to make it right, provide an editable syntax "$title $s $e $S".

$title = title
$s = season
$e = episode
$S = searchword


"Searches by IDs wouldn't apply the restrictions"
If "search by name" disabled, then disable tickbox for add "..." to search.

"Results with the required term later in the release name (ie. Series.Title.S01E01.HDTV.x264.german would be filtered out)"
See 1.

"Potential for making searches that only return duplicates of results you already have"
I dont know, adding a word to search shouldnt really provide the same results.

**Comment by markus101** [comment]
>"Multiple release restrictions with "add to search term" would be a problem since order would matter"
I would ignore that problem. If yu want to make it right, provide an editable syntax "$title $s $e $S".

You could search for each word individually, but you'd still have the problem with extra words between the end of the normal search term and the additional term. I'm not sure how a custom syntax would help solve this, though this particular case could be overcome by search each word on it's own.

> "Searches by IDs wouldn't apply the restrictions"
If "search by name" disabled, then disable tickbox for add "..." to search.

That decision is made at search time and differs per indexer, you can't simply disable the ability to set them in that case.

>"Results with the required term later in the release name (ie. Series.Title.S01E01.HDTV.x264.german would be filtered out)"
See 1.

That suggestion doesn't help if you don't know what is there before searching.

>"Potential for making searches that only return duplicates of results you already have"
I dont know, adding a word to search shouldnt really provide the same results.

It absolutely would if you search for `Series Title S01E01` then search for `Series Title S01E01 german`.

Being able to perform customized searches would probably be more useful as a way to do it manually, when required, instead of trying to solve it on automated searches and hope you get the results you want, such as: https://github.com/Sonarr/Sonarr/issues/1128

**Comment by nuhll** [comment]
Ive got an even easier idea how to implement.

Currently i can change the language he searchs for from english to german. Make a tickbox next to it "Add language to search?".

viola.

**Comment by Taloth** [comment]
Please don't ask for a specific solution. Explain your actual problem instead: If you're getting 1000+ results on search then we need to know why and how that happens.   
Come up with an example and a list of the results that Sonarr produces in Manual Search (screenshot for example, or debug level log file of the search). So we can investigate if your indexer returns erroneous results for the search.

Given you're talking about query strings, you're probably be using Jackett, since proper indexers don't use query strings. So which indexers do you use in Jackett? And do you use those individually in Sonarr or did you add the aggregate feed instead?

We cannot help you without an example and details of the actual problem.

**Comment by nuhll** [comment]
No, you dont want to help. I guess, if a release is tagged correctly than a german release always has german in the release. Thats why you should search for it. There is nothing to explain or show its liek this for the last 30 years. I disabled now torrent, because its unuseable, might be bc u dont look for german, or maybe its just too less for germans there. 

You are right with jackett, i just came to the idea with adding german because jackett cached 900 results (3 indexer) and none of them included "german", thats why i asked for adding german to the search. 

But since i removed now bittorrent, i dont need it anymore.

**Comment by nuhll** [comment]
NzbSearchService | Searching 3 indexers for [Girls Trip] | 
8:32pm
-- | -- | --
  | DownloadDecisionMaker | No results found | 8:32pm

![1](https://user-images.githubusercontent.com/34555093/34322167-a37acd22-e820-11e7-845e-152d418f378f.jpg)
![2](https://user-images.githubusercontent.com/34555093/34322168-a3981850-e820-11e7-95de-21cf3a43a46c.jpg)

Ofc, same indexers in both programs.
