### ISSUE TITLE
Stack overflow in Newtonsoft JSON deserializer

### ISSUE THREAD

**Issue by ohner** [Sonarr/Sonarr#2344]
### System Information/Logs
**Sonarr Version:** 2.0.0.5085
**Operating System:** Arch Linux 
**.net Framework (Windows) or mono (macOS/Linux) Version:** 5.0.0.100-2

### Additional Information
A Stack Overflow in JSON deserialization: 
sonarr[391]: Native stacktrace:
sonarr[391]: Stack overflow: IP: 0x562daf05752e, fault addr: (nil)
sonarr[391]: Stacktrace:
sonarr[391]:   at <unknown> <0xffffffff>
sonarr[391]:   at (wrapper alloc) object.AllocVector (intptr,intptr) <0x0015b>
sonarr[391]:   <...>

Full stack trace attached. 
[stacktrace1.txt](https://github.com/Sonarr/Sonarr/files/1573432/stacktrace1.txt)

**Comment by markus101** [comment]
This is a crash in mono and not something Sonarr can work around. It may be due to unamanaged memory corruption or a bug in mono.

If the issue is with mono, upgrading (or even downgrading) may help.

Feel free to open a thread on the forums to discuss/troubleshoot further, but closing this out as it's not a bug with Sonarr.
