### ISSUE TITLE
File dates for episodes prior to 1970 don't get set.

### ISSUE THREAD

**Issue by MikuroK** [Sonarr/Sonarr#2345]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

## Bug Report
Sonarr does not update file modification dates for episodes aired prior to 1970.
[](url)

### System Information/Logs

**Sonarr Version:**
2.0.0.5085

**Operating System:**
Arch Linux

**.net Framework (Windows) or mono (macOS/Linux) Version:**
Mono 5.0.0.100

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**
Basilisk 55.0.2017.11.30

### Additional Information
Aug 30  2008 'I Dream of Jeannie S05E12 - My Sister, the Home Wrecker (DVD).avi'
Aug 30  2008 'I Dream of Jeannie S05E13 - Jeannie, the Matchmaker (DVD).avi'
Aug 30  2008 'I Dream of Jeannie S05E14 - Never Put a Genie on a Budget (DVD).avi'
Jan  6  1970 'I Dream of Jeannie S05E15 - Please Don'\''t Give My Genie No More Wine (DVD).avi'
Jan 13  1970 'I Dream of Jeannie S05E16 - One of Our Hotels is Growing (DVD).avi'
Jan 20  1970 'I Dream of Jeannie S05E17 - The Solid Gold Jeannie (DVD).avi'

**Comment by markus101** [comment]
Windows won't show last modified dates before 1970 and I assume the same is true for Linux as that is the beginning of time for systems.

Nothing actionable for us here.

**Comment by Taloth** [comment]
It's essentially a 'Not Implemented' in mono (see https://github.com/mono/mono/blob/f408d2c4c4e7da44a8c17c1fd5a62549cd00ba55/mono/metadata/w32file-unix.c#L1524-L1546 )
Instead of checking what the minimum supported value is, they just limit it to 0 (so 1970 epoch). It's a bit lazy as emphasized by the `This is (time_t)0.  We can actually go to INT_MIN, but this will do for now.` comment in the code.   
Let's face it, we're (ab)using the modtime to denote how old the content is, not the actual file... which is not what modtime was intended for.   

I've no intention to report this issue to upstream mono, it's not worth it imho. But what we could do is have Sonarr set it to 1970 instead of not changing it at all (and thus also avoid the 'Invalid Parameter' warnings in your log).
If that's a preferable resolution.

**Comment by MikuroK** [comment]
markus101, linux (at least) will record dates down to 1901-12-13. while 1970-01-01 00:00+00 is the unix epoch, unix time is a _signed_ integer, so it can go below this value if you use negative numbers, which i imagine is not being taken into account.
taloth, if it's a mono issue, then i should file a bug with them, yes. and i understand sonarr setting the dates is both an abuse of the modtime feature and not a critical feature anyway, i still find it nice to see right from my file manager when episodes came out, this information is more useful than the 'true' mod time of when i dumped/encoded/whatever the files.
I agree than setting to 1970 instead of failing outright is a good idea. at least they will then display in the correct order.
