### ISSUE TITLE
Sonarr iffy with ability to use indexers from within lxc

### ISSUE THREAD

**Issue by atytel** [Sonarr/Sonarr#2362]
## Bug Report

**Sonarr Version:**2.0.0.5085

**Operating System:**ubuntu 17.10 lxc

**.net Framework (Windows) or mono (macOS/Linux) Version:**5.4.1.6

**Link to Log Files (debug or trace):**https://ghostbin.com/paste/wtdvh

Basically, torrents have issues too but it's mainly with Usenet indexers. They either won't pull results, or won't pull all results or only some of them will pull results and in that case not all of them. Btw think you guys are doing an awesome job, keep it up!

**Comment by markus101** [comment]
Please use the forums for support.

Not all indexers have the same content and some don't have releases don't appear in search results because they're not linked to the correct series ID (and other results are returned) or title based searches fail for various reasons. If you have a specific example in the logs, please point that out when you open the forum thread.
