### ISSUE TITLE
Auto search configuration

### ISSUE THREAD

**Issue by mikafouenski** [Sonarr/Sonarr#2372]
# Feature Request

Hello,

It would be nice if you could add some sort of customization to the auto search functionality.

The goal of this program is to save time by searching downloads for us. In the case of using torrent to download, the primary search factor is the number of seeder of a torrent. For now the choice of the auto matcher is hardcoded in the file `DownloadDecisionComparer.cs`. 

In the current situation, torrent only users always have to switch to manual mode to select the good torrent, which kills all the good advantage of the automatisation. The other solution is to have a custom version of the code and modify the `Comparer` file by changing the priority of `ComparePeersIfTorrent`.

We don't need a fancy web menu for this but a file configuration or even an executable flag would be really nice.

Sonarr is a very useful software and better it not lose it's interest with something like this.

Keep up the great work, Mika.

PS : extend #1244

**Comment by mikafouenski** [comment]
#1244

**Comment by markus101** [comment]
We do not have plans to support reordering the comparers in `DownloadDecisionComparer`. Doing so would complicate things for minimal benefit.

Some of the reasons they are in the order they are is here:

Quality - Since quality is a preference in itself, more wanted qualities need to be weighted higher
Protocol - Again, there is a preference here, but if you only use Torrents or Usenet and not both it won't change anything
Episode Count - Allows Sonarr to prefer season packs over individual files and prefer single episode releases over multi episode releases (the latter comes into play when upgrading to a higher quality)
Episode Number - Grab episode 1 before later episodes, for a single episode search it won't impact anything

For a purely torrent setup in a single episode search the only one that will likely matter is the quality, but given quality drives upgrades, it doesn't make sense to grab a lower quality and then later download an upgrade that was originally available.

Since the number of seeders is a concern you can specify a minimum number of seeders on a per indexer basis and Sonarr will reject anything with less seeders.
