### ISSUE TITLE
Copying to different hard drive corrupts files.

### ISSUE THREAD

**Issue by metaMMA** [Sonarr/Sonarr#2468]
This issue started between 10 and 25 days ago.  

The issue is, sonarr _apparently_ succeeds in moving files from the "download" hard drive (name: D) to my other hard drive (name: E) and my NAS. However, the file size is generally 90-99% of the original file size. Occasionally the file size will be identical (executing _ls -l_ returns identical sizes), but running a checksum (_md5sum_) returns a different hash. All files moved to E or NAS fail to play all the way through. 

Manual importing from sonarr "wanted" page yields the same result. 

The issue does not exist when sonarr hardlinks to a directory on the same hard drive as the download (D). 

Radarr uses the same download drive and does not have this issue when importing to any of the three destination locations mentioned. 

Only solution is manual copy (_cp /D/path/to/file.mkv /E/path/to/destination_ ). Then, once on the correct drive, I can do a manual import successfully. 

"Use hardlinks instead if copy" is checked
Version 2.0.0.5163
Mono 5.10.0.160

**Comment by Taloth** [comment]
which os and machines are involved?

Check the log files for 'DiskTransferService' and any warn/error that may appear with that text.
Also immediately enable Trace level log files in Settings->General.

**Comment by metaMMA** [comment]
The OS is Debian 9.4. **D** is external USB HDD drive, **E** is internal HDD drive, **NAS** is Buffalo Terrastation. All three are mounted at startup using /etc/fstab.  I held off on opening this issue (even though failure rate has been at 100% for two weeks), because I wanted to make sure it wasn't something on my end, so I turned on Trace level log last week. Below is a failure from yesterday.

```
username@debian:~$ ls -l /mnt/D/done/The.Z-Files.S11E10/the.z-files.s11e10.mkv 
-rw-r--r-- 1 username username 1116102418 Mar 21 20:16 /mnt/D/done/The.Z-Files.S11E10/the.z-files.s11e10.mkv

username@debian:~$ md5sum /mnt/D/done/The.Z-Files.S11E10/the.z-files.s11e10.mkv 
b19126f771a781b2978383e2c5aaf99f  /mnt/D/done/The.Z-Files.S11E10/the.z-files.s11e10.mkv
```

```
username@debian:~$ ls -l /mnt/NAS/TV\ Shows/The\ Z-Files/Season\ 11/The\ Z-Files\ -\ S11E10\ -\ Title.mkv 
-rwxrwxrwx 1 username username 1116102418 Mar 21 20:16 /mnt/NAS/TV Shows/The Z-Files/Season 11/The Z-Files - S11E10 - Title.mkv

user@debian:~$ md5sum /mnt/NAS/TV\ Shows/The\ Z-Files/Season\ 11/The\ Z-Files\ -\ S11E10\ -\ Title.mkv 
9f380065f9a0715903a6e120cebb109e  /mnt/NAS/TV Shows/The Z-Files/Season 11/The Z-Files - S11E10 - Title.mkv
```


I have the trace logs. I can PM you the megalinks to your reddit account, unless there's a better way.

**Comment by Taloth** [comment]
Yes, please send the tracelogs, PM is fine. But I won't be able to check them till tomorrow.
Meanwhile you might want to look at them yourself as well, there is transaction logic in Sonarr that's supposed to detect truncated target files and will log the transfer steps at trace level.
But that's based on file length and triggered by an issue with CIFS, which doesn't seem applicable in the example you just posted since there the file lengths are the same, but with difference hashes.
That could mean that the download client is still busy downloading and that the file gets imported prematurely. Which leads me to the next questions: which download client? and how does the files get imported? via external script, Drone Factory, or the automated system in Sonarr called Completed Download Handling?

**Comment by Logicail** [comment]
@metaMMA have you found any solution to this, I've had a similar problem for months.

For me it only seems to happen if theres a queue of lots of files to be downloaded and processed, even then it's only 1 or 2 files in every season.

```
root@fileserver:~# lsof|grep ****
mergerfs    697             root    5w      REG              8,129 588877824     141295952 /srv/dev-disk-by-label-content6/****.mkv
mergerfs    697 11432       root    5w      REG              8,129 588877824     141295952 /srv/dev-disk-by-label-content6/****.mkv
mergerfs    697 11434       root    5w      REG              8,129 588877824     141295952 /srv/dev-disk-by-label-content6/****.mkv
mergerfs    697 11445       root    5w      REG              8,129 588877824     141295952 /srv/dev-disk-by-label-content6/****.mkv
mergerfs    697 11446       root    5w      REG              8,129 588877824     141295952 /srv/dev-disk-by-label-content6/****.mkv
mergerfs    697 11447       root    5w      REG              8,129 588877824     141295952 /srv/dev-disk-by-label-content6/****.mkv
mergerfs    697 11449       root    5w      REG              8,129 588877824     141295952 /srv/dev-disk-by-label-content6/****.mkv
mergerfs    697 11450       root    5w      REG              8,129 588877824     141295952 /srv/dev-disk-by-label-content6/****.mkv
mergerfs    697 11451       root    5w      REG              8,129 588877824     141295952 /srv/dev-disk-by-label-content6/****.mkv
mergerfs    697 11452       root    5w      REG              8,129 588877824     141295952 /srv/dev-disk-by-label-content6/****.mkv
mergerfs    697 11453       root    5w      REG              8,129 588877824     141295952 /srv/dev-disk-by-label-content6/****.mkv
smbd      17944             root   15w      REG               0,39 588877824 9350285099344 /srv/fa6868aa-a538-483a-a914-77f08a2068f4/****.mkv
```

The file is still being written to but the source had already been deleted, it's only copied about 75% of the file. I end up having to restart samba so I can delete the incomplete locked file and download it again.

Destination is mounted by autofs (openmediavault + mergerfs), nzbget 20, Ubuntu 16.04.4 LTS, Mono 5.10.1.20 (since updated)

**Comment by clowrym** [comment]
I have this issue occasionally on my servers, Although in my case the Media drive is on a seperate server but mounted on my download server. So transfer is over a network,

**Comment by markus101** [comment]
@clowrym that'd be a different issue, probably with mono + CIFS shares, it's well known and mentioned on the forums. Using NFS instead is recommended.

Closing this out, we can re-open if there is something actionable for the original issue.
