### ISSUE TITLE
Option to prefer smaller files

### ISSUE THREAD

**Issue by chuckheron** [Sonarr/Sonarr#2512]
## Feature Request
Option to prefer the smallest version of a show for a given range of qualities.

### What problem are you looking to solve?
For a given profile, nzbdrone picks the highest quality available (and seemingly the largest version)
I use a pre-paid (per MB) block usenet service, and so I prefer smaller versions of a given quality. 
For me, 720p is good enough quality for regular tv shows. 
I've tried creating profiles that limit the size of the downloads, but that gets cumbersome when some shows are 1/2hr or 1hr, or they are sometimes only available in 1080p.

I'd like a profile that would include all qualities 720p or better, but always grab the smallest version available.
Just a switch in general settings to change the overall behavior would be great for me.. 

### Other Information
Thanks! 
Other than this issue,  I really like sonarr/nzbdrone!
Used a 'competitor' for many years, but switched recently and think it's great!

**Comment by Thirrian** [comment]
Not a complete solution, but what would help a little:
You can create a profile where the qualities are reversed. E.g. go into Settings > Profiles > enable advanced settings > create or edit a profile.
Standard the best quality (e.g. Bluray-2160p) will be at the top, so reverse them all by drag & drop with the handlebars on the right of each quality.
Set the cutoff to the best quality which you have enabled for this profile (and which should now be at the bottom):

![screenshot](https://user-images.githubusercontent.com/5676839/38863662-9ef30fd6-4238-11e8-8941-f13ed7922786.png)

This ensures that when sonarr finds multiple candidates, it will pick the lowest quality profile, which is now considered the "best" because it's at the top of the list, and it will not try to "upgrade".
Given a choice between DVD and Bluray-1080p, the DVD release will always win.

I think this gets you 90% of the way. Remaining 10% below.

What it *doesn't* do:
- pick the smallest size in case multiple candidates are available with the same quality. E.g. it will still prefer the biggest HDTV-720p if there are 2 or more HDTV-720p releases. I think this is negligible, since the size difference between releases of the same quality is going to be rather small.
- not entirely realistic, but let's say a HDTV-720p (size: 2gb) and HDTV-1080p (size: 1gb) release is available. Sonarr will still pick the bigger HDTV-720p release since the quality is considered "better" in this profile. This is Bad(tm) for your use case.

_Disclaimer: qualities in the list above may not 100% match a "reversed" list since I already played around with the order a bit, but you get the idea._

**Comment by markus101** [comment]
Going to tie this in with it's opposite: https://github.com/Sonarr/Sonarr/issues/724

**Comment by chuckheron** [comment]
Thanks!
That looks like it will do the job mostly.
I'll try it and see how it goes.

Thanks
-chuck
