### ISSUE TITLE
Different episodes showing when changing a show from Standard to Anime

### ISSUE THREAD

**Issue by nemchik** [Sonarr/Sonarr#2537]
### System Information/Logs

**Sonarr Version:** 2.0.0.5163

**Operating System:** Ubuntu Server 17.10 x64

**.net Framework (Windows) or mono (macOS/Linux) Version:** Mono 5.4.1.7

**Link to Log Files (debug or trace):** N/A (not relevant)

**Browser (for UI bugs):** Google Chrome

### Additional Information

When adding the series `Dragon Ball Z Abridged` with the `Series Type` of `Anime` Season 1 shows 10 episodes and Season 2 shows 20 episodes. When changing `Series Type` to `Standard` Season 1 shows 12 episodes and Season 2 shows 22 episodes. The extra episodes in standard mode are legitimate episodes and should be shown in anime mode. I would keep this show in standard mode except that this show uses absolute numbering for episodes, and standard mode does not use absolute numbering which makes adding this show manually a bit difficult (since manual import DOES show absolute numbering in the import UI when a show is set to anime mode).

**Comment by markus101** [comment]
Episodes with duplicate absolute episode numbers are filtered out when the series type is set to anime, in season 1, episodes 10, 11 and 12 all have the absolute episode number of 10. Often the duplicate absolute episode numbers are done in error and filtering the duplicates is done to match episodes by absolute episode numbers for anime which allows seasons to be changed on the TVDB and files remain connected to the episode with the same absolute episode number.

Since we're mapping by absolute episodes with anime there isn't a way to show the episodes with duplicate absolute episode numbers.

**Comment by nemchik** [comment]
Would it be possible for the Manual Import UI for standard to show the absolute episode numbers (either all the time, or as an option)?

**Comment by fryfrog** [comment]
I'm also editing the show so that each episode has an absolute episode number.

**Comment by fryfrog** [comment]
Yeah, at that point I had already done all of S01, S02 and most of S03. I finished it off, but will reach out to tvdb to see what the "right" move is. :/

**Comment by nemchik** [comment]
I'm in agreement with @Taloth that the absolute numbers shouldn't be changed. The issue is that Episode 10 was released in 3 parts, and each part has separate metadata (episode description, air date, etc). The thumbnails showing up in Plex all have the absolute episode number in them so to have that mismatch wouldn't make much sense either.
