### ISSUE TITLE
Completed Download Handling fails and never tries again

### ISSUE THREAD

**Issue by davidnewhall** [Sonarr/Sonarr#2561]
## Bug Report

I'll start this by explaining what I'm doing and the problem I'm running into. This may be a bug or it may wind up being some sort of a new feature request. 

I'm creating an application that extracts files after Deluge downloads them. During my testing phase, I managed to exacted archives, and then deleted the extracted contents before Sonarr finished importing all the episodes. It managed to import 1-2 eps per season that was downloaded. I didn't notice this for a week or so, and now the downloads seem to be in a limbo state.

Completed Download Handling appears to have run at least once and then stopped or gave up. I've looked through docs and the forums, but I can find no mention of how often Completed Download Handling runs or which downloads it decides to run against. I can make some educated assumptions about this, but I'd really like this information to be cleared up somewhere. To remediate the situation, I had to re-extract all the archives and use the `manual import` feature.

Here's where I'm concerned, and where I think things can and should be improved. While an episode is downloading, or queued, it shows up on the `/api/queue` list. If the files are not compressed, the download seems to quickly disappear from this list. When the files are compressed, this is where "Completed Download Handling" needs better explanation. The `/api/queue` list at this point generally just says `Completed` and/or lists an available sample file as a found but not-importable file. My extraction application tends to extract the files within a few minutes, but it can be slow to extract a lot of episodes in a large season. 

The Download Handler appears to be too fast; it grabs the first couple episodes during extraction, removes *all* the unimproved entries from `/api/queue` and then fails. It never seems to run or check the download (now `seeding`) folder again. The status of the episodes on the `/api/history` endpoint is now "download sent to client" and it never changes. There is no apparent "go check the download folder again" option.

I recently added "wait 10 minutes before deleting" code to my app, and that wasn't long enough for Completed Download Handling to re-run. It still only imported a couple episodes while the rest were still being extracted, and 10 minutes later (after the last file was extracted) it had not checked again.

### System Information/Logs

**Sonarr Version:**  2.0.0.5163 

**Operating System:** macOS 10.12.6

**mono Version:** 5.10.1.47

### Additional Information

This is the application I'm writing, if there is any interest in that end of things. 
https://github.com/davidnewhall/unpacker-poller

### What problem are you looking to solve?

1) I'd like a clear and concise view of what state a download is in. If it failed to import, make that more obvious. Imported downloads often continue to read "download sent to client" and do not indicate completion without drilling down (more api calls). I'd like the `/api/history` endpoint to be more accurate about item status.

2) The `/api/queue` endpoint should not remove "downloaded but not yet imported" items. This makes it very difficult to find things that were missed when you have hundreds of folders. If it must remove them, can that time be adjustable? Can the status be updated to properly reflect failure?

3) To sum up 1 and 2: it's programmatically difficult to determine if a season's episodes have been imported and are safe to be deleted.

4) Download Handler, Open questions: Does it ever run a second time? Can it be forced to re-run for an episode or season download? Is the final state of the download handler saved anywhere? ie. it failed, or imported 2/10 episodes, etc.

5) Manual Import could have `Hard Link` as an option, in addition to `Move` and `Copy`. 

Thanks!

**Comment by markus101** [comment]
A few things:

- Sonarr has no knowledge that unrarring is taking place unless the client has a way to communicate that and unfortunately that's not something we see outside of usenet clients
- Unrarring takes times (more on this later)
- Completed Download Handling runs every 60-90 seconds

Assuming a season pack, if Sonarr imports while unrarring is happening it'd see only one or more of the files and import what it sees, at that point it deems the download complete and won't try the same download again. It's not ideal, but with a season pack there isn't a guaranteed way to know how many files are part of it (maybe it was a partial pack), so comparing what was imported to what Sonarr thinks was possibly in the pack isn't planned.

1. If the episode hasn't imported it won't be in history, there is no event for download complete, there are grabbed and imported events
2. It's removed when the download is marked complete, which happens when one or more files is imported
3. 
4. It'll run multiple times if nothing is imported, otherwise only once. You can call https://github.com/Sonarr/Sonarr/wiki/Command#downloadedepisodesscan via the API. The state is represented in history by what is imported, no status for the download as a whole is retained.
5. Copy is hard link or copy (whatever the settings in Sonarr are set to and if the system supports it)

To avoid Sonarr seeing files before they are unpacked you have a few options:

- Extract them to another folder on the same volume and move them back when extracting is complete
- Extract them to another folder and use the API to tell Sonarr to import: https://github.com/Sonarr/Sonarr/wiki/Command#downloadedepisodesscan
- Disable Completed Download Handling, extract them to the same folder and use the API to tell Sonarr to import

This PR (which is a starting point and not ready to merge): https://github.com/Sonarr/Sonarr/pull/2337 will improve how Sonarr deals with importing and should make things more flexible. Something like https://github.com/Sonarr/Sonarr/issues/791 could also be useful to be used to delay Sonarr's import process if we decide to go that route, though Transfer Providers expands things a lot more, such as handling RARed files.

**Comment by davidnewhall** [comment]
Your reply was thorough and should gives me plenty of paths for dealing with this. Thank you very much.
