### ISSUE TITLE
Seach won't work with multiple indexers

### ISSUE THREAD

**Issue by Levi--G** [Sonarr/Sonarr#2574]
### System Information/Logs

**Sonarr Version:** 2.0.0.5163

**Operating System:** Debian Stretch

**.net Framework (Windows) or mono (macOS/Linux) Version:** mono V4.6.2.7

**Link to Log Files (debug or trace):** https://pastebin.com/uFFmKzzn (debug)

**Browser (for UI bugs):** [empty result](https://gyazo.com/0b0bee6407baa4a89470b5f16edad50e) | [indexers](https://gyazo.com/58734190874f2f43e9395be03dc0c4c9)

### Additional Information

I did a fresh install and some indexers that used to work now only work with RSS and search turns up empty:
- Nyaa (new site)
- HorribleSubs
- rarbg

So I added Jackett to see if that solves the problem, added 7 indexers with search support, tested manual search in jacket that is ok. Then I added jacket to sonar, again only RSS works, manual searches turn up with "no results". Am I missing anything?

If you check the logs, near the end I do an auto/manual search for a popular episode that has a lot of results in jacket, the request is OK but still returns 0 results...

I didn't mess with quality settings and they are present in jackett results, also the categories should be ok.

**Comment by Vyolex** [comment]
Experiencing the same issue here, using windows.

**Comment by markus101** [comment]
> I do an auto/manual search for a popular episode that has a lot of results in jacket, the request is OK but still returns 0 results...

Sonarr made the request properly, why didn't Jackett return the results?

> http://orangepiprime:9117/api/v2.0/indexers/all/results/torznab/api?t=tvsearch&cat=5030,5040,2000,5000,100080,100148,100071,100075,100006,100041,100152&extended=1&apikey=(removed)&offset=0&limit=1000&q=Sword%20Art%20Online%20Alternative%20Gun%20Gale%20Online&season=1&ep=1

That's a lot of odd categories, perhaps that's tripping up Jackett.

Instead of using the aggregate `/all` indexer in Sonarr try adding each one and adding the ones Soanrr supports (rarbg) directly. The aggregate indexer does not do RSS paging properly so any gaps in the RSS feed won't be filled in (assuming the indexers support paging).

If you're still having issues, open a thread on the forums for support.
