### ISSUE TITLE
Add MediaInfo Language to naming options

### ISSUE THREAD

**Issue by drwyrm** [Sonarr/Sonarr#2593]
Please, include the option to add the audio languages to the naming scheme, like Radarr does. Currently it's only available with {mediainfo full}.

Thanks!

**Comment by markus101** [comment]
This already exists, but not all options are presented in the UI.

https://github.com/Sonarr/Sonarr/wiki/Sorting-and-Renaming#rename-options

**Comment by markus101** [comment]
Sorry, this doesn't currently exist.

**Comment by drwyrm** [comment]
Hi Mark, thanks for taking a look at it. Current scheme used by radarr is perfect for my use case. {mediainfo audiolanguages} is an empty string when audio is english only, "[xx]" for any language other than english and "[xx+yy]" for multiple audio track files.

**Comment by RandomNinjaAtk** [comment]
FYI this doesn't seem to work in the current V3 {MediaInfo AudioLanguages}

**Comment by markus101** [comment]
It's there, but is not included if the only auto language is English, which case been the case since it was implemented.

**Comment by RandomNinjaAtk** [comment]
Ah... Seems strange to not include it if the language is English only. I was expecting it to work like Radarr and the whole time, I just thought it was a broken... I know its not listed as an option, but I hadn't been including the tag because I presumed it didn't work at all because of that... Maybe that should be changed?
