### ISSUE TITLE
Stops looking for matches after 100 episodes

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [Sonarr/Sonarr#2601]
**Describe the bug**
I have the entire Pink Panther collection on my hard drive which are numbered 01 through 124. Sonarr sees nearly all of them, but it can't find episodes numbered 101-124. I believe this is because it assumes that 101 == S01E01.

**Screenshots**
![image](https://user-images.githubusercontent.com/1719461/40890616-e466543c-6746-11e8-9937-9ea25846b470.png)
Stops on Pink Lightning
![image](https://user-images.githubusercontent.com/1719461/40890621-fedce178-6746-11e8-865a-46b997abe6e7.png)
Pink Lightning is episode 100, past that Sonarr wont identify.

**System Information**

 - Sonarr Version: 2.0.0.5163
 - Operating System: FreeBSD 11.1 (FreeNAS 11.1)
 - mono Version: 5.2.0

**Comment by markus101** [comment]
Without any additional information, 101 is assumed to be season 1 episode 1 as it's ambiguous, but most often associated with some less than ideal release names. In order to be treated as an absolute episode number in that case it needs to have the release group in square brackets at the beginning or end, the hash in square brackets at the end or use S01E01 or 1x01 for the episode numbering.

Some improvement may come with https://github.com/Sonarr/Sonarr/issues/457, but it's not coming short term and may not solve it if the series type is not set to anime.

**Comment by Adrian-at-CrimsonAuzre** [comment]
Thanks.
I assumed that was happening, but I didn't know if it was intended or not.
