### ISSUE TITLE
Sonarr doesn't import file if folder doesn't match the parse too

### ISSUE THREAD

**Issue by ivanbeldad** [Sonarr/Sonarr#2663]
**Describe the bug**
According to the wiki, Sonarr will search inside the downloaded folder for files who pass the parse:

>Sonarr will scan that completed file location for video files. It will parse the video file name to match it to a show, season, and episode. If it can do that, it will rename the file according to your specifications, and move it to the TV Series folder.

But, if the folder doesn't match, it will ignore even if the episode is completely sonarr-friendly.

**Logs**
[https://gist.github.com/ivanbeldad/622db91c22ed31175a00719fa5d3aa12#file-sonarr-parse-log-L63](https://gist.github.com/ivanbeldad/622db91c22ed31175a00719fa5d3aa12#file-sonarr-parse-log-L63)

**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System: Windows 10 and Ubuntu 18.04 (dockerized)

**Comment by markus101** [comment]
@Taloth this is an interesting issue with the aggregation/augmentation.

`The Handmaids Tale.S01E02.HDTV-720p.Spanish.mkv` is pretty straight forward, but `The Handmaids Tale - Temporada 1 [HDTV 720p][Cap.102][AC3 5.1 Espa�ol Castellano]` is also parsed (which appears may be the download name as well), except `102` and parsed as absolute episode number 102, we say that because that was parsed we prefer it over the file's parsing, then ultimately can't find any matching episodes because there isn't an episode with that absolute episode number.

**Comment by Taloth** [comment]
This is where the advanced parser comes in. It can say "'102' looks like an abs 102 or 1x02 style episode number" and can use other info to squeeze out the truth, especially with a filename like that.
What's odd is that the filename is most definitely a valid scene name, and the folder name is not. I'd say it should prefer the filename in that case.
Foreign language release titles can always be a bit tricky, especially with these kind of torrent names which are clearly not standard.
