### ISSUE TITLE
"Grab queue" to work around limited grabs per indexer

### ISSUE THREAD

**Issue by usenetDude** [Sonarr/Sonarr#2675]
**Describe the problem**
A lot of usenet indexers have very strict limits on daily grabs. With more and more shows getting released with full seasons at the same time, sonarr isn't able to grab all episodes.
**Example:** 
- Indexer has a daily grab limit of 10
- New Show release with standard 24 episodes
- Sonarr will grab the first 10 episodes, then get an error
- Over the day other episodes release so after 24h/grab reset the missing 14 episodes aren't in rss anymore

**Describe any solutions you think might work**
Create a local queue for grabs per indexer. Found releases are added to the grabbing queue and the queues get worked on as long as the indexer allows. If a grab fails the (newznab-compatible)indexer also sends the time to wait with a special header. Then pause the indexer's queue for that time.

With that solution rss-parsing and grabbing are separated and Sonarr won't miss any releases, even if it can't grab them at once.
**Additional context**
Questions still open:
- How does it work with torrents? Are there trackers with daily limits?
- How would that handle releases found on multiple indexers? E.g release already in indexer-queue A and can't be grabbed and is also found on indexer B.

**Comment by markus101** [comment]
> A lot of usenet indexers have very strict limits on daily grabs

For trials/free accounts, yes, this is common, donations unlock more in addition to more API calls.

The bigger problem over a low number of downloads a day is going to be the low number of API calls, with an RSS Sync interval of 15 minutes you need 96 API calls, just for the RSS Syncs at which point nothing is going to be seen or grabbed.

Sonarr already has an internal queue of things to grab in the future for pending releases as well as for handling failed downloads, we could look at expanding this to failed grabs due to too many requests, but hitting API limits will have at least the same impact, though I suspect it'd be hit more often.

One additional concern with this would be how to avoid spamming an indexer with requests for queued downloads when grab limits are already reached, not sure if/how we handle that right now.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR
