### ISSUE TITLE
Shows airing after midnight show up on the wrong day

### ISSUE THREAD

**Issue by hagabla** [Sonarr/Sonarr#2692]
**Describe the bug**
Shows that air after midnight show up on the wrong day when using localised time. See screenshot for example. The show in question airs Monday night after midnight at 00:35 (actually Tuesday but tvdb shows airdate Monday) which translates to 06:35 local time and shows up in calendar on Monday, when actually it should show on Tuesday morning.

**Screenshots**
https://imgur.com/a/v0lrcBc

**Additional context**

**Comment by markus101** [comment]
This is awkward behaviour due to the air date being listed that does not match the real world air date, but the network's scheduling date. We've previously tried to handle this, but it was inconsistent because some shows respect it, but others don't and TheTVDB changes things.

https://forums.thetvdb.com/viewtopic.php?t=34566

Given the air dates, setting the air time to 24:35 should trick Skyhook into returning air dates 24 hours in the future, which will align with the time the episode really airs. Beyond that there isn't anything we can do to improve this due to the inconsistent data.
