### ISSUE TITLE
Turning Torrents & Usenet On and Off

### ISSUE THREAD

**Issue by mccorkled** [Sonarr/Sonarr#2704]
It would be great if there was an option under 'download clients' to turn off torrents or usenet completely. I frequently disable one or the other of my clients but this does not stop searching all of my indexers which can jam up my api calls. It is a pain to have to go through and disable 15+ indexers when a single switch could disable indexers and client at once.

Thank you

**Comment by markus101** [comment]
Why would you want to disable one protocol or the other temporarily?

I don't see this being something we'll implement, but I'd like to understand the use case more first.

**Comment by mccorkled** [comment]
Usually usenet has the best releases over torrents so I try to stay with that. If usenet doesn't have a release Sonarr will keep searching all the indexers even though I know none have it using up all my api calls for the day. Also, my usenet just expired and I won't have money for many months to purchase it again and therefore it would be beneficial to just turn off all usenet features since Sonarr keeps searching all my indexers. I am sure other people could chime in with benefits as well. 

If the download client is turned off then all related indexers should also be turned off. 

Thanks.

**Comment by markus101** [comment]
> If usenet doesn't have a release Sonarr will keep searching all the indexers even though I know none have it using up all my api calls for the day. 

Sonarr doesn't actively search indexers, it watches RSS feeds for new releases (using 96 API calls a day with the interval set at 15 minutes), this is explained in the FAQ.

Without an download client Sonarr can still track releases for grabbing when the download client is available (same reason we wouldn't want to disable indexers if the download client is unavailable for a period of time).

I don't really see a repeatable use case for a switch to disable a protocol's indexers in such a way, I'll see if another developer sees a need/place for it before closing.

**Comment by Taloth** [comment]
@markus101 Maybe he's also talking about FDH performing searches on all indexers? The Rss/Auto/Manual search switches we talked about would likely address that, although still per indexer.

I'd like to avoid a global switch for usenet/torrent, because it's usecase is fairly limited and it's another thing that ppl can accidentally toggle. TBH I sincerely doubt many share your usecase, ppl don't tend to toggle their clients on and off. And, as markus mentioned, the indexer api calls are relatively constant except for searches resulting from failed downloads.

As an alternative I think we could stop querying indexers if the protocol's download client is disabled (not just unavailable). 
Sonarr can queue downloads even when the client is (temporarily) unavailable or when it's disabled. Meaning that functionality would become limited to 'unavailable' only.

**Comment by mccorkled** [comment]
"As an alternative I think we could stop querying indexers if the protocol's download client is disabled "

I believe this would be perfect. Thank you.

**Comment by bakerboy448** [comment]
Closing; No or limited User interest noted; if you stumble here and want this, please open a new detailed GHI FR


can be scripted via the api
