### ISSUE TITLE
not getting series info for just 1 show from tvdb.

### ISSUE THREAD

**Issue by tostane** [Sonarr/Sonarr#2713]
Nothing shows up in my logs    when I try to pull info for this show 101st-proposal      its the 2006 version.
it shows 0 seasons and 0 episodes.     I even went to tvdb and made sure it has some data for each episode in english.        this is the only show that seems to be happening on.
here is what shows in the browser for the show

101st Proposal | 0 | Any | SBS
the 0 should be a 1     any ideas.        It seem if it was a bug it should affect other shows.  I compared the data from this show to others on tvdb and it looks correct.

I'm running this on the latest windows version.

**Comment by tostane** [comment]
I looked through my show list and found others doing same thing.   most have episode info but sonar shows none  and no seasons. 

Freezing Point
I'll Give You The Stars and The Moon
I'll Teach You Love
Kokkiri
Lotus Flower Fairy
Love Can't Wait
Love Hymn
My Life's Golden Age
Nonstop
Noriko, Goes To Seoul
Orange
Pianist
Soonpoong Clinic

**Comment by markus101** [comment]
Please provide the information requested when opening this issue, including debug logs (of the refresh).

**Comment by tostane** [comment]
something strange   after I edited tvdb   i restarted and refreshed it still did not work   but now after a few hours the 101st proposal   started to work as it should.   does tvdb have to set some flag before the season updates work ?            also  there is nothing in my log other than it tried to update..   no errors listed.    i am not sure if debug is on.

**Comment by tostane** [comment]
If the season shows as 0 it seems to mean tvdb  has not approved the data.  I cannot find any thing that says this.

**Comment by markus101** [comment]
Series information takes some time before it's updated on the API and Sonarr can pull it in, approximately 90 minutes for all the caches to update.

I looked at a couple series:

Noriko, Goes To Seoul - One episode (a special), without a title in English, which shows up correctly in Sonarr, but is unmonitored by default.
Kokkiri - no episodes listed on TheTVDB

> If the season shows as 0 it seems to mean tvdb has not approved the data. I cannot find any thing that says this.

TheTVDB doesn't approve anything, any edits are live almost immediately.

Closing this out as there is nothing wrong on Sonarr's side, either episodes are missing titles and air dates (which are excluded because they aren't valid), episodes don't actually exist on TheTVDB or they are unmonitored specials.
