### ISSUE TITLE
Daily / Standard conflict

### ISSUE THREAD

**Issue by Pantar2205** [Sonarr/Sonarr#2720]
Show name = "example"

Sometimes the file Sonarr finds has both Daily and Standard file name for eg "example.s01e01.2018-09-06".

If I add this show as a Daily show it will be rejected because it contains the Standard information.

If I add this show as a Standard show it will be rejected because it contains the Daily information.

Even though in both cases it is the correct file, Sonarr will reject both.

There is two shows I am following in particular that are always named this way and are the only two I have to always manually import. Is this working as intended and I am using the system incorrectly or is this a bug?

Thank you

**Comment by markus101** [comment]
> is this a bug?

Sounds like it, but without filling out the bug template and the requested information we have no way of knowing. In the future use the forums for questions or fill out the bug template and we can respond accordingly instead of having to fish for more details.

A quick test on my side shows `example.s01e01.2018-09-06` parses properly.

**Comment by Pantar2205** [comment]
Ok, thank you. please leave this open and I will post with proper bug template when it next happens.

**Comment by markus101** [comment]
Closing this out, we can re-open when more information is available.
