### ISSUE TITLE
Add button for Single Episode Scan

### ISSUE THREAD

**Issue by Samuel98** [Sonarr/Sonarr#2736]
**Describe the Feature**
Often when I move or add a new episode to a series on a weekly basis it becomes quite slow and resource heavy to scan the drive for the entire series so I propose that a button is added to the episode info panel which simply scans for just that episode in the hope that this might increase the efficiency and general usability of the software.

By the info panel I mean on this screen:
https://i.imgur.com/tUdeTrE.png

**Comment by Samuel98** [comment]
I mean only search for that single episode instead of the whole series (update series info + scan button on the series page)

**Comment by markus101** [comment]
Sonarr has no way of knowing that a new file exists without scanning the series folder (the one folder for that series, not all series folders) and getting all files then it excludes anything it already knows about and processes everything else. Unless there are a lot of untracked files the process isn't very resource intensive and should finish quickly.

Alternatively you could use Manual Import (from Wanted: Missing) to scan another folder and have Sonarr import the file(s) from that location, instead of moving the files then rescanning each series.
