### ISSUE TITLE
snap applications show up as locations as diskspace

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#2743]
**Describe the bug**
snap applications show up as locations as diskspace
![sonarr](https://user-images.githubusercontent.com/7855682/45917427-8a123680-bea9-11e8-9746-747bda832d59.png)

This is for both v2 sonarr and v3 sonarr. I didn't mind earlier but now that I am using more snaps. The number of locations keeps increasing filtering all /snap/* directories should be enough.  The same thing happens in radarr as well. 

**System Information**

Version
3.0.0.260
Mono Version
5.14.0.177
OS: Linux Mint 18

**Comment by Dnkhatri** [comment]
I am still getting snap directories in v3  Sonarr. Radarr seems to have fixed it as I no longer get in radarr

**Comment by Taloth** [comment]
Can you please specify the version you're currently using?

**Comment by Dnkhatri** [comment]
> Can you please specify the version you're currently using?
I am currently on
3.0.1.378
![capture](https://user-images.githubusercontent.com/7855682/53476834-48b43180-3aae-11e9-9383-7a89c9008903.PNG)

**Comment by Taloth** [comment]
Tnx. To elaborate, Sonarr uses two methods to get the list of drives. One is using `/proc/mount` and one is using .net/mono's native DriveInfo. `/proc/mount` picks up certain mounts that DriveInfo doesn't, such as zfs mounts. Sonarr combines the list from both sources.
We started filtering `/snap/` from the `/proc/mount` output since that has been enough to filter `/var/lib/docker` mounts as well. The fact that you're still seeing them indicates that DriveInfo _does_ in fact report those drives. So the filter will have to be done at a higher level.

**Comment by Taloth** [comment]
@Dnkhatri I hopefully dealt with it on the latest phantom-develop release v3.0.1.392. Can you test it for me?

**Comment by Dnkhatri** [comment]
Yes its fixed I no longer see the snap drives thks
