### ISSUE TITLE
Download Handling strange behavior toward season pack

### ISSUE THREAD

**Issue by hergonoway** [Sonarr/Sonarr#2755]
**Describe the bug**
Context : I'm using download handling feature not drone factory. My local server host sonarr and my media library, my distant (over wan) server handle rtorrent. Once a file is downloaded, a Syncthing instance sync back the file from the distant server to the local one. Folder mapping in the download handling settings is setup correctly and works.

Issue : If sonarr find and ask to download a single episode, everything works fine, in activity tab it shows the progress of the download, once download it show the little yellow icon of file missing until the file is pull back to the local server, then it's processed and activity tab is cleared.

When a season pack is found and asked to be downloaded (1 torrent file for X episodes), in activity tab all single episodes from this pack appear, which is not problematic. When the pack is downloaded, episodes are sync back from my distant server to the local one procedurally (file by file). But once sonarr found 1 episode of the pack (while other are still syncing back), it post-process this single file and clear the activity tab of the whole pack as everything is done, which is technically not the case. In result each time I download a pack only 1 file is processed by sonarr (the first one to be sync back), I have to manual import the rest.

**System Information**
 - Sonarr Version: Sonarr Ver. 2.0.0.5228
 - Operating System: docker (linuxserver.io build)

**Comment by markus101** [comment]
A few options to work around it currently:
- Sync to an alternate folder then move to the remotely mapped folder
- Find a way to have all files marked as transferring until all complete (so Sonarr doesn't see one file and import prematurely)
- Use another method to mount the remote file system instead of sync, such as sshfs

Until something like https://github.com/Sonarr/Sonarr/issues/282 there won't be enough flexibility to do things exactly as you are.

**Comment by hergonoway** [comment]
Thanks for the help, think I'll wait then, it's not so often. I
