### ISSUE TITLE
Accept/Reject releases based on indexer's release attributes

### ISSUE THREAD

**Issue by jordandrako** [Sonarr/Sonarr#2782]
**Describe the problem**
Some indexers, such as HDBits, support tags on their releases. It would be great if we could specify required tags in the indexer settings like Radarr does so we can avoid grabbing releases that will unnecessarily increase seed ratios. General support would be great, but I'm specifically looking for HDBits internal tags to be supported as a requirement before grabbing.

**Describe any solutions you think might work**
Here is some documentation on the tags Radarr supports: https://github.com/Radarr/Radarr/wiki/Indexer-Flags#1-required-flags

**Additional context**
These tags can also be used as a preference to grab freeleech or golden popcorn over other encodes. I've searched the issues and can't find anything related specifically to indexer tags, just sonarr tags in the restrictions which aren't the same: they require the required term to be in the release name. Indexer tags are part of the indexer's api as far as I know.

**Comment by jordandrako** [comment]
Also, here is how Jackett handles it (I think): https://github.com/Jackett/Jackett/blob/060972475f13ffe59fcc09c51ffe91a547a29029/src/Jackett.Common/Definitions/hdbits.yml#L73

**Comment by markus101** [comment]
Wouldn't `Internal` be part of the release name?

Something like additional parameters could be used to exclude releases if they can be filtered on HDBit's side, but I don't see a good way to translate "tags" on the indexer to specific restrictions within Sonarr and I don't think it makes a lot of sense to attempt it for a single indexer.

**Comment by shauder** [comment]
This would be helpful for me also and is useful in Radarr.

**Comment by 2fst4u** [comment]
Please support this. Radarr handles this without issue and allows the flag to be shown on the search interface which is really helpful for making sure you grab a release that won't "cost" you.

Radarr can also prioritise entries with flags above ones without flags.

Same as OP, I'd like to be able to tell Sonarr to only grab torrents if they're freeleech.

**Comment by 2fst4u** [comment]
A further addition to why this would be great:

If you have multiple private trackers with different freeleech parameters, it would be preferable to prioritise one over the other if the same file is freeleech on one but not in another.

For example I have one tracker that makes all releases freeleech for a certain period of time, I would prefer these for brand new releases. I have another tracker that makes all releases over a certain file size freeleech, these would be preferable for older files.

Because my trackers aren't prioritised in any other way for the same file in a search, one of my indexers keeps being used more than the other when I'd like the one with freeleech releases to be used instead.

Jackett parses the freeleech tag correctly for both of these, so it would be super appreciated if it carried through to Sonarr in the same way it does for Radarr.

**Comment by omeryagmurlu** [comment]
any updates?

**Comment by don4of4** [comment]
Hello all,

This issue is vexing enough that I will happily take up the development if @Taloth 
and @markus101 point me in the direction you want to go.  

I would propose a focused approach:
-  _Starting_ with a very simple PR of showing the loadingfactor on the UX, like radarr does.
- Then, looking at adding a config option (checkbox) to _prefer_ better loading factors.  As a user, I would expect that given a certain quality profile (group), that the best loadingfactor (for download) is preferred. e.g. freeleech is better than half-leech, is better than normal, etc.  As a secondary selection, the best uploadloading factor would be selected.  _(I'm guessing the complexity here is how this all interacts with other preference flags.)_
- Finally, we can look at (separate effort) to allow configuration of this behavior, and more significant lifts, like filtering, upload preference, etc.  It sounds like we want to push as much of that "filtering" down to Jackett.  #3036 probably stalled because it had a wide scope.

Related Items:
- #3036 -> Incomplete work.
- #1464 -> Adding the torznab attributes. (See also [428107792dfeafbf920da05404ad41920140fa76](https://github.com/rlightner/Sonarr/commit/428107792dfeafbf920da05404ad41920140fa76))
- _any others I should look at?_

Any guidance is appreciated! 

Thank you,
-Don

**Comment by plsharevme** [comment]
When sonarr will update this? It very important for us no using usenet.

**Comment by batuhankrmn** [comment]
I don't want to be disrespectful, I am completely grateful for your work, just wonder:  Radarr already has provided this feature very nicely and the same feature has been requested by Sonarr users over and over. A user has even stated above that he is willing to help with the development part. 

I am looking forward to this feature that will significantly improve the user experience. It would be nice if we could at least get an update from the developers on this feature. Even if we find out whether there is a positive or negative planning about this feature, it will be enough.

**Comment by Taloth** [comment]
You're not wrong. tbh I have no idea what happened around May last year. I sometimes just mark all github notification email as read. :smile: Sometimes I read while at work and promptly forget about it after work. :shrugs:

Anyway, I think the approach remains an extension of #3036, which is effectively merged into sonarr v3 over a year ago, but I've been keeping it alive since it contains all the follow up discussions.
The idea was that we first needed indexer specific filtering and some foundational work. There's a lengthy discussion about it in that PR.
There are two approaches there:

1. `tag:freeleech` preferred word. The idea is that the logic should support prefixes such as `tag:` `origin:` `group:` kinda how the current ones are effectively defaulted to `title:`. Crux here is that I want autocompletion in the UI to expose the prefixes and possible values. 
Problem here is that preferred words do 'upgrades', which means it could decide to prefer to upgrade to a freeleech torrent. Something you don't want. But I seem to recall that we want to add a checkbox to Release Profiles to prevent it from being considered in upgrades, which would 'fix' it, but I fear many users will misconfigure that.
2. 'Prefer freeleech' checkbox. This would mean that downloadvolumefactor would be considered, so 0 > 0.5 > 1.0. Challenge here is to decide [where in the sort](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs#L31-L40) to do this. It's damned if you do, damned if you don't, coz most ppl will want preferred words to be prioritized over freeleech, but some might the other way around. Anyway, I think it should sit below CompareProtocol.

As for 'when', my 'high priority' list is fairly lengthy. Let's just say that when you have to focus writing code at work for weeks due to deadlines, you don't want to spend your evenings writing code too. 😅

**Comment by batuhankrmn** [comment]
> You're not wrong. tbh I have no idea what happened around May last year. I sometimes just mark all github notification email as read. 😄 Sometimes I read while at work and promptly forget about it after work. :shrugs:
> 
> Anyway, I think the approach remains an extension of #3036, which is effectively merged into sonarr v3 over a year ago, but I've been keeping it alive since it contains all the follow up discussions.
> The idea was that we first needed indexer specific filtering and some foundational work. There's a lengthy discussion about it in that PR.
> There are two approaches there:
> 
> 1. `tag:freeleech` preferred word. The idea is that the logic should support prefixes such as `tag:` `origin:` `group:` kinda how the current ones are effectively defaulted to `title:`. Crux here is that I want autocompletion in the UI to expose the prefixes and possible values.
>    Problem here is that preferred words do 'upgrades', which means it could decide to prefer to upgrade to a freeleech torrent. Something you don't want. But I seem to recall that we want to add a checkbox to Release Profiles to prevent it from being considered in upgrades, which would 'fix' it, but I fear many users will misconfigure that.
> 2. 'Prefer freeleech' checkbox. This would mean that downloadvolumefactor would be considered, so 0 > 0.5 > 1.0. Challenge here is to decide [where in the sort](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs#L31-L40) to do this. It's damned if you do, damned if you don't, coz most ppl will want preferred words to be prioritized over freeleech, but some might the other way around. Anyway, I think it should sit below CompareProtocol.
> 
> As for 'when', my 'high priority' list is fairly lengthy. Let's just say that when you have to focus writing code at work for weeks due to deadlines, you don't want to spend your evenings writing code too. 😅

Here is one idea, might be stupid tho: If Sonarr can reference and support the Custom Formats feature from Radarr, It'd be super great since most of Sonarr users also use Radarr too. So they are already familiar with the Custom Formats, It wont be a problem to figure out settings. Also custom formats offers much more than just freeleech. When I saw Radarr's custom formats, I was like "damn, this is the ultimate customization!". Has Custom Format support for Sonarr ever been considered?

**Comment by neo-neo1** [comment]
Any current plans to add this? Been 3 years since Radarr has it. Is it possible to adopt the same code?

**Comment by Mavyre** [comment]
Up'ing this issue, as this would be awesome to have it like Radarr. In Radarr, that really helps a lot to have a semi-automatic download without impacting the ratio for automatic downloads.

**Comment by cybersteel8** [comment]
Sadly this doesn't still seem to be a feature. I set up private trackers in Radarr successfully, and I was looking for the Required Flags section in the indexer screen here in Sonarr, but it looks like it's a completely missing feature in Sonarr.

The only workaround right now is to hopefully be able to refer to your indexer flags in the indexer itself (eg. Jackett). However this is global for all your *arr applications, if they all refer to the same Jackett instance.

This is a glaring omission from a codebase that I thought was extremely similar to Radarr. I would really like to see this get added, and based on the age of this feedback and suggestions I've seen on the forums and suggestion site, it's been wanted for years. Let's make it happen.

**Comment by sdbigio** [comment]
Upping this longstanding issue. Would  be fantastic to implement free leech tag exactly as radarr has done. TY!

**Comment by neo-neo1** [comment]
> Upping this longstanding issue. Would be fantastic to implement free leech tag exactly as radarr has done. TY!

We can only dream at this point

**Comment by sdbigio** [comment]
> > Upping this longstanding issue. Would be fantastic to implement free leech tag exactly as radarr has done. TY!
> 
> We can only dream at this point

Curious as to why this hasn't been prioritized. I would have thought this feature would be a "must have" for anyone using private trackers where ratio can be a concern. Is there some other way to manage this?

**Comment by Theetjuh** [comment]
I was actually surprised it wasn’t implemented yet, since Radarr has it right there.

Would love an indexer flag like Radarr has so I can prefer freeleech.
