### ISSUE TITLE
Use newsnab attributes for subs

### ISSUE THREAD

**Issue by rborsaru** [Sonarr/Sonarr#2784]
Hi,

I am using sonarr with nzb.su indexer. I want to be able to get only shows that have english subtitles.
Found that newsnab has attributes that allow this like subs="English". 
I have added this in the attributes box that I have for my indexer. However, sonarr is just ignoring it and brings also episodes without subtitles.

Is there a way to filter the episodes by subtitles in Sonarr?
I am using the latest version from development branch on Windows 10.

Thank you.
Radu B.

**Comment by markus101** [comment]
If Newznab can filter results with/without a specific attribute you can do that via Additional Parameters, otherwise this would require Sonarr to be able to filter on those parameters, which is not something that is currently supported and similar enough to https://github.com/Sonarr/Sonarr/issues/2782
