### ISSUE TITLE
Add {MediaInfo HDR} to Naming Options

### ISSUE THREAD

**Issue by Ashkaan** [Sonarr/Sonarr#2824]
**Describe the problem**
Just like we naming files based on quality and source, it would be helpful to be able to add the HDR tag to our files like we can in Radarr.

**Describe any solutions you think might work**
Implement the {MediaInfo HDR} feature as it's implemented in Radarr.

**Comment by Prolesious** [comment]
Please add this!

**Comment by nismanoke** [comment]
+1 Support

**Comment by markus101** [comment]
If you want to support a feature add a thumbs up to the original post. If you have something to add to the conversation then add a comment. Comments with +1 and without adding anything to the conversation will be removed.

**Comment by markus101** [comment]
At this time we're not actively merging changes into the v2 branches outside of bug fixes. It'd need to be based off of the v3 work.

**Comment by Matty666** [comment]
ok, no problem. I can take a look at v3. Which branch should I look at?

**Comment by markus101** [comment]
`phantom-develop`

**Comment by Matty666** [comment]
@markus101 @Taloth I'm happy to help out with this, the HDR flag in the name is something I wanted now that more 4K HDR content is appearing, so that's why I wanted to help with this issue. If you explain in a bit more detail what you are both thinking I can have a go at it and submit more pull requests

**Comment by Matty666** [comment]
Regarding the name of the token, `VideoColourRange` might be confusing, there is a `colour_range` element in the mediainfo output that has a value `Limited` in the files I have checked.

And if we changed it to `VideoColourRange` or similar to indicate the type, then I guess it would need to return `SDR` or `HDR`, rather than just a flag to indicate if the media is HDR or not

**Comment by Taloth** [comment]
Ok, lemme know how far you want to take it after you've read this.

Radarr added support for additional audio codecs like Atmos. To do that they upped the CurVer to 5. They also removed some backward-compatible support for VideoCodec (which was deprecated by mediainfo and replaced with VideoFormat), something i'd like to keep.
Personally I don't see a reason to support all the exotic audio formats that apply only for movies, but there's something to be said for being somewhat compatible with Radarr with the mediainfo detection.
My biggest issue with the Radarr code was that it lacks sufficient test cases for the new audio formats.
So I'd like to have that ported back to Sonarr so we only have a single version increment. Which means that the code needs to be refactored properly and additional unittests added.

The second part is that currently, the FileNameBuilder constructs the various mediainfo token values regardless of whether they're going to be used in the formatted. If we make that lazy-loaded then we could, for the HDR token, check whether the MediaInfo is v5 and if not do a refresh. Alternatively we could just do two passes over the format. one to check the minimum required version for the used tokens (and optionally refresh) and one to format the filename.

Regarding the token, I was asking about it because HDR is rather specific and we need to avoid adding a dozen {MediaInfo xx} tokens. If 3d was a thing, ppl would ask for {MediaInfo 3D/SBS/etc}.
Once you add something, you cannot remove it, so we better be sure.

**Comment by Matty666** [comment]
> Ok, lemme know how far you want to take it after you've read this.

No worries, I'll work on this, what you've described makes sense to me.

> Regarding the token, I was asking about it because HDR is rather specific and we need to avoid adding a dozen {MediaInfo xx} tokens.

Yes, I understand. We don't want to add a lot of booleans, HDR, SDR, HDR10, Dolby Vision etc... Maybe `{MediaInfo VideoDynamicRange}` which could output SDR, or HDR for now. I see that mediainfo's basic view sometimes outputs HDR10, but other times doesn't output anything even though the properties are set. I think it uses `Format_Commercial_IfAny` which sometimes has HDR10 in it, so we could probably extend the code to use that in certain circumstances. Also there are specific Dolby Vision elements as well.

**Comment by Ashkaan** [comment]
Bless all of you.

**Comment by Taloth** [comment]
Released on v3 phantom-develop branch.

**Comment by sifotes** [comment]
Any chance this will be ported back to v2? Since there is no automatic upgrade path, it would be nice to write this information into file names with v2 in the meantime before manually migrating to v3 sometime in the future.
