### ISSUE TITLE
Allow minimum log levels above info (i.e. warning, error)

### ISSUE THREAD

**Issue by rochdev** [Sonarr/Sonarr#2827]
**Describe the problem**

Right now the minimum log level is `info`, which is too verbose when there are no issues.

**Describe any solutions you think might work**

Allow configuring the minimum log level to any valid value.

**Comment by markus101** [comment]
What exactly is the problem? Writing to disk too much? You don't want to see them?

With an RSS Sync time of 15 minutes there are ~12 messages logged an hour, which I don't see as being very verbose. I don't see this as something we'll change, but I am wondering why.

**Comment by rochdev** [comment]
Ok, so most of the log entries were indeed warnings. I've resolved the underlying issue.

Setting the log level manually in `config.xml` seems to have worked as well, but this should be available in the UI.

**Comment by Taloth** [comment]
It is, under Settings->General.

_Considering your problem is solved, I'll close this issue._

**Comment by rochdev** [comment]
<img width="269" alt="image" src="https://user-images.githubusercontent.com/1596303/48949121-e70b8680-ef04-11e8-88db-c51ab1874dff.png">

@Taloth It's not possible to set the minimum level above "Info", which this issue is about.

**Comment by rochdev** [comment]
I'm not sure I understand the reasoning of not allowing this. I would gladly open a PR but I'd like to make sure it doesn't go against some past decision.

**Comment by Taloth** [comment]
Because it's entirely useless for the average user to do so, if set to Warning/Error ppl might accidentally set it to Warning and start missing otherwise useful Info events. Considering the low volume of info events there's no reason to limit that any further, especially since the UI has a filter option when displaying the events.

You mentioned a log shipper. It's entirely possible there to filter out irrelevant events, assuming you're using it to do error/fault reporting to a central system.

**Comment by rochdev** [comment]
Ok, makes sense. I still have to update the config but will definitely have some formatting/filtering to do. Thanks for the explanation :)
