### ISSUE TITLE
Sonarr saying file is downloaded, when nothing is in root folder

### ISSUE THREAD

**Issue by antigravity83** [Sonarr/Sonarr#2891]
I've duplicated my Sonarr installation to allow for 4K downloads alongside my existing library. 

The new instance has a different appdata folder and different root folder applied to all my existing content. 

However Sonarr is still saying that everything is "Downloaded" - even though there is nothing in the new root folder. 

I've forced a library refresh, that doesn't help. 

Example (see 4K root folder - and file showing as "Downloaded"
![image](https://user-images.githubusercontent.com/27241813/51219348-3fe32280-197c-11e9-977e-f43b1d2b9250.png)

![image](https://user-images.githubusercontent.com/27241813/51219459-c1d34b80-197c-11e9-87af-c8929e226f79.png)

Actual 4K Folder (empty):
![image](https://user-images.githubusercontent.com/27241813/51219394-7faa0a00-197c-11e9-86ba-b79d907eef4e.png)

 - Sonarr Version: 2.0.0.5298
 - Operating System: Ubuntu 16.04
 - Mono: 5.12.0.301

**Comment by markus101** [comment]
If you look at your logs you'll see `Series' root folder (/home/media/Library/TV 4k) is empty.` in there, because that folder is empty and Sonarr intentionally won't rescan a series folder if the root folder is entirely empty because it could be unmounted.

Create an empty folder or one for a specific series and it'll pick it up.
