### ISSUE TITLE
[Proposal] Improved Anime Searching

### ISSUE THREAD

**Issue by 0aeonnoea0** [Sonarr/Sonarr#2909]
I've been recently working with the AnimeBytes indexer in Jackett to try and get it to play more nicely with Sonarr, and have come up with a few potential improvements to the Sonarr side of things that I wondered if you'd be willing to give some feedback on.

Currently when Anime is searched for, there is only the option of a normal text search via Torznab. I wonder if extending the spec (mentioned before by @Taloth I believe) to include official support for Anime searching may be helpful? Specifically, extending the capabilities like so:

```xml
<searching>
    <search available="yes" supportedParams="q" />
    <.../>
    <anime-search available="yes" supportedParams="anidbid,aep" />
</searching>
```

The first major hurdle here however is that Sonarr doesn't use AniDB directly, we need to get the mappings somehow. Helpfully, TheXEM generally has mappings between the two - but even more helpfully, when splitting things into multiple seasons, it has distinct AniDB IDs for those seasons (for example, [JoJo's Bizarre Adventure](http://thexem.de/xem/show/3334)).

If these mappings were to be utilised, we could have extremely precise searching via indexers that support AniDB.

However, TheXEM's map endpoint doesn't expose these IDs - only the season, episode & absolute episode number. I've been looking into [their codebase](https://github.com/thezoggy/xem) _(is this the one that's currently being used live?)_, and it looks doable to extend the endpoint to include these IDs, perhaps behind a flag to avoid sending lots of extra data?

Finally, this would allow Sonarr to send a request, with a correct (according to TheXEM) AniDB ID, and absolute episode number (based off of the AniDB metadata) - whilst slotting nicely in to the existing TVDB backend.

Does this sound like something that might be feasible, both on the side of TheXEM but also within Sonarr? Please let me know your thoughts on this.

I'm keen to try to implement this when time permits, if the feedback is positive.

**Comment by 0aeonnoea0** [comment]
Further to the above, I've also been wondering whether these changes might ease some of the problems currently experienced with Anime "Specials", i.e. OVAs and the like - currently if there isn't an absolute numbering set up then you're stuck.

I was thinking that we could potentially use TheXEM to map the specials to their unique AniDB entries, and then be able to use the updated searching to then look then up directly in the indexers (or alternatively just search by name).

To avoid absolute numbering issues we could have the specials folder for Anime shows not use absolute numbering, as more often than not they're not directly numbered like the season folders - making name based searching for specials make more sense. This would also mean that searching would just work without any mappings in TheXEM, which I feel may also be more convenient?

**Comment by Taloth** [comment]
Years ago I started drafting up a more comprehensive torznab documentation. The draft is at https://torznab.github.io/spec-1.3-draft, but it's far from complete.
The aim was to create a document that does not only contain the spec, but also requirements for services & clients supporting it. As well as formalizing new additions that are backward compatible.
PS: The latest revision 1.3, [release tags](https://torznab.github.io/spec-1.3-draft/revisions/1.3-Torznab-Release-Tags.html) was never completed, and is important for anime indexers as well.

I wouldn't be a proponent of adding anime-search. adding some additional params to tv-search should suffice. In the same period I asked the newzab developers whether they would approve if adding absolute eps nr support, and they were positive. I just wanted to gather a bunch of regexes & examples on how such releases should be parsed. But I never actually did that.
For anime, i'd just add `absep=`, and add it as an 'or' requirement. (i'm open to alternative param names, but not aep, that's way too ambiguous)
The `anidbid=` would just need to be formalized, since a lot of indexers already add additional parameters not specified in the spec.

That said, querying by anidbid doesn't seem particularly useful except on very specific indexers because it means the indexer has to explicitly support that. Any 'wrapper' like Jackett would likely have to query some database to get the query titles anyway, and that can be done with tvdbid as well.
But still, I'm all for formalizing that parameter.

However, if we're going to do this then some stakeholders need to be contacted. I'd suggest to rename 1.3 to 1.3.1 and add 1.3.2 for anidbid+absep and related stuff.
Particularly animetosho and nyaapantsu, as well as newznab coz i prefer to be in sync with them. (I can contact them all, but not till we have something solid)
FYI we're not going to tack this on in 1 afternoon, coz it has to be done right.
