### ISSUE TITLE
[phantom-develop] Error occurred while executing task MessagingCleanup.

### ISSUE THREAD

**Issue by telans** [Sonarr/Sonarr#2940]
**Describe the bug**

The task Messaging Cleanup fails consistently, with this error: `[v3.0.1.364] System.Data.SQLite.SQLiteException (0x80004005): database disk image is malformed`

**Logs**

Trace: https://pastebin.com/raw/SbAxMDCT

**System Information**

 - Sonarr Version: [3.0.1.364]
 - Operating System: [Unraid/Docker 18.09.1 (4.19.17-Unraid)]
 - mono Version: [5.18.0.240]
- sqlite3 Version: [3.11.0 2016-02-15 17:29:24 3d862f207e3adc00f78066799ac5a8c282430a5f]

**Additional context**

All shows, downloads, imports works as expected. Just this task that won't work.

**Comment by markus101** [comment]
> `database disk image is malformed`

Your database is corrupt, you'll either need to repair it or restore a backup. It may be possible to drop all rows from the `Commands` table to resolve it.

**Comment by markus101** [comment]
Housekeeping won't fail if one task fails in order to still clean up everything else. Refreshing all series/running the Refresh Scene Mappings task should fix that (it'll wipe out the items already there and reload them).

If you have any further questions/issues please open a thread on the forums or subreddit for support.
