### ISSUE TITLE
Additional Connection Events

### ISSUE THREAD

**Issue by tidusjar** [Sonarr/Sonarr#2965]
**Describe the problem**
I'd like the Webhooks functionality to have improvements,

**Describe any solutions you think might work**
What would be very useful is if we could have options for the following:
 - Series Added
 - Series Delete
 -  Season Monitored Change
 - Series Monitored Change 
 - Episode Monitored Change.

**Additional context**
The reason for this request is so Ombi wouldn't have to poll Sonarr to get updates, Ombi could consume the webhook for any updates to content making the process simpler and cleaner.

**Comment by markus101** [comment]
These aren't really webhook specific, though that would be the mostly likely usecase for it.

I'm curious why Ombi constantly needs to know at such a low level exactly what Sonarr is monitoring.

**Comment by tidusjar** [comment]
Reason being it's quicker to query is own database than to call the API. 

So if something is already monitored, we don't need a user to request it. 

This is just a suggestion.

**Comment by Taloth** [comment]
Hm, I wonder what happens if Ombi uses a SignalR connection to Sonarr. It'd get most such notifications automatically. We use the same thing to notify our UI of changes.
I'm not opposed to adding some webhook functionality, but we need to be sure there's a good reason to add it because it's another thing we'll have to maintain.

I'm also considering the usecases.
Querying the series api means you get the list of series, series monitored flag and season monitored flags. It doesn't really need to be called more often than once every 15 min or even more. It excludes the episode monitored flags of course.
If the user makes a request, Ombi could easily figure out the exact state while processing the request, and doesn't need polling.
If the user accesses the Ombi UI, Ombi might need to have a more recent state, so it can preemptively show what is monitored or not. But again that's only if the user is active.
So it largely depends on when the data needs to be accessed and how fast.

**Comment by markus101** [comment]
I think signalr is the better option here it'll provide all this information and more as long as Ombi is online, which it'd need to be for the webhooks to succeed.

We can reconsider if there is a reason this won't work, but closing this for now.
