### ISSUE TITLE
Proposal: Create an open standard file format to store release file metadata

### ISSUE THREAD

**Issue by ratoaq2** [Sonarr/Sonarr#2967]
### **Proposal**: Create an open standard file format to store release file metadata

When managing media libraries (movies, tv series, etc), it's very common to move and rename files.
Copying them to a different volume/disk, different filesystem. When renaming them, it's very usual
to remove some important release information (source/format, release group, video codec, screen size, etc).
This kind of information is very important when organizing your files, like when you try to find a subtitle for it that fits that release.
People usually also changes their media organizer software. Moving from couchpotato to radarr, or from SickRage to sickchill or medusa, from a simple filebot to a more complete media organizer like sonar, radarr, bazarr, sick*, medusa. All these organizers keep the release information in their database, that's completed detached from the media file. If you move from one app to another, you lose that info. If for some reason you start from a fresh install, you lose that info. And sometimes you also want to integrate with other tools, like to download/manager subtitles using subliminal, bazarr, subzero. What I see is that each of these apps and tools try to solve the same problem in different ways. And an open standard could just facilitate these things.

Some common solutions to store file metadata are:
1. filesystem extended attributes
2. database
3. separate (hidden) file/directory

Option 1 is completely dependent on the filesystem and when moving/copying files around you can just lose your metadata
Option 2 is exactly what all these apps do. If you change app or reset your db/config, you lose your metadata
Option 3 is similar to the common standard about storing subtitles alongside media files. All the media organizers handles these associated files correctly during renaming and moving. If you start from scratch or move to a different application, your metadata is just alongside your file and you can easily copy and move your library to different volumes/filesystem/disks.

My proposal is to create an open standard file format to store release file metadata, similar to the way external subtitles are stored.
Some initial ideas is to have the file as follow:
```
My Media - Some Title.mkv
.My Media - Some Title.xattr
```
and also to support:
```
My Media - Some Title.mkv
My Media - Some Title.xattr
```

`xattr` name is just inspired by the filesystem extended attributes (xattr)
And inside this file we could store key/value pairs about the release metadata, such as:
```
release.name=My.Media.1080p.Some.Title
```

We should standardize all the keys under `release` namespace. And each media organizer could keep/use any custom/vendor keys under their namespace. E.g.:
```
subliminal.subtitle_provider=opensubtitles
medusa.provider=rarbg
```

My proposal is to keep the standard and conventions as simple as possible:
- The metadata file should have the same name of the media file with `.xattr` extension. It could start with . (optional)
- The content is a very simple `key=value` (no quotes, no escapes. Keys cannot contain non visible characters and cannot contain =. Everything after = is a value, including spaces, quotes and any visible character)
- UTF-8 encoding

I'm opening the discussion to see whether people think there's a need for it. People won't be oblige to use it. It's just an additional available option when managing their media libraries.
After the discussion to define the standard, devs from all these Apps: medusa, sonarr, radarr, sick* forks, couchpotato, bazarr, subliminal should add minimal support to it (make sure that these associated files are move/copied/renamed together with the media file). Then some of them could add additional support to have an option to write/read from these files to give their users a better experience.

I'm a developer and contributor for several projects, including subliminal, guessit and medusa and for long time I see a need for such thing.
I'm opening a github issue for each of these projects to start a discussion and check if there's any interest/need for it. If the feedback is positive, I'll later centralize the discussion in the subliminal project.

**Comment by Taloth** [comment]
What you're basically asking devs to do is to put effort into defining a data structure that's redundant to what they already have, with the primary purpose of making it easier to switch between applications.
That leaves the usecase of data exchange with supplementary applications, such as sonarr+subliminal. Doing data-exchange using such files would be a step back, and relies on recursive directory scans rather than api/database lookups.
There is some merit in it, if only to keep track of what kind of numbering scheme the directory uses, but I do wonder whether it would be worth the effort. It's similar to the Kodi nfo file format. Most users will not want these files to pollute their disk.

Please note that you can already configure sonarr to move and rename additional file extensions, but that's not particularly useful if nothing is done with such files.

**Comment by ratoaq2** [comment]
I don't see the primary purpose to move between apps, but to integrate with supplementary tools.
Bazarr needs to communicate with sonarr to get the original release name to get the proper subtitle. Then it needs to communicate to radarr to do the same. And if you want to integrate with sickchill or medusa, you'll need to develop same thing and also ask sickchill and medusa devs to expose an api. 

If subliminal wants to download subtitles for all your videos, you'll need to figure out where to find and integrate the info for each file: radarr, sonarr, couchpotato, medusa?

All these organizers already checks the associated files : subtitles for instance. There's no recursive scan. Just check the existence of files with the same name and different extension.

And people are not obliged to have them, the same way I'm not obliged to generate kodi nfo.
But if have this option, I can just use the info in the supplementary tools :

For instance, it would be blazing fast subliminal to get the release name with a file sitting alongside the video, the same way it does with existing external

**Comment by nobodyoncetoldme** [comment]
FYI Matroska supports tags [internally](https://matroska.org/technical/specs/tagging/index.html)
[Examples for video](https://matroska.org/technical/specs/tagging/example-video.html)

There are also official tags which will probably standardize most of what you want. There's a draft spec here: https://datatracker.ietf.org/doc/draft-ietf-cellar-tags/?include_text=1

Getting uploaders to adopt it will be the hard part. You wouldn't want to automatically modify the tags downstream because it requires modifying the files, which would change file checksums and break torrent seeding. You could make sonarr either generate separate XML files in [the format mkvmerge expects](https://matroska.org/files/tags/matroskatags.dtd) and/or give the user the choice to write the tags to the files via mkvmerge.

It would be fantastic if there was an authoritative source for UIDs, since then metadata could be updated/fixed without modifying files, just load the data from remote databases. TheTVDB and TheMovieDB are great, but I don't know if their IDs are permanent enough. In particular apparently the former deletes duplicate values, when ideally they would turn them into aliases.

**Comment by markus101** [comment]
On one hand you have:

> And people are not obliged to have them, the same way I'm not obliged to generate kodi nfo.

but on the other:

> For instance, it would be blazing fast subliminal to get the release name with a file sitting alongside the video

It sounds like for me to have a better experience I'd need those files on disk, but I don't want those files on disk because that impacts my experience if I look at the files directly and to me is just noise. So you end up in the same place, using the API for the various clients.

Why do you want to avoid the APIs?
 - Are they slow?
 - Do they not have the information required?

Having a standard sounds a lot like ISO 8601, in particular the XKCD comic https://xkcd.com/1179/ having a standard isn't necessarily a bad thing, but I'm not really sure what we're trying to solve with it, it just seems like an alternative to avoid using an API.

**Comment by ratoaq2** [comment]
I'm not a big fan of having yet another file as well.
It's just frustrating to see so many missed opportunities with the technologies available.
My frustration is only about the release metadata, that could allow you to organise your files the way you want, almost like the audio files with their tags.

The missed opportunity was to have a standard way to store proper release information in the mkv header. Not having a standard, everyone stores crap and no tool can use it. 

Maybe all these media organizers could have at least a standard way to read and store metadata per file. Agree on a standard rest api to list/query (and update as well, why not?) release data for all files in your library.
But only info related to the release, like the original/ release / scene name, release group/streaming service, date, proper. Most of the info is in the release name anyway. 

Instead of standard file, a standard rest api to query release info

`/releases`
That could return a list of items containing:
`path`: the file path
`release _name`: the original release name
And maybe the other release info. Not more than that. 

All apps already return this info somewhere in some of their endpoints. And even not believing that people will agree or have consensus, I still need to say how frustrating is to integrate with so many different apis to retrieve such simple information of your file. An information that could have been in the mkv header since the beginning.

**Comment by Derkades** [comment]
It is better to have this stuff in a file than available through an API. One of the reasons one would want this, is so that you and applications now where media came from in a hypothetical scenario where a program would corrupt its database, or a disk fails and data is lost (but you still have the media).

I agree with others that it shouldn't be stored in files though. That creates a lot of clutter. In the same way that good release groups have mostly moved on from putting subtitle files everywhere to putting it in the video itself, we should do that with release information.

As @nobodyoncetoldme said, the Matroska container supports tags. Hopefully we all can agree on a specific way to put the release information in the file using these tags. The downside of storing this data in the container is that it's harder to read than simple json or text files. There are libraries available to read Matroska containers for the majority of programming languages, so it shouldn't be a problem.

It would be amazing if release groups would put this tag in their videos themselves, but that probably won't happen so software like Sonarr should add this tag to the file when it is not present.

**Comment by markus101** [comment]
We don't have plans for Sonarr to alter files/add tags, but this could be achieved with custom scripts. Closing this as it's not something we plan to implement (as files or something else).
