### ISSUE TITLE
Wiki installation instructions

### ISSUE THREAD

**Issue by nemchik** [Sonarr/Sonarr#2978]
I've noticed https://github.com/Sonarr/Sonarr/wiki/Installation seems to have instructions about installing Sonarr via a third party called PlexGuide. I didn't think this was officially supported by Sonarr, and it seems to use the LinuxServer.io docker image that's already mentioned on the page. It seems the PlexGuide developer has made multiple attempts to include their information or move it around to more prominent locations in your wiki:

https://github.com/Sonarr/Sonarr/wiki/Installation/_history

https://github.com/Sonarr/Sonarr/wiki/Installation/248c6f481afd9a7c5855af6cab65ac40a277ba7c
https://github.com/Sonarr/Sonarr/wiki/Installation/bd38b72394891f1d75d32c2911fe5f9e00597f7b
https://github.com/Sonarr/Sonarr/wiki/Installation/2861e940cd26698f90d30c662587138257cc5203
https://github.com/Sonarr/Sonarr/wiki/Installation/423d7f7418d880c85e42bd39acfdfdfcf6b4c2a6

I'm wondering as the developer of a similar project ( https://dockstarter.com/ ) if other projects are welcome to add their information to your wiki?

**Comment by Taloth** [comment]
It's been reverted before, and again a couple of hours ago.  I wish we could enforce pull requests for the wiki pages so it's more easily moderated.
So thank you for contacting us first.

We're not opposed to linking to alternative installation methods, but only as a reference instead of an instruction. For Sonarr v3 we're moving most of those instructions to the website instead, so it will change anyway.

Regardless, I've added a [section](https://github.com/Sonarr/Sonarr/wiki/Installation#other-references) that links to both toolkits.
If you prefer it to be linked to the website instead (or any page there specific for Sonarr), feel free to modify the link.

**Comment by nemchik** [comment]
There's a few options with wikis actually. Aside from having them publicly editable like yours (and mine) you could also keep a docs branch or a separate documentation wiki under https://github.com/Sonarr/ that keeps documentation in markdown (`.md`) and people could submit pull requests for changes.

Anyway I look forward to what you have in store and thank you for all your work on Sonarr!
