### ISSUE TITLE
RSS sync finds releases that manual/auto searching doesn't

### ISSUE THREAD

**Issue by herrwusel** [Sonarr/Sonarr#2982]
**Describe the bug**
RSS sync finds releases that manual/auto searching doesn't. This bug is specific to shows with special chars - in my "case you're the worst".
When I do a manual search I see this in the debug:
```
/results/torznab/api?t=tvsearch&cat=5000,5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Youre%20the%20Worst%202014&season=5&ep=1
```
Sonarr has omitted the '. It won't find releases on my defined indexer. If I search with the ' manually in jackett, I get releases.

RSS sync seems to search differently:
```
19-3-8 08:45:28.9|Info|DownloadDecisionMaker|Processing 94 releases
19-3-8 08:45:30.9|Info|DownloadService|Report sent to rtorrent. You're the Worst S05E09 1080p [....]
19-3-8 08:45:31.3|Info|RssSyncService|RSS Sync Completed. Reports found: 94, Reports grabbed: 1
```
My guess is that rss searches with the ID or doesn't omitt anything. I can provider proper logs next week - if needed -when a new episode aired because I didn't have debug turned on.

**System Information**

 - Sonarr Version: 3.0.0.348 (same problem with 2.xx)
 - Operating System: Ubuntu 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.8.0.127

**Comment by markus101** [comment]
RSS Sync doesn’t search, it just compares the release name to the series title (which ignores most special characters) and goes from there. Most release groups strip special characters from titles (part of their rules) so this is not an issue and real indexers (the ones that allow searching by ID instead of strict titles and have a proper API) since they’re able to ignore the subtle difference and return accurate results.

We have an existing issue for the stripping of special characters when searching here: https://github.com/Sonarr/Sonarr/issues/1225
