### ISSUE TITLE
multi-episode naming - prefixed range

### ISSUE THREAD

**Issue by markpeo** [Sonarr/Sonarr#3006]
**Extra space in pre-fixed range naming**
When naming multi-episode files using the prefixed range, an extra space gets added after the - and before the second E. Neither Plex or Emby recognize this, they need Exx-Exx, not Exx- Exx. See screen shot below.

**Screenshot**
![image](https://user-images.githubusercontent.com/38840743/54868753-8e82b380-4d55-11e9-85c1-0372c9d58f2b.png)

**Logs**
Link to debug or trace log files.

**System Information**

 - Sonarr Version: 2.0.0.5301
 - Operating System: unRaid docker. Arch linux - not sure of version.
 - Mono (macOS/Linux) Version: 5.16

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
I’m pretty sure this is due to the space between the season and episode numbers. Sonarr replicates that when building multi part names.


This has been the case for years and I’m not sure this is really a bug since its specific to that naming format (Plex recommends having SxxEyy without the space, even though it’s more flexible than that in most cases).

**Comment by markpeo** [comment]
Ah yes, you are right. I tried playing with spaces after the Episode number but not after the season number. Yes, Plex and Emby both seem to be more flexible than the lie respective naming conventions document, but not on the multi episode part as far as I could see. Plex showing correct now, Emby not. Will take that up with Emby. Thanks for the feedback.
