### ISSUE TITLE
High CPU usage - constantly scans existing shows

### ISSUE THREAD

**Issue by jayroedk** [Sonarr/Sonarr#3027]
**Describe the bug**
Sonarr is constantly scanning existing shows for media info.

**Screenshots**
Rather than a screenshot, just imagine this line repeated to infinity:
**19-4-3 18:05:59.0|Debug|MediaInfoFormatter|Formatting audio channels using 'AudioChannelPositions', with a value of: '2/0/0'**

**Logs**
https://hastebin.com/wufuwezada.cs

**System Information**

 - Sonarr Version: linuxserver/sonarr (Latest: 2.0.0.5322)
 - Operating System: Ubuntu
 - .net Framework (Windows) or mono (macOS/Linux) Version: Mono, don't know the version.

**Comment by markus101** [comment]
It's not constantly scanning, that's just logged when the stored media info is formatted. It has to due with formatting the mediainfo for the API response, it's already been addressed in v3.

**Comment by Taloth** [comment]
@markus101 Those logs contain v3 api calls. Any third party app that's already using the v3 api like that?

**Comment by markus101** [comment]
I haven't heard of anyone using it, but it's been a few months so it seems likely.

**Comment by jayroedk** [comment]
Thanks for the swift reply @markus101 

Any idea why the CPU usage is close to 100% all the time?

**Comment by jayroedk** [comment]
I forgot to mention I keep seeing lines like these:
```
  | DiskScanService | Completed scanning disk for It's Always Sunny in Philadelphia | 18:42
  | DiskScanService | Scanning disk for It's Always Sunny in Philadelphia | 18:37
  | RefreshEpisodeService | Finished episode refresh for series: [75805][It's Always Sunny in Philadelphia]. | 18:37
  | RefreshEpisodeService | Starting episode info refresh for: [75805][It's Always Sunny in Philadelphia] | 18:37
  | RefreshSeriesService | Updating Info for It's Always Sunny in Philadelphia | 18:37
```

It's doing one show after another. Nomatter when an episode last aired.

**Comment by jayroedk** [comment]
Quick follow up.

I'm starting to suspect this issue is related to overly aggresive polling from Bazarr.

**Comment by markus101** [comment]
Bazarr is telling Sonarr to refresh it's metadata and rescan the series folder constantly? It should never need to tell Sonarr to refresh the metadata, maybe rescan the folder if a subtitle file was downloaded, but there is a separate command to only do that.

Trace logs will show API calls prior to those refreshes running.

**Comment by jonasion** [comment]
![image](https://user-images.githubusercontent.com/15011654/62426096-1fe13980-b6e9-11e9-8db8-cc205aae1a2a.png)

I have the same issue. Constant 14% CPU load from this one little process.

**Comment by espenja** [comment]
Same thing here. After a restart of Sonarr it goes down to normal levels, and randomly after a while it goes up to 15% and is stuck there until I restart it again. The strange thing is that this happens equally with both Sonarr and Radarr. Screenshot only has Sonarr acting this way right now, because the issue hasn't kicked in for Radarr yet after restart.

![image](https://user-images.githubusercontent.com/1131968/62821825-34a34e80-bb7b-11e9-92df-0722475ecdec.png)

Maybe related: I investigated CPU usage issues sometime last year regarding Jackett, and I was debugging my way down into the libraries for socks5 proxy which seemed to have a never ending connection problem, basically stuck in a while loop. Is anyone else with this issue also using proxy?
