### ISSUE TITLE
"tvDbEpisodeId" missing in API

### ISSUE THREAD

**Issue by wessel145** [Sonarr/Sonarr#3062]
**Describe the bug**
For a script i'm building i need the tvdb or imdb ID from each episode. The documentation shows that this field is available under /Episode, unfortunately this field is not returned by the API.

Wiki link:
[https://github.com/Sonarr/Sonarr/wiki/Episode](https://github.com/Sonarr/Sonarr/wiki/Episode)

Request URL:
http://someIP:8989/api/Episode/?apikey=MYAPIKEY&seriesId=19

Snippet of returned Json:
      
```
"hasFile": true,
          
"monitored": true,  

"absoluteEpisodeNumber": 69,  

"unverifiedSceneNumbering": false,  

"id": 3870  
```
According to the Wiki the field should exist before 'absoluteEpisodeNumber'

**System Information**

 - Sonarr Version: [2.0.0.5322]
 - Operating System: [Ubuntu Server 18.04]
 - .mono (macOS/Linux) Version: [5.18.1.0]

**Comment by Taloth** [comment]
Hmm, that field was [removed](https://github.com/Sonarr/Sonarr/commit/9f403b46ffac7ef040c096d6175d866d0335ce41) 6 years ago, back when we were still using trakt as source. In fact is was removed before the api wiki page was created, so the wiki was probably created using an older version at the time.

@markus101 I assume we don't want to re-add the field?

**Comment by wessel145** [comment]
Hmm thats sad, although I already assumed the page was outdated, I suppose trakt doesn't have these kinds of unique ID's per episode? What i'm trying to build is a script that takes the episode ID from Sonarr and do something with it in Emby, IMDB or TVDB ID would be best practise I guess. The only other matching value would be Episode name, which is not preferred.

**Comment by markus101** [comment]
we removed it because it was incredibly unstable, instead of editing an episode it’d be re-added and the old one removed.

The season and episode numbers are much more stable as are absolute episode numbers for anime.

I’d definitely recommend using the season + episode numbers for most episodes and use absolute episode numbers for anime. If you really want the TVDB ID you could get that straight from TheTVDB, but I wouldn’t rely on it.

It’s not something we’re going to add though.
