### ISSUE TITLE
Utilize LastSearchTime for missing search (search never/older searched episodes first)

### ISSUE THREAD

**Issue by eihns** [Sonarr/Sonarr#3067]
**Describe the problem**
I have around 5000 or so missing items.
Everytime i click this button, it searches in the same order... behind the curtain one indexer closes after 100 searches, the next closes after 1000 searches, the next one closes after 5000.

Since it always goes in the same order, i dont think theres a chance i get everything i could get if it would be random after each time.

So please, randomize the search for wanted items, so eventually i get all releases i coudl get.

If i manually search some series, which are at place 4588, i get results, so this is a real problem.

(im not searching for EN content, thats why that would be important)

**Comment by markus101** [comment]
Not planning to randomize it, but we do have plans to utilize the last searched time to allow for filtering/searching. At this time you can either search by page (in v3 the page size is customizable), or at the series level.

**Comment by eihns** [comment]
Sorry, i cant understand it. Why you dont want to make your program better?

Dont you understand the problem?

My english is not the best, so please ask if you dont understand me.

Sonarr will search, it doesnt matter if a indexer is not allowing to search, this is complete useless.

Also i will 100% not goin to each page and manually search.. like wtf?

Where is the problem for such an easy fix?

Most indexers have daily limits, if it always search in the same way, youll never get 100% results back, dont you understand?

**Comment by markus101** [comment]
Where did I say I didn't want to make it better? I said randomization isn't the approach we're planning to take. I understand the problem just fine.

> Also i will 100% not goin to each page and manually search.. like wtf?

I said that's a way around it _right now_ I didn't say that was the solution (or this would be closed).

There is no point in searching for the same things over and over again every day, which is what randomization will do for _some_ of the episodes, which is why we'd want to base this off of the last searched time not just a random selection (which will have it's own issues since multiple missing episodes in a season will trigger season searches to allow for season packs).

I understand:
- What you're asking for
- Indexers have limits
- Searching the same thing again and again is useless
- The solution isn't as "easy" as you think it is to do it right
- After the initial search, searching will add little to no value as Sonarr is watching RSS feeds

The title has been changed to reflect the solution, which will cover your use-case indirectly, either a button that will search for things not searched for in X days, or more likely a filter that can be applied to the current view + a way to search only for the filtered items, not all missing items.

**Comment by eihns** [comment]
Hey, thanks for explaining!

You say "after initial search, searching will add little to no value" - but that is wrong!

I dont know what content you search, maybe its different for other ppl. But for my german content, i can search literally every show i have in my library and will find new items to pick up "every time".

It might be because sonarr didnt picked up rss (what ever caused this), or because indexer ran into limits and it never got actually searched for (but sonarr thinks it searched for and didnt found anything). Or maybe a indexer manually loaded releases in, or updated his "anti obfuscation technique" (pretty big thing in GER).

When you say you add manual search per page as a workaround, why not just add randomizion for a workaround? Isnt that much less work? Whats the bad point about this? If you randomize, every scenario has atleast the chance to get picked up, if you have many items, if you have less... if you have 1000 api limit or 10... at some point it might search for it.

I can just tell you that researching is working great to find new content.

**Comment by markus101** [comment]
When Sonarr is constantly running and RSS Syncs are occurring then any new will be caught by that, a search for the same episode won't yield anything new unless the indexer failed to return the result the last time for some reason or you added a new indexer with different content. That is what I mean a search will add little value, there is always the chance that Sonarr misses something for some reason, but the "RSS Sync" logic covers the majority of newly posted content.

> When you say you add manual search per page as a workaround

We're not adding anything, this exists right now. The point is it exists as a work around right now, it's not something we need to add.

> but i use hydra, which will never return an error on search, even if all inexer has reached their limits

That seems like a problem in itself, but that's an overall problem with aggregation, which is going to have it's own issues. If you're using Jackett with the aggregate indexer (which we do not recommend for various reasons), it'll return an error if any indexer fails to respond properly, which isn't what you want and also limits the results that Sonarr receives (a general problem with aggregation in Hydra/Jackett).

> Still the same items gets searched and after the api limits are reached, you dont get any results, even sonarr thinks, it has searched successfully

IMO, that's a problem with Hydra then, if a search fails for a particular indexer Sonarr needs to know, masking it will be a problem. I don't think it's our responsibility to deal with intermediate applications doing something that will affect Sonarr negatively, if their mimicking the API they should behave like the API.

Again, randomization of searching really isn't the solution here, but I think we could likely utilize the last searched time to automatically search for things that were last searched longer than something else. This would eventually lead to everything missing being searched and quicker than randomly searching for things since it would be `x/y` (where `x` is missing and `y` is  the API limit) where randomization could take days/weeks/months to randomly select each one.

**Comment by eihns** [comment]
Hmm, guess that makes sense. Should be even better as random, like u said. Bc lets say last item didnt got all results back because limits were reached.. next time it would get searched first... clever.

What about a auto search every X month? :)

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/issues/761 though it's a very low priority item for us for the reason that RSS Sync is superior in reducing loads on indexers (and not getting Sonarr banned from indexers).

**Comment by Taloth** [comment]
Just FYI, I'd like to point out that I know indexers that rather explicitly recommend Sonarr over the alternatives _because_ we do not do periodic searches.
But these indexers have a paged rss api, which allows Sonarr to grab up to 24h old rss results in case of downtime.
You might want to check System->Logs/Events it'll contain a warning if Sonarr detects a 'gap' in the rss feed of an indexer.

**Comment by eihns** [comment]
I slept over it.

Lets say it searches 1, 2,3 ,4,5 ,6,7... 

now when it arrange them after last searched..

wouldnt it search 7,6,5,4,3,2,1 ... and next time 1,2,3,4,5,6 ? And we have teh same problem like now? :D

**Comment by eihns** [comment]
> Just FYI, I'd like to point out that I know indexers that rather explicitly recommend Sonarr over the alternatives _because_ we do not do periodic searches.
> But these indexers have a paged rss api, which allows Sonarr to grab up to 24h old rss results in case of downtime, so that kinda removes the need for them anyway.
> You might want to check System->Logs/Events it'll contain a warning if Sonarr detects a 'gap' in the rss feed of an indexer.

I would let standard as it is -> no auto search. So 98% of all sonarr users still wont auto search.

It makes virtually no difference if i manually do the search every month or every day or if sonarr does it on itself. But i would set the auto search at a min high like every 3 month, every 6 month, every year. I think no one can complain about that.

**Comment by thezoggy** [comment]
man this thread is painful to read through..  doing what eihns wants would get sonarr banned pretty quickly for doing straight up dumb logic.  it sounds like eihns is asking for this because they have gaps in their indexer data because they dont leave sonarr running / have a really high rss feed time..   things that could probably be rectified on the user end before causing such a waste in resources for everyone else.

**Comment by eihns** [comment]
> man this thread is painful to read through.. doing what eihns wants would get sonarr banned pretty quickly for doing straight up dumb logic. it sounds like eihns is asking for this because they have gaps in their indexer data because they dont leave sonarr running / have a really high rss feed time.. things that could probably be rectified on the user end before causing such a waste in resources for everyone else.

Painful is reading such nonsense from ppl like you, youre right.

Read & understand, then come back.

**Comment by eihns** [comment]
Any news on this @markus101

**Comment by eihns** [comment]
Any news on this @markus101

**Comment by eihns** [comment]
> #761 though it's a very low priority item for us for the reason that RSS Sync is superior in reducing loads on indexers (and not getting Sonarr banned from indexers).

Any news? Why you think it will make bigger loads? It will in fact reduce the load, because ppl get what they are looking for instead of searching the same things over and over again....????

**Comment by thezoggy** [comment]
you are probably going to take this wrong but to humor you. 

specifically about why rss sync is superior and reducing loads:
rss feeds are pretty fixed, think of it like `tail -f file`.pretty low overhead with db. when you start searching that is more effort the site has to do. if you add a show and content comes out, sonarr will see it on the rss feed and grab it. now if you added a show after stuff has aired, then relying on rss means you have to wait for stuff to get reposted.  for majority of people generally rss feeds alone take care of everything (with context that the show exists before content is posted). 

now if you are limiting your question to content that is old and not freshly posted, where the only way to get it is to search (assuming its not going to be reposted) there is a multitude of variables here to consider. season packs / retention / nzb age. a few years ago, going back 5 years for a nzb wasnt an issue.. nowdays you prob dont really want to go back that far.. besides dmca, because quality is much better nowdays (better sources/codecs/etc). and since the majority of users that use sonarr is focusing on newer/upcoming/current shows.. this becomes less of a priority as soanrr devs have noted.

**Comment by eihns** [comment]
> you are probably going to take this wrong but to humor you.
> 
> specifically about why rss sync is superior and reducing loads:
> rss feeds are pretty fixed, think of it like `tail -f file`.pretty low overhead with db. when you start searching that is more effort the site has to do. if you add a show and content comes out, sonarr will see it on the rss feed and grab it. now if you added a show after stuff has aired, then relying on rss means you have to wait for stuff to get reposted. for majority of people generally rss feeds alone take care of everything (with context that the show exists before content is posted).
> 
> now if you are limiting your question to content that is old and not freshly posted, where the only way to get it is to search (assuming its not going to be reposted) there is a multitude of variables here to consider. season packs / retention / nzb age. a few years ago, going back 5 years for a nzb wasnt an issue.. nowdays you prob dont really want to go back that far.. besides dmca, because quality is much better nowdays (better sources/codecs/etc). and since the majority of users that use sonarr is focusing on newer/upcoming/current shows.. this becomes less of a priority as soanrr devs have noted.

I just dont see it. Its like were using different programs. I dont know why, but i know if i manual search, i find new stuff, mostly ofc older things, but sometimes even new things. Anyway.

Sonarr has a function to manual search. Thats what this topic is about.

But its useless, because you search the same stuff over and over, and all indexers have some sort of limit... its probably literally 5 min time to do a pseudo random code for searching.

**Comment by thezoggy** [comment]
if you check sonarr logs between the auto/manual/rss are the differences you seeing specific to foreign shows that are not put in the correct category or associated with the tvdb/rage/imdb ids? do you notice the 'issue' is mainly with newznab sites or nzebd sites or sites that dont have an api?

**Comment by eihns** [comment]
There are many problems, missing, deleted shows, thing wrong recorgnized. Sometimes sonarr thinks indexer (i guess its meaning hydra2 is down (which it is not), but radarr doenst has these problems)

im using "all" indexers avaible publicy bc i get so low results anyway. They are all combined into hydra2 

https://imgur.com/a/IZoy8N3

It might be other issues because this is happening, but still it wouldnt hurt to make the search better...

**Comment by thezoggy** [comment]
and if you dont use hydra and put the indexers in sonarr, do you have the same issue?

**Comment by eihns** [comment]
Since i have that many indexers i thouight thats the best approach?

**Comment by eihns** [comment]
in the meantime btw radarr and sonarr can be automatically added each indexer, ofc this didnt changed anything.

This is still broken.
