### ISSUE TITLE
Prioritise quality, then release profiles, then delay profiles?

### ISSUE THREAD

**Issue by GOvEy1nw** [Sonarr/Sonarr#3082]
**Describe the problem**
I'm running v3, and I'm testing out the preferred terms feature. 
I have the following settings (note: I download mainly hevc)

**Must contain:**
* vyndros
* qxr
* utr
* psa
* bvs
* mkvcage
* mzabi
* heteam
* rzerox
* joy
* ime
* megusta

**Preferred:**

* Vyndros =100
* QXR = 90
* ImE = 90
* UTR = 80
* Joy = 80
* PSA = 70
* Megusta = 40

I also have the auto created 'usenet' delay protocol that prefers usenet over torrents.

Because sonarr seems to proritise in the following order: quality, delay profile, release profile, when I do a search (eg, the simpson s30), I get a lot of files downloading like so:

`1080p.HEVC.x265-MeGusta-Obfuscated` (usenet files) this has a release profile match of +40 for preferred terms.

They match the show & the episode etc, which is fine. But if I do a manual search for the same thing, I can see that there are plenty of files like so"

`(1080p WEB-DL x265 HEVC 10bit AAC 2.0 ImE) [QxR]` (torrent files) this has a release profile match of +180 for preferred terms

These ones rank much higher in my preferred settings etc compared to the megusta files. Also, since the megusta files don't say web/hdtv, sonarr assumes they are hdtv, which makes it even odder as to why it would go for that file instead of the ones marked web-dl

**Describe any solutions you think might work**
I believe if we were able to alter the preferred order of the main profiles to: quality, release profiles & then delay profiles, we'd be able to get the better matching file overall.

I think it would make more sense also if the 'prefer usenet' option was only enforced when a version on usenet exact matches a preferred version on torrent.

**Example 01:** an auto search finds the following files:
Torrent: (1080p WEB-DL x265 HEVC 10bit AAC 2.0 ImE) [QxR] = +180 match
Nzb: 1080p.HEVC.x265-MeGusta-Obfuscated = +40 match

File chosen to download = Torrent: (1080p WEB-DL x265 HEVC 10bit AAC 2.0 ImE) [QxR]

**Example 02:** an auto search finds the following files:
Torrent: (1080p WEB-DL x265 HEVC 10bit AAC 2.0 ImE) [QxR] = +180 match
Nzb: (1080p WEB-DL x265 HEVC 10bit AAC 2.0 ImE) [QxR] = +180 match
Nzb: 1080p.HEVC.x265-MeGusta-Obfuscated = +40 match

File chosen to download = Nzb: (1080p WEB-DL x265 HEVC 10bit AAC 2.0 ImE) [QxR]

**Example 03:** an auto search finds the following files:
Torrent: 1080p.HEVC.x265-MeGusta-Obfuscated = +40 match
Nzb: (1080p WEB-DL x265 HEVC 10bit AAC 2.0 ImE) [QxR] = +180 match

File chosen to download = Nzb: (1080p WEB-DL x265 HEVC 10bit AAC 2.0 ImE) [QxR]

*Additional context**
Here's an example:  https://imgur.com/a/s35KCq0

**Comment by markus101** [comment]
> Because sonarr seems to proritise in the following order: quality, delay profile, release profile.

No, it's quality, language, preferred words, protocol, etc as shown in the code here:

https://github.com/Sonarr/Sonarr/blob/ca4b03f48a2124467e56dcc262f936f6b511f2aa/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs#L22-L35

For your Simpson's example it's impossible to say why one release was chosen over another, but my best guess is Sonarr never saw those results when it performed the season search, but you see them in the individual episode search, which would be an issue with the indexer, but debug logs would tell you if Sonarr saw them if they were rejected.

The order of the results in the interactive search results is the result Sonarr will attempt to download releases in if a manual search was performed.

Your photo example doesn't really show anything, since it's bits and pieces of the overall picture.

Please open a thread on the forums if you want to troubleshoot this further as Sonarr is using preferred words over preferred protocols.
