### ISSUE TITLE
Repack/Proper Priority

### ISSUE THREAD

**Issue by antigravity83** [Sonarr/Sonarr#3084]
Sonarr currently prioritises ANY repack or proper, regardless of source or release group.

In reality, they should only be rated over either
1. the same release group (Repack) 
OR
2. the same source type (Proper)

For example, I have set manual priorities for AMZN releases and NTB (both +10 each), so in essence, if an AMZN and/or NTB release is available, I want to download it, instead of any other release group or source.

However, in this scenario, because a group has released a Repack, Sonarr ignores all my above preferences, and instead wants to download the Repack, despite the fact it's not an AMZN or NTB release.

![image](https://user-images.githubusercontent.com/27241813/56863409-46f8e280-69f9-11e9-8c8f-15152d9383eb.png)

I don't want to download the MEMENTO release - I ALWAYS want to download an AMZN or NTB release if it's available. 

Ideally, a Repack/Proper should only be taken into considering if it has the same "points" allocation as other downloads. At least then Sonarr wouldn't be ignoring my priority preferences. 

So if there was a Repack/Proper that also had +10 priority, then it would be downloaded over a non repack/proper with +10 points.

But if there was a Repack/Proper with no points, Sonarr would ignore it, and download a release that has +10 points.

The current method of prioritising repacks/propers over EVERYTHING else, breaks the whole weighting system introduced with V3.

 - Sonarr Version: 3.0.1.458
 - Operating System: Ubuntu 18.04 Minimal
 - Mono 5.20.1.19

**Comment by markus101** [comment]
1. https://github.com/Sonarr/Sonarr/issues/3084
2. Same source is already applicable (WEB and WEB-DL are the same thing)

Propers are complicated, you can't simply preferred a higher score over a proper and expect things to be 100% correct, since Sonarr doesn't have a way to verify the proper only supersedes the nuked release (and we don't have plans to check every release against a predb to verify). We do have plans to extend the disabling of propers to provide a way to also not prefer them.

**Comment by antigravity83** [comment]
Thanks @markus101 . When I refer to source, I meant the Web/Web-DL source (ie. AMZN, NF, Itunes etc). 

Why can't you prefer a higher score over a proper?

If a file has higher points than a proper, wouldn't that suggest that user never downloaded the original file that needs a proper/repack?

Using the original example:

1. Sonarr initially downloads the AMZN release with +10 priority. 
2. Memento Repack is released, but as it has a rating of +0, it doesn't get picked up. 
3. User keeps originally downloaded file with requested release priorities

Now say an AMZN release had a Proper/Repack released:

1. Sonarr initially downloads the AMZN release with +10 priority
2. Repack is released with AMZN in the file name. As it has a +10 priority also, but is a repack, it is downloaded
3. User now gets repacked file with the requested release priorities 

If the user has multiple priorities, the above scenario works even better - in that it'll only download the Proper/Repack in a more specific scenario

Either scenario is better than the current, where the MEMENTO repack is always downloaded over the original download that met the requested release priorities.

**Comment by antigravity83** [comment]
If you're going to provide an option to turn off Proper/Repack (which would be even worse as they would never be picked up), can you also provide an option for Proper/Repacks to be prioritised but ONLY if they have the same or more points than the existing download?

That would be a much more nuanced approach, and whilst not perfect, is better than having it fully on or fully off.

**Comment by markus101** [comment]
> When I refer to source, I meant the Web/Web-DL source (ie. AMZN, NF, Itunes etc).

The underlying source of that is irrelevant to Sonarr.

> If a file has higher points than a proper, wouldn't that suggest that user never downloaded the original file that needs a proper/repack?

How so? A proper is a fix for another release from another release group with the same source (HDTV, WEBRip, WebRL, etc) and resolution. Your example only works because it's a repack and a repack from group A shouldn't be prioritized over a non-repack from group B.

There is absolutely no guarantee a valid proper will be able to replace a non-proper with a specific score if score is preferred over proper/repack.

> Either scenario is better than the current, where the MEMENTO repack is always downloaded over the original download that met the requested release priorities.

That's specifically a repack issue, proper is unrelated.

> If you're going to provide an option to turn off Proper/Repack (which would be even worse as they would never be picked up),

They'd be the exact same as turning off propers now, which means Sonarr won't upgrade to them automatically, but also allow your scoring to override it (exactly what you want). You can't prefer score over propers and simultaneously proper over non-proper when it meets your custom rules (unless you add proper/repack to your rules). If you want propers/repacks to upgrade (in your perfect scenario), give them a score, that's the only way you're going to achieve it without knowing specifically what release was nuked and de-prioritizing it instead of prioritizing the propers/repacks.

**Comment by antigravity83** [comment]
> > When I refer to source, I meant the Web/Web-DL source (ie. AMZN, NF, Itunes etc).
> 
> The underlying source of that is irrelevant to Sonarr.
> 
Sure, but it is relevant to Sonarr when the user inputs these as Release priorities

> > If a file has higher points than a proper, wouldn't that suggest that user never downloaded the original file that needs a proper/repack?
> 
> How so? A proper is a fix for another release from another release group with the same source (HDTV, WEBRip, WebRL, etc) and resolution. Your example only works because it's a repack and a repack from group A shouldn't be prioritized over a non-repack from group B.
> 
> There is absolutely no guarantee a valid proper will be able to replace a non-proper with a specific score if score is preferred over proper/repack.

I think you're being too pedantic about the Proper/Repack having to replace the specifically related previous release. Ideally this would be preferable, but it doesn't have to be that specific. 

The process I'm trying to get to is this:
- Only download a Proper/Repack if it has _equal_ or higher weighting to other releases.

For example:

**Release Profiles Preferred**
AMZN +10
NTB +5
QOQ +5

**Original Downloaded File**
Show.Name.S01E01.1080P.WEBDL.AMZN.NTB (+15 points)

**3 Propers released**
1. Show.Name.S01E01.1080P.WEBDL.PROPER.AMZN.MEMENTO (+10 points) <--- Sonarr ignores as it has lower points than the originally downloaded file
2. Show.Name.S01E01.1080P.WEBDL.AMZN.PROPER.NTB (+15 points) <--- Sonarr downloads as it has the same points as originally downloaded file but is a proper
3. Show.Name.S01E01.1080P.WEBDL.AMZN.PROPER.Q0Q (+15 points) <--- Sonarr downloads as it had the same points as originally downloaded file, but is a proper. 

Where I think you're getting too pedantic is with the third option. Because it's not the same release group, you're saying it should be downloaded. But the current implementation does that anyway? 

At least with the above process, Sonarr will _only_ download a proper/repack if it has the same points or higher. 

So in this scenario- sure, it downloads a file it doesn't technically need to download, but at least it still keeps the users Release priorities (AMZN and QoQ) when a Proper/Repack comes along. 

> 
> > Either scenario is better than the current, where the MEMENTO repack is always downloaded over the original download that met the requested release priorities.
> 
> That's specifically a repack issue, proper is unrelated.

So Sonarr treats Propers and Repacks differently? From my experience, if a Proper or Repack is released, Sonarr will download it - and ignore any Release Profile Priorities. 

> 
> > If you're going to provide an option to turn off Proper/Repack (which would be even worse as they would never be picked up),
> 
> They'd be the exact same as turning off propers now, which means Sonarr won't upgrade to them automatically, but also allow your scoring to override it (exactly what you want). You can't prefer score over propers and simultaneously proper over non-proper when it meets your custom rules (unless you add proper/repack to your rules). 

Turning off proper upgrades stops Sonarr from downloading them. Users don't want that. They just want Sonarr to consider Release Priorities in addition to the fact they are Propers/Repacks.

>If you want propers/repacks to upgrade (in your perfect scenario), give them a score, that's the only way you're going to achieve it without knowing specifically what release was nuked and de-prioritizing it instead of prioritizing the propers/repacks.

Ok thanks - I will give that a shot - that might do the trick. 

But I still think you should consider the above process as the default process - as I don't think most users are aware that Sonarr ignores all Release Profile Preferences when a Repack/Proper is available.

**Comment by antigravity83** [comment]
If I turn off "Download Propers" and instead give them a score, will Sonarr still auto-upgrade a download based on Release Profile Preferences alone?

So if a file is downloaded, and a new file is released with a higher points (same quality profile etc), will Sonarr auto download it?

**Comment by markus101** [comment]
> I think you're being too pedantic about the Proper/Repack having to replace the specifically related previous release. Ideally this would be preferable, but it doesn't have to be that specific.

Huh? That's exactly what the reason they exist. They exist because a release was nuked and a release was 

> Because it's not the same release group, you're saying it shouldn't be downloaded. But the current implementation does that anyway?

That's not what I'm saying... a proper is a fixed release for a _different_ release group, a repack is a fixed release for the _same_ release_ group, you'd never see NTB release a proper for an NTB release, but QOQ would for an NTB release (or vice versa).

> The process I'm trying to get to is this:
> Only download a Proper/Repack if it has equal or higher weighting to other releases.

I know... which is why we need to have an option to de-prioritize propers/repacks so the score makes a difference, but you argued against that because that would mean they'd never download, but you can't have something that's equal priority and lower priority at the same time. It's a trade off.

> Turning off proper upgrades stops Sonarr from downloading them. Users don't want that. They just want Sonarr to consider Release Priorities in addition to the fact they are Propers/Repacks.

It doesn't stop them, it stops _upgrading_ to them. That's where this gets complicated as I've said before there is no guarantee that a proper/repack will come out that is of equal or greater score, so no matter what you could end up with a lesser release because of it.

> If I turn off "Download Propers" and instead give them a score, will Sonarr still auto-upgrade a download based on Release Profile Preferences alone?

No, that's why I said: "We do have plans to extend the disabling of propers to provide a way to also not prefer them."

The fact that we're mostly talking about p2p releases as opposed to scene releases is a further complication, in a scene-only world, which is where the rules come from, p2p by comparison is chaos.

From my POV there are two ways to solve this:

1. De-prioritize propers, let you add a score to prefer them over a non-proper of an otherwise equal score (this is what we've discussed implementing already)
1. Compare quality, followed by preferred word score, then proper/repack (this is what you're suggesting, at least how I understand it)

Option 1 works well for scene releases where there is 1 release for a quality then either a repack or proper to fix it, because you'd get a proper for a bad release regardless of how much you preferred the original release.

Option 2 works for p2p releases where there could be multiple releases of the same quality. A proper would only replace a release of the same score.

I think the biggest question I have, is which is more expected to a user.

With option 1 they explicitly disabled a setting and have the ability to override it with an additional preferred word. With option 2 they implicitly disable a setting and may not understand the impact it's easier for us to communicate that by turning of X you're disabling a setting, but with preferred words effectively disabling potentially valid propers without knowing.

**Comment by antigravity83** [comment]
You understand the software much better than I do, so whichever way you feel is better to implement any change is obviously your call :)

As a user (and I've seen this raised by others on Reddit and here), there just needs to be something implemented that stops Sonarr from ignoring Preferred Release Profiles. 

I think Option 1 is what I'm after. An ability to apply a score to Proper/Repacks (even +1 would work), so they would then only be downloaded/upgraded if they met the same priorities as other files, but would be only slightly prioritised because they have a score of +1

So using my existing example:

**RELEASE PRIORITIES**
AMZN +10
NTB +5
Q0Q +5
PROPER +1
REPACK +1

**ORIGINALLY DOWNLOADED FILE**
show.name.s01e01.1080P.WEBDL.AMZN.NTB (+15)

**REPACKS RELEASED**
show.name.s01e01.1080P.WEBDL.MEMENTO.REPACK (+1, not downloaded as lower score than existing file, not AMZN and NTB or Q0Q)
show.name.s01e01.1080P.WEBDL.AMZN.REPACK (+6, not downloaded as lower than existing file, not NTB or Q0Q)
show.name.s01e01.1080P.WEBDL.AMZN.NTB.REPACK (+16, downloaded as higher than existing file. Meets original preferences AMZN and NTB + repack)
show.name.s01e01.1080P.WEBDL.AMZN.QoQ.REPACK (+16, downloaded as higher than existing file. Is AMZN and release group has same weighting as existing file + repack)

The above scenario is much improved over the current solution - where the existing file would be upgraded by the first file, despite it not being AMZN, QoQ or NTB. 

Hope that makes sense.

**Comment by thezoggy** [comment]
repack and proper mean two different things. repacks will always be from the same group. as they are just repacking the release. and this is a scene 'tag'. proper means that a group (could be the same) wants to replace an already existing release. hence the previous one should be nuked. now sometimes propers are done proactively by some groups to spite others.  now all this is scene lingo. 

when your talking about web-dl your talking about p2p rips. which have no concept of a nukenet or predb...  so no 'propers'.

**Comment by antigravity83** [comment]
Sure thanks, understand the difference between Repacks and Propers.

The issue isnt whether or not Sonarr distinguishes between the two (my understanding is that it doesn't anyway), but rather that it prioritises a Repack or Proper over everything else in the same quality group. 

My original example highlights this. It prioritises a scene Repack over a P2P release that better suits my requirements.
