### ISSUE TITLE
Create a 2.1 release

### ISSUE THREAD

**Issue by Qazerowl** [Sonarr/Sonarr#3125]
I came on here to suggest a couple features, only to find they've already been suggested, accepted, and completed... several years ago. In fact, there are currently 172 issues that have already been fixed slated for the 3.0 release, dating back almost 4 years. Please push these changes into the stable branch. Seeing that a bug you've had problems with was fixed **4 years ago** is extremely frustrating for users. And if you save up 4 years of work to release all at once, you're just ensuring you will get flooded with 4 years worth of bug reports once v3 finally comes out.

Could you at least shed some light on the decision to go straight from v2.0.0.x to v3.0 instead of braking it into smaller milestones?

**Comment by Dnkhatri** [comment]
> I came on here to suggest a couple features, only to find they've already been suggested, accepted, and completed... several years ago. In fact, there are currently 172 issues that have already been fixed slated for the 3.0 release, dating back almost 4 years. Please push these changes into the stable branch. Seeing that a bug you've had problems with was fixed **4 years ago** is extremely frustrating for users. And if you save up 4 years of work to release all at once, you're just ensuring you will get flooded with 4 years worth of bug reports once v3 finally comes out.
> 
> Could you at least shed some light on the decision to go straight from v2.0.0.x to v3.0 instead of braking it into smaller milestones?

The fixes that can be backported have already been backported. The remaining probably would require too much work.  A lot of users have already moved to v3 so I would advise you to try the v3 release although the devs don't consider it stable I have been on it for the last few months with  almost no problems and the devs are quick to fix any breaking changes. Try the v3 you won't regret it.

**Comment by markus101** [comment]
> Seeing that a bug you've had problems with was fixed 4 years ago

AFAIK we don't have bugs that were fixed 4 years ago in the v3 release that aren't also in the v2 release already. Not sure where you're getting us saving up 4 years of fixes, because that simply hasn't happened. v2 has been around for ~6 years and had had fixes and features added for the last 5+ years. A lot of the v3 things involve UI changes we didn't want to do in the old UI and everything else has come after we decided to focus on v3 only. 

ANything not fixed in v2 won't be back ported, v3 is available in an alpha/beta and will replace v2 when we decide it's ready.

**Comment by Qazerowl** [comment]
https://github.com/Sonarr/Sonarr/milestone/2?closed=1

Maybe I'm misunderstanding what this list represents, but to me it looks like it's a list of bugfixes and enchantments that have not been put in the stable branch yet. The oldest of which was marked complete on Jul 22, 2015. I picked 3 or 4 just now and it doesn't seem like any of them are in stable, but maybe I've just picked poorly. 

I would still be interested to hear the thought process behind such a long development cycle. Even the release naming scheme "2.0.0.xxxx" is pretty bizarre and seems to imply that smaller milestones were originally intended. Regardless, I will try out the v3 beta. I prefer to only run stable software on my server, but I suppose that's relative.

**Comment by markus101** [comment]
Correct, and _most_ of them are UI fixes, done during a rewrite of the entire UI. None of those are intended to be part of v2 due to the nature of the rewrite. https://github.com/Sonarr/Sonarr/issues/344 is a dupe, the actual issue wasn't resolved until much later, there are several things already in develop too, not sure why they were tagged with the v3 milestone, but it doesn't really matter.

Long cycle:

1. We work on Sonarr in our free time
2. We changed the UI frameworks
3. We upgraded to a new .net framework version (Breaking change)

> Even the release naming scheme "2.0.0.xxxx" is pretty bizarre

Pretty standard numbering, Major, Minor, Revision/Patch, Build.

> smaller milestones were originally intended

We only started using milestones with v3, we originally intended
