### ISSUE TITLE
Sonarr confuses episode information for concurrent, same series downloads.

### ISSUE THREAD

**Issue by jokker23** [Sonarr/Sonarr#3178]
**Describe the bug**
When multiple same series files are ready for processing, Sonarr sometimes confuses the episode information and moves the files incorrectly, ie:

Moving episode file: /my/path/Show.S01E01.EpisodeUno.720p.mkv to /my/path/Show.S01E02.EpisodeDos.720p.mkv

**Screenshots**
https://i.imgur.com/lXPQOYP.png

**Logs**
[trace.log](https://github.com/Sonarr/Sonarr/files/3312657/trace.log)

**System Information**
 - Sonarr Version:     2.0.0.5322
 - Operating System: Debian GNU/Linux 8.11 (jessie)
 - mono Version: Mono JIT compiler version 5.0.0

**Additional context**
I'm using SABnzbd to download/sort files into the Processing folder. I have verified that before Sonarr picks up the downloads for Import they are correctly named.

**Comment by Taloth** [comment]
Can you run the 'Test' in Settings->Download Client->Sabnzbd? We suspect you have job folders disabled in Sabnzbd.

**Comment by jokker23** [comment]
Testing Succeeded. I'm not sure what you are referring to by job folders? Is this the download folders?

**Comment by markus101** [comment]
Job folders are folders SAB creates for each individual job, SAB should be reporting `/my/path/Show.S01E01.EpisodeUno.720` as the path, instead of just `/my/path` the way it's set up right now tells Sonarr to import multiple different downloads from the same location and due to Sonarr using the download name instead of the file name (to handle cases where the download name and file name are different due to dir fix releases) it gets imported to the wrong location.

SAB will not use job folders if the Sonarr category is configured like this:

![image](https://user-images.githubusercontent.com/413544/60148818-69a04100-9787-11e9-97c7-2fe30f9654b4.png)

Specifically the `/*` after tv in the `Folder/Path` column, Sonarr should detect that as a misconfiguration and fail the test though (it did when I just tested it), but regardless this is a misconfiguration on SAB's side, not a bug in Sonarr.

**Comment by jokker23** [comment]
![image](https://user-images.githubusercontent.com/2975764/60154047-015b5a80-979b-11e9-98c8-a973be2bfe4e.png)

This is how I have it.

**Comment by markus101** [comment]
Sonarr’s logs show that the file was not in a folder specific to that download it was directly in the processing folder. You can see that when Sonarr logs the input and when it gets the response from SAB (SAB’s response does not have a “job” folder included).

**Comment by markus101** [comment]
TV sorting in SAB could also cause this, though again it’s something Sonarr warns against when testing.

Based on the output path from SAB this is something outside of Sonarr control and not something we can taken action on.
