### ISSUE TITLE
Download only one series from multi-series torrent release

### ISSUE THREAD

**Issue by Dm3Ch** [Sonarr/Sonarr#3188]
**Describe the problem**
Sometimes some TV-Shows are exists only as a single torrent release that is updating weekly.
It would be cool to have ability to download series from such releases automatically. Suddenly it's not possible now.

**Describe any solutions you think might work**

**Additional context**

**Comment by markus101** [comment]
Sonarr does not support full series packs. We do not have plans to support that or this use case.

**Comment by Dm3Ch** [comment]
Currently sonarr already support downloading series pack if all series are not exists locally.

I understands that ideal implementation of this feature would require sonarr to control which files from the torrent release should be downloaded and that's not trivial cause it would require tightly integration with torrent downloaders and changing some "core" code.

Maybe it would a good compromise to implement this feature as it's implemented in flexget (https://flexget.com/Plugins/series/season_packs).
I meant adding some configurable threshold option that would specify how many missing series should we have to allow downloading release with series that already downloaded and meets requirements.

Such implementation wouldn't require changing search and import code for my opinion. So it only requires adding new "threshold" option and modifying code that makes decision about downloading release.

@markus101  What do you think about this?

**Comment by markus101** [comment]
Assuming you mean a single season, not the entire show (series), then yes it does.

At this time we don't have plans for a threshold for grabbing a season pack, allowing them to be grabbed wouldn't be complicated, but the post-download importing is more complicated, because it would need to be able handle not being able to import all the files.

Season packs can be forcibly grabbed via Interactive Season Search in v3, it still has the import concerns, but the user has made a conscious choice at the time of grabbing, not one in the past and should better understand the limitations.
