### ISSUE TITLE
Folder no permission

### ISSUE THREAD

**Issue by BugFinder2000** [Sonarr/Sonarr#3215]
**Describe the bug**
QBitTorrent moves file too the tv-sonarr folder and sonarr cant see them
-> https://i.imgur.com/rQF4MRp.png

qBitTorrent have no extra rights like admin or so.

I give Sonarr System rights and it didnt find the files

And on the folder everyone have full access.

The files are there i can see them and move them but sonarr cant, it seems it dont use his own rights on imports.

The root folder has the same security settings, but sonarr dont have a problem there it can move rename delete without problems.

**System Information**

 - Sonarr Version:3.0.2.537
 - Operating System: Windows 10

**Comment by markus101** [comment]
Please use the forums/subreddit for help and support. We'll need to see the requested debug logs.

**Comment by BugFinder2000** [comment]
In the error msg: 

`E:\Output\tv-sonarr\TheFileName. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder`

Sonarr didnt print the file extension.
In this case its .mkv and sonarr have only a point in the path, is that right ?

**Comment by BugFinder2000** [comment]
@markus101 This is a bug, i hope you can reproduce it with a manual grab on a single episode with more then 1 file and then try too manual import it.

**Comment by markus101** [comment]
Sonarr gets the path from the download client. If the wrong path is reported by the download client or it's reporting a folder instead of a file then Sonarr won't be able to do anything. It sounds like qbit is moving the video file directly to the `tv-sonarr` folder and not including the job folder, which is why Sonarr it looks like Sonarr is excluding the extension. Either the job folder needs to be maintained or qbit needs to report the path to the file only.

**Comment by BugFinder2000** [comment]
The files are directly in the tv-sonarr folder.

That can be because i turn off too create subfolders in qbit.

Now i can fix that, thanks
