### ISSUE TITLE
Add wiki page giving details of the Qualities available for video files

### ISSUE THREAD

**Issue by samta0** [Sonarr/Sonarr#3224]
**Describe the problem**
I was wondering what some qualities like Raw* represent and why there is no interlaced quality like 1080i. Then I found the following page from a different application : 
https://github.com/pymedusa/Medusa/wiki/Quality-Settings#quality-names-to-recognize-the-quality-of-a-file

**Describe any solutions you think might work**
Could you create a "Qualities" page in the wiki of sonarr? It could be placed in the wiki index right above the already existing "Profiles" page. 

Thanks.

**Comment by markus101** [comment]
That is not a page we want to create and maintain as it's a growing list. The tests we maintain cover everything, broken down by for each quality. https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core.Test/ParserTests/QualityParserFixture.cs

RAW HD is the only oddball as it's not something you'd easily be able to google and figure out what it is, but otherwise the difference between Bluray and Bluray Remux or WebRip and Web-DL are available elsewhere.
