### ISSUE TITLE
Inefficient Completed Download Handling

### ISSUE THREAD

**Issue by Nfinished** [Sonarr/Sonarr#3228]
**Describe the problem**
If Completed Download Handling is A) Enabled and B) set to remove after completion, the file is still copied and then removed instead of just being moved, even if the files are ready to be removed.

**Describe any solutions you think might work**
If the removal conditions are met immediately, could the file just be moved instead of copied? On my Pi 3 copying larger files can take hours, it'd be wildly more efficient to cut the mustard when possible.

**Comment by markus101** [comment]
That depends where the file is being moved to. Moving files across file systems will effectively be a copy. On the same filesystem Sonarr will move the file.

**Comment by Nfinished** [comment]
My setup connects to a remote drive that hosts both the downloads folder and the media folders. Even though it's the same drive, the files are being copied.

**Comment by markus101** [comment]
Depending on how that remote drive is mounted Sonarr is likely doing this to avoid corrupted files, which can occur under mono, mostly with SMB network shares, which can occur with moves and copies, the copy is done to ensure the integrity of the source file as a move that ends up truncated files has no recovery path.

**Comment by Nfinished** [comment]
Gotcha, thanks for clearing that up.

**Comment by Nfinished** [comment]
Wait, still not sure I understand. It's an SMB share, but it's only one SMB share. I'm not moving data between networks.

**Comment by markus101** [comment]
If the mount is the same then Sonarr shouldn't do a transactional move. Please open a thread on the forums or subreddit and we can take a look, trace logs would be preferable to see everything we can. We're most interested in what happens before the file starts copying, since an hour of trace logs is a lot of information.

The underlying issue could have to do with how the SMB share is mounted and whether the OS sees them as the same volume, similar to how docker paths work. https://old.reddit.com/r/usenet/wiki/docker

If you have different mounts on the rpi3 for the completed downloads and the sorted downloads then those will be different volumes, even if they are subfolders on the same share on the server.

We recommend NFS over SMB to avoid this issue entirely.
