### ISSUE TITLE
Add ability to edit Release Group

### ISSUE THREAD

**Issue by theimmortal68** [Sonarr/Sonarr#3237]
**Describe the problem**
Currently Sonarr doesn't parses the Release Group if it is not formatted in a particular way (with a dash or brackets I think are the only two supported), which results in some episodes missing the release group in the name. Currently the only want to add the release group is to edit the file name manually. This also includes older episodes that were imported before this naming convention was used/available.

**Describe any solutions you think might work**
Add the ability to edit/add the release group from the "Manage Episodes" screen. Include a text box that can be typed into next to the Quality drop down select box. Then we can check the boxes next to to the episodes we want to add/change the release group for and do a mass edit in the same manner as changing the quality.

**Comment by jemus42** [comment]
I was really happy that now in v3 you can bulk-edit quality etc. on the **manual file import** window – especially there I would love to also be able to set the release group. That way I don't have to carefully rename files before import.

**Comment by accelaptd** [comment]
seconded. it's weird that sonarr uses and stores this data but it isn't able to be manipulated from sonarr. i'm also doing the carefully rename files thing which is antithetical to why i use sonarr.

**Comment by Maxtoid** [comment]
Just plugging for this enhancement - Since the release group is an element in the database for each episode, it would be **Incredibly helpful** to be able to modify the release group at the show or season level, or add one if the name parsing wasn't able to correctly find it upon import, perhaps something similar to the mockup below?

![ModifyEpisodesMockup](https://user-images.githubusercontent.com/68936574/107713587-94f7dc80-6c99-11eb-904d-e8947d788b69.png)

**Comment by markus101** [comment]
Closing this in favour of https://github.com/Sonarr/Sonarr/issues/3811
