### ISSUE TITLE
Feature Request: Restore if database corupts 

### ISSUE THREAD

**Issue by BradleyPJ** [Sonarr/Sonarr#3340]
**Describe the problem**
Linuxserver/sonarr docker install on Windows 10 pro, if the computer is shut down without first stopping the containers the db will corrupt. 

**Describe any solutions you think might work**
I would like the option to restore/rebuild the db from backups either automatically or with a prompt.

Instead of having to delete the db - wal ect rebuild and restore backup manually dailyish.

**Comment by markus101** [comment]
Docker in Windows is not supported due to the fact DBs are hosted over SMB, which Is unreliable.

We don’t have plans to automate restoration, but v3 will restore a DB if restoration was started in the UI before the restart of Sonarr, you could probably take advantage of that. The dB to restore needs to be named `Sonarr.restore`. This is a workaround at best for a setup that is not supported.

Repair option on startup is covered here: https://github.com/Sonarr/Sonarr/issues/2134
