### ISSUE TITLE
Reanalyze media files for proper media management rename

### ISSUE THREAD

**Issue by nismanoku** [Sonarr/Sonarr#3366]
The problem is that i download an episode and have it imported to my media directory. The file is the gets a new filename, with audiolanguage and subtitlelanguage tags, as set in sonarr, this works good. But then i noticed that some episodes have their language tags not set so the episode file is named incorrectly because the language tags where missing from the original file (mkv). So i manually update the tags of the file to the proper ones. But then i have no way to have sonarr reanalyze the file and rename it with the proper language tags.

Would like to see a button to manually reanalyze a file and to rename it with the reanalyzed tags. Down under a sample.

* Animal Kingdom (2016) S04E01 AMZN 1080P Web-DL EAC3 5.1 h264 [NL] -NTb

Changed the audio tags to proper language as it was not set. and press button in sonarr ;) to reanalyze and rename and voila the result down under.

* Animal Kingdom (2016) S04E01 AMZN 1080P Web-DL EAC3 5.1 **[EN]** h264 [NL] -NTb

Now i rename them manually, but sometimes there are a lot and i batch tag them and reimport a season or complete tv-show so they get reanalyzed and named properly. 

By the way love the prefer name tags have AMZN automatically set with it as you can see in the sample.

**Comment by markus101** [comment]
I don't see the problem. The audio language tags come from the media info, not the file name. If there is a new file name Sonarr will re-analyze it unless you have `Analyse video files` disabled.

**Comment by nismanoku** [comment]
I change the audio language tags of the file manually (batch) then i have to manually edit or reimport the file for the language tags to be updated or manually change filename, because i can't reanalyse the file in sonarr if the filename doesn't change. Rescan & Refresh doesn't update media info of the file. Would be handy to have a option to reanalyse a file so the renamer of sonarr can set the updated media info tags of the file to the filename automatic without having to change filename manually or to have the file reimported.

**Comment by markus101** [comment]
> I change the audio language tags of the file manually 

Changed them how?

**Comment by nismanoku** [comment]
I use mkvpropedit to batch multiple and mkvtoolnix for single files

**Comment by nickp85** [comment]
I would like to see this implemented.  My use case is that I use a docker container called Tdarr to analyze my library and automatically convert anything h264 to h265.  The container automatically puts the new file back in the same source location with the same file name so nothing appears to be touched.  Sonarr refuses to see the new file unless I remove the series and re-add it.  This is especially troublesome because I use the renamer to apply the video codec to the file name so it also doesn't see the file changes for rename.  I would like to have a way to manually force a scan that will pick up these changes without removing and re-adding the series.

**Comment by ragmanii** [comment]
@nick Currently I am manually moving all the files from the season directories to the "root" of the show then clicking re-scan. This forces sonarr to FULLY rescan the files, then I can "rename" them back into the season folders with the x265 tag. Still, when I manually click to rescan I wish sonarr would FULLY rescan rather than just looking for files with a different name.

**Comment by cbrherms** [comment]
I am also re-encoding my library to x265 and would love a rescan media info button.
Believe this would be more ideal so that we could retain file history within Sonarr. Removing then re-adding would lose this

**Comment by jeff47** [comment]
> @nick Currently I am manually moving all the files from the season directories to the "root" of the show then clicking re-scan. This forces sonarr to FULLY rescan the files, then I can "rename" them back into the season folders with the x265 tag. Still, when I manually click to rescan I wish sonarr would FULLY rescan rather than just looking for files with 

Good idea, although this isn't as smooth if you have the "unmonitor upon delete" option checked.

**Comment by jeff47** [comment]
Totally agree.  There should either be an option to analyze when rescanning, or have analysis linked to file size or modification time instead of filename.  It really messes up my workflow to have to change the name to get Sonarr to analyze it again.

**Comment by yekul** [comment]
Just to provide a more concise update on this Sonarr issue. I am using Sickbeard MP4 Automator to encode my files as they're being imported. Works great. The problem is, for my particular use case I need to do the encoding part after the file has been moved to it's final folder location. 

So what happens is Sonarr imports the file, then the script does it's job (which in my case is converting any x264 files to x265, as well as standardising audio for my devices) and informs Sonarr to do a RenameSeries command. However Sonarr sees no file name changes and so will not do a rename command. My current file name structure has the codec listed in it, for a bunch of reasons but the main one being it lets Plex users easily choose what is compatible for them[1]. 

[1] For some reason on various pieces of hardware Plex thinks it can decode HEVC but it cannot (or it thinks it can't, but it actually can which is equally annoying), resulting in transcoding happening even when there's a perfectly viable alternative to use; as an example of why this is useful. Given the HEVC/x265 files are ~30% the file size it's a big deal for remote users.

**Comment by modem7** [comment]
> I would like to see this implemented. My use case is that I use a docker container called Tdarr to analyze my library and automatically convert anything h264 to h265. The container automatically puts the new file back in the same source location with the same file name so nothing appears to be touched. Sonarr refuses to see the new file unless I remove the series and re-add it. This is especially troublesome because I use the renamer to apply the video codec to the file name so it also doesn't see the file changes for rename. I would like to have a way to manually force a scan that will pick up these changes without removing and re-adding the series.

This is exactly my issue. I've processed just under 6000 files, but Sonarr hasn't picked up the changes, which I suspect may also affect how searches for episode upgrades are done.

**Comment by bakerboy448** [comment]
Please don't comment unless you have something constructive to add.

comments such as me too or I want this are not productive.

additionally, I don't believe additional use cases are needed; it's pretty clear

**Comment by salomj** [comment]
I would like to say that this does break downstream services like Plex and Bazarr and forces workarounds on those services to be used. Plex, you need to manually re-analyze each file, and Bazarr you need to manually run `Scan Disk` on each file. I was wondering if there was a good workaround that worked with Sonarr that anyone was aware of, because the workarounds in Bazarr and Plex are very tedious.

**Comment by bakerboy448** [comment]
Workaround is to modify the file name on disk and then trigger a refresh/rescan.

this should only be an issue with Bazarr

Plex watches the files on disk; unless you disabled that or have a niche configuration where that is not supported, but that is not a discussion for here.
