### ISSUE TITLE
Option to disable Scene Numbering on Indexer/Series/Quality

### ISSUE THREAD

**Issue by lps-rocks** [Sonarr/Sonarr#3385]
### What problem are you looking to solve?

Currently there is no way to disable scene numbering when using specific indexers or series or quality types. Web-DL/WebRip qualities tend to come from P2P release groups which do not follow scene episode numbering. This creates massive problems for series where the scene has screwed the numbering up beyond belief (*cough* American Dad *cough*) 

Adding an option to disable scene numbering for specific indexers, series, or quality types would make it easier to interchange as the scene is quickly becoming outdated and obsolete.

**Comment by lps-rocks** [comment]
The interesting part is that most of the code necessary to make this work already exists... The options just aren't exposed and the logic over setting UseSceneNumbering is purely left up to the XemFixtureService..

**Comment by markus101** [comment]
Ultimately we don’t want this to be turned on or off. That isn’t really a decision people should need to make and for every person that wants to there are many more that don’t know or don’t care, which would lead to issues when it’s disabled for a series that needs it, or more poking to try and uncover why something unexpected was/wasn’t grabbed (and that itself can be a pain already).

This is similar to adding/removing aliases instead of having a central place for them.

The solution we want to see is for thexem or a replacement to handle this automatically, perhaps that exists as a service that link multiple TVDB orders (something that’s been mentioned for their v3 site) or it’s all done there.

We want to see this improve, but we’re not going to take a shortcut to try achieve it.

**Comment by lps-rocks** [comment]
> Ultimately we don’t want this to be turned on or off. That isn’t really a decision people should need to make and for every person that wants to there are many more that don’t know or don’t care, which would lead to issues when it’s disabled for a series that needs it, or more poking to try and uncover why something unexpected was/wasn’t grabbed (and that itself can be a pain already).

I don't see how putting an option under 'Advanced Options' to allow a user to toggle the option manually causes any of these scenarios you're talking about. 

> This is similar to adding/removing aliases instead of having a central place for them.

No, not really because there's also no global scene naming option on or off...

> The solution we want to see is for thexem or a replacement to handle this automatically, perhaps that exists as a service that link multiple TVDB orders (something that’s been mentioned for their v3 site) or it’s all done there.

Why is it thexem's responsibility to fix this? This sounds like a pass-the-buck play here. They simply supply mappings of episode numbers for where the scene failed to follow the actual season/episode number - It's actually a bandaid for a bigger problem in the first place.

> We want to see this improve, but we’re not going to take a shortcut to try achieve it.

Giving the user an option under 'Advanced Options' is not a shortcut - Especially when its a flag in the database that already exists for a given series and would just be a toggle option. 

Developers removing options simply because they don't feel like a user would ever need them is a unilateral choice for the entire ecosystem of users made by a single person. Google the exact issue I'm coming up with and many have posted about it in many different forums. This is not as isolated as you think. 

It boggles my mind that a flag that already exists in the database table for series is not going to be available to end users simply because one developer feels like end users cant handle it. Stop treating end users like idiots.

**Comment by lps-rocks** [comment]
Furthermore how many times has this been brought up before and dismissed. Here's two large piles.

- https://www.google.com/search?q=sonarr+turn+off+scene+mapping+site:forums.sonarr.tv&sa=X&ved=2ahUKEwjzpLHNmdzlAhUBLqwKHS1jD6cQrQIoBDAAegQIBRAN&biw=1920&bih=1040
- https://www.google.com/search?q=sonarr+turn+off+scene+mapping+site:www.reddit.com&sa=X&ved=2ahUKEwjzpLHNmdzlAhUBLqwKHS1jD6cQrQIoBDABegQIBhAJ&biw=1920&bih=1040

**Comment by Taloth** [comment]
We've repeatedly made the point that TheXEM needs more development capacity to implement the appropriate support for it there. This is something that the main xem moderators want too, just lack the capacity to implement.
Users love to fix stuff for themselves, instead of doing it for everyone. I assure you that if we had that mindset, Sonarr wouldn't exist.

You're welcome to propose an extension to the xem api that would allow us to properly map these scenarios, just be mindful that it's not just scene vs p2p, but also variations between p2p groups and sometimes even between scene groups, American Dad is a particular kind of [nasty](https://www.reddit.com/r/sonarr/comments/bx50h1/american_dad_messed_up_yet_again/eq7lrl6/).
It'd ultimately require work on both xem and sonarr side.
