### ISSUE TITLE
Prevent Downgrading Language during Quality Upgrade

### ISSUE THREAD

**Issue by eihns** [Sonarr/Sonarr#3394]
**Describe the problem**
Currently you can enable multiple languages and can also prefer some over the other, but sonarr will ignore the prefered language if there is a better quality in another language. I would like a option (or standard) that other languages over the prefered ONLY get chosen when there is not prefered language.

**Describe any solutions you think might work**
**Currently behaivior**

Language selection
Upgrade until Language 1

Language 1 (higher is prefered)
Language 2

_Avaible Releases:_
Release language 1 720p
Release language 2 720p
Release language 1 480p
Release language 2 1080p

It will choose Release language 2 1080p, even there is a prefered language 1 720p.

I want it this way:

Suggestion:
Take language 1 720p

I think it would be clever to make this standard behaivior, but if you dont want to do that, then atleast give us an option to make it this way.

**Comment by markus101** [comment]
We don't have plans to support language over quality at this time, but will be looking at preventing downgrades of the language in order to upgrade the quality.

**Comment by eihns** [comment]
What is the idea behind the whole language thing then?

You can prefer a language, which doesnt get prefered.

**Comment by moreje** [comment]
I would expect such a fonctionnality with languages.
If I start monitoring a TV serie, I want to download episodes as soon as they are available (in english for example).
But I also want to Sonarr upgrade the files until the optimal quality is here AND a multi language is (i.e. english + french) is available. So that, at the end, I get a madia library with the best quality & the languages I love.
so yes, I'm expecting a function like: upgrade until Multi (french / english) is downloaded

**Comment by robson90** [comment]
fyi. 

I grouped all 720p options into one 720p group. Im searching for English and German, German is the cutoff. That works perfectly in my testing, so not really necessary to implement anything !

Quality Profile is called "720p - grouped"

**Comment by eihns** [comment]
HEy, can you post a screen from neccessary changes?

**Comment by robson90** [comment]
Language Settings: 
![Bildschirmfoto 2021-02-02 um 07 57 47](https://user-images.githubusercontent.com/39960884/106563692-73298780-652c-11eb-84fd-56aef6e4e020.png)

720p example:
![Bildschirmfoto 2021-02-02 um 07 59 03](https://user-images.githubusercontent.com/39960884/106563741-89374800-652c-11eb-96f6-3f42f7bb008f.png)

It is only working, when the quality that is existent, and you have found are equally. Not working for 720p English vs 480p German.

Wie du richtig erkannt hast, geht es nur bei gleicher Qualität. Ich hab es gestern bei Badwomen probiert ohne Probleme. Supernatural genauso. Vorher hab ich die Serie in Englisch 720p laden lassen und wenn sie komplette war einfach auf Deutsch 1080p gestellt. Ne richtige Lösung wäre natürlich geil, aber wenn das Ticket schon von der Grundidee abgelehnt wird, brauchst du auch keinen PR stellen, weil er eh abgelehnt wird.

Falls du noch Hilfe brauchst oder Fragen hast, schreib mir ne PM. Man könnte auch mal Indexer abgleichen, vllt würde das bei dir helfen.

**Comment by eihns** [comment]
We dont use sonarr to have a manual solution. It cant be that hard to make an option (or default) prio language over quality.

Die Variante ist wie ich es hatte, mittlerweile ist es nicht mehr so das er deutsch löscht um besseres englisch zu laden (theoretisch, wobei ich mir da nicht sicher bin). Schreib dir wegen den Indexern.

@markus101 any news on this? We have a auto prio system, cant we just artifically add +1000 score to selected german if we [ X ] prio language over quality (i dont understand whats so complicated about that)

**Comment by DjRicko** [comment]
This would be really nice to have actually.
I prefer to have some animated series in danish, but if the episode is not available in danish, it should just grab the english one.
If my target is set to 1080p, i want it to download a 480p danish one over 1080p english, as language should be priority.

**Comment by eihns** [comment]
they dont understand or dont care

**Comment by rubasace** [comment]
I've run into the exact same issue. Current behaviour makes it impossible to prioritize Dual (English + Spanish) over quality which I would say sounds like a very sensible requirement

**Comment by rubasace** [comment]
What about giving an arbitrary priority to quality so, at least, we can add a hardcoded value to hack the behaviour via the preferred words; If, let's say, quality is a +10, it's up to users to add higher values for the languages on the preferred words section. That would, at least, provide us some mechanism to automate our downloads

**Comment by eihns** [comment]
i cant understand whats the problem is.

**Comment by bakerboy448** [comment]
Folks - Markus was rather clear in his comment.  Repeatedly asking for or `me too`ing an issue is simply noise.

> [We don't have plans to support language over quality at this time](https://github.com/Sonarr/Sonarr/issues/3394#issuecomment-556944433)

There's 1 item to do from this GHI:
 - preventing downgrades of the language in order to upgrade the quality.


If you want a workaround then group all your qualities together and handle quality preferences as preferred words.  This would effectively remove quality from the equation as they'd all be equal.
https://wiki.servarr.com/sonarr/faq#how-are-possible-downloads-compared

**Comment by eihns** [comment]
> Folks - Markus was rather clear in his comment; that decision has not changed.
> Repeatedly asking for this or `me too`ing an issue is simply noise and unproductive.
> 
> > [We don't have plans to support language over quality at this time](https://github.com/Sonarr/Sonarr/issues/3394#issuecomment-556944433)
> 
> There's 1 item to do from this GHI:
> 
> * preventing downgrades of the language in order to upgrade the quality.
> 
> If you want a workaround then group all your qualities together and handle quality preferences as preferred words. This would effectively remove quality from the equation as they'd all be equal.
> https://wiki.servarr.com/sonarr/faq#how-are-possible-downloads-compared

Hi,
if there is really a working solution... could you please ellobrate it a little bit more and maybe show how to do it? maybe some screenshots?

**Comment by bakerboy448** [comment]
> if there is really a working solution... could you please ellobrate it a little bit more and maybe show how to do it? maybe some screenshots?

Not sure how well it works, but it does exist.

It was previously pictured here, which is just editing the groups: https://github.com/Sonarr/Sonarr/issues/3394#issuecomment-771416439

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for further discussion on this / for support/questions.
You may also check out the [wiki](https://wiki.servarr.com/sonarr)

**Comment by eihns** [comment]
that simply does not work.

**Comment by rubasace** [comment]
@bakerboy448 @markus101 I understand metooing isn't the solution but please also understand that you guys are kinda only focused on the use case for English speakers. It has been the same with Sonarr v2 and I ended up having to recompile a forked version of Sonarr so it could search for different languages properly (there was even a PR lying around that never got merged because it was being fixed in v3).

This is not a support request, this is a feature request that has been demanded many times. The decision you guys have made about quality over language makes no difference for anyone with only one language and it simply doesn't work for users with multiple ones: if you only have one language (i.e. English speakers) it won't matter if language comes first in the comparison as there's nothing to compare. On the other hand, if you have multiple languages, it makes sense that you prefer the cutoff ones over the rest. This would automatically implement the "Prevent downgrading language during quality upgrade" just by changing the order on the list of decisions you are applying. 

It's worth mentioning that the prevention mechanisms on their own won't solve much either as, for the first automated download, the highest quality language will be picked up, potentially never grabbing a release on the preferred language, so there wouldn't be any language downgrading.

In addition, the proposed workaround with quality groups is flaky, hacky, and it doesn't seem to work for all cases as using preferred words for quality selection is very verbose and seems error-prone (Sonarr has quite some logic to get that right). 

All we are asking is for a mechanism of inverting the order of these two lines: https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/DecisionEngine/DownloadDecisionComparer.cs#L31-L32

I'm even happy with an if on an environment variable or any other hacky way that saves me from having to recompile that class and replace it the hard way.

**Comment by markus101** [comment]
This should be achievable with Custom Formats.
