### ISSUE TITLE
Sonarr becomes unresponsive while doing a disk scan on a FUSE mount

### ISSUE THREAD

**Issue by Makeshift** [Sonarr/Sonarr#3397]
**Describe the bug**
While Sonarr is doing a disk scan on my Rclone FUSE mount, it becomes completely unresponsive and can no longer keep up with any of its jobs (UI won't load, API won't respond, won't move files, can't keep up with downloaded files etc.). The disk scan takes a very long time(8+ hours), leaving me little-to-no time to actually do things in the Sonarr UI unless I restart it to kill the scan.

This has been an issue for ~2 years, but the size of my library is now getting to the point where Sonarr is now almost constantly scanning. However, I don't really understand why the scan takes so long with media analysis disabled. 

**Logs**
I let this trace run while I was writing this issue.
Trace: https://gist.github.com/Makeshift/626bf695f07b58e2679f9de5705cb799
**System Information**

 - Sonarr Version: 3.0.3.654-ls149 (Linuxserver.io container)
 - Operating System:  Host: Ubuntu 18.04 x64, Container: linuxserver/sonarr:preview
 - Mono 5.20.1.34

**Additional context**
These containers run on a 32 core VM with 32GB RAM, all on RAID 0 SSD.
I have a folder called '/shared/merged' mounted to the container, which is a FUSE mount containing merged downloads and media folders (in order to speed up file system moves).

This mount is provided by Rclone with the following config:
```
[union]
type = union
remotes = plexdrive: /shared/separate encryptedgdrive:

[plexdrive]
type = crypt
remote = /plexdrive/encrypted
workers = 16
filename_encryption = standard
directory_name_encryption = true
password = <snip>
password2 = <snip>

[gdrive]
type = drive
scope = drive
workers = 32
root_folder_id = 
service_account_file = /credentials.json
token = <snip>
use_trash = true
chunk_size = 512M
acknowledge_abuse = true
pacer_min_sleep = 1
pacer_burst = 5000

[gcache]
type = cache
info_age = 48h
chunk_total_size = 10G
remote = gdrive:/encrypted
acknowledge_abuse = true
workers = 32
tmp_upload_path = /shared/caches/tmp_upload_path/
db_path = /shared/caches/db_path/
chunk_path = /shared/disk_caches/chunk_path/
cache_dir = /shared/caches/vfs/
db_purge = true

[encryptedgdrive]
type = crypt
remote = gcache:/
workers = 64
filename_encryption = standard
directory_name_encryption = true
password = <snip>
password2 = <snip>
```

I've tried dozens of different configurations for this over the past ~2 years and so far this is the fastest and most stable, but the disk scan issue remains. 
I am not being throttled by GDrive, nor is rclone using much CPU during the scans. 
Sonarr performs great when not disk-scanning and just handling downloads and moves, but it completely dies when doing a disk scan.
I have a gigabit up/down internet connection, and have had my limits on Google drive increased, so there are no bottlenecks there. CPU and RAM usage remain quite low during all of this, 

There is approximately 975 series in /Media/TV, so the library Sonarr is scanning definitely isn't small. Sonarr's DB is ~92mb. I can move this into memory if you think the SSD's aren't fast enough for this.

In the log you can see I tried to load the web UI at 18:04:41. As of 18:40 it's still loading with the ripple loading indicator. There are extremely large gaps between things happening in the trace log, plus quite a few complaints about the DB being locked.

Please let me know if there's any more information I can give, I'd love to know that I'm doing something stupid and this is an easy fix :)

**Comment by Taloth** [comment]
I've seen collections of 2000+ or even more series, that is not a problem.

One of the biggest question marks regarding your log is: Why are you generated RoksboxMetadata, WdtvMetadata and XbmcMetadata? That hardly seems useful.
Disable that immediately, all of them, and then evaluate performance. You can enable one of them again later if desired but having them all put serious load on your cloud storage since Sonarr has to create and update those metadata files.

Next is https://gist.github.com/Makeshift/626bf695f07b58e2679f9de5705cb799#file-sonarr-trace-txt-L126-L132
Time going backward and jumping around? It almost looks like two sonarr containers with different clocks logging to the same directory.

I also see delays of 30+ seconds doing nothing, the log isn't particularly clear on what Sonarr is doing/waiting for at those times, but you might want to analyse those events and see if there's a common factor.
Take this one for example: https://gist.github.com/Makeshift/626bf695f07b58e2679f9de5705cb799#file-sonarr-trace-txt-L646-L647
There's very little in terms of code between those two log lines.

Finally, the database errors combined with the weird log time stamps make me suspect that the storage of those two isn't really locally directly on the raid0 ssd, but rather with the unionfs between. I'm not sure but there's definitely weirdness going on there.

**Comment by Makeshift** [comment]
The reason I was running all of the metadata is purely because I like to have as many options as possible available when scraping for data. I'll disable them for now though if they might be related.

There is definitely only one Sonarr container, and the directory isn't shared. I noticed the time jumps as well and it's incredibly weird. I haven't noticed that in previous setups, but nor was I specifically looking for it.
```
connor@media [/data/ssd/media2/sonarr] 0 $ docker ps | grep sonarr
26fa7a8879f4        linuxserver/sonarr:preview   "/init"                  23 hours ago        Up 23 hours
                media2_sonarr_1

sonarr:
    volumes:
      - ./sonarr/:/config
      - ./shared/:/shared:rshared
```

I couldn't see a reasonable reason for the delays either, which is my main reason for posting. I'll see if I can scrape the log to see if there's anything specific happening around those times.

Sonarr's folder is definitely separate from the unionfs. All of my config is in `/data/ssd/media2/sonarr` and the unionfs only exists within `/data/ssd/media2/shared/merged`. I get very good speeds from Sonarr's config directory:
```
connor@media [/data/ssd/media2/sonarr] 0 $ sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.96345 s, 547 MB/s
connor@media [/data/ssd/media2/sonarr] 0 $ sudo sysctl -w vm.drop_caches=3
connor@media [/data/ssd/media2/sonarr] 0 $ dd if=tempfile of=/dev/null bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 2.23616 s, 480 MB/s
```

Medusa, Jellyfin and Plex handle scanning without an issue. Radarr has similar issues, but due to the vastly lower number of movies compared to episodes it's not as noticeable. (Note that I'm not running all of these at the same time - I'm trying to sandbox Sonarr for these experiments.)

If I could figure out exactly which piece is being slow then I could try to address it, but I haven't got a clue! I've disabled metadata for the moment, and if that does fix it then I'll definitely be kicking myself.

**Comment by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [comment]
"isolated" processes in containers compete for CPU, RAM, disk, network etc. - and **kernel** resources. So this might be collisions in kernel space. Might be worth to check with perf / replicate the environment on a dedicated kernel.

**Comment by Makeshift** [comment]
So @Taloth I think you may have nailed it. I just did a complete scan in ~20 minutes and everything remained usable the whole time. I never thought the metadata would be causing that much of an issue.

The initial scan was very slow, by the looks of it Sonarr was removing the metadata from its DB. After that though, it's lightning-fast.

I'll give it another half a day or so to make sure the automated disk scan goes alright, then I'll close this issue.

Thanks!

**Comment by Taloth** [comment]
I think improvements can be made, but we need to find out which parts are slow with updating. Normally it isn't a problem that Sonarr reads back the existing kodi/xbmc metadata file to update it's contents, but for cloud storage it's an issue. I think we might mitigate that by storing the previous file hash in our database and compare it with that. Something we can think about.
The images/posters aren't updated if they already exist, so that's not a problem.

I'm still concerned with the jumping timestamps etc. So keep an eye on that and check the logs in a bit to see if it's stable.

**Comment by markus101** [comment]
@Taloth are we wanting to update this GHI to something we’re going to look at or close it?

**Comment by markus101** [comment]
Closing, we can re-open if need be.
