### ISSUE TITLE
Empty seasons when adding series

### ISSUE THREAD

**Issue by dippynark** [Sonarr/Sonarr#3424]
**Describe the bug**
I add a series (in this case Misfits) in the normal way

Series -> Add Series -> 'type Misfits' -> Add

But when I view the series, the seasons are listed but are all empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/28210877/69501351-07956480-0efc-11ea-9175-88693c285467.png)

**Logs**
Debug logs do not seem to show anything strange
```
[Debug] Api: [GET] /api/diskspace: 200.OK (41952 ms)
[Info] AddSeriesService: Adding Series [124051][Misfits] Path: [/tv/Misfits]
[Debug] Api: [POST] /api/series: 201.Created (1847 ms)
[Debug] Api: [GET] /api/Episode?seriesId=212: 200.OK (53 ms)
[Warn] MediaCoverMapper: File /config/MediaCover/216/poster.jpg not found
[Debug] Api: [GET] /api/Episode?seriesId=212: 200.OK (1 ms)
[Debug] Api: [GET] /api/Episode?seriesId=212: 200.OK (3 ms)
[Debug] Api: [GET] /api/Episode?seriesId=212: 200.OK (1 ms)
[Debug] Api: [GET] /api/Episode?seriesId=212: 200.OK (1 ms)
[Debug] Api: [GET] /api/Episode?seriesId=212: 200.OK (1 ms)
[Debug] Api: [GET] /api/Episode?seriesId=212: 200.OK (1 ms)
[Debug] Api: [GET] /api/Episode?seriesId=212: 200.OK (4 ms)
```

**System Information**

 - Sonarr Version: `10.0.0.35054`
 - Operating System: `Linux`
 - Mono Version: `5.20.1.34`

**UI Bugs:**
 - OS: `OS X`
 - Browser: `chrome`
 - Version: `78.0.3904.108 (Official Build) (64-bit)`

**Additional context**
This problem is not unique to Misfits - `Defending The Guilty` gives the same issue for me for example.

**Comment by markus101** [comment]
I don’t see issues with either of those series in v2 or v3.

Your logs don’t show the series info being refreshed after the series was added, perhaps due to the task queue not yet executing it.

Check System: Tasks to see if scheduled take are not running. Restarting Sonarr may be required. If it happens again look at the trace logs.

> Sonarr Version: 10.0.0.35054

This indicates it is not an official Sonarr build and not something we provide support for.
