### ISSUE TITLE
Use of curly brackets {} as text in filename templates does not work

### ISSUE THREAD

**Issue by pjaclark** [Sonarr/Sonarr#3434]
### System Information/Logs

**Sonarr Version:** 3.0.3.659

**Operating System:** Windows 10 Pro

**.net Framework (Windows) or mono (macOS/Linux) Version:** 4.0.30319.42000

**Link to Log Files (debug or trace):** n/a

**Browser (for UI bugs):** n/a

### Additional Information

On `/settings/mediamanagement`, enter a value for `Standard Episode Format` of `{Series Title} - S{season:00}E{episode:00} - {Episode Title} {{Quality Title}}`. The preview will show `Single Episode: The Series Title! - S01E01 - Episode Title (1)` and not `Single Episode: The Series Title! - S01E01 - Episode Title (1) {HDTV-720p}`. Renaming and importing files do not show the quality title. 

This works under Sonarr v2.

**Comment by markus101** [comment]
This is due to the new support for episode title truncation, but the result is a bit spotty (`{{Quality Full}}` is working, but `{{Quality Title}}` is not).

@Taloth currently we replace unknown tokens with nothing, though in this case we're replacing the unknown token with itself and losing the extra braces.

Given the awkward support we need to fix things here regardless, but have some options I think:

- When we find an unknown token don't replace it at all, that means if someone tried to use `{Episode TitleReversed}` that would become part of the filename, instead of being replaced and disappearing

- Acknowledge that we don't support wrapping in `{}` and ensure we're properly handling it in all cases

I'm leaning more towards allowing unknown tokens to persist, as it allows for this scenario as well as makes it much more obvious when a token isn't supported (instead of disappearing like a token that resolves to nothing would).

**Comment by Taloth** [comment]
What he really needs is escape characters, so the example should be `{{{Quality Title}}}`, where `{{` gets turned into `{`.
Also, the validation should explicitly reject formats with unknown tokens, so should stray `{` and `}`.

**Comment by markus101** [comment]
If we ever changed the process to do all the replacements in a single pass that'd result in `{{HDTV-720p}}` in the file name though.

`{{{Quality Full}}}` currently results in `{{HDTV-720p Proper}}`

**Comment by Taloth** [comment]
No, i'm not saying that it's a workaround, I'm suggesting to change the code to actually support the escape sequence explicitly.

**Comment by markus101** [comment]
`{{` is how string.Format handles it, no need for a third brace. `string.Format("Hello {{0}}", "Taloth");` results in `Hello {Taloth}`, which makes sense here too, we just need to not nuke unknown tokens the second time around.

**Comment by Taloth** [comment]
`{{` is for the literal `{`, the last `{` is for the start of the actual token, eg `string.Format("Hello {{{0}}}", "hi")` becomes `"{hi}"`.
