### ISSUE TITLE
Series runtime is 0

### ISSUE THREAD

**Issue by BodingClockchian** [Sonarr/Sonarr#3468]
**Describe the bug**
Sonarr is rejected a release because of the following status:
Series runtime is 0, unable to validate size until it is available

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/28387829/71284149-5d75f480-2362-11ea-9a23-c6581ab6a3a4.png)

**Logs**
Series runtime is 0, unable to validate size until it is available
No more logging info with debug mode on

**System Information**
- Sonarr version: 3.0.3.668-ls158 by linuxserver.io   
- Mono Version: 5.20.1.34
- Operating System: Ubuntu 18
- .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**UI Bugs:**
 - OS: Windows
 - Browser: Firefox
 - Version: Latest

**Comment by markus101** [comment]
Not a bug, the series information coming from the TVDB doesn’t have a runtime, one will need to be set there.

**Comment by markus101** [comment]
Not a bug, the series information coming from the TVDB doesn’t have a runtime, one will need to be set there.

**Comment by mafeu102** [comment]
would be nice if sonarr could assume a default runtime if none is set (45 minutes for example) instead of just forcing manual grabs for the whole series.

**Comment by bcsteeve** [comment]
OK, so I'm confused.  Ran into the same problem with Game of Thrones.  Saw this post so I check TVDB and there are runtimes listed.  I tried refreshing the series. I tried removing and re-adding it.  All seasons, all episodes I get this same Series runtime is 0 thing.

**Comment by digitalface** [comment]
I am having the exact same error with the exact same series (GoT)

**Comment by RhinoRhys** [comment]
@markus101 How does sonarr deal with series that have multiple runtimes listed on TVDB? I'm having this issue with History 101, someone on reddit is having this issue with This Is Us and the two above with Game of Thrones. The only similarities between these shows I can see is that multiple episode lengths are listed. This Is Us hasn't been updated in nearly a month on TVDB which rules out API propagation delays.

**Comment by markus101** [comment]
To Sonarr there aren't multiple runtimes. Only one runtime for the series is exposed from TVDB's API. They seem to return the most common runtime, but it's completely out of our control.

**Comment by bcsteeve** [comment]
Is it though?  When you depend on external data, your software should handle exceptions.  Could you not inform the user that poor data is returned and give then an opportunity to input a manual number?  Or just use some sensible default if zero causes a problem.  Is series runtime really so critical?  Obviously accuracy isn't paramount if we're looking for a series average that would rarely coincide with any given episode runtime, right? 

Surely there is a Sonarr solution for what is perceived to be a TVDB problem.

**Comment by markus101** [comment]
> Is series runtime really so critical? 

It is for size limits, there is no other way to limit it.

> Obviously accuracy isn't paramount if we're looking for a series average that would rarely coincide with any given episode runtime, right?

An average of what? Just guess at how long a series could be? Based on what? If we assume it's 60 minutes long, but it's actually 30 minutes long then file sizes could be 2x what you expect. Or if we assume it's 30 minutes we start filtering out valid releases because the size limits are too restrictive.

This isn't a perceived TVDB problem, this _is_ a TVDB problem, they're not reporting any runtime for the series, but they have that data for the episodes. Even better they could start returning the runtime for the episodes and we wouldn't have to do things like double the allowed size for premieres and finales.

**Comment by RhinoRhys** [comment]
That's a bummer. If their API is throwing out inconsist data to what's on the webpage, it would be pretty sweet to have an "if 0 ask" input popup, even if it only applies to a manually triggered search and not a saved value for RSS.

**Comment by bcsteeve** [comment]
Ok fine, TVDB sucks.  So?  Your software depends on crappy data then.  The software needs to handle that, no?  What good does it do to blame something we can't change?  

As you said, it is a series figure that you're going by, yes?  CLEARLY that can rarely be accurate to the episode level.  So for all series, you're more or less guessing as it is.  So yes!  If the data isn't there, take a reasonable guess... or simply ask the user.  It doesn't make sense to halt all downloads because an external source erroneously fails to provide the data you want in the format you want it.

What about utilizing your own user base?  I would trust the community to provide corrections for when TVDB drops the ball.

I get your frustration.  Over the years, the arrogance of the TVDB admin on the forums has been shocking.  Simple (and logical) suggestions for improvement get berated constantly.  You can't actually contribute because everything is locked.  But I'm assuming it works most of the time or you wouldn't use it.  I'm just suggesting that you add some error handling, of sorts, for the robustness of your software for cases like these.

**Comment by markus101** [comment]
> What good does it do to blame something we can't change?

It’s not blaming them, it’s explaining where the issue lies, so that it can be reported and fixed (regardless of your opinions of the mods, complaining here on a closed issue doesn’t fix the root of the problem).

> CLEARLY that can rarely be accurate to the episode level.

That’s nonsense, what are you basing this thought on? Outside of specials and the odd double episode it’s accurate for _most_ series.

> If the data isn't there, take a reasonable guess... or simply ask the user.

Do we just throw a dart at the board or use a random number generator? Blindly guessing doesn’t make sense, that’s not a solution.

> What about utilizing your own user base? I would trust the community to provide corrections for when TVDB drops the ball.

99 times out of 100, runtime of zero means TVDB does not have runtimes set or the API hasn’t updated, in those cases the solution is to fix TVDB and wait, we’re not going to maintain a TVDB clone where users can go tweak things. In the case of GoT we can override TVDB in Skyhook to fix it.

In the future if this issue arises again, open a thread on the forums, please don’t comment on old, closed issues, they will go unnoticed more often than not.

**Comment by bcsteeve** [comment]
> That’s nonsense, what are you basing this thought on? Outside of specials and the odd double episode it’s accurate for most series.

Maybe its just the type of shows I watch?  Game of Thrones, Vikings, Community and Tiger King are four I just looked up quickly.  3 out of the 4 have variable runtimes.

> In the case of GoT we can override TVDB in Skyhook to fix it.

There you go.  So there is a solution?  That's great!  I don't know what Skyhook is.  GoT isn't exactly a recent series nor is it remotely unpopular, so why wasn't this done?  Don't take that as me expecting you to have done it... I'm just finding it unbelievable that a community as large as Sonarr's and a show as popular as GoT ends up with lowly me watching it late running into a problem at this point.  Or is it that TVDB just recently screwed up the data for this show?

> In the future if this issue arises again, open a thread on the forums, please don’t comment on old, closed issues, they will go unnoticed more often than not.

Forgive me.  When there are multiple support avenues, you have to expect they'll get used.  I'm not that active and I only Googled when this particular problem came up and I didn't find a solution.  I typically try to find the answer myself because, as eluded above, I'm usually late to the game and there are usually answers to any problems I find.  Google brought me here, and there was no apparent resolution yet it seemed to be a live issue.

Thanks for your time.  I won't bug you again on this.

**Comment by digitalface** [comment]
As far as I understand it Skyhook is an intermediary between Sonarr and TVDB that the Sonarr devs have control of, so I guess they can intercept and manipulate the data there. Either way GoT works now 😁

**Comment by majorgiant** [comment]
I have the exact same issue with The Expanse right now.

**Comment by mptpro** [comment]
I'm having the same problem.  Is there a way to instruct Sonaar to ingore the size and just dowload it anyway?

Perhaps even have this setting per-series?

**Comment by Jas0n99** [comment]
> I'm having the same problem. Is there a way to instruct Sonaar to ingore the size and just dowload it anyway?

Caveat Emptor:  If you set your sizes (Settings -> Quality) to unlimited (0 min / 400 max), it will ignore the file size / runtime issue and download.
