### ISSUE TITLE
Preferred Word Specification compares new release title vs old file name

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#3488]
**Describe the bug**
PreferredWord comparison compares the new release title vs the filename of the existing file. This means that it might actually consider the same release as an upgrade if the release title contains a preferred keyword, but the matching file does not.

This is readily apparent for season packs where the pack release title matches scene format, but the files are simplified.
eg. `Party.S01.DVDRip.AAC2.0.x264-ABC`
with `Party - S01E01 - Pilot (DVD).mkv`
where -ABC is the preferred word +50.

This issue is exacerbated by the fact that a manual (series) search disables the HistorySpecification that would normally block the same release from being downloaded again. So the same pack gets downloaded repeatedly.

**System Information**

 - Sonarr Version: 3.0.3.679
 - Operating System: Linux
 - .net Framework (Windows) or mono (macOS/Linux) Version: 6.6.0.161

**Comment by cptv** [comment]
This issue also presents itself if you have Sabnzbd replace periods with spaces. I set `.it.` (for iTunes releases) as a preferred word. It successfully grabs them, however since my Sabznbd replaces the periods with spaces, Sonarr does not detect the preferred word in the end filename and will later attempt to replace the file with the same exact release. A very minor inconvenience in my case but thought I'd share the relevant
