### ISSUE TITLE
Multi-language and sub language releases

### ISSUE THREAD

**Issue by samip5** [Sonarr/Sonarr#3497]
**Describe the bug**
Releases that have "Nordic" in the tittle are incorrectly marked as Norwegian for language.

**Screenshots**
The releases are tagged as Norwegian even when it's not.
![image](https://user-images.githubusercontent.com/1703002/71948777-d89c2f00-31d9-11ea-9705-34121db0b962.png)

The release page on Nordicbits:
![image](https://user-images.githubusercontent.com/1703002/71948811-008b9280-31da-11ea-877b-3439521c0c0d.png)

**System Information**

 - Sonarr Version: 3.0.3.687
 - Operating System: Docker container, powered by Linuxserver.io (Package Version
3.0.3.687-ls166 by linuxserver.io)
 - Mono Version: 5.20.1.34

**Additional context**
This can be seen here https://github.com/Sonarr/Sonarr/blob/d45d9e356c563c3851d8a47a02c6fc21af44f32f/src/NzbDrone.Core/Parser/LanguageParser.cs#L81-L82 where @Taloth has specified that it's Norwegian even if that's incorrect.

Nordic can be any language from: Finnish, Norwegian, Swedish, Danish or even English. Most of the time it only means Nordic subtitles are included.

**Comment by diblaze** [comment]
I guess it is made like this because "Nordic" does not exist as a language in Sonarr v3 (obviously it shouldn't). 

Maybe Sonarr V3 should be able to work with languages in arrays, where "nordic" will return all of the Scandinavian languages and allow shows to match within this array? So if a show has the language set to Swedish, and the scraper finds a "nordic" release, then it should assume it has Swedish in it.

Workaround:
Set all nordic shows to Norwegian. Create a Release Profile that prefers/contains the tag "nordic". 
Use the release profile on all nordic shows, and it will download nordic content.

**Comment by markus101** [comment]
There are two things here, one is being able to support multiple languages, instead of just one. The other is common sub-only languages getting treated as the audio language, which happens for things like VOSTFR as well.

The former issue would need to be solved for https://github.com/Sonarr/Sonarr/issues/2854 as well.
