### ISSUE TITLE
Anime fails to import

### ISSUE THREAD

**Issue by WildOrangutan** [Sonarr/Sonarr#3552]
## Describe the bug
When anime is downloaded, it sometimes isn't correctly imported, or imported at all. Sometimes it's imported as a different episode entirely. Other times, not imported at all.

Can happen when it's downloaded automatically or manually triggering download search.

## Example
Trying to download Sword Art Online S04E11.

First, it episode was monitored, and sonnar automatically tried to download it. It was downloaded twice, once on tuesday and once on thursday. Was not imported. Btw, seems like episode name was correctly determined (`Sword Art Online - 4x11 - Heartless Choice [HDTV-1080p]`).

Today I manually downloaded it again, by triggering search button. Same thing. Fails to import.

I then proceed and try "manual file import". Import succeeded. 
At this point I notice E10 goes missing. Not sure if it was on disk before, or if that was a result from invalid E11 import or correctly downloaded E10.

I've downloaded quite a lot of anime in the past, but this is first time I've encountered this kind of problem.
Also note, that I've had similar problems somewhere around E05. After that it magically started working again, and I've been able to download up to E11.
Episode was especially weird, since it managed to get imported with different season and episode name.

### Logs from manual download and import from today
- [sonar.txt](https://github.com/Sonarr/Sonarr/files/4140910/sonar.txt) 
- [sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4140911/sonarr.debug.txt)

Timestamps:
- 18:09 - Manual download of E11 triggered
- 18:26 - Episode download finished
- 19:42 - Successful manual import of E11

### Logs from automatic download on thursday
- [sonarr.debug.8.txt](https://github.com/Sonarr/Sonarr/files/4140981/sonarr.debug.8.txt)
- [sonarr.debug.9.txt](https://github.com/Sonarr/Sonarr/files/4140978/sonarr.debug.9.txt)
- [sonarr.debug.10.txt](https://github.com/Sonarr/Sonarr/files/4140979/sonarr.debug.10.txt)
- [sonarr.debug.11.txt](https://github.com/Sonarr/Sonarr/files/4140980/sonarr.debug.11.txt)

Timestamps: 
- 22:59 - Received notification that episode was grabbed

## System Information

 - Sonarr Version: 3.0.3.688
 - Operating System: 4.19.97-1-ARCH
 - Mono version: 6.4.0

**Comment by markus101** [comment]
Sword Art Online has been having a lot of data issues from TheTVDB recently. I believe the issue was episodes getting different absolute episode numbers, which will affect which episodes are linked to which files since episodes are linked by absolute episode number for anime.

> Was not imported.

If Sonarr has already grabbed an imported a release it won't import it again. Based on the logs I don't see Sonarr attempting to import the file again, but see it marking it as imported and asking your download client to remove it.

Based on the information here and knowing there have been some issues recently with that series I don't see anything actionable on our side here. If you remove the series from Sonarr and re-add you'll clear the import history and likely be able to correct the outstanding issues, otherwise manually grabbing outside of Sonarr and importing.
