### ISSUE TITLE
Keyboard Shortcuts for Season/Episode Entry

### ISSUE THREAD

**Issue by owine** [Sonarr/Sonarr#3585]
When manually importing an episode it would be great to be able to use keyboard entry for the season/episode number selection rather than selecting with the mouse each time. Especially helpful when doing a large number of manual imports.

**Comment by markus101** [comment]
It's selection because you're picking the episode, not picking the episode number so entry based on keyboard alone would be tricky and not something we're planning to do, at least at this time. In v3 batch selection is available and should help when dealing with multiple items (at least within the same season).

**Comment by owine** [comment]
Thanks for your reply. Just for the sake of clarification, the request is not to do freeform entry, but to aid in selecting from the season/episodes list as below.

<img width="526" alt="Screen Shot 2020-02-21 at 2 03 51 PM" src="https://user-images.githubusercontent.com/4283702/75067678-3303fd00-54b3-11ea-9639-3da4cc51104f.png">

In the above, press 1 on the keyboard to select Season 1.

<img width="1050" alt="Screen Shot 2020-02-21 at 2 04 10 PM" src="https://user-images.githubusercontent.com/4283702/75067683-34352a00-54b3-11ea-9d16-edcaa8712ec4.png">

In the above, press 5 on the keyboard to select Episode #5.
