### ISSUE TITLE
{MediaInfo VideoCodec} Displaying an encoder as a codec

### ISSUE THREAD

**Issue by JySzE** [Sonarr/Sonarr#3588]
`{MediaInfo VideoCodec}` - Defines H.264 and AVC video streams as the encoder "x264" where it should be the codec "H.264"

 - Sonarr Version: 2.0.0.5338 and 3.0.3.701
 - Operating System: Ubuntu 19.10
 - mono (macOS/Linux) Version: 6.8.0.96

**Comment by markus101** [comment]
That will happen if media info returns x264 for the format or the filename includes x264 instead of h264, this is expected behaviour given the commit that introduced that: https://github.com/Sonarr/Sonarr/commit/2b3956cb6003f7b050e53a7276dcb00d3215b052 in response to https://github.com/Sonarr/Sonarr/issues/2500

We don't have plans to change that or have an option for it.
