### ISSUE TITLE
`LogInaccessiblePathError` throws if mount cannot be found

### ISSUE THREAD

**Issue by HexEditHD** [Sonarr/Sonarr#3598]
**Describe the bug**
After BitTorrent finishes downloading an episode/season it drops in the completed folder. Sonarr can't import said download and it stays in the completed folder until I manually import it.

**Logs**
https://pastebin.com/UBzGaAWg

**System Information**
 - Sonarr Version: [v3.0.3.711]
 - Operating System: [Windows 10 in Hyper V]
 - .NET Framework 4.6.2

**Additional context**
Permissions are fine and the service is running as a user that can access the shared drive on the hyper-v host. This used to work in previous versions of V3.

**Comment by markus101** [comment]
Based on the logs Sonarr is running into an issue accessing the file(s) and is attempting to log an error that it can't access it, which fails because it can't find the drive it's trying to access.

Regardless of the user running the service, mapped network drives are _not_ supported by Windows services. If you want to use a Windows service, use a UNC path or if you want to use a mapped network drive don't run Sonarr as a Window service as covered in the FAQ.

**Comment by HexEditHD** [comment]
At the moment I'm using a UNC path by setting it as my root folder \\servername\share\TV Shows.

**Comment by markus101** [comment]
That's for the destination, but the source is likely the issue. We're going to need debug logs, not just the error message/stack trace to investigate further.

**Comment by HexEditHD** [comment]
https://pastebin.com/YJ4WiZQa the error pops up at around 18:00

**Comment by markus101** [comment]
It actually blows up =before any paths are logged because it can't find a file or folder with the path provided by the download client. I've added some additional logging and fixed the attempted logging resulting in an error being thrown, but the underlying issue with the path not being accessible is still something you'll need to address.

Look for `Processing path: x` and an `Import failed` message for those downloads in the next release, I suspect you'll see a mapped network drive coming from your client, or at least a UNC path that the user running Sonarr does not have acess to.
