### ISSUE TITLE
Show historic activity in manual search

### ISSUE THREAD

**Issue by shanecasey** [Sonarr/Sonarr#3612]
**Describe the problem**
Doing a manual search doesn't show which releases have previously been tried.

**Describe any solutions you think might work**
Would be great to have another column like the ❗️column of rejections that shows an icon for the history of that release. e.g.

- ✅ Download successfully completed
- ⏳ Release successfully grabbed
- ⛔️ Couldn't grab release
- ⚠️ Error downloading reported

The tooltip (on hover) could show the date and whatever detail is reported by the client.

**Additional context**
Existing rejection functionality for context.
![Screenshot 2020-03-09 at 11 47 42](https://user-images.githubusercontent.com/1871492/76210343-d7987580-61fb-11ea-867b-c543f39058e8.png)

**Comment by burtybob** [comment]
The version I'm currently running does say that a release is blacklisted (which will almost always be because it's been tried and failed to download) when hovering over the release rejected option.
Only time I miss some sort of flag is on the main episode list when upgrading qualities and it still shows e.g. [SD] instead of the progress bar.

**Comment by markus101** [comment]
We don’t have plans for this at this time. Tagging for something to re-consider in the future.
