### ISSUE TITLE
WEB is seen as WEB-DL

### ISSUE THREAD

**Issue by bokkoman** [Sonarr/Sonarr#3643]
When searching for a release, a ".WEB." (in filename) is seen as a WEB-DL. But it is not a web-dl.
Even though there is a group for WEB 1080 and WEB-DL 1080, and I've set a profile with only WEB-DL 1080, it still downloads .WEB. files.

I think the searcher has to be updated in such a way that files with .WEB. in their filename should be marked as WEB.

I'm using latest dev/beta release through docker.

**Comment by markus101** [comment]
WEB is Scene's WEB-DL.

https://www.reddit.com/r/Piracy/comments/9mpylc/web_vs_webdl_vs_webrip/

> Even though there is a group for WEB 1080 and WEB-DL 1080, and I've set a profile with only WEB-DL 1080, it still downloads .WEB. files.

WEB 1080p is a group that contains WEB-DL 1080p and WebRip 1080p, by only choosing WEB-DL 1080p you exclude WebRip 20180p, but include WEB 1080p because WEB 1080p is WEB-DL 1090p.

Next time, please use the template to file issues ("latest") is not a useful version to us.
