### ISSUE TITLE
Anime batch not recognized with [releasegroup] prefix, only suffix

### ISSUE THREAD

**Issue by cjmanca** [Sonarr/Sonarr#3698]
**Describe the bug**
An example that I just came across:
`[Judas] Black Clover 091-123 [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]`
Isn't recognized by sonarr, but as soon as I rename it to:
`Black Clover 091-123 [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs]-Judas`
then Sonarr picks it up no problem. Notice that the only change made was to move the release group to the end. This doesn't seem to be an issue with normal show season packs, just anime bulk releases.

**System Information**

 - Sonarr Version: 3.0.3.770
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.8

**Comment by Taloth** [comment]
Such release would usually be `[subgroup] Black Clover - 091-123 ...`, including a hyphen after the title.
Judas seems to be rather inconsistent with their names, most of their releases have the hyphen, some don't.
`Anime Land` seems to exclude the hyphen too.

Other example `[HorribleSubs] Black Clover 01 - 119 [1080p] [Batch]`

is it Black Clover 01... episode 119, or is it Black Clover... episode 1-119? _(Shame on your, HorribleSubs, I expected better from you)_

Now, before you're gonna say that this is obviously Black Clover... what about this one:

`[Glenn] Ani ni Tsukeru Kusuri wa Nai! 3 - 11 (1080p AAC)[C34B2B3B].mkv`

In case you're wondering... that's a single episode 11 of [Ani ni Tsukeru Kusuri wa Nai! 3](https://anidb.net/anime/14956). 

See the problem?

**Comment by cjmanca** [comment]
Yes, I can see that. But could you explain why it matched and imported automatically by just moving the release group to the end? None of the hyphenation changed...

Also, I'd think that could be solved via a greedy match on the name prior to matching the episode number.

**Comment by Taloth** [comment]
Because we have different regular expressions for the different formats. The prefixed one is what normal fansubs are using and is tailored for ordinary releases. The postfix is not standard anime, so it's safe to assume the rest of the title won't be standard either, so the regex is probably a bit more broad (i'm not sure about the difference).

The Ani ni Tsukeru Kusuri wa Nai! example vs the HorribleSubs one should show why a greedy match is not really possible without more metadata or an AI.

Sonarr primary goal here is to match single episodes correctly, batches are a bonus.

@markus101 Given the various examples, do you think we can tweak it without a negative impact for single eps? Or is this a case for the advanced parser usecases list?

**Comment by markus101** [comment]
I think we could be strict enough that batches with that format need to match 2-3 digits, not just one, that should eliminate most if not all season aliases that just append a number  since they use a single number from what I've seen.
