### ISSUE TITLE
Tear out chown and merge chmod flags

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#3752]
**Describe the bug**
chown never works. We should remove it for v3.
Produces support question from ppl that expect the app to magically getting root and fix their permission issues.

File & Folder probably don't need separate masks either.
If a file should be accessible by some group then so should the folder.
When applying chmod to files , simply clear out 'x'.

**Comment by xelra** [comment]
Chown is very much needed for everyone who set up permissions in his library correctly. Today my setup broke over this.
We need this back asap.

The reason why you believed that chown isn't working is probably because only the superuser can change the owner of a file. But chown also does group.

So you would just leave owner blank and specify the group. As soon as you specify a user, chown throws an error. If you want to make it more user-friendly, just remove the field to enter an owner and set it to default to blank.

**Comment by xelra** [comment]
There's more. I also saw that the modes for files and directories have been compressed. This is not common practice on any posix system.
I agree that the separation doesn't make sense, but it should now ask for `umask` instead of arbitrarily asking for either file or directory mode and then adding/removing execution bits for the other.
That would be expected behavior within the POSIX toolset.

**Comment by Taloth** [comment]
I agree on the umask, but ppl shouldn't be needing these options. Setup the umask and uid/gid of the sonarr process any any new file/folder will get created properly. Do the same on the downloader.
Relying on the app to fiddle around with chown is a bad practice in my opinion.

I wanted the settings gone now while v3 is in beta, precisely because it's a breaking change.

If there's a scenario in which this breaks where setting up process umask/uid/gid doesn't work, let me know.

**Comment by Taloth** [comment]
> In my own setup it's a little bit different, since the download location is on a remotely mapped drive, which is mounted with the media gid. So Sonarr gets access to these files that way.

Anyone with a local storage and separate services will not have that 'workaround'. Remote network shares that don't use unix permissions the same way are kinda out of scope because imo.
How would it work in your case if that network share was just a local drive?

Without being owner, sonarr can't change permissions nor the group.
Sonarr would be required to copy the file first, to gain ownership.

So your approach works, ONLY because you use separate filesystems for your download and library locations. Forcing the copy and thus giving ownership of the moved file to sonarr. Which is then capable of adjusting the permissions and group.
How would it work if both download and library locations are on the same filesystem?

Imo there are still several approaches the user can take that does not sacrifice security:
- shared gid+umask 022/077 for services. and inapp umask 002. (admittedly, sonarr's default systemd umask is 002, while it should've been 022)
- use `setfacl` to give sonarr and users the appropriate rights in the library folder (more advanced version of setgid)

PS: I'm playing devils advocate on purpose because I want a critical look at this before we take further action.

**Comment by xelra** [comment]
You're right. Setting group and mode is only possible when Sonarr copies the file.
In the case of moving the file or creating a hardlink, the target will retain the original owner, group and mode.
This is a problem for the user to solve though, depending on however he set up his system.
Let's assume the download client is downloading onto the same volume and we want to use hardlinks. Then the user needs to make sure the download client is creating those files with the group `media` and the intended mode. Then Sonarr can see them and create the hardlinks. That way the problem is out of Sonarr's hands.

The issue is when people use copy instead. Since ownership now falls to Sonarr, it needs to take care of creating those files with the intended mode and group. The same is also true for the metadata files and directories that Sonarr creates inside the library.

**Comment by Taloth** [comment]
>  creating a hardlink

Hardlinks are even more tricky because the inode determines the owner+permissions. Change permissions in the library folder and you're effectively also changing it in the download/seeding folder.

> This is a problem for the user to solve though, depending on however he set up his system.

Assume a single filesystem, with usenet & torrent download client, sonarr, radarr, and plex.
What approaches would the user take to solve it?
The steps that user has to take to make it work with all the services might make chgrp unnecessary. Which would mean that chgrp in Sonarr is only useful in your particular workflow.

**Comment by xelra** [comment]
`mv` uses `ln` internally when on the same volume.

It's what I tried to get into. The owner of a file is responsible for its permissions and group. If you're on the same volume, this responsibility falls towards the download client.
If someone does copy instead of move, it falls towards Sonarr. And also falls towards Sonarr for the directories and files it creates itself within the library.

So for someone who uses copy, it might look like this in the library:
```
drwxrwx---  2 sonarr media  4.0K Aug  5  2019 .
-rw-rw----  1 sonarr media   26K Aug  5  2019 Show.S05E13.WEB-DL.1080p-Group-thumb.jpg
-rw-rw----  1 sonarr media  2.4G Aug  2  2019 Show.S05E13.WEB-DL.1080p-Group.mkv
-rw-rw----  1 sonarr media  1.1K Apr 12 11:50 Show.S05E13.WEB-DL.1080p-Group.nfo
-rw-rw----  1 sonarr media  329K Dec 10  2018 poster.jpg
```

And for someone who uses move, it should look like this in the library:
```
drwxrwx---  2 sonarr media  4.0K Aug  5  2019 .
-rw-rw----  1 sonarr media   26K Aug  5  2019 Show.S05E13.WEB-DL.1080p-Group-thumb.jpg
-rw-rw----  1 nzbget media  2.4G Aug  2  2019 Show.S05E13.WEB-DL.1080p-Group.mkv
-rw-rw----  1 sonarr media  1.1K Apr 12 11:50 Show.S05E13.WEB-DL.1080p-Group.nfo
-rw-rw----  1 sonarr media  329K Dec 10  2018 poster.jpg
```

**Comment by ta264** [comment]
Is it fair to summarise that your objection to the current situation is you don't want to end up with sonarr.db having permissions:
```
-rw-rw-r--  1 sonarr media 16231424 Jun 11 15:13 sonarr.db
```
you'd rather instead it ended up with 
```
-rw-rw-r--  1 sonarr sonarr 16231424 Jun 11 15:13 sonarr.db
```

If so, you could just run sonarr under the media group with umask `077` (or whatever it is) to end up with 
```
-rw-------  1 sonarr media 16231424 Jun 11 15:13 sonarr.db
```

And we can expose a umask option to be applied to library files that sonarr creates so you get what you want above.  This way we can avoid exposing a chgrp option that more often than not will fail and result in support requests.

**Comment by xelra** [comment]
Running Sonarr as anything else but `sonarr:sonarr` is not a good default. If anyone wants to do this for whatever reason, ok, they're free to do so. But we should stick to best practices and normal defaults.

If Sonarr were to only have a umask option, then people could work around the issue by setting the SGID bit at the top of the library. But it's a workaround. Sonarr should be able to properly `install` its files within the library directory itself.
Explaining SGID to users is a whole support story by itself.

I think the reason why many people ran into questions with Sonarr's chown functionality is, because we exposed the owner field, which didn't make sense. People would just make a bad assumption and not leave it blank or write sonarr in there. If we were to only expose the group field, the confusion should be cleared up.
Maybe there should also be a tooltip that explains that umask and group can only be applied to files that Sonarr creates or copies.

**Comment by xelra** [comment]
So I've tried to work around this by using SGID, but unfortunately that is not possible. The current set of options does not allow it. The problem is that you would want e.g. `2770` on directories, but `0660` on files.

So the minimum you would need is a checkbox like "Use SGID on directories?"

This is probably an issue I never encountered, but which users of the SGID solution have probably run into already in the past.

**Comment by xelra** [comment]
I also just found out that the field doesn't accept entering `2660` as the mode, stating that it isn't a valid Unix permission. So even if someone were willing to accept the SGID bit on files, it wouldn't be possible. Previously this also wasn't an issue.

**Comment by xelra** [comment]
I found another issue, which is one of the reasons why the currently available options are a dead end.
It is possible to `chmod 750`, which under normal behavior would keep the first octal unchanged. So a directory that was `0770` woud then be `0750` and a directory that was `2770` would then be `2750`.
This is majorly important for setting up file permissions in groups via the SGID method.
In Sonarr, right now, it is possible to just set `640` for the mode, but it would replace it with `0640` behind the scenes.

So what's the course of action now? Which method should be forced on users? As it stand right now, this is broken in v3 and I have to constantly SSH into the server and fix permissions every day.
