### ISSUE TITLE
Episodes incorrectly reordering themselves when thetvdb changes data

### ISSUE THREAD

**Issue by Trevor159** [Sonarr/Sonarr#3785]
This mostly happens in anime. When a show with multiple seasons (a recent example is "Haikyuu!!") gets it data changed so one of the specicals (which are normally unmonitored in sonarr) is changed to have an absolute episode number then it will shift all of the episodes of the seasons with higher absolute order to be incorrect.

To be clear here is an example
Haikyuu has 4 seasons with a normal absolute order of 73 episodes
Someone adds one of the specials as episode 26 (the first episode after season 1)
Now the 1st episode of season two get transferred to that special (it keeps the same absolute episode number but changes episodes, which is wrong)
Now all of the episodes season 2 and higher are placed in the wrong episode inside of sonarr.

Forgive me if this explanation is terrible, it is hard to describe. I would suggest an option for episode files to never change episodes inside of sonarr after they are downloaded. This would be helpful.

**Comment by markus101** [comment]
Anime episodes are updated based on their absolute episode number, if that absolute episode number gets changed to a different season due to their renumbering then it will affect Sonarr.

Why did that absolute episode number get changed in the first place?

We don't have plans to change how episodes are linked for anime series or introduce a setting for it, especially without having more examples. The reason it's done this way is because we've seen seasons split and joined in the past and the only thing that remained constant was the absolute episode number.

**Comment by Trevor159** [comment]
I assume people change them because they have different opinions on what specials are apart of the story and what are filler or something. I do not change them so I do not know why the website allows this. It always happens to an ongoing show so maybe it is just people contributing to the website going rogue? This has also happened to me with two other series in my library within the last year (out of ~30) so it is definitely not a 1 off thing.

I do not have a perfect solution but as a user I would expect an episode that was downloaded with a name S2E02 to always be linked to season 2 episode 2.

**Comment by Taloth** [comment]
Wouldn't the situation fix itself again automatically once the data on tvdb is corrected?

I suspect that maybe the problem lies in the way absolute order can be edited on the new tvdb site. At least if it allows a user to insert the special in the absolute order list and automatically renumbering the following ones. I don't know if it works that way but it would definitely leading to users misediting it.

**Comment by Trevor159** [comment]
> Wouldn't the situation fix itself again automatically once the data on tvdb is corrected?
> 
> I suspect that maybe the problem lies in the way absolute order can be edited on the new tvdb site. At least if it allows a user to insert the special in the absolute order list and automatically renumbering the following ones. I don't know if it works that way but it would definitely leading to users misediting it.

The situation would correct itself if sonarr does not download anything and the tvdb goes back to its original state. I think these are bad assumptions to make though. Like I said this only seems to happen to ongoing shows so the chance of downloading a new episode while this happens is not low.

**Comment by thezoggy** [comment]
'changing data' means you have to make assumptions one way or another. and changing data with tvdb is somewhat a nature of the beast with crowd sourced data that can change to fit whoever has the time.. then add in the never ending api issues that randomly result in missing seasons or all data completely.

I can't even begin to count how many times I've had to reshuffle 100+ topgear episodes because someone gets the bug to redo the tvdb data to fit their collection.

Personally I would not want sonarr to try and fix stupid.

**Comment by Trevor159** [comment]
An intuitive solution might be to track both relative and absolute episode numbers for each episode and if one of them changes then alert the user and let the user handle how they want to deal with the conflict.

**Comment by ItsCinnabar** [comment]
Grimgar of Fantasy and Ash just got changed.

> Why did that absolute episode number get changed in the first place?

They added a new special, s00e01. Absolute number 3. It is NOT the old s01e03 moved down to there. Season episode 3 is now absolute 4, with the same name as what it used to have 'Are Goblin Pouches Filled with Our Dreams?'. So basically, the actual 12 episode season is exactly the same 12 episodes as before. There is just a new special that was added. So... now sonarr put my s01e03 into s00e01 with a filename of s01e03 goblin pouches, and moved down all my other episodes so my s01e12 is placed into sonarrs s01e11, and my s01e12 is empty leaving sonarr to try to look for a new one. Plex and Jellyfin on the other hand have no change obviously because sonarr did not rename. 



> Like I said this only seems to happen to ongoing shows (I assume shows are only editable on the tvdb when a show is ongoing?) so the chance of downloading a new episode while this happens is not low.

Every time i've seen this happen it has been for older shows. The show I just mentioned is from 2016.

Guys... literally my solution is every single time this happens I have to delete the show and re-add it. Sonarr will then scan in the files correctly due to the filenames Thats so silly. Just keep my s01e03 in the s01e03 slot dont move it to the s00e01 slot because the absolutes changed.

**Comment by netpok** [comment]
This happened again, it seems absolute episode number is not as constant as it was assumed. Maybe it would be better to store the external id and use that as a link? That should only change if the episode is literally deleted and added again.

**Comment by thezoggy** [comment]
the data is always dynamic, which rears its head when things get renumbered (insert whatever reason). that fundamentally is the issue, is how to deal with dynamic data when everyone treats it as static. now the information a lot of time is _static_ because it just simply is not touched for long periods   or a mod goes and locks the series down to prevent changes (still doesnt solve with the mods themselves change stuff)

**Comment by netpok** [comment]
That's why I mentioned the tvdb id as link since it should not change. But the v4 has a point.

**Comment by kani-27** [comment]
Please forgive me if I'm not commenting in a correct format or place, I'm very unfamiliar with GitHub; and I am assuming because this is open and labelled discussion I shouldn't open a new issue that pertains to this specific thing.

This is specifically my input on absolute numbering and why we should be able to either
A. Offset the absolute numbering within the series for searching, or;
**B. Set episode number used in search manually, perhaps setting first episode in the season**
C. Assign a manual search through the episode list to the specific episode of the search 

![image](https://user-images.githubusercontent.com/120398796/207091932-46fb524a-c8e8-4d8e-90f3-30ccb5fe9589.png)

Here I use Mobile Suit Gundam: The Witch From Mercury as an example. The series was working fine until episode 9, where on TVDB the admin has locked in an additional Prologue episode as the first episode in absolute order. This isn't to debate if that should have happened or not, this is more to show that this change makes all episode searches incorrect from now on.

Following the new absolute number, all search results will no longer be correct, if you search for the Prologue Episode (Episode 0), you will instead fetch Episode 01 and miss the Prologue. Searching for Episode 01 will fetch Episode 02, and so on. This change in TVDB's absolute order does not retroactively change all torrent titles/episode number and will forever be offset by the number of added episodes.

A. Proposal 'A' is to simply allow the user to offset the number used in the search/fetch in the series setting, either by manually inputting a number (in this case, I could input '-1') or to subtract by the number of episode within Specials that is included within the absolute order (although I don't think this method would work 100% of the time, so I'm not too sure about this one).

If this is done then the search will work regardless of TVDB changes as long as the user is aware of the offset and adjusts the value. However, this only solves the issue if the added episodes exist before 01. So what if the order is messed up between seasons, perhaps due to recap episodes that may or may not be included within the database order, or the torrents of the recap episode after episode 12, for example, possibly being numbered 12.5 and/or 13?

B. Maybe we can instead set search number start per season? For example, if the recap episode scenario above occurs, and it's possible for season 2 to begin on either 13 or 14, perhaps we can set what number the search should start with per season? This solves the original issue of prologues being added to absolute order as well. So in the case of both the prologue and recap episode problem occurring, being able to set what number Season 1 and Season 2 should start with would ensure correct fetching of the episodes. For example, I can set Season 1 to start at 01, and Season 2 to start at 13 (if the recap episode was numbered 12.5).


Proposals A and B would solve automatic fetching and B is in my opinion the best timeline to live in. But if neither is possible, then can we at least allow manual user searches be assigned to the episode being searched?

C.

Here I decide to manually search for Episode 10 by clicking the little dude on the right:
![image](https://user-images.githubusercontent.com/120398796/207099253-d4f366d2-038e-47b6-b5d4-bfb64a759377.png)

I find the torrent I want for Episode 10 (of a free show available legally on Youtube for free):
![image](https://user-images.githubusercontent.com/120398796/207101678-aeab4b9a-8d8d-4090-8f0e-51e76f3b3ebe.png)

It's detected as Episode 9:
![image](https://user-images.githubusercontent.com/120398796/207099932-6ecc3bf9-e7c9-4f97-8d4f-212827c6b9cd.png)

It downloads as Episode 9 instead:
![image](https://user-images.githubusercontent.com/120398796/207100130-ed3b5abf-bcc1-4ddb-be69-cf7d313f6057.png)

So if possible, perhaps assign manual user search to the selected episode that's being searched?

(I am aware of manually assigning the episode, which I will probably do in the meantime; this is more so a suggestion that could save a lot of time for anyone experiencing this issue)

I apologize if this isn't the right place and for writing a wall of text. I also apologize to myself if no one reads this because I don't know how GitHub works. And sincerely, thank you.

**Comment by markus101** [comment]
Your comment is loosely related to this issue, but your question is better suited for Discord or another support channel. Sonarr uses TheXEM.de to handle remappings, we have the #xem channel on Discord for related discussions and this exact subject was discussed there yesterday.

**Comment by markus101** [comment]
No short term plans to change how episodes are matched, we've previously attempted to use TVDB's IDs for this, but often saw things deleted and recreated, thus generated new IDs.
