### ISSUE TITLE
Sonarr wants to rename files that are already named

### ISSUE THREAD

**Issue by 19wolf** [Sonarr/Sonarr#3814]
**Describe the bug**
Sonarr wants to rename files that are already named and remove the Release Group info

**Screenshots**
Not a screenshot but example:
```
- Another - 12 - Stand by Oneself [Judas - Bluray-1080p - x265 Opus[JA+EN] [EN]].mkv
+ Another - 12 - Stand by Oneself [Sonarr - Bluray-1080p - x265 Opus[JA+EN] [EN]].mkv
```

**System Information**

 - Sonarr Version: Docker Linuxserver/sonarr:latest

**Comment by markus101** [comment]
Because it doesn't have the release group (based on that name it has no way to parse it out). Typically this happens if Sonarr never imported the file or lost track of it and had to re-import it from the series folder. Impossible to say why with certainty and not a bug since it can only use the info it has to rename.
