### ISSUE TITLE
Language profiles: allow upgrading until multiple languages exist

### ISSUE THREAD

**Issue by MayeulC** [Sonarr/Sonarr#3844]
**Describe the problem**
Currently, there is no way to specify that a given set of languages *at the same time* is preferred, if possible.

**Describe any solutions you think might work**
Add an additional field to the "upgrade until" functionality, to allow specifying that a given set of languages is wanted.

**Additional context**
It might be possible to just add a "all languages are wanted" checkbox, but might not account for fallback languages, that might not be necessarily wanted in the final version.

That could go well with #3843 to grab both the original version, and an a given dub (English, for instance). The Multi tag is mentioned in #2854.

**Comment by markus101** [comment]
Are you expecting Sonarr to keep multiple files around to meet these requirements? Or it'd keep one file with the most preferred language + others it finds?

The former would most likely fall under https://github.com/Sonarr/Sonarr/issues/312 and the latter I don't see as being something we'd ever do, it's too complicated to get right and avoid the pitfalls.

**Comment by MayeulC** [comment]
Thanks for your answer. I'd prefer the latter for now, I think.

What I'd like to have, is something that would at least prioritize a multiple audio file over a single one for the initial download. I could achieve something similar using a release profile that bumps `MULTI` and other tags, but I expect the results to be more random than a native solution.

Maybe in the future we'll have an ecosystem that's versatile enough to only download the audio from a container file and sync it up with another video-only file, but that's not really an option for now.

**Comment by markus101** [comment]
I think that behaviour would mostly tie into the changes required for https://github.com/Sonarr/Sonarr/issues/2854 then. Since right now Sonarr only tracks a single language, but would need to understand that there can be multiple languages in order to handle `multi` tagged files.

Things get tricky when you try to determine an upgrade for an existing file or comparing otherwise equal releases if there are more than 2 preferred languages.

If you prefer, French, German then English.
Would you want to replace a file that has French and English, would you want to replace that file with a file that has French and German?
What about a file that has German and English, would you replace it with a file that only has French?

That's just the complications I've come up with so far, probably more edges to be worried about.

**Comment by markus101** [comment]
This isn't somehting we have planned for the time being, tagging for a review later on.
