### ISSUE TITLE
Allow filtering episodes by title during manual import

### ISSUE THREAD

**Issue by aschampion** [Sonarr/Sonarr#3862]
**Describe the problem**
Some series have hundreds of episodes in a season, so including a filter input in the interactive import's episode selector modal like the one in the series modal would greatly ease the process of navigating these series.

**Describe any solutions you think might work**
The filter for series already works great, so replicating that functionality in episodes should be sufficient.

A related but distinct change for these massive series/seasons would be including an indicator for each episode row in the import modal whether that episode already exists in the database.

**Comment by markus101** [comment]
Filtering episodes by title is like filtering series by TVDB ID. Episode number is more often going to be useful for filtering than the episode name because the user is going to know that most often.

A better solution would be to parse the input and determine if it’s a number, if so it should also be used to filter by the episode number.

**Comment by aschampion** [comment]
My particular use case was for review or parody shows where the episode number often isn't included but the title always is since it comes from the referenced media (hence needing manual import), but can see your point for the more general case. I added a commit to the PR that also compares the episode number. It doesn't check if the parsing was successful because comparison with `NaN` is false in that case anyway.
