### ISSUE TITLE
jay leno's garage

### ISSUE THREAD

**Issue by gregcbrown** [Sonarr/Sonarr#3878]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:**

**Operating System:**

**.net Framework (Windows) or mono (macOS/Linux) Version:**

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

**Comment by markus101** [comment]
After retiring from his perch atop the American late-night TV ratings in 2014, comedian Jay Leno has more time to partake in one of his passions: collecting cars. That is the focus of `Jay Leno's Garage', which showcases the `Tonight Show' veteran's journey throughout America as he searches for unique rides and the stories behind them. Leno explores different aspects of automobiles, including the history of iconic brands, testing supercars, checking out the latest innovations, and even offering consumer advice. He also talks with fellow gearheads, including celebrities, to learn about their collections. Leno says cars, to him, are "kinetic artwork" - rather than being stagnant, it is art that is "rolling down the highway."

> Please use forums.sonarr.tv for support. Support requests or questions will be redirected to the forums and the issue will be closed.

Unless this is a bug, with logs, please open a thread on the forums or subreddit.

**Comment by gregcbrown** [comment]
Sorry, I was looking to see if anybody had the same issue as me. I didn't know I opened an issue.
