### ISSUE TITLE
Downloaded, renamed... but not Imported?!

### ISSUE THREAD

**Issue by DejaVu** [Sonarr/Sonarr#3881]
Sonarr Version: 3.0.3.899

Strange issue this one.
Sonarr has found, sent download to client, found after client download, renamed, located and all went well. Plex found it...

However, a picture speaks a thousand words....
![image](https://i.imgur.com/rpPfA2d.png)

Season 2, 3, 4, 5, worked are fine and "imported".
It's done this on a number of my shows. I can supply logs if required. Scanning the Show doesn't update either, even though files exist.

**Comment by markus101** [comment]
Please use the templates when filing issues, you're missing a lot of critical information.

Which OS? (and mono version if relevant?)
What do the debug logs of the rescan show?
What does the history in Sonarr show?

Without having the other pieces this sounds like a permissions issue, though that doesn't explain how the file got there in the first place, only debug logs of the import would.

**Comment by DejaVu** [comment]
Sorry. Using Synology's SPK and updated to latest version. 
Version 3.0.3.899
Mono Version 5.20.1.34

The history looks correct and states
"Episodes downloaded correctly and picked up from the download client" and imported/renamed to the correct location.

Logs were only set to Info only.I've now switched to Debug and have removed the files from the library and re-imported manually. Issue remains and log attached. 

[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/4977357/sonarr.debug.txt)

**Comment by markus101** [comment]
If it imported it, then it was no longer on disk (could no longer see it at least) then it should also have a deleted event after the next refresh.

Without removing the files and re-importing, what’s do the debug logs show for a refresh of the series?

**Comment by markus101** [comment]
Actually, looking closer at your picture, this doesn't appear to be Sonarr not seeing it imported, but Sonarr complaining about not being able to process the download (was manual import used to import? since Sonarr doesn't support multi-season downloads it won't process that release). The status shows any items in queue over the import status in v3 so queued items show downloading status instead of the existing file (you can also see that Sonarr shows x/x episodes in each season beside the season number.

Best thing to do would either force Sonarr to import using manual import from Activity: Queue or from the queue tell Sonarr to ignore it so it stops trying to process it.
