### ISSUE TITLE
Support for running service as system with mapped drive

### ISSUE THREAD

**Issue by 23833716** [Sonarr/Sonarr#3882]
**Describe the problem**
I run Sonarr as the System account on a VM that maps a network share.  I use SysInternal's PsExec to create a persistently mapped drive.  This allows Sonarr to have full access to my mapped drive even though it runs as System, however there are places inside the app that like to complain about this superficially.  I understand this is expected behavior and I could use UNC paths, but my method causes no issues with Radarr and the automation still works fine in Sonarr.  I just can't edit series, because of this validation check that seems to happen.  Another example is when I try to manually import a series.  It doesn't want to see my mapped drive originally, but as soon as I start typing the path (ie D:\tv\....) it works fine.  It's complaining about something it doesn't need to in my case. :)

Invalid request Validation failed: 
 -- Path: Mapped Network Drive and Windows Service

![sonarr](https://user-images.githubusercontent.com/28731603/88467640-acf34480-ce9e-11ea-8ee8-ecbecd85a564.PNG)
![sonarr2](https://user-images.githubusercontent.com/28731603/88467641-acf34480-ce9e-11ea-9603-1965f17c1d4b.PNG)
![sonarr3](https://user-images.githubusercontent.com/28731603/88467642-ad8bdb00-ce9e-11ea-9f4d-5bf455a3803a.PNG)

**Comment by markus101** [comment]
Mapped network drives are not supported by windows services (this comes from MS directly), the validation is there because even though sometimes it works it tends to fall apart at some point and surprises users

We have no plans to guess at whether the mapped network drive will work more often than not and have chosen to not support them with Windows services, we don’t have plans to change that behaviour or have another workaround.
