### ISSUE TITLE
Docker - SignalR negotiate failure on Docker Desktop, UI not updated

### ISSUE THREAD

**Issue by adamskoog** [Sonarr/Sonarr#3885]
**Describe the bug**
When running Sonarr in a Docker container SignalR fails with a 500 error when calling to `http://localhost:8989/sonarr/signalr/negotiate?apiKey=<apikey>&_=1595613604262`. This causes UI changes to not occur when using the application.

Not sure if it's related, but there is also a 501 Not Implemented when calling `https://piwik.sonarr.tv/piwik.js` immediately preceeding the negotiate call above.

The docker command I am running:
`docker run -d --name=Sonarr -e TZ=America/Chicago -p 8989:8989 -v C:\Docker\Sonarr\config:/config -v M:\:/data --restart unless-stopped linuxserver/sonarr`

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Windows 10 2004 - Docker Desktop (Hyper-V) [linuxserver/sonarr image]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**
This issue is also see in Radarr and Lidarr, which I'm also using the linuxserver.io docker images. I have tried the hotio Sonarr image as well with the same issue.

**Comment by markus101** [comment]
You're lacking a lot of critical information, including logs and mono version.

I know BSD users had a similar issue due to the lack of a writable path: https://forums.sonarr.tv/t/signalr-problem/5785

Unless docker on Windows has changed how volumes are mapped you're going to have a bad time with SQLite on a network share, https://github.com/Sonarr/Sonarr/issues/1886

If you help troubleshooting, please open a thread on the forums or subreddit for support.
