### ISSUE TITLE
Anchor previous/next buttons in series viewer 

### ISSUE THREAD

**Issue by senses3** [Sonarr/Sonarr#3947]
![2020-09-09_22-41](https://user-images.githubusercontent.com/1409298/92675594-c258ec80-f2ed-11ea-99b0-9dd673c67ad5.png)
**Describe the problem**
Series viewer next/previous and the expand all buttons feel like they should be swapped around. I find myself having to scroll up to the top of the page with a bunch of expanded seasons to go to the next series.  

**Describe any solutions you think might work**
Either swap them around, or add the next/previous buttons to the top bar next the the expand all button. Or maybe you could anchor a floating next/previous button that remains fixed as you scroll down. 

**Additional context**
This is a request as of Version 3.0.3.913.

**Comment by markus101** [comment]
Putting them into the toolbar would bury them on mobile, which is why they weren't there in the first place. Floating buttons is something we've played with before, but it ends up having unintended side effects when people accidentally click them expecting to hit a search button instead.

Given you can collapse open seasons and jump most the way to the top (depending on the number of seasons) and the edge cases above we do not have plans to make changes at this time.
