### ISSUE TITLE
Rclone Gdrive Mount Showing Local Used Space as Free Space Rather than Free Space as Free Space

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#3950]
**Describe the bug**
Title...
![image](https://user-images.githubusercontent.com/55419169/92800561-6a1bfc00-f37a-11ea-833d-bbf81b60af11.png)

MergerFS command
`/home/bakerboy448/bin/mergerfs /home/bakerboy448/local:/home/bakerboy448/cloud=NC /home/bakerboy448/merge -o rw,async_read=false,statfs_ignore=nc,use_ino,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true,nonempty`

Logs: N/A

XHR from Chrome Dev  Free Space is being showed as used.
Can we check based on lack of label or a UUID in path? and re calculate actual free space?
```
37: {path: "/mnt/mpatht/bakerboy448/merge", label: "", freeSpace: 7758986383360,…}
freeSpace: 7758986383360
label: ""
path: "/mnt/mpatht/bakerboy448/merge"
totalSpace: 1137897908469760
```

Xref Radarr https://github.com/Radarr/Radarr/issues/4989

**Comment by bakerboy448** [comment]
![image](https://user-images.githubusercontent.com/55419169/92804445-f4b22a80-f37d-11ea-972b-d8c2977f20c3.png)

**Comment by markus101** [comment]
No, it's showing the same thing `df` is, 7.1 TB free space, ~1 PB total (formatting is likely the discrepancy between Sonarr and `df`). Given Sonarr knows nothing about the cloud mount this is what I expect it to see, plus it only cares about the local free space because that would affect the importing, being unable to transfer to cloud storage Sonarr knows nothing about is something it's not concerned about.
