### ISSUE TITLE
Parsing Incorrectly Matches Obfuscated Filename

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#3990]
**Describe the problem**
Subject...  The first it rejects due to picking up season 10 and the second due to season 78
![image](https://user-images.githubusercontent.com/55419169/94874213-164f8080-0417-11eb-9333-921fffcb85d2.png)
![image](https://user-images.githubusercontent.com/55419169/94874224-19e30780-0417-11eb-8403-b7d66a8ffa1d.png)

**Describe any solutions you think might work**
If file name starts with abc.xyz, assume obfuscated and ignore any season detection of the file name

**Additional context**

**Comment by markus101** [comment]
We can't just assume because it starts with X it is Y and most obfuscated items don't start with that, so it's a waste trying to do it for one particular thing.

This isn't really a feature request though, it's a bug, so we're going to need all the normal bug information to see if there is something we can improve.

**Comment by bakerboy448** [comment]
Version
3.0.3.937
Mono Version
5.20.1.19

Trace Logs of S2E24
https://pastebin.com/cx271ja5

Trace Logs of S2E04
https://pastebin.com/7QpdB7Xz
