### ISSUE TITLE
I can copy my password

### ISSUE THREAD

**Issue by thijsjek** [Sonarr/Sonarr#4011]
**Describe the bug**
In the V3 version of sonarr/lidarr it is possible to copy the password of download client.

**System Information**
Version 3.0.3.970
Mono Version 6.8.0.105
Truenas 12 RC1

**Additional context**
Security wise i wont be happy if someone could get on my server, and copy in plain text my passwords.
The passwords are dots, but you can select and copy them to retrieve the plain password.

**Comment by markus101** [comment]
If they have access to the UI then they have access to the API key and have full access to Sonarr and anything it can do. Instead of copying from the UI they could pull it from the API, or grab a back up of the DB and get it from there.

TLDR security wise if someone has access to Sonarr’s UI they’ll have access to the things it has access to, whether they copy dots or get things from the API.
