### ISSUE TITLE
Skyhook refresh of recently ended shows

### ISSUE THREAD

**Issue by Dnkhatri** [Sonarr/Sonarr#4024]
It seems to me that skyhook for shows that have ended is refreshed at a longer frequency. Which is understandable as long time ended shows are unlikely to have any updates. The problem I am seeing is that shows are being marked as ended on the day they end before the last episode airs but the episode name is updated a bit later which results in the episode name of the last episode not being updated for a long time in skyhook.

**Comment by bakerboy448** [comment]
the skyhook cache refreshes every ~24 hours
do you have any specific shows taking longer than that?

**Comment by markus101** [comment]
Skyhook does cache ended shows for longer (5 hours vs 1 hour), but that's largely a non-issue because TheTVDB takes 24 hours to update their API after a change is made on the site. So yes, it can be slower capping out around 29 hours instead of 25 hours (if things align perfectly), but until TheTVDB reduces caching on their side we're stuck at 24+ hours in a lot of cases.
