### ISSUE TITLE
Add .NET Version to UI

### ISSUE THREAD

**Issue by napei** [Sonarr/Sonarr#4057]
**Describe the problem**
The issue template requires/asks for the .net framework version. I can't find this in the UI anywhere, and to ease issue creation perhaps that information could be added to the `About` section of the `System` menu. This would make troubleshooting a little easier perhaps.

![image](https://user-images.githubusercontent.com/8946502/97798690-63c04700-1c7c-11eb-81ca-21dee6bd4e08.png)

This could also be extended to include the platform type/version for scenarios where Sonarr is running remotely.

**Additional context**
One example of the presentation of such information is in Tautulli
![image](https://user-images.githubusercontent.com/8946502/97798709-9e29e400-1c7c-11eb-89ba-d9df5fe1866f.png)

**Comment by bakerboy448** [comment]
This would make sense, but it's up to Markus and Taloth.

We do give the mono version in status, so this would make sense.

**Comment by markus101** [comment]
But does it make sense?

I’m not sure how valuable it actually is, mostly it’s useful if you’re running v2 without 4.5 installed, but requires higher than that and v2 isn’t going to get any active development.

I’ll take a look and if it’s easy to do well add it, otherwise just remove it from the template.
