### ISSUE TITLE
Allow customization of search string sent to indexer

### ISSUE THREAD

**Issue by boban-bmw** [Sonarr/Sonarr#4069]
**Describe the problem**
Certain indexers name seasons with "Season xx" instead of using "Sxx", causing (manual) searches to miss results.

**Describe any solutions you think might work**
A per indexer advanced "search string" setting would do the trick.

**Additional context**
Mock-up of possible solution:
![image](https://user-images.githubusercontent.com/66882653/98489641-2c7b0880-222f-11eb-97f9-06be80bc48bb.png)

**Comment by markus101** [comment]
Better indexers will use parameters to get the season number instead of hardcoded strings, which accounts for most indexers Sonarr supports directly, indexers accessed through Jackett should be fixed in Jackett (Sonarr sends the season number as a parameter), we don't have plans to support customizations in Sonarr.

The closest related feature would be: https://github.com/Sonarr/Sonarr/issues/1128
