### ISSUE TITLE
Add Sanity Check for Recycling Bin

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4135]
Users should not be able to set the recycling bin to the path of the root folder or any of the root folder parent folders

Bad things happen....

Radarr xref https://github.com/Radarr/Radarr/issues/5447

**Comment by Taloth** [comment]
"Please can I shoot myself in the foot? "
Should we protect against C: , C:\Windows, C:\Users, w/e as well?

I'm fine with adding the root folder guard, but sometimes people just gotta feel the consequences.

**Comment by bakerboy448** [comment]
Austin had similar comments on the radarr issue

> Although i dont disagree the thought of a health check would be nice, there are a lot of ways someone can screw this up & all the ways have something in common.. They know their paths and they have to manually set the location.
> 
> Example.. If they map their movie folder to
> M
> and shows to
> S
> with real locations being
> D > Movies|Shows
> 
> Well set the recycle bin to D and a simple check wouldn't catch that since D is not M or S.. same outcome with unc paths, etc
> 
> I guess adding a check for a path of D\Movies and recycle bin of D sure, but keep in mind the cases that wont catch this is all.

**Comment by beyondmeat** [comment]
There's also a bug with the recycle bin.
I'm using rclone union mount and everything is set right (hardlinks work, etc). Importing goes right to the local folder as I expect, etc.

However, when I enable the recycle bin, instead of moving the files on the remote side, it actually downloads the files locally and puts them into the trash folder. Radarr does not do this, radarr behaves like I expect.

My guess is a missing argument in the code needed for this operation, that exists on the import code but not the recycle code.
It could also be a mono-bug/limitation as radarr v3 is now .netcore (hopefully .net5 soon).

**Comment by bakerboy448** [comment]
Need to pull from radarr
https://github.com/Radarr/Radarr/pull/5514

**Comment by markus101** [comment]
Looks like this came in with the move to .net https://github.com/Sonarr/Sonarr/commit/1169741c54a13b316eef81ea83e14e6ef1ac998b
