### ISSUE TITLE
Add "Are you sure you want to exit?" dialog in interactive import

### ISSUE THREAD

**Issue by Nimradd** [Sonarr/Sonarr#4143]
**A mis-click when manual import(Interactive Import) on "Cancel" instead of "Import" makes you lose all your work performed in Manual Import**
I quite often do manual imports on old local shows as they're not named correctly. Quite often it's a lot of work and I sometimes mis-click the "Cancel"-button instead of "Import"-button. Every episode mapping disappears and the work I performed is lost.

**Suggested solutions**
1. A standard "Are you sure you want to exit?" dialog box would be helpful. 
2. A more refined solution would be similar logic to the "Unsaved changes"-dialog when editing settings and then clicking on something else. If something is changed manually in the Interactive Import there could be a dialog box asking if you really want to exit as you have done some changes to the import but not imported.

**Comment by markus101** [comment]
We added confirmations on navigation to settings pages because it be not be clear to some people (especially coming from v2) that switching pages would lose settings. Clicking cancel, even by accident in the import modal is clear that it'll cancel and we don't have plans to add a confirmation dialog there.
