### ISSUE TITLE
Add confirmation on manual quick import that it does a move, instead of a copy/hard link

### ISSUE THREAD

**Issue by benihanaz** [Sonarr/Sonarr#4210]
**Describe the problem**
When completing a quick import, it appears that it completes with a move command which is fine. However, depending on the user and case setup, this may not be the most ideal scenario. It would probably be helpful to add a confirmation when the user presses quick import, so this is clearly identified to the end user that this is completed via move and not hardlink/copy.

**Describe any solutions you think might work**
Add a confirmation step when the user presses "Quick Import" so this is clearly acknowledged by the end user that this is completed via move and not hardlink/copy, so the user has the option to proceed with "Interactive Import" instead if they wish.

**Comment by benihanaz** [comment]
Just adding here to say.. as another alternative I think removing the manual import would be a good option too, honestly - the interactive import is way more user friendly (imho) and a better experience all around.

**Comment by markus101** [comment]
A confirmation is nagging, removing it seems overkill, so we're going to rename `Quick Import` to `Move Automatically`.

**Comment by JohnDelisle** [comment]
What's the default operation during an automated import?  I'd like to configure Sonarr to *always* hardlink (assuming requirements are met), but cannot find a way to do so.

I'm working through some filesystem consolidation to reduce redundant disk use (ie - putting downloads and media on the same filesystem and always using hardlink instead of copying or moving data around). I made the mistake of using "quick import" only to discover that quick import defaults to move, not hardlink.  I'm hoping the automated imports don't do that..

**Comment by markus101** [comment]
Renaming the button isn’t going to change that. Unless the download client indicates the file shouldn’t be moved (a torrent still seeding), it’s going to get moved, there is no hard link only setting. Move Automatically/Quick Import don’t have download client information, it’s always going to be a move.

If you want to discuss this further, 
please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.
