### ISSUE TITLE
Unable to change show from Daily to Standard naming convention

### ISSUE THREAD

**Issue by rrik** [Sonarr/Sonarr#4270]
**Describe the bug**
When changing the Series Type from Daily to Standard, the change does not persist. I have tried deleting and re-adding the show after restarting Sonarr. 

**Screenshots**
N/A

**Logs**
Found daily-style episode for non-daily series: [194751][Conan (2010)]

**System Information**

**UI Bugs:**
 - OS: Unraid Docker
 - Browser: chrome
 - Version: 2.0.0.5344 Mono Version 5.20.1.34

**Additional context**

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

additionally v2 is no longer seeing any  development work

PS a single line that doesn’t show the issue are not proper bug reporting logs (the template explicitly says debug or trace)

**Comment by markus101** [comment]
There originally was a list of series that were considered daily and on refresh they are reset to daily, this is changed in v3, but it makes no difference since the log line you posted rejects all date based release/files if the series is not daily.

If you want to change how daily series are named during import, change the format, because what you’re trying to do will not work.
