### ISSUE TITLE
Delay profiles do not apply to upgrades

### ISSUE THREAD

**Issue by alucryd** [Sonarr/Sonarr#4271]
**Describe the bug**
Delay profiles are working correctly for new episodes, but upgrades are grabbed instantly, usually overwriting something I wanted to keep with an arguably worse version.

**System Information**
* Version 3.0.4.1077
* Package Version 3.0.4.1077-ls35 by linuxserver.io 
* Mono Version 5.20.1.34

**Comment by Taloth** [comment]
Please provide the appropriate log files, used quality profile, used delay profile etc.
Also elaborate on your usecase.

If the release is the highest quality in the quality profile, the delay is ignored. Since Delay Profiles are intended to 'wait for a better release', no point in waiting for something that's already considered 'best possible'.

**Comment by alucryd** [comment]
There isn't much in terms of logs, it just says it grabbed 2 reports from RSS (using jackett), here are the lines:

```
21-1-20 00:08:44.0|Info|DownloadDecisionMaker|Processing 299 releases
21-1-20 00:08:47.2|Info|DownloadService|Report sent to Transmission. [Delivroozzi] To LOVE-Ru S01 [VOSTFR BD x265 10bits 1080p FLAC]
21-1-20 00:08:49.3|Info|DownloadService|Report sent to Transmission. [Delivroozzi] To LOVE-Ru S02 [VOSTFR BD x265 10bits 1080p FLAC]
21-1-20 00:08:49.3|Info|RssSyncService|RSS Sync Completed. Reports found: 299, Reports grabbed: 2, Reports pending: 22
```

Both seasons were already the highest quality possible (Bluray-1080p), and the series is configured as HD-720p/1080p. Delay profile is 7 days and torrent only. With the current system, it shouldn't have grabbed any upgrade in this case, unlike what you can do in radarr with the custom format and rating system, which I quite like to be honest, haven't been able to get the same level of control with sonarr yet, but maybe I'm doing it wrong.

While I'm at it, it's indeed been doing that for series that weren't yet the highest quality, so I assumed this was normal behavior, although I still would like the delay to be applied because some bluray encodes are arguably worse than webdl and even hdtv, so even then I'd like to have a 7-day the delay to make the final decision.

**Comment by bakerboy448** [comment]
Do you have any preferred words set?

the delay only applies for waiting until the best quality is met; if the best quality is met it will grab immediately without delay

**Comment by Thirrian** [comment]
You could let sonarr add the download reports as paused to your client.

**Comment by alucryd** [comment]
> Do you have any preferred words set?
> 

Yes sir, this part works quite well on choosing the best version when I don't have any, however it falls short for upgrades imho, where the radarr custom format score coupled with the upgrade score threshold works wonders, at least in my use case.

> the delay only applies for waiting until the best quality is met; if the best quality is met it will grab immediately without delay

Alright, I understand the design. But shouldn't sonarr stop upgrading when the highest quality is already met? As it is, it seems to grab everything that flies by its radar, regardless of the existing quality.

> You could let sonarr add the download reports as paused to your client.

That is an excellent suggestion, I didn't spent much time in the download client settings page and didn't realize that was possible, thanks!

**Comment by bakerboy448** [comment]
> Alright, I understand the design. But shouldn't sonarr stop upgrading when the highest quality is already met? As it is, it seems to grab everything that flies by its radar, regardless of the existing quality.

there is no cutoff, so there is no “highest” preferred word to stop upgrading.
I wonder if that’s something we should add a option or modify for to delay profiles: delay always even if max quality encountered or existing function Delay unless max quality encountered


As to preferred words not working great; I bet what’s happening is you’re not storing them in the file name; sonarr loses track of the file or otherwise loses the original name; and thus it upgrades regardless.  (Disclaimer: thoughts on this are my own based on my own experience and may not reflect the opinion of the team)

**Comment by markus101** [comment]
I think this should be fixed when https://github.com/Sonarr/Sonarr/issues/3913 is closed.
