### ISSUE TITLE
Add Toggle for Delay Profiles to wait until end of time

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4301]
**Describe the problem**
We previously discussed on Discord a bit.  Currently the delay profile only waits for the best quality releases before grabbing. This may cause a premature grab if a same quality release with a higher preferred words score is released later. 

**Describe any solutions you think might work**
Add a toggle to have the delay profile take the best release at the end of the time (new) or have the delay profile grab the highest quality (existing)

**Additional context**

**Comment by Redundant1** [comment]
Would love to see this implemented as it sounds like it would allow a lengthy enough delay to wait for something like a preferred x265 release before allowing Sonarr to grab the larger x264.  For those of us dealing with data caps, x265 is a godsend, but we're currently limited to **only** allowing x265 and then having to remember to manually download x264 if the episode is still missing later and we're willing to spare the bandwidth.  If we try to prefer x265 over x264–because x265 is almost always released after x264–we usually wind up grabbing both, which only hits our data cap even harder.

**Comment by Taloth** [comment]
Closed in https://github.com/Sonarr/Sonarr/commit/d668e923af83ab7f1589d947fec9f40a3919e0b8
