### ISSUE TITLE
Add Toggle for Preferred Words Upgrade

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4302]
**Describe the problem**
Currently preferred words ALWAYS upgrade.

**Describe any solutions you think might work**
Add a toggle for preferred words upgrades allowed 
**Additional context**

**Comment by markus101** [comment]
How does this work across multiple profiles?
If enabled it would always upgrade, this also needs a cutoff threshold.

**Comment by bakerboy448** [comment]
Some spitballing thoughts:

- a per quality profile upgrade release profile toggle
- a per release profile cutoff
- a per quality profile release profile cutoff
-  a per quality profile release profile by profile cutoff
- a per release profile upgrade toggle

**Comment by jackmeat** [comment]
My issue is some shows only release in HDTV x265 (which i would want to keep) and then get bumped by webdl x264 since i have webdl higher rated. but the inverse also happens with the release type. so having a score (like radarr) would solve this since i can apply that to x265 and then once that is met, it would not then take the webdl version over the HDTV x265 version.

**Comment by Redundant1** [comment]
> You could group all the qualities together and then use clever score of preferred words to achieve that. Something like 265 +100 while all the rest add up to less.

Most of us doing this are trying to prefer 265 to save bandwidth, so we have a delay of a few days before grabs happen in order to allow enough time for the 265 to hopefully show up.  However, if it doesn't show up by the allotted time, we'll allow it to grab a 264 because a 265 isn't guaranteed.  Even if a 264 is scored as a -2 after the delay period, it's still allowed to grab it.  After that grab, if a 265 shows up and is scored as +100, it'll upgrade, which people in this position don't want.

@markus101 Before searching, I was about to suggest closed issue #3129 as a feature to achieve this, but then saw that was already shot down; a pity.  I also saw there that you suggested a Custom Script to accomplish the unmonitoring after an import, but I don't think most of us have the programming skills to write a script.  (I realize that's our problem, not yours, though.  ;)  )

At this point, I have SAB set to pause any duplicate series/season/episode and I periodically go in and clear the alert from SAB, then go into Sonarr's queue and manually delete each paused duplicate.  It's tedious, but my only current option to avoid duplicate grabs.  In trying to automate the removal, I first attempted to use SAB's "Fail job (move to history)" option for duplicates, but that caused Sonarr to immediately grab it again.  I then tried SAB's "Discard" option, but that simply caused SAB to refuse to add it to the queue, throw an alert to clear, and Sonarr was stuck thinking it was still waiting in SAB to be grabbed, resulting in a... status mismatch... between the two programs.

**Comment by jackmeat** [comment]
I still don't get why that "upgrade until custom" that radarr uses couldn't be implemented. I set that to 1, make my custom worth 1 and i never have an issue with movies preferring bluray x264 over webdl x265. it won't go past the x265 after it hits the custom score. So many people continue to say (including me) that it isn't too complex, and works fine. as it is i have to eyeball which releases seem to pop down hdtv x265 and then go and unmonitor that when i see it, if i see it. juggling shows i keep for archiving and finding out after the fact that it grabbed a 1gb single episode when the 150mb x265 looked better and was overwritten in the night really sucks.

**Comment by fryfrog** [comment]
Something like radarr's minimum and cutoff score is probably roughly how it'd end up working in Sonarr. Developer time is likely just the biggest reason it doesn't exist yet. This is a known shortcoming.

**Comment by markus101** [comment]
Being superseded in v4 for custom formats.
