### ISSUE TITLE
Change TBA Behavior; 24hr delay is not effective compared to 24hr TVDB cache

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#4307]
**Describe the problem**
Currently Sonarr has the option to delay importing episodes if the episode is TBA for up to 24 hours.  TVDB's API has a 24 hour cache on it + skyhook's cache + time for the show to update "naturally"; thus it can take upwards of 36 hours for sonarr to not have a TBA title.  Thus the episode will always be imported as TBA and need a manual rename.
**Describe any solutions you think might work**

- Change or add an option to the delay to wait indefinitely until the episode is not TBA

- Increase the wait time to up to 48 hours

- Various other options including notify it can be renamed, automatic rename, etc. But these won't happen

**Additional context**
Alternatively remove the TBA Delay as given the status quo it serves no purpose and simply confuses users.

**Comment by thezoggy** [comment]
generally the whole TBA issue stims from netflix (and any other show that really doesn release all at once) when the show airing does not have the ep titles posted on the broadcaster site until the show goes live. so in the scenario of tvdb, this means a lot of time that the show starts to air and tvdb has TBA, then ep titles get added roughly right before episodes get ripped or right afterwards. then factor in tvdb delays.. its already going to be a min.. then add skyhook and it just delays things more.  this REALLY became a sore spot after the whole tvdb v3 api and the need to cache so aggressively on skyhook. users can just disable the TBA logic and deal with it in the short term, long term.. tvdb's new api****** should hopefully allow the original logic to work as expected, only really need to delay until next tvdb refresh.. so ~12 hour.

**Comment by sfan786** [comment]
> users can just disable the TBA logic and deal with it in the short term, long term.. tvdb's new api****** should hopefully allow the original logic to work as expected, only really need to delay until next tvdb refresh.. so ~12 hour.

How do we do this the TBA issue is happening a lot with my current library

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Sonarr_Settings#Importing

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Comment by willhughes-au** [comment]
> https://wiki.servarr.com/Sonarr_Settings#Importing


I'm guessing you're referring to the setting "Episode Title Required"? 

Unless I'm misreading this page, this option does not seem to exist for me. 

Sonarr Version: 2.0.0.5344

On page `/settings/mediamanagement` there's three options showing, even with Advanced Options showing:  Skip Free Space Check, Use Hardlinks instead of Copy, and Import Extra Files. 

I've checked under the other pages, but I can't seem to find it.

**Comment by bakerboy448** [comment]
Again, 
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

correct that is not an option in v2; and no further development work is planned on v2.

**Comment by Byter09** [comment]
Just found this issue.

Just today I had to manually refresh three series to get the episode titles (the shows I refreshed air tomorrow, but more often than not does Sonarr not refresh till then, so I end up with TBA imports). I already import regardless of whether there is a title available, but the fact that Sonarr still does not automatically refresh a series more often before a release is weird to me - that's the time a lot of metadata gets updated.

One possible solution, I think, would be to refresh a series every 3 hours when the next planned release is in under 24 hours instead of relying on the task that runs only every 24h.

Or am I missing something crucial here, that would make this impossible?

**Comment by thezoggy** [comment]
The fundamental problem is that some episodes titles arent known until the it airs/released. Such is the case for a lot of netflix shows. TVDB has a 24 hour cache on their API. TVDB's API then needs to populate through their CDN cache which takes several hours. Sonarr's Skyhook has a much smaller few hour cache on top of that. Additionally, Sonarr only runs the Refresh Series task every 12 hours. This task can be manually ran from System => Tasks; "Update All" from the Series Index, or manually ran for a specific series on that series' page. 
Therefore for a change on TVDB to get into Sonarr automatically it will typically take between 36 and 48 hours (24 + ~3 + ~3 + 12).
If a series or episodes are missing on TVDB, they'll take 36 to 48 hours from when they're added to populate into your Sonarr instance.
https://wiki.servarr.com/sonarr/faq#tvdb-is-updated-why-isnt-sonarr?


The hope that when tvdb v4 api goes live and is proven stable, it will reduce the time from site data -> tvdb api data happens. Also the skyhook cache timers can be reduced so there is less chance of having stale data. So instead of a 36-48 hour turn around it could* be a lot shorter, which would be a huge step in dealing with this issue. Which we already know was a thing back before this latest api happened.. as it introduced a lot of issues that sonarr had to mask with skyhook and increasing cache timers.

**Comment by austinwbest** [comment]
Is there some logical reason `Always` cant be changed to actually be  `Always` and `Delay` be added to do what the incorrectly named `Always` currently does?

I really dont understand what harm that would cause, but for sure are benefits from it.

**Comment by Byter09** [comment]
So just that I understand this correctly. Instead of reducing the delay to check more often for changed data, you increased the delay to import because TVDB will have updated their data by then?

Definitely a solution that won't increase their API traffic, but now shows will import even later. Is that really the optimal solution? :/

**Comment by bakerboy448** [comment]
> Instead of reducing the delay to check more often for changed data

That won't help in anyway whatsoever.  TVDb's internal API caches for at least 24 hours, so it's not possible to get any data any earlier.

**Comment by Byter09** [comment]
Oh that makes sense then. Thanks :D
