### ISSUE TITLE
Interactive Search "Unable to load results for this episode search."

### ISSUE THREAD

**Issue by giosann** [Sonarr/Sonarr#4329]
**Describe the bug**
When i try to make an interactive search of any episode of "That Time I Got Reincarnated as a Slime" it returns the "Unable to load results for this episode search. Try again later" error.

**To Reproduce**
1. Open any episode of "That Time I Got Reincarnated as a Slime" from the series or from the calendar
2. Click on 'Interactive Search'
3. Wait
4. See error --> "Unable to load results for this episode search. Try again later"

**Expected behavior**
I'm expecting sonarr to load search results passed from jackett

**Screenshots**
![image](https://user-images.githubusercontent.com/10052873/108032450-c9212380-7032-11eb-9215-aa49658cfb35.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker: Yes
 - mono: 6.10.0.104
 - Sonarr Version: 3.0.4.1126
 - Sonarr Branch: phantom-develop

**Trace Logs**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/5986887/sonarr.trace.txt)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](http://webchat.freenode.net/?channels=#sonarr) for support/questions.

The search results returned from the API properly after 70742 ms. Most commonly this issue is a result of a poorly configured reverse proxy that terminated the request before Sonarr returned the results.

**Comment by giosann** [comment]
For any person making it's way here:
As markus101 suggested it was a reverse proxy problem. I am using nginx-proxy on cloudbox and the solution was edting the configuration file found at /opt/nginx-proxy/conf.d/proxy.conf or at /opt/nginx-proxy/proxy.conf and setting the Increase timeout section as follows:

```
# Increase timeouts
send_timeout 100m;
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 30m;
```
