### ISSUE TITLE
Importing anticipated shows via trakt does not honor the Series Folder Format '{Series TitleYear}'

### ISSUE THREAD

**Issue by cppsse** [Sonarr/Sonarr#4346]
I have several lists importing new shows from Trakt (anticipated, popular, topwatchedbyweek, trending).

I have 'Series Folder Format' defined as '{Series TitleYear}' which results in a year being added to all shows.  This is useful for shows like Magnum PI:

Magnum P.I. (2018)
Magnum, P.I. (1980)

However, when shows are imported via trakt lists (anticipated) this format is not always obeyed, especially for upcoming shows.  

Do I just need to disable anticipated shows or is there a way to fix this?

![image](https://user-images.githubusercontent.com/28080250/109246845-cc857f00-7797-11eb-8a3e-3b951ba327f9.png)

**Comment by bakerboy448** [comment]
Markus or Taloth will swing by and correct me and re-open if needed.

If memory serves skyhook/sonarr uses the episodes to determine the year

So I’m going to hedge a guess it’s due to the absence of any episodes thus no year to add.

so assuming anticipated includeds shows that don’t yet have ANY episode information, probably just filter those out
