### ISSUE TITLE
More suitable help text for On Grab and On Download

### ISSUE THREAD

**Issue by tim-durrant** [Sonarr/Sonarr#4351]
In 'Connections', the help text for "On Grab" and "On Download" begins with "Be notified..."

This makes perfect sense if you're setting up - for example - a Pushover notification.

I only noticed this because I was setting up a subtitle check script for all new downloaded episodes.  Obviously "Be notified..." isn't quite relevant for certain use cases.

**Comment by markus101** [comment]
That verbiage applies for all connections, notifications are the most common type of connection. It may not be 100% accurate in other situations, but it's close enough without making it confusing for _most_ of the cases.

If you have a proposed way to word it that applies to all we can see if it makes sense, otherwise this is not really something we intend to change.
