### ISSUE TITLE
Plex db sync

### ISSUE THREAD

**Issue by snickers2k** [Sonarr/Sonarr#4455]
Hey there.

I have massive problems with sonarr recognizing my library (in german language). the recognition is just day and night compared to plex.

So i wish there was an option to import directly from plex. plex already knows the path, metadata (quality, language-profile), and everything one needs (like tvdb/tmdb-id). without having mismatches all the time and without the need for quadrable checks on my (api-hits-limited) gdrive.

right now, i guess the easiest way is to completely rename my library with filebot, to get better results in sonarr :/

**Comment by bakerboy448** [comment]
sonarr library import is meant for an organized library; no plans to change that

my guess is that is the root cause of your issue

no plans to ever import from plex sync functionality

no template followed

and finally, please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

**Comment by snickers2k** [comment]
a library in foreign language is not organized? i dont think so. but okay, got it. sonarr is for english users only.

**Comment by markus101** [comment]
> sonarr is for english users only.

At this time Sonarr only supports English metadata.

> don't allow for feature requests here

Feature requests are allowed, but you didn't follow that template and it was worded as a question, not a request, but for the request aspect, no we don't have plans to sync from Plex.

You could use the API (the UI does everything via the API) to achieve this if you were inclined.
