### ISSUE TITLE
Create empty series folders doesn't work if root folder is empty

### ISSUE THREAD

**Issue by DIDev1** [Sonarr/Sonarr#4473]
**Describe the bug**
I've enabled "Create Empty Folders" to reseed my data storage after a data loss.
But it created the folders only for TV shows (Standard) not Anime ones.

It seems that it was because root folder was empty it didn't started creating sub folders
I don't know if it can affect tv shows too as i already had subfolders in it.

**To Reproduce**

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: YES
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): 6.12.0.122
 - Sonarr Version: 3.0.6.1219
 - Sonarr Branch: develop

**Trace Logs**
2021-05-04 06:06:38.6|Warn|DiskScanService|Series' root folder (/animes/) is empty.

**Comment by bakerboy448** [comment]
This is by design as a fail safe and not a bug.

effectively if the whole folder is missing it's ignored in case say a mount drops out 

with parts like that you will have double space for seeds and copy + deletes rather than atomic moves

https://trash-guides.info/Hardlinks/Hardlinks-and-Instant-Moves/
