### ISSUE TITLE
Acceptable episode format (S##E## vs ##x##)

### ISSUE THREAD

**Issue by xeviff** [Sonarr/Sonarr#4515]
**Is your feature request related to a problem? Please describe.**
There are tons of episodes that Radarr is not able to identify because of the insignificant detail when instead of specify something like "S02E06" the name is "02x06".
It looks like it only want to understand the format "S##E##", and I think it's kind of hardly strict.

**Describe the solution you'd like**
Accept and understand the format "##x##" (case insensitive, and optional zero on the left) in the episodes name retrieved from Jackett. It would enable the compatibility of dozens of trackers with Sonarr. I swear it would be greatfull for a lot of people. 

**Additional context**
Here is the proof:
![image](https://user-images.githubusercontent.com/73612508/119840582-68dd3000-bf05-11eb-886d-2e9e173ad12e.png)

![image](https://user-images.githubusercontent.com/73612508/119839519-83fb7000-bf04-11eb-85df-a3f87040202f.png)

Thanks for your time and have a nice day

**Comment by bakerboy448** [comment]
this is not a sonarr issue it is either a jackett or tracker issue.  sonarr provides jackett the show (either name or id based if supported) and season/episode to search, anything behind that is not a sonarr problem

the search result was not returned by the indexer...if it was it'd be there and be rejected

99.9% chance the search you are doing is not the same search sonarr is doing

**Comment by thezoggy** [comment]
sonarr searches indexers by id (if the indexer supports it/has api) so that way different in formats (usa s#e# vs eu - #x##) doesnt matter. but the season/episode not being right would show up as unknown/something in the list.. look at sonarr logs on whats its querying the server for and its results. it should be obvious what the issue is.. but that one you shown doesnt look valid for the series
