### ISSUE TITLE
Able access /api without API Key

### ISSUE THREAD

**Issue by blmhemu** [Sonarr/Sonarr#4533]
The following image explains it all.
![image](https://user-images.githubusercontent.com/19410501/121629245-63045480-ca98-11eb-9391-e2102a794001.png)

Also, can you make health-check API public? (i.e Without any API key). This will be useful when running in a container or any CO apps.

**Comment by markus101** [comment]
This is due to how the web server under mono handles double slashes, mono passes it through as-is and because the route doesn't match the correct API route is is not getting authenticated by the API, but instead by basic/forms auth (or nothing if you don't have auth configured in Sonarr), under .net (Windows only) this still falls under API auth because the multiple slashes as converted to `/`.

If you don't have auth configured, anybody could log into Sonarr and get the API key then use that to authenticate to the API, so while this appears to be broken it's not something we're going to resolve, it'll be resolved when we move to .net core.
