### ISSUE TITLE
German releases detected as English instead of German

### ISSUE THREAD

**Issue by virusperfect** [Sonarr/Sonarr#4538]
**Describe the bug**
The releases of one of my German trackers don't get detected as German but as English instead. I think the problem is that they use only "Ger" in the name of their releases instead of "German". Releases with "German" are detected correctly.

**To Reproduce**
Releases that gets detected as English:
"Attack.on.Titan.S04E16.Ger.Sub.AAC.1080p.WebRip.x264-Mindus"
Releases that gets detected as German:
"Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ"

**Expected behavior**
I'm not sure if this even unexpected behavior. But I would like releases with "Ger" to also be detected as German and not English.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - .net Framework (Windows) or mono (macOS/Linux) (System -> Status): Mono 6.12.0.122
 - Browser and Version (Only needed for UI issues):
 - Sonarr Version: 3.0.6.1196
 - Sonarr Branch: main

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/6649209/sonarr.trace.txt)

**Comment by thezoggy** [comment]
ger.sub would imply that it only has german subs.. so still english release

**Comment by virusperfect** [comment]
Sorry that was an unlucky example. This also gets detected as being English even though it has German audio:
"To.Your.Eternity.S01E03.Ger.Dub.AAC.1080p.WebDL.x264-TKP21"

**Comment by thezoggy** [comment]
usually the language like "French" / "Spanish" / "German" is used. the three letter abbrv is not standard which is why its never been supported. i assume this is from some torrent site by the name of the p2p releases?

**Comment by virusperfect** [comment]
Yes this is from a private tracker. If you don't plan to support three letter abbreviations I guess can close the issue.

**Comment by markus101** [comment]
If it's not something we're going to support we'll close it.

**Comment by reloxx13** [comment]
there is another somehow related issue. 
after sonarr renames the files, there is no way to get the origin language again if you have to reimport the files. you can add `{MediaInfo AudioLanguages}` to the file name which i "DE" or PL", but sonarr is not able to recognize it as it is not looking for iso codes.

All foreign languages are reimported as english now.

This is noticable if u use tdarr to reencode everything to x265 and rename x264 to x265. now sonarr detects a new file and re-imports it as english instead of german.

On the subtitle regex is iso detection added, nomal language does not have it.
https://github.com/Sonarr/Sonarr/blob/a97e83ea4d610e30902f835ad8d36914baadc323/src/NzbDrone.Core/Parser/LanguageParser.cs#L29

Either add a way to detect iso language code like DE PL RU or add a filename placeholder with the written origin language (german, not deutsch).

if the db every gets corrupted and backup losts, all language informations are lost.

**Comment by thezoggy** [comment]
sonarr language is at the filename/releasename level. not mediainfo data.

**Comment by reloxx13** [comment]
> 
> 
> sonarr language is at the filename/releasename level. not mediainfo data.

then tell me how to preserve the language info?
