### ISSUE TITLE
Monitor "Pilot Episode" fails when new episodes feed in

### ISSUE THREAD

**Issue by Muskehound** [Sonarr/Sonarr#4597]
**Describe the bug**
When adding a new TV show with the Monitor option set to "Pilot Episode", Sonarr will work correctly with the information it is fed at present - i.e. if there are 3 episodes listed, it will monitor the first and set 2 and 3 to unmonitored. However, when further details of the episode run come through at a later date, these are then marked as monitored as opposed to unmonitored as per the initial setup.

**To Reproduce**
Add a show with very limited information on TVDB currently (usually something that hasn't aired)
Mark it to Monitor: Pilot Only
... wait days/weeks for new information to come out
Observe new episodes being marked as monitored

**Expected behavior**
New episodes fed in should be marked as unmonitored

**Platform Information:**
 - OS: macOS
 - Docker: No
 - Mono: 6.10.0.104
 - Sonarr Version: 3.0.6.1265
 - Sonarr Branch: Main

**Comment by bakerboy448** [comment]
[Please edit to actually fill out the bug report template.](https://github.com/Sonarr/Sonarr/issues/new?assignees=&labels=&template=bug_report.md&title=)

My guess is this is due to 1) monitoring being at a hierarchy level; i.e. to monitor a pilot episode the first season and the series must both be monitored and 2) accordingly a bit of a lapse in logic somewhere.

There is probably logic (addition or adjusting) needed so that when the metadata is refreshed sonarr checks the monitored status and unmonitors new seasons/episodes accordingly as needed.

**Comment by markus101** [comment]
> monitoring being at a hierarchy level; i.e. to monitor a pilot episode the first season and the series must both be monitored

This is incorrect. The season's monitored state doesn't affect the episode's monitored state, it's used to control new episodes added to a season, the only two monitored states that apply when grabbing are the episode's and the series'.

> There is probably logic (addition or adjusting) needed so that when the metadata is refreshed sonarr checks the monitored status and unmonitors new seasons/episodes accordingly as needed.

That is how it works already, if the season is monitored new episodes are monitored, if a new season is added it's monitored by default.

The option selected when the series is added doesn't matter after the series is added so there is nothing to adjust there, otherwise if you selected `Future` for the monitoring option every time you refreshed the series any episode already aired would be unmonitored.

The issue here is that the first season (usually season 1) is monitored when the series is added, more episodes are added to the first season later and they are monitored because the season is. The fix is to not monitor the first season when the series is added, just the first episode.

**Comment by Muskehound** [comment]
Thanks, have updated the OP to follow the template and flesh it out a bit, sorry I should've used an existing thread to base mine off, didn't spot I should've kept the headers etc.

I think markus has pretty succinctly understood the issue at hand, so listen to him not me! :)
