### ISSUE TITLE
Sonarr can't grab The First 48 episodes because the scene is screwy

### ISSUE THREAD

**Issue by bmtphoenix** [Sonarr/Sonarr#4619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The First 48 never gets correctly downloaded because of the scene being a complete mess. Also, I'm not sure why this is, but Sonarr is somehow coming up with 1700+ releases for every search, while manually searching Jackett yields far fewer and more relevant results. 

### Describe the solution you'd like

Please change how Sonarr searches for "The First 48"

Search using "First 48" +episode title 
and if it doesn't find anything, try "First 48 s00e00" 
and then also try "First 48 Hours s00e00" because some people have added "hours" to differentiate it. 

For season packs, "First 48 Season 11"
then "First 48 S11"
then "First 48 hours s11" and "First 48 hours Season 11"

The episode titles rarely match Sonarr's season and episode, so searching by episode title first would be good. This is the best way I've found to search for them.

### Describe alternatives you've considered

Manually searching for the ep title name, or removing "the" from the search, is sometimes helpful, but it's not easy to see if you actually have the correct episodes without going through and checking/renaming them. 

### Anything else?

Image shows the difference between in results in manual search via Jackett vs Sonarr. 
![sonarr first 48](https://user-images.githubusercontent.com/6809957/128789673-6a893142-4802-4ac5-aec9-d9f777f2b454.jpg)

**Comment by bakerboy448** [comment]
> somehow coming up with 1700+ releases for every search

this is not sonarr; this is indexers either 1) returning poor and signifcant results due to mismatch ids and associations on their end or 2) an indexer that does not support an id based search and thus you're at the mercy of text queries.

Specific coding to handle a specific show is just about likely to never be added.

Since you're using jackett, sonarr is passing a torznab request then. anything beyond that including how search is handled on the website is a jackett (or prowlarr) or site issue and not a sonarr issue (999/1000 times)


> Image shows the difference between in results in manual search via Jackett vs Sonarr.

Wrong image? That shows nothing of use?  Can't see what was queried on jackett's end; don't have any information as to how sonarr searched (trace logs that the template notes) and don't even show results of a search in Sonarr.


>Search using "First 48" +episode title
and if it doesn't find anything, try "First 48 s00e00"

No plans to spam indexers with more hits then necessary.  Sonarr will pass the series and season info based on what jackett claims the indexer supports. from there it's jackett's problem.

> and then also try "First 48 Hours s00e00" because some people have added "hours" to differentiate it.

this is covered on the FAQ and the search [troubleshooting](https://wiki.servarr.com/sonarr/troubleshooting) as a common problem; not a code change.

> For season packs, "First 48 Season 11"
> then "First 48 S11"
> then "First 48 hours s11" and "First 48 hours Season 11"

This is a jackett problem to solve on a site by site basis not a sonarr issue. Sonarr will pass the season/episode and series info in a standardized torznab request to jackett/prowlarr/hydra based on the capabilities they report the indexer has. How those are handled from there has nothing to do with sonarr.

Working through this; it's a support question, not a feature request.
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.
