### ISSUE TITLE
Sonarr using old Let'sEncrypt Root certificates?

### ISSUE THREAD

**Issue by instylegithub** [Sonarr/Sonarr#4668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Seems like any indexers, etc... Using letsencrypt SSL certificates fail Certificate Validation if enabled under Settings > General > Certificate Validation > Enabled

### Expected Behavior

Certificates should pass checks.  Also Radarr is fine.

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.6.1335
- Docker Install: no
- Using Reverse Proxy: yes
- Browser: n/a
```

### What branch are you running?

Main

### Anything else?

This issue started Sept 30th:
https://techcrunch.com/2021/09/21/lets-encrypt-root-expiry/

**Comment by PearsonFlyer** [comment]
There was a new main commit less than 2 hours ago that fixes this. Update and it should be solved.

**Comment by instylegithub** [comment]
Thanks!

**Comment by humanthrope** [comment]
I haven't been able to get this to work. I see commit 0d99c87d873. Does this mean we need mono 7.x for this fix?

**Comment by Taloth** [comment]
No, it doesn't mean that. Also, mono 7 doesn't exist. It simply means that a workaround that was in place for mono version below 6.10 has been extended to include newer mono versions as well since mono didn't fix an issue in their code.

If you properly updated Sonarr and your OS, seek support on discord, irc or forums.
