### ISSUE TITLE
Pilot Episode Only not working for new releases

### ISSUE THREAD

**Issue by wizzardking** [Sonarr/Sonarr#4695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Through the lists it continuously adds new series. These are automatically set to "Monitor: Pilot Episode", because I want to see only the first episode of a new series to decide if I should add it to my repertoire.

However, as soon as new episodes appear after adding the series, they are automatically monitored, even if when importing through the list it was originally selected that it should only download the pilot episode.

### Expected Behavior

Until I change something manually, only the first episode should be monitored.

### Steps To Reproduce

1. Add a Series with the settings "Monitor: Pilot Episode"
2. Wait until new episodes will be released

### Environment

```markdown
Docker on a Qnap NAS.
```

### What branch are you running?

Develop

### Anything else?

-

**Comment by bakerboy448** [comment]
Closing 
- user did not search, this is a duplicate post https://github.com/Sonarr/Sonarr/issues/4597
- Template and required information not filled out


Please actually search next time

For future bug reports - complete the template in full and do not ignore required information.

you're likely out of date given this was fixed in Aug - update
