### ISSUE TITLE
Do Not Import Files that Do Not Have Matching Titles/Aliases

### ISSUE THREAD

**Issue by DevYukine** [Sonarr/Sonarr#4826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Sonarr currently does ignore filenames for newsnab entries with a wrong TVDB Id which is problematic as Usenet Indexer sometimes bad match uploads themself which causes wrong downloads and even import.

My Example was that this Release `MacGyver.1985.S01E21.1080p.BluRay.REMUX.AVC.DD.2.0-NOGROUP.mkv` which was on my indexer wrongly matched to TVDB Id `311902` which is the new 2016 Show, Sonarr did not match filename here whatsover and imported successfully even tho the year in the filename clearly states that its the 1985 show, not the 2016 one.

### Describe the solution you'd like

Sonarr should not trust Indexers blindly and in my example problem should've not successfully imported a file which in the name already provides a year which shows that it's not the correct series. Usenet Indexer are mostly automated and only have humans fine tune it so release of shows which got remastered / a new show after a while which are wrongly mapped are common and will happen from time to time.

### Describe alternatives you've considered

Sonarr could've avoided this in many ways, either completely ignore this one on the RSS sync and not downloading it or failing in import and let ppl manually check before importing when years mismatch more than 1 year (over 36 years in this case is pretty obvious that its not the same show) but either way it should've not replaced my current season with this 

### Anything else?

Not really no, should explain my issue / feature request pretty well

**Comment by markus101** [comment]
For grabbing, title matching does not matter when the indexer supplies a TVDB ID, otherwise any difference would result in it begging rejected, there is trust there that they’re providing a valid ID.

I agree that an import should not happen if titles matching fails, though that gets tricky with how the queue functions in order to properly track things, previously we were rejecting things that had mismatched titles, but that changed/broke somewhere along the way.

This is similar to https://github.com/Sonarr/Sonarr/issues/4698 in some ways.
