### ISSUE TITLE
Connect trigger on moves

### ISSUE THREAD

**Issue by edrock200** [Sonarr/Sonarr#4842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Presently connect triggers on grab/import/delete/rename/upgrade, but doesn't appear to send a notification if an item is moved, e.g. moved from one root folder to another or has it's parent folder renamed. 

### Describe the solution you'd like

Add a connect trigger for moves that triggers for the source and destination folders.

### Describe alternatives you've considered

Have attempted all connect options but doesn't work in my testing. 

### Anything else?

Thanks in advance for your consideration.

**Comment by markus101** [comment]
Move is a unique case, the most obvious reason for an event to trigger on move would be to update the series in a media player, but the only way to achieve that would be to refresh every single series, otherwise Sonarr just tells the media player app to refresh that series, which would result in it removing the episodes because they no longer exist in the expected location.

Moving series to a new drive would take time and if the media player doesn’t know about the nee location it won’t actually rescan the files and having it rescan all for every series that could be moved would result in a mix of updates that are adding and removing files for different series.

Because of all the edge cases this isn’t something Sonarr will trigger an update for.

**Comment by edrock200** [comment]
Thank you for the response. Just want to ensure we are talking about the same thing. Example scenario:
I have Plex, it has tv shows with /root/path/1/ and /root/path/2/ as members. In sonarr I move a show from path 1 to path 2. Sonarr sends triggers for /root/path/1/Show and /root/path/2/Show. Plex, from my experience, will target scan those folders, it won't refresh everything. If those folders are gone, it will delete from the db.

The scenario you are referring to is moreso how Emby works. It won't target scan a folder that hasn't existed prior, it will scan the entire root. 

But for Plex, it would be an efficient scan process. I hope I'm describing this in a manner that makes sense. If still not possible, no worries and thanks for taking the time to review!
