### ISSUE TITLE
Download Clients with Duplicate File entries are re-imported on completion

### ISSUE THREAD

**Issue by brettpetch** [Sonarr/Sonarr#4852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Files imported directly from the client watch category are being re-imported after duplicates complete (for x-seeders with multiple of the same torrent in the same category this can result in wasted io operations). Pretty much what happens is after Some.Release.S01E01.whatever.mkv gets imported, and the same release with the same name/filesize/creation date Some.Release.S01E01.whatever.mkv is added to the same category, the application reimports the Some.Release.S01E01.whatever.mkv for each time it's in the queue.

TLDR: Essentially it sees the release in the download queue category and reimports even if the file is redundant.

### Expected Behavior

Ideally, we would have the file checked to ensure that it is not a duplicate before import, then have it decide to import or ignore the release entirely.

### Steps To Reproduce

1. Use a client like autodl to automatically download releases into the sonarr watch category, downloading multiples of the same file for x-seeding.
2. Watch Sonarr reimport.

### Environment

```markdown
- OS: Debian 10
- Sonarr: 3.0.6.1342
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox
```

### What branch are you running?

Main

### Trace Logs?

Unneeded. essentially it sees the release in the download queue and reimports even if the file is redundant.

### Anything else?

no.

**Comment by markus101** [comment]
This is expected behaviour. Sonarr will import equal quality releases as that can allow for replacing a bad release with a different one that wasn't released as a PROPER/REPACK. Previously Sonarr would reject the exact same release (based on quality/file size), but that lead to some weird edge cases and was removed almost two years ago: https://github.com/Sonarr/Sonarr/commit/be3b3df9036ca7d4f970fffc53af5e4d553ab0e5 we do not have plans to re-introduce it.
