### ISSUE TITLE
Wrong air date is displayed and used for file date when local air time isn't set in TheTVDB

### ISSUE THREAD

**Issue by brossow** [Sonarr/Sonarr#4853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary
When the air time for a series isn't set in TheTVDB, the air date is showing the wrong date/time in the Sonarr UI, and the file modified dates aren't changed during import/rescan when Local Air Date is selected in the settings.

### Details
Under Media Management, I have the Change File Date setting set to Local Air Date. If I change that setting to UTC, the file modified dates are updated, but with the wrong date. Changing back to Local Air Date has no effect on UI or file dates on rescan. This applies at least to US series; I haven't checked series from locations that would have had UTC/GMT air dates (e.g., UK series) but assume any time zone west of UTC would be similarly impacted.

For example, _Knight Rider_ premiered on September 26, 1982. However, when I click on the episode in Sonarr, it says it aired on September 25 at 11 PM. I'm getting the same thing with (for example) _The Waltons_, so it's not specific to a series. Other series are fine (e.g., _The Masked Singer_) and show the correct date and time. This appears to correlate directly with whether the series has an air time listed in TheTVDB or not. No air time listed = wrong air date displayed in Sonarr.

Similarly, I've noticed Sonarr isn't changing the file modified date/time for those same series/episodes (that is, it's not changing the date at all) when Local Air Date is selected in the settings. If I change the Change File Date setting to UTC and rescan the series, then it updates the file dates -- but with the wrong dates, the same as those displayed in the Sonarr UI. If I flip the setting back to Local, it does nothing for the file date nor for the date displayed in the web UI. Everything behaves as expected for series with a local air time listed in TheTVDB.

If this has been discussed previously, I apologize. I searched and didn't find anything similar, here or elsewhere, prior to posting.

### Expected Behavior

1. Episodes should show the correct air date in the web UI even when a specific local air time hasn't been set in TheTVDB.
2. File modified dates should reflect the correct local air date even when a specific local air time hasn't been set in TheTVDB. Perhaps default the time to noon to further mitigate time zone issues? Just an idea, but maybe not a good one.

### Environment

```markdown
- OS: Synology DSM 7.0.1-42218
- Sonarr: Sonarr 3.0.6.1342
- Docker Install: Yes, version 20.10.3-1239 using image from linuxserver/sonarr:latest
- Using Reverse Proxy: No
- Browser: Chrome 97 and others, but not relevant to this issue
```

### What branch are you running?

Develop

### Trace Logs?

See below. I enabled trace logging, then rescanned _Knight Rider_. Please let me know if you need more logging.

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/7864986/sonarr.trace.txt)

### Anything else?

I've verified this on different computers on different networks and in different web browsers (Chrome, Firefox, etc.). The server date and time zone are correct.

**Comment by thezoggy** [comment]
Knight Rider - tvdb: 77216 
tvdb says " Friday, at 9:00pm " which means nothing to most. its supposed to be the original airing time slot of the main region which could be east or west cost usa. then sonarr takes the data and converts the time to utz and normalizes things (because tvdb has some wildly bad data a times for series start). then you also have things like daylight savings.

so looking at skyhook (tvdb proxy):
https://skyhook.sonarr.tv/v1/tvdb/shows/en/77216

you can see s01e01 airdate is "1982-09-26T04:00:00Z"

so that looks to be PDT (not PST) of 9pm -> utc. 

but i have to ask, a series that aired decades ago and is not airing.. why does this matter?

**Comment by thezoggy** [comment]
and also all this is moot until tvdb v4 which may 'fix' the whole airing if they add timezone on their data and do airing slot per season/episode rather than globally for the series

**Comment by markus101** [comment]
Air time is vital to show the correct air date because the local air date relies on the air date, the air time and the network it airs on, without an air time it'll be treated as airing in 00:00, which for NBC network was -4 UTC, then that gets translated to UTC, so 04:00 UTC, so the first episode shows as airing at `1982-09-26T04:00:00Z` instead of `1982-09-27T01:00:00Z`.

This is a data issue, not a bug in Sonarr, once the air time makes it through TheTVDB's cache, then skyhook and into Sonarr it'll be fixed.

**Comment by brossow** [comment]
@thezoggy I should have mentioned, but obviously forgot to do so, that I updated the air day/time for _Knight Rider_ in TheTVDB myself, and I just got a notification that my request to add it to _The Waltons_ was done for me (since the series is locked). Other series would need to be used to test/demonstrate this.

**Comment by thezoggy** [comment]
sure, just was stating that sonarr uses data from tvdb and can only go off what they have. which may or maynot be correct or anything at all. its crowdsourced so someone needs to update tvdb. eventually it will show up in skyhook -> sonarr.  it is what it is for now. and about series locked, you need to submit a ticket with tvdb to get a mod to update it.

**Comment by brossow** [comment]
@thezoggy Yup, I know about TheTVDB ticket system. That's how I got them to add the info for that series as mentioned. I appreciate the input and information here. I was just trying to help despite clearly being unaware of all the things involved in making the magic happen. 🙂
