### ISSUE TITLE
package_info only works if arr is installed in a directory bin/

### ISSUE THREAD

**Issue by mvanbaak** [Sonarr/Sonarr#4859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Package and release configs can be forced with a file `package_info` and `release_info` using the `DeploymentInfoProvider`
This only works if the `appFolderInfo.StartUpFolder` has `bin/` as last part
See https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Configuration/DeploymentInfoProvider.cs#L43

On `FreeBSD` the arrs are installed in `/usr/local/share/sonarr` and thus dont have `bin/` as last directory part.
This means the package_info and release_info dont work there.

### Expected Behavior

`package_info` and `release_info` in the directory where the Sonarr/Radarr/Prowlarr binary is located sholud be read by the application

### Environment

```markdown
- OS: FreeBSD 13.0-RELEASE-p6
- Sonarr: 3.0.6.1342 But I'm testing this with Radarr and was told to create the issue here under Sonarr.
- Radarr: 4.0.2.5836
- Docker Install: No, using pkg from FreeBSD
- Using Reverse Proxy: No
- Browser: Safari 15.2 (17612.3.6.1.6)
```

### What branch are you running?

Main

### Trace Logs?

N/A

### Anything else?

N/A

**Comment by Taloth** [comment]
This is intentional, when preparing for the v3 releases we wanted more consistency. And therefore package_info handling is limited to when the binaries are placed in a bin subdirectory, that subdirectory is 'owned' by the release, whilst the parent (and thus the package_info itself) is owned by the package.

We have no plans to adjusting this behavior.

**Comment by mvanbaak** [comment]
I will change the layout of the FreeBSD package so it is installed in `/usr/local/share/sonarr/bin` with the `package_info` in `/usr/local/share/sonarr`
It does make sense, although the `bin/` looks weird ;P

Thanks for explaining the why behind this layout.

**Comment by Taloth** [comment]
btw. one of the thoughts behind it was that at one point we wanted the build-in updater to create bin_3.0.6.xxxx during update, and rename the folders quickly... then restart Sonarr, instead of having the updater copy individual files.
By having a bin folder, we can make more assumptions about what's in there. So that's what we did for the debian package.
That's not that relevant for third-party packages which tend to lock it down. But there's an advantage to some consistency.
