### ISSUE TITLE
Better support for non-Latin languages

### ISSUE THREAD

**Issue by J4gQBqqR** [Sonarr/Sonarr#4886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

There are always multiple ways to written down Asian characters, for example, 

1. Korean
    - 장호근
    - 張民好
    - 张民好
    - Jang Minho
2. Japanese 
    - 稲葉浩志
    - 稻葉浩志
    - 稻叶浩志
    - Inaba Kōshi or Inaba Koshi
3. Chinese
    - 鄧紫棋
    - 邓紫棋
    - Deng Ziqi
    - Tang Tsz Kei

This does not have to be Korean or Japanese names. For example, in anime series, different indexes sometimes follows different convention and represent Korean/Japanese/Chinese series title with different names. More often than not, an automatic search query will **partially match on one indexer and completely miss on another indexer**.

This creates serious difficulties for international titles encoded in non-Latin characters.

Due to the flexibility of Language representation and the huge amount languages in this world, it would be almost impossible for Sonarr to try to cover each and every scenario.

### Describe the solution you'd like

1. Provide a search entry override feature in "interactive search" that allow user to override any search string that is going to be sent to the search engine, and still choose one of the search result to be imported into the current series.
2. Enable user to skip search indexer and override the search result directly with "a magnet link", "a torrent file" or "a usenet link"; and import the downloaded files like interactive search.

### Describe alternatives you've considered

If the developer would like some challenge, one could consider an implementation to automatically decode/encode/transcode to support all these variances in all different languages:
1. Korean
    - 장호근
    - 張民好
    - 张民好
    - Jang Minho
2. Japanese 
    - 稲葉浩志
    - 稻葉浩志
    - 稻叶浩志
    - Inaba Kōshi or Inaba Koshi
3. Chinese
    - 鄧紫棋
    - 邓紫棋
    - Deng Ziqi
    - Tang Tsz Kei

### Anything else?

#1128 is not really a solution. This ticket is trying to propose a way to override "search string"/"search result", but still import the downloaded result into Sonarr.

**Comment by markus101** [comment]
1. #1128 is the closest we have planned for this, but realistically this is probably better suited for Jackett or Prowlarr. I know you said it's not a solution, but unless Sonarr can parse it, it's not going to import it, because this can lead to overriding the wrong thing, even if Sonarr understands it to be something else. Aliases/alternative names are the best way to get Sonarr to understand alternate titles, whether they're in English or any other language.
2. Sonarr already supports processing manually grabbed downloads from your download client, but it needs to be in the correct category (or subfolder for download clients that use subfolders for categories).
