### ISSUE TITLE
v3.0.9.1549 Malforms my database disk images

### ISSUE THREAD

**Issue by Rojikku** [Sonarr/Sonarr#5115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Context: I noticed this issue immediately upon upgrading to the new version. Restoring to previous backups fixed the issue for less than five minutes, before I got corruption messages again. Downgrading fixed the issue. I wrote up a really nice report for it, went to get logs...and couldn't reproduce it when I upgraded again. 

System ran fine for about 3 days, then I noticed today it was malformed again. Tried to restore, noticed my last backup is when I previously downgraded, which is a known good I ran for 3 days. Disk still malforms.

In this testing I restore my backup, set logging to trace, disabled my downloader (Because I have the episodes it just doesn't know it), and let it run.

### Expected Behavior

Just run without corrupting my databases?

### Steps To Reproduce

1. Running in Kubernetes using a docker image of v3.0.9.1549 https://github.com/Rojikku/k3s/blob/main/cluster/apps/vpn/sonarr/helm-release.yaml as specified
2. Run the program literally at all apparently
3. Database corrupts itself before it even gets far into scanning my library

### Environment

```markdown
- OS: Linux
- Sonarr: v3.0.9.1549
- Docker Install: Yes
- Using Reverse Proxy: Yes
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/9324718/sonarr.trace.txt) It's this one
[sonarr.trace.0.txt](https://github.com/Sonarr/Sonarr/files/9324719/sonarr.trace.0.txt) From the moment I reloaded after the restore and switched to trace logging.

### Anything else?

Nothing else. https://github.com/Rojikku/k3s/pull/743 is my changelog for switching versions since the issue emerged. Ended up keeping latest because I wasn't able to reproduce for several hours...But it returned.

**Comment by markus101** [comment]
The only change to the database was adding support for Malayalam and Ukrainian languages, no libraries were updated or replaced. You can view the full list of changes here: https://github.com/Sonarr/Sonarr/compare/v3.0.8.1507...v3.0.9.1549

We've seen no other reports of similar corruption in this release, but regardless, please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) to troubleshoot the issue further.

If your database is not running on local storage (because you're running it in a cluster) there is a higher probability that of database corruption depending on how it's configured and not something we recommend with a sqlite DB.
