### ISSUE TITLE
Quality Maximum Set by API Not Recognized as Unlimited

### ISSUE THREAD

**Issue by owine** [Sonarr/Sonarr#5149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting a quality maximum (`maxSize`) via the UI sliders, the maximum is recognized as `Unlimited` while the text field displays `400`.

When setting a quality maximum via API to 400 (and viewing on the UI), maximum is `23.4 Gb/h`.

The result is that releases can be incorrectly ignored for being too large.

### Expected Behavior

Setting value to `400` via API should recognize as unlimited.

### Steps To Reproduce

Set quality maximum to 400 via API
Observe via UI, slider is at the maximum, value is parsed as `400` rather than intended `Unlimited`

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.0.2178
- Docker Install: Yes (sonarr-851a7ce by hotio)
- Using Reverse Proxy: Yes - Traefik
- Browser: n/a
```

### What branch are you running?

Develop

### Trace Logs?

to come

### Anything else?

When set via slider
![CleanShot 2022-09-09 at 14 48 08](https://user-images.githubusercontent.com/4283702/189431886-af8f35b3-27e3-4c8e-8e9e-fe0c17ccaf9c.png)

When set via API
![CleanShot 2022-09-09 at 14 47 59](https://user-images.githubusercontent.com/4283702/189431892-d77d17b7-d24a-4863-8ac1-220f96426c21.png)

Note: This can be slightly worked around by setting `maxSize` to `null` but I believe respecting `400` as `Unlimited` is likely the intended/preferred behavior.

**Comment by markus101** [comment]
The UI also uses the API. The UI shows 400 because it needs to be within the bounds of the slider, the actual value sent is `null`.

**Comment by davidnewhall** [comment]
And you have no intention on fixing that API implementation? Interesting choice.

**Comment by markus101** [comment]
No, no plans to change the API, leaving null as unlimited and 400 at 400 allows the limit to be increased later if necessary (it's already been done once for 4k). If anything the UI could show a different value when unlimited, but that gets complicated.

**Comment by davidnewhall** [comment]
```
if new_limit == hardCodedMaxLimit {
  new_limit = null
}
```
Would a conditional like this not also allow you to increase the max later if necessary too? The problem with hiding a `null` value in a float or int is that it is then no longer a float or int in many json implementations. Golang, being the one I'm interested in. Even adding a new field like `"max": bool` would alleviate this problem. This isn't just a UI display problem, this is a third party application integration problem.  

Questions 2 and 3: 
Does Sonarr treat the omitted field as `null`? Does Sonarr return `null` via API when the max is selected?

**Comment by davidnewhall** [comment]
I'm also curious if `"maxSize": 0` could accomplish the same thing?

**Comment by thezoggy** [comment]
> ```
> if new_limit == hardCodedMaxLimit {
>   new_limit = null
> }
> ```
> 
> Would a conditional like this not also allow you to increase the max later if necessary too? The problem with hiding a `null` value in a float or int is that it is then no longer a float or int in many json implementations. Golang, being the one I'm interested in. Even adding a new field like `"max": bool` would alleviate this problem. This isn't just a UI display problem, this is a third party application integration problem.
> 
> Questions 2 and 3: Does Sonarr treat the omitted field as `null`? Does Sonarr return `null` via API when the max is selected?

so setting the max limit of null, means whatever version of sonarr the user is running its using the 'max'.  if you were to just send over 400. lets say older sonarr may not have that upper bounds..  maybe 250 was its max?  then if you use 0 to mean max.. it gets messy because lets say min is 10. so then range is 10 to 0, which is confusing and prone to issues.  is the issue you cant send null  (dont set a value)?

**Comment by davidnewhall** [comment]
> 0 to mean max.. it gets messy because lets say min is 10. so then range is 10 to 0, 

If `0` means max, then this makes sense to most programmers - the people most likely to be dealing with API calls and json payloads. Even `-1` is easier to program in than `null`. The UI wont let you set max to 0 if min is set to 10, so the confusion isn't really going to happen with users. I'm just trying to suggest allowing for something other than `null` to indicate max so third party devs can get expected behavior. I can absolutely work around this, but it took a week to even realize it was a bug - the behavior is just unexpected.

I don't want y'all to dig into this yet. I need to do more testing; I sort of think passing 0 is setting it to max anyway, so my suggestion may be moot.

Appreciate the responses!
