### ISSUE TITLE
Consider download failed if episode language doesn't match profile

### ISSUE THREAD

**Issue by KucharczykL** [Sonarr/Sonarr#5225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have set all shows to be downloaded in their original language, let's call it $LANGUAGE1. Sometimes, due to bad metadata, an episode is described as $LANGUAGE1 but after downloading and getting its media info, it turns out to be $LANGUAGE2.

This passes as successful because even though Sonarr has the capability to detect audio track language, it doesn't use it after the episode is downloaded.

### Describe the solution you'd like

If, after an episode is downloaded, it turns out that language of the episode is not the language set in the profile, mark the episode as a failed download and grab a new one.

### Describe alternatives you've considered

Use Release Profiles and set Must Not Contain or Preferred. This is VERY unreliable and gets increasingly complex as you try to wiggle around the many filenames that people can come up with.

### Anything else?

N/A

**Comment by markus101** [comment]
Do you have a concrete example of this?

**Comment by KucharczykL** [comment]
I have an anime that is set to Japanese language profile, but it downloaded a few episodes in English. The indexer didn't provide any language information so it just downloaded whatever it scored highest I suppose.

**Comment by markus101** [comment]
Looking for specifics on all that, https://github.com/Sonarr/Sonarr/pull/5173 + Custom Formats should help a lot, but more information should help confirm.

What was the release name?
What Language did Sonarr think it was when it grabbed it?
What does the Language profile look like?
What actual language tracks are in there?

Realistically we're unlikely to treat a download as failed because the language is wrong, but maybe it's a scenario where it makes sense to do _something_, but we need more information.

**Comment by KucharczykL** [comment]
I am ashamed to say that I didn't notice that my profile was set to English. If I later discover that it still happens despite that, I will let you know.
