### ISSUE TITLE
Calendar: reveal full title on mouseover if truncated

### ISSUE THREAD

**Issue by dnnr** [Sonarr/Sonarr#537]
Currently, if a series title is too long and truncated in the calendar, the only way to see the full title is to click the entry and close the modal window afterwards. When a string is truncated, the usual expectation is that hovering reveals the full string in a balloon after a certain delay.

And I'd like to piggy-back a suggestion here: I read in the forums that episode numbers are deliberately omitted in the calendar to keep the interface clean. How about adding this information to the balloon? This would be especially useful when multiple episodes of the same series are aired on the same day.

**Comment by markus101** [comment]
Originally the calendar did show extra information on mouse over, but it ended up causing a number of issues with the popovers getting stuck, didn't really fit well with the design and doesn't work on mobile.

Design wise mouse overs at that density are awkward because you eneivitably end up with a tooltip covering something you want to click on which leads to people wanting to be able to trigger a search from the popover.

The modal let's us have consistency across multiple entry points.

I'm closing this, but if @kayone or @taloth disagree they can reopen it.

**Comment by dnnr** [comment]
Good points. Just a quick follow-up: have you considered using "native" tooltips (alt-texts or whatever they're called) instead? Those are usually pretty robust with regards to getting stuck, and much more lightweight than a custom popover.

**Comment by SAKUJ0** [comment]
I believe "alt-texts" are attributes for only a select number of HTML tags that are associated with images (like IMG).

**Comment by dnnr** [comment]
Well, SPAN does support the "title" attribute, and most browsers render it as a tooltip, just like alt-texts on images. Actually, I couldn't think of a more literally correct use of this attribute. It *is* the title after all.

**Comment by Taloth** [comment]
@markus101 Only option would be to animate height on hover to fit the whole title. But I totally agree on the risk of feature creep.

Although I wonder: why is this so important? In 99.9% of the case the readable part of the title should be enough to identify it.

So yes, I second closing the issue.
