### ISSUE TITLE
Improved automation for new series discovery, import

### ISSUE THREAD

**Issue by bugmancx** [Sonarr/Sonarr#5410]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In some cases, media collections can be modified from outside of Sonarr, and this may include the addition of new shows to the root directories that Sonarr monitors.

Although Sonarr has the ability to detect when there are unmatched directories in these and the user can import any new shows through the manual import feature, this is a slow process because it must be done manually for each root directory. In some cases there can be many of these (especially libraries which are split up into per-letter root folders and so on.)

### Describe the solution you'd like

Sonarr should include the option to display all newly detected shows from all root directories combined into a single page and allow the user to check the matches and import them. Importantly, and this may be a separate feature, Sonarr should allow users to ignore (via a toggle) certain folders from being matched on future attempts (this is because you may occasionally have directories which will never match for various reasons, and you don't want to keep having to deselect/skip these over and over and over again each time you use the import feature.) Users should have the option to skip ignoring these if they want so that they can be matched if new metadata appears in thetvdb / other reasons.

This would make the detect/import feature more useful in situations where new shows get added outside of Sonarr and then need to be imported into Sonarr for montoring.

### Describe alternatives you've considered

None

**Comment by markus101** [comment]
No plans to merge root folders into a single view when importing series or ignoring folders within root folders.

**Comment by bugmancx** [comment]
Isn't this the point of suggesting a feature? You're just one person saying "No" and closing it without further consideration. Are you saying that you have already discounted this idea before, and if so, why?

**Comment by markus101** [comment]
Sure, you suggested a feature and it's not something I think would bring a lot of value because it fits a niche use case. When we don't intend to implement a feature request we close it.

No, I'm saying I looked at your request and your reasoning why you wanted it and thought about the impact of making such a change and the potential for additional feature requests that could come in a deal with an edge case and I don't think it's worth it.

> especially libraries which are split up into per-letter root folders and so on.

This is more of a workaround, Sonarr supports creating subfolders per letter by setting the `Series Folder Format` to something like: `{Series TitleFirstCharacter}\{Series Title}`, the problem is that Sonarr couldn't parse those back properly, with https://github.com/Sonarr/Sonarr/commit/81d2b18ce1c079c2a9dc3de037c9dceea16733fd if you add one root folder and use that format Sonarr will look into the letter subfolders for the series folders for unmapped folders.

I (and most of the support/moderators) would recommend having Sonarr add the series/creating the folders and then consume them else where.
