### ISSUE TITLE
Newznab downloading feed error

### ISSUE THREAD

**Issue by astalush** [Sonarr/Sonarr#5420]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The search within sonarr v4 shows only the torrent indexer results and not the Newznab results.
I've searched in the logs and the problems seems to be the capital letters for season and episode when the api does the search.

Example : https://nzbs example site/api?t=tvsearch&cat=5040,5045&extended=1&apikey=removed&offset=0&limit=100&q=Velma&season=1&ep=7 - doesn't work
https://nzbs example site/api?t=tvsearch&cat=5040,5045&extended=1&apikey=removed&offset=0&limit=100&q=Velma&Season=1&Ep=7 - WORKS

### Expected Behavior

The xml file with the results show the releases when using Season / Ep instead of season / ep

<newznab:response offset="0" total="0"/> when using season / ep
<newznab:response offset="0" total="92"/> when using Season / Ep

### Environment

```markdown
- OS: Debian 11
- Sonarr: v4 Develop 4.0.0.371
- Docker Install: 
- Using Reverse Proxy: Nginx
- Browser: Brave / Chrome / Firefox
```

### What branch are you running?

Develop

### Trace Logs?

2023-02-08 01:00:46.7|Debug|Newznab|Downloading Feed https://nzbs example site/api?t=tvsearch&cat=5040,5045&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=396625&tvmazeid=53473&season=1&ep=7
2023-02-08 01:00:46.8|Debug|Newznab|Downloading Feed https://nzbs example site/api?t=tvsearch&cat=5040,5045&extended=1&apikey=(removed)&offset=0&limit=100&q=Velma&season=1&ep=7

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Sounds like that indexer isn't following the specification or that causes he indexer to ignore those parameters and gives back results that are otherwise failing to return, but regardless this is something the indexer will need to resolve.
