### ISSUE TITLE
Sonarr only gets partial history

### ISSUE THREAD

**Issue by hr1232** [Sonarr/Sonarr#5452]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

On systems with low CPU power, downloads happen faster than post processing. In situations with large queues (e.g. just added a few old series with several thousand episodes), the post precessing queue can be quite large with thousands of releases waiting for post processing.

Sonarr doesn't check the entire history queue (why?), but only part of it. Function [GetHistory()](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs#L108)) limits amount of queue items to `_configService.DownloadClientHistoryLimit`. Therefor, Sonarr doesn't see all items in the queue; it looks to Sonarr, as if some of the items were deleted in SABnzbd.

To make matters worse, Sonarr gets the youngest items in history queue and not the oldest ones. Because of this error, finished releases will be ignored as long as history queue contains more than `_configService.DownloadClientHistoryLimit` unprocessed releases. Sonarr will only continue to import episodes after the number of unfinished releases is lower than `_configService.DownloadClientHistoryLimit`.

Current workaround on system with slow CPUs is to set SABnzb to pause downloads during post processing, but that has a huge impact in download speed.

### Expected Behavior

Option 1) Sonarr should not get the youngest, but the oldest `_configService.DownloadClientHistoryLimit` entries of history queue, so it can continue to import episodes, even with large queues. This potenially breaks imports if there are many unprocessable items in queue.

Options 2) Sonarr should get the entire queue. Both problems (current problem and potential problem of option 1) will be avoided. With *very* lare queues, Sonarr will have to process hugh amounts of releases.

### Environment

```markdown
- OS: Debian Bullseye
- Sonarr: 3.0.9.1549
- Docker Install: hotio release-e45c7bb
```

### What branch are you running?

Develop

### Trace Logs?

No trace logs needed. This issue concerns code
[line 108 in /src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs#L108)

**Comment by markus101** [comment]
Sonarr doesn’t get old history items because after importing it’s a waste of time, if we continually got every history item it’d get slower and slower. It gets the most recent because it doesn’t know that there are older items waiting to be imported and there is no way to ask the download client for things that haven’t been imported.

Turning on Remove Completed for SAB in Sonarr will avoid this issue, or you can tell Sonarr to get more history items.

**Comment by Taloth** [comment]
> Therefor the NZB keeps being added over and over again by RSS task, because it looks to Sonarr as if it was deleted from SABnzbd

Sonarr generally doesn't download the same release over and over again until like 12 hours after it was first grabbed. https://github.com/Sonarr/Sonarr/blob/6216a71f8c813ac3480b5fd95b3ef6a37c666d0d/src/NzbDrone.Core/DecisionEngine/Specifications/RssSync/HistorySpecification.cs If it does, then that should be investigated as a separate bug.

Fetching more of the history has an unacceptably high performance hit, but for sonarr and for sabnzbd, it'd hit the sabnzbd api hard, and cause even more cpu load, slowing down the entire process more.

The 'DownloadClientHistoryLimit' config option can only be changed manually in the sqlite database. But I would refrain from setting that too high.

**Comment by hr1232** [comment]
As I wrote before, this mainly happens after "adding a few old series with several thousand episodes". Downloading several large shows can take a week or more, so handling this problem by limiting RSS-downloads to "once-per-12-hours" doesn't cut it. Even with freshly aired releases being prioritized, as soon as they are post-processed by SABnzbd they won't be visible to Sonarr anymore as long as there are more than 60 finished downloads in SABnzbd post-processing-queue.

Also, as I wrote before, I have enabled "Remove Completed" and "Remove Failed" Download-Client-Settings for SABnzbd (These should be enabled by default, who keeps a download history in SABnzbd when Sonarr does this?). Therefor all downloads in SABnzbd's tv category are relevant to Sonarr and none of them should be ignored. Filtering them by post-processing status is no strain on the CPU. Also, this so-called strain could be reduced by not hammering SABnzbd's API every minute with `RefreshMonitoredDownloadsCommand` Task. Changing this however, is not possible because Sonarr resets it with every restart (why is that?).

I cannot find 'DownloadClientHistoryLimit' in Config table in sonarr.db, so I guess Sonarr normally uses your default of 60, as stated [here](https://github.com/Sonarr/Sonarr/blob/6660e0c3f37fade91d39141b2830dba4e20a46e2/src/NzbDrone.Core/Configuration/ConfigService.cs#L177).

Am I correct in assuming, that adding it manually like this will make Sonarr stop ignoring some of my downloads or does it have to be set somewhere else? Just stopped Sonarr, changed it and started Sonarr up again. Seemed to work on first glance, as Sonarr immediatly started importing things that had been sitting in SABnzbd's history for days...
```
sqlite sonarr.db
INSERT INTO Config (Key,Value) VALUES ('downloadclienthistorylimit','1000000');
.quit
```

**Comment by icenine9** [comment]
Interestingly enough, this is not an issue with nzbget, though it's seemingly been abandoned by its author. Sonarr for whatever reason dislikes Sab's queue. I went to the team's discord to help me troubleshoot, running into this very problem it seems. None of them knew anything about it apparently, but the answer is right here it seems. 

After finding that Sab was just slower and clunkier in most ways to nzbget, they stated I should stick with sab because it was better and faster (clearly neither of which is true in my idiotic and meaningless opinion). I was helped for a time by 'zoggy' and 'fryfrog' on the team's discord server, and they were clearly interested in helping address the problem. I was then asked for trace logs of this behavior, which could take a while since I have 5Gbit internet, NVME temp storage and a very recent machine to do the work. There was a good chance the machine might keep up with the queue for a while. 

And for a while, Sonarr kept up with the queue - several hours. But eventually a bunch of smaller animated episodes wound up in the download queue. When those came in at a quick pace, the sheer number of other episodes FINALLY outpaced the smaller episodes in the queue - pushing those small releases to the lower reaches, seemingly out of sonarr's reach (i'm guessing). Of course, the searches ahead of it wound up in the download queue before Sonarr had a chance to clear out the smaller animated episodes, meaning the queue always looked like it was busy downloading, never having anything "completed" to process because they were pushed far enough down into the queue.

Eventually this behavior would lead to the 4TB NVME drive to fill with none of those pending downloads ever being imported. 

Trace logs were provided as requested, but the moment I provided them, one of the support staff decided to tell me that my logs weren't wanted, and ESPECIALLY if they had to be downloaded and put in an archive file - because "no one wanted to sort through them" and that "I would have to sort through them myself to find the problem". So not only was I chastised for trying to help, they expected me to fish through logs to find a problem I couldn't possibly know where to find. They clearly didn't seem to want to offer any help with where to even start looking. 

My guess is they didn't know (or care) that I was asked for these logs, and instead took the not-so-high road, assuming I was just some schlep who wandered in 5 minutes ago. I tried to help - but it certainly wasn't appreciated - and that's too bad. 

I don't know how nzbget's queue structure is in comparison to sab's, but I can tell you that this is not a problem with Sonarr/nzbget at all. While this might not be considered a "bug" by the sonarr team with regards to Sab, it's certainly a limitation that another download client does *not* have, and I don't feel it should be tossed aside now that nzbget has been abandoned. 

The big question is, where does the "fix" need to be? On the Sab side or on the Sonarr side? Either way, my assistance was not wanted by some members of the "support" team (though they were great about pointing out semantics and calling up bot commands to show me how much of an idiot I am for providing something that was actually asked for). 

Something tells me this issue could have been handled better in both technical and social aspects, but sadly it wasn't. So for me, the fix is to keep using nzbget, and keep a close eye on any CVEs that might come its way.  Though I do hope someone on either the SAB or Sonarr side  (or both) take ownership of this problem. I have no desire to run abandoned software if a better option is available.
