### ISSUE TITLE
Uptime is negative... it counting down...

### ISSUE THREAD

**Issue by Tristan79** [Sonarr/Sonarr#5527]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Uptime is negative.

It counting down... to 0. It started at one hour negative.

See screenshot.

### Expected Behavior

Uptime count from up from 0. Can't be negative.

### Steps To Reproduce

? idk. set your date on you system ("before" running docker container...)
Currently +1 with summertime.

### Environment

```markdown
- OS: Debian
- Sonarr: 3.0.10.1567-ls184 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Nah
- Browser: Any
```

### What branch are you running?

Main

### Trace Logs?

Could supply on request.

### Anything else?

[Screenshot](https://ibb.co/6YY6sKw)

**Comment by markus101** [comment]
Sonarr’s backend reports the start time (as UTC) and the UI uses the current time compared to the time stamp it received to determine the uptime. One of your systems appears to have the wrong time zone or DST setting.

**Comment by Tristan79** [comment]
Maybe... then again.

Uptime. It should be time (in utc) when started... minus (utc) it is now.
*OTHER* systems should *not *(how badly configured, will look into that)
affect a counter for uptime.

**Comment by markus101** [comment]
That's exactly what it is, except one of the systems thinks it's a different time than it really is and then the math doesn't work because what should be a consistent point in time is not.

If Sonarr's backend thinks it's 01:00:00 UTC, but the front end thinks it's it's only 00:00:00 UTC then the front end is going to see everything the backend reports as being one hour in the future.

**Comment by Tristan79** [comment]
Then the bug is that the frontend time is used instead of the backend when
comparing? Making it inconsistent on wrong.
Again, why does a remote machine (how badly configured) influence uptime?

It's a minor glitch :-)

**Comment by Tristan79** [comment]
Compare backend time to backend time...
There should be no remote *frontend" time involved.

Anyway! Have a nice weekend!

**Comment by markus101** [comment]
Every date from the backend is UTC time, the front end then determines how to display it, if one of those is wrong then then every date generated by the backend is going to be wrong (history, start time, logs, etc).

Given the fact that this discrepancy is going to throw everything off in the UI, you need to fix the underlying issue instead of us putting a band-aid fix in place to mask the problem.

**Comment by Tristan79** [comment]
Again...

This is a bug.

The frontend should not have influence on the backend. And visa versa!

You ask me to fix my discrepancies with my front end and back end. To fix
this bug...

I ask you to fix your bug (if it has priority, again it a minor glitch).

This app should not be an indicator I config something wrong... (but thanks
anyway)

Again. Start Time - Now Time = Up Time.

There are no "OTHER" machines involved...

**Comment by Tristan79** [comment]
Fixed my discrepancies...
You still have a bug.

Start Time - Now Time = Up Time

Where Start Time and Now Time is read from the *SAME* machine. That is what
you would expect. Not?

Not two different back and front end with possibly two different time
zones, bad config etc...
Anyway minor glitch :-) No worriez

**Comment by Thirrian** [comment]
> Start Time - Now Time = Up Time

If you like a negative uptime, sure. The calculation would actually be now - start...

**Comment by Tristan79** [comment]
Negotiating that negative uptime is bad in general and especially when
comparing time with two different machines.
And feeling like there is a glitch in the matrix. Makes one a little more
sarcastic yeah :-) Should have added /sarcasm tag *sign*!

Negative uptime 4u all!

:-)
