### ISSUE TITLE
Rarbg indexer integration

### ISSUE THREAD

**Issue by d2dyno** [Sonarr/Sonarr#555]
It would be awesome if we could get Rarbg integrated to Sonarr :)

API doc (use json_extended): https://rarbg.com/pubapi/apidocs.txt

Forum discussion: https://forums.sonarr.tv/t/eztv-has-been-hacked-please-remove-that-from-the-sources-and-add-rarbg/5629/7

@rarbg

**Comment by M0UL** [comment]
this already possible with jackett(https://github.com/zone117x/Jackett)

**Comment by d2dyno** [comment]
Yes, and that's what I was using (removed, due to lacking API integration). But since Rarbg is a quickly rising site, it's probably a good idea (and I would love) to natively integrate it.

**Comment by Taloth** [comment]
@markus101 i'm inclined to agree in the integration, but only after we get torrentrss in develop and eztv indexer retired. Probably good to have something other than kat in the base.
Remove proposal if you agree.

**Comment by rarbg** [comment]
@Taloth 
im happy to help if needed.

**Comment by markus101** [comment]
Nope, I agree as well :+1:

**Comment by Taloth** [comment]
@rarbg We'll implement the api. If I have trouble, I'll let you know. Thank you.

Could you take a look at [Torznab](https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer)? See what you think about it?
I'm not asking you to implement it, just some feedback.
It's basically a filtered [rss feed](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core.Test/Files/RSS/torznab_hdaccess_net.xml) almost identical to Newznab, but for torrents instead of nzb/usenet.
Adoption is slow atm, but we have 2 supported sites and 2 more interested.
I've been trying to stick as close as possible to newznab spec, but I'm considering some additional query params might be desirable.

**Comment by rarbg** [comment]
@Taloth 
Ill need some time , but i can implement that.
I got one question tho ...
Implement the t=caps endpoint, feel free to put it behind an apikey check. It provides useful information about which categories you support.
t=caps or t=cats ? :)

**Comment by Taloth** [comment]
t=caps is capabilities, see example [here in the spec](https://github.com/nZEDb/nZEDb/blob/master/docs/newznab_api_specification.txt#L95).
Doesn't only cover the categories, but also which kind of searches are supported.
I've been thinking about adding an extra attribute to [these elements](https://github.com/nZEDb/nZEDb/blob/master/docs/newznab_api_specification.txt#L121-L123) so the site can specify which query params (q=,rid=,season=,ep=,imdb=) are supported. But not sure yet if that's wise.

Normally newznab has user-registered accounts with apikeys. But the apikey can be optional, albeit rarely.
Not sure how that fits in with your current access token. But I would imagine the user has to register an account to actually get the apikey. Giving you some flexibility in limiting the number of daily api calls. But you could also just leave out the apikey.

Finally, the t=tvsearch option uses season&ep number query params as shown in the examples. These may require more complicated queries in your db.

Let me know if you want to go the torznab route. Otherwise I'm entirely happy with implementing rarbg's api.

Tnx for looking at it.

**Comment by rarbg** [comment]
@Taloth 
Torznab looks like a complete api rewrite for me , can you implement our current api ?
Btw the token in it is exactly for limiting requests , everyone using the api has to create himself a token before using it every 15 minutes.
Our current api however is searching in the last 10000 results only if its not provided with imdb , tvrage or tvdb id. Does sonarr actually know which show the user is searching for before the search is performed so this limit can be skipped?

**Comment by Taloth** [comment]
We default to search by rageid if the rageid is known, otherwise we revert to query.

The thing I will have to deal with is the season & ep numbers. Normally we have the indexer filter those for us, saving bandwidth.
Looks like I'll have to fetch the entire series and then filter it ourselves. Doable, of course.

Btw. this only happens for the occasional manual backlog search. By default Sonarr only monitors the 'recent' feed every 15min, so 96 calls daily regardless of how many shows the user has.

**Comment by rarbg** [comment]
@Taloth 
I can return you the season & ep numbers in the api , they are easily extractable with a single reg on my side. Also you can search by them in the api using the search_string so dont worry about that ?

**Comment by Taloth** [comment]
We can extract them from the results too, that wasn't my concern.

But apparently I can use both search_tvdb and search_string at the same time, which is what I was after. Gives me a way to limit the number of results returned during episode searches. tnx.

**Comment by rarbg** [comment]
Oh yeah :) You can mix the params however you like
I think you mean narrow , not limit tho ? :)
You can even limit them further using the limit param and min_seeders/min_leechers

**Comment by Taloth** [comment]
yeah, narrow. :)

One thing I just noticed. the api seems to return Content-Type: text/html as instead of application/json. I think that's something that should be fixed.

**Comment by rarbg** [comment]
The replies of the api are mixed , thats why its returning Content-Type: text/html
I cant move it to json only responses because a lot of applications have these text responses hardcoded already. Its a plan to upgrade it soon with a parameter response_type which will force a json response for example , but i cant give any estimates on that...

Here are all the strings it can return which are plain text 

Cant find imdb in database. Are you sure this imdb exists?
Cant find search_imdb in database. Are you sure this imdb exists?
Cant find search_tvrage in database. Are you sure this imdb exists?
Cant find search_tvdb in database. Are you sure this imdb exists?
Cant find thetvdb in database. Are you sure this thetvdb exists?
Cant find tvrage in database. Are you sure this tvrage exists?
ERROR
Error occured. Please contact support
Invalid character in category
Invalid imdb
Invalid mode
Invalid search_imdb
Invalid search_tvrage
Invalid search_tvdb
Invalid sort
Invalid token set!
Invalid token. Use get_token for a new one!
Invalid tvdb
Invalid tvrage
Invalid value for min_leechers
Invalid value for min_seeders
No results found
No token set!
Too many requests per minute. Please try again later!

**Comment by rarbg** [comment]
@Taloth 
Actually wait , ill update the api now to support it :)

**Comment by rarbg** [comment]
@Taloth 
Done. Please append &response_type=json to all your api requests

**Comment by Taloth** [comment]
@rarbg Got some things again. Neither are a big deal.
First, I hit a bit of a snag with daily series:
https://torrentapi.org/pubapi.php?mode=search&search_tvdb=270261&search_string=2015.05.22&category=18;41&limit=100&format=json_extended&response_type=json&token=
nor
https://torrentapi.org/pubapi.php?mode=search&search_tvdb=270261&search_string=Sting&category=18;41&limit=100&format=json_extended&response_type=json&token=
returns any results.
Makes me wonder how the search_string works internally in conjunction with search_tvdb.

Also the response_type=json makes the result a bit inconsistent:
{ "error": "errortext" }
vs
[ {...}, {...}, {...} ]
I'm already handling it, but if you want to wrap the latter in { "torrents/results" : [..] } so that both are Json objects (only for response_type=json of course), now would be the time.

**Comment by rarbg** [comment]
@Taloth 
Search fixed. Thanks for finding that bug. It was actually hitting it on the daily shows , which was hard to find.
About the inconsistency in json response_type just handle it like that please...

**Comment by d2dyno** [comment]
Glad to see everyone working together to improve both services! @rarbg and @Taloth You're both awesome, and have done/are doing a fantastic job! I look forward to the awesome things that will be accomplished with the teamwork here.
