### ISSUE TITLE
Anime Standard Format Search  (allow search by seasons)

### ISSUE THREAD

**Issue by pixelroll** [Sonarr/Sonarr#5616]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This option allows you to search with the standard type but only on episodes and this is all the problem since this type also allows you to find season packs. 

### Describe the solution you'd like

The solution would be that when the standard search is launched, sonarr also looks at the season packs and not just the episodes.

### Describe alternatives you've considered

I tested with the series type and it works very well with some anime, I have the series pack but I miss the search with the anime type...

### Anything else?
2023-05-02 21:18:42.7|Trace|HttpClient|Req: [GET] http://ip:9696/8/api?t=tvsearch&cat=5070,102179&extended=1&apikey=(removed)&offset=0&limit=100&q=Hajime%20no%20Ippo&season=1&ep=69

if we raise the ep parameter we have the season pack
_No response_

**Comment by fryfrog** [comment]
I'm not sure how hard it would be to actually achieve, but it seems logical to do a standard *season* search when the per indexer setting "Anime Standard Format Search" is used. It would be more efficient to do *one* standard search and find X episodes and season packs vs. doing X searches for SxxEyy style results and *not* getting season packs.

**Comment by ShubhamPatilsd** [comment]
Will be reserving this for students at [CodeDay Labs](https://labs.codeday.org/) to be working on in our summer cohort.

**Comment by markus101** [comment]
For anime typical season packs don't always exist, so individual episodes are searched, this returns a lot of results, but is expected given the lack of consistent season packs and unknown batch sizes.

The desired change here is to keep the existing behaviour for season searches of anime and when `AnimeStandardFormatSearch` is enabled also search for season packs.

**Comment by ttran913** [comment]
Ok, I think I have a better picture of this issue now. So I just want to confirm its _current_ behavior for searches.

- When setting up one of a desired anime series, there's a checkbox for `Anime Standard Format Search`. 
- Then I only used interactive searches.
- I've found that there's no difference currently whether the `Anime Standard Format Search` option is checked or not. 
- I get the same results. When searching for a season of an anime, season packs are found, in both on or off for `Anime Standard Format Search`, which makes sense, I'm purposely looking for the whole season. 
- While when searching for individual episodes, only single episodes are found, in, again, in both on or off for `Anime Standard Format Search`, no season packs are listed.

My search setup for current understanding of the app's behavior:

- Used only torrent indexers. Did _not_ use the Usenet indexers just because many of them are pay-to-use in my research.
- Searched under the **Nyaa** torrent site because its files under the Indexer folder had the key word `AnimeStandardFormatSearch`.
- Searched for old and new Animes. Hajime no Ippo, Naruto Shippuden, Spy x Family, and One Punch Man. Animes with both no definite distinctive seasons(well, just Naruto I guess) as well as ones that do have definite seasons.
- Searched with both `Anime Standard Format Search` on and off for the animes.
- Tried various different filters(`0` Rejections in the search, seeds at least `1`, etc.)
- Adjusted my profiles and quality settings to be extremely forgiving to get more results.

My current understanding of the desired solution:
When searching for _individual_ episodes, make it so that that season packs, of which that episode is included in, will show up as well _**if**_ the option `Anime Standard Format Search` is checked for that anime's settings.

Is my understanding correct? If not, is it because I didn't use any of the Usenet indexers or any other reason?

**Comment by markus101** [comment]
Nyaa might already be returning these results because it's a fairly capable anime indexer, but a lot of Newznab/Torznab based indexers won't. There might be an open indexer that Jackett/Prowlarr supports that you can use to test that implementation.

When `AnimeStandardFormatSearch` is enabled a search for an anime season should in addition to search for each episode, should also search for `Sxx` where `xx` is the season number padded to two digits. This is similar to how a standard season search functions, but would use the anime categories instead.

`ReleaseSearchService` needs to be able to figure out which seasons needed to be searched and generate search criteria (for example `AnimeSeasonSearchCriteria`) so that the indexers (Newznab, Nyaa, Fanzub) in Sonarr can generate the correct params for the request and turn those params if `AnimeStandardFormatSearch` is enabled into a chain of pageable requests.

High level steps:

1. User presses search for an anime season
2. The search processing gets to `ReleaseSearchService.SearchAnimeSeason`
3. Criteria for each episode is generated and are processed as they currently are
4. An additional criteria for searching the whole season is generated and requests are made
5. All existing indexers are updated to handle requests for anime seasons, this could mean no requests are generated and they return an empty list of requests
6. Indexers that currently support `AnimeStandardFormatSearch` are updated to generate requests for full seasons when enabled, otherwise no requests should be generated
7. Results are processed like normal

**Comment by ttran913** [comment]
Throughout some testing of the app (aided by Prowlarr, only added/used 1337x's site), I get more results, that are still relevant, when I search for both `Sxx` and `Sx`, one with padding to 2 digits, one without. With the option, `AnimeStandardFormatSearch` on, do you want the season number very strictly padded to 2 digits?

**Comment by markus101** [comment]
For Prowlarr (and other Torznab/Newznab indexers) Sonarr should search with a `season` param and the indexer should handle that distinction. For searches where Sonarr is forced to search by a string query that includes the season number then we should maintain the existing functionality for standard season search, which is passed if I recall correctly.

**Comment by markus101** [comment]
Closed via https://github.com/Sonarr/Sonarr/pull/5814
