### ISSUE TITLE
Remove failed from torrent client as off by default

### ISSUE THREAD

**Issue by IllMethods** [Sonarr/Sonarr#5775]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This never used to be an issue, but it left me scratching my head for a while. Out of no where I started getting a decent amount of HNR's on both Sonarr and Radarr, which really sucks when you have private trackers, especially one as good as BTN... I finally found the issue, which was during one of the updates, a separate setting in the download clients, under the download client to remove failed downloads. If Sonarr decides the download failed, just because possible one episode was a double, it will remove the download even though there was nothing wrong with it, and give me dishonor among my fellow seeders... 

### Describe the solution you'd like

Have this setting off be default, even if the old setting was set to remove failed downloads.

### Describe alternatives you've considered

I searched high and low and finally found what caused it, but this could lose a lot of people their precious private trackers, especially if they don't have the time to monitor everything daily.

### Anything else?

Thankyou for all your hard work, I really appreciate it.

**Comment by markus101** [comment]
Failed downloads are only reported from the download client, Sonarr doesn’t treat unable to import as a failure. Since most torrent clients don’t actually have a concept of failed downloads this setting mostly only applies to Usenet (and might exclusively apply to Usenet still at this time).

This sounds like something else is removing “failed” downloads from Sonarr in hopes that another release will work properly and best suited for one of our support channels.

**Comment by IllMethods** [comment]
Well, it never did it before this became an option, and once I turned it off, it stopped. To be clear, it is, 

Settings, Download Clients, Manage Clients, Removed Failed - Set to No

When it was set to Yes, they were being removed. Under activity, it would still show as Manual Import, I would then correct everything and Import, and during that procedure it would show failed in the bottom left hand corner and then the torrent and content was removed from qBT, which would result as a HNR on BTN...

**Comment by bakerboy448** [comment]
As Markus said, there's no logic or functionality in sonarr to remove failed downloads from qbit....there's no concept of failed downloads for qbit in sonarr at all.

you have some other third party app removing your torrents from qbit and the correlation you're seeing is likely just by chance

failed in the bottom left corner will have the details in the logs and means some part of the manual import failed.   Likely permissions or db issues.

**Comment by markus101** [comment]
Before it was a client setting it was a global setting which also defaulted to enabled, the only "recent" (it's been 2 years) change was to move them to per-download client.

The manage modal now exposes that the setting's default (it's hidden for torrent clients in the edit modal), but otherwise no behaviour has been changed.

This code search shows all places where Sonarr sets the status to failed for a download: https://github.com/search?q=repo%3ASonarr%2FSonarr%20DownloadItemStatus.Failed&type=code or look at Sonarr's qbit implementation where the status is set: https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs#L240-L302 and note that qbit never sets the status to failed.
