### ISSUE TITLE
Option to assign post-import tag instead of category for qbittorrent

### ISSUE THREAD

**Issue by sgtsquiggs** [Sonarr/Sonarr#5791]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Changing category in qbittorrent triggers a move (when you are using default settings). Tagging does not.

I don't want to re-categorize the torrent in qbittorrent, i just want to tag that it has been imported.

### Describe the solution you'd like

I'd like to be able to assign a tag post-import like you can with Flood. Ideally the options for qbittorrent should be similar to flood

### Describe alternatives you've considered

I _could_ do this with a script but it would be held together with string and duct tape.

**Comment by markus101** [comment]
Tags are used in Flood because that fills in for what Categories are in Qbittorrent, we're just using the correct terminology for them in the UI. I don't recall why we opted to use Categories over Tag in qbit, though on-disk sorting seems like a reasonable reason. We do not have plans to support tags in addition to categories in Sonarr, for the vast majority of users this would just add confusion. You could instead use a Custom script triggered after importing to set the tags for you.
