### ISSUE TITLE
Squiggly brackets, {}, behave differently between file and folder names.

### ISSUE THREAD

**Issue by tehniemer** [Sonarr/Sonarr#5888]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

My desired file naming scheme uses `{imdb-{ImdbId}}` to add the IMDB ID, but only if it exists, the desired result is seen at the folder level, but not at the file level. If the outer brackets are removed, `imdb-{ImdbId}` it seems to be recognized at the file level.

### Expected Behavior

`{imdb-{ImdbId}}` works both in folder names and in file names.

### Environment

```markdown
- OS: Debian 12
- Sonarr: 4.0.0.602
- Docker Install: Yes
- Using Reverse Proxy: Traefik V2
- Browser: Edge
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/12283588/sonarr.trace.txt)
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/12283589/sonarr.debug.txt)

### Anything else?

![image](https://github.com/Sonarr/Sonarr/assets/11021632/e5f9a789-4576-423f-8ef8-225e520c3563)

**Comment by stevietv** [comment]
I believe `{{imdb-{ImdbId}}` will work

**Comment by tehniemer** [comment]
Alright, color me confused, it does, but why? 

`{{imdb-{ImdbId}}` produces the same results in Sonarr as `{imdb-{ImdbId}}` does in Radarr . I can't wrap my head around it, why is the behavior different?

**Comment by markus101** [comment]
`{` is used to start the violent replacement, Sonarr will strip out invalid matches, but using `{{` escapes it and bypasses the matching for token replacement.

**Comment by tehniemer** [comment]
@markus101 why does `{{imdb-{ImdbId}}` and `{imdb-{ImdbId}}` produce the same result when used in the `Series Folder Format` field?

**Comment by markus101** [comment]
It's because file name formats go through multiple rounds of replacement to deal with path section restrictions, once to replace most of the tokens and a second to replace the episode titles which are truncated if necessary, this was originally addressed in https://github.com/Sonarr/Sonarr/issues/3434, but likely was due to a side effect in https://github.com/Sonarr/Sonarr/commit/34d81356a3b3b378ce669ea65c5802b64efaad6e

This is quite a complicated edge case which breaks the formatting one way or another so not something we're going to change.

**Comment by tehniemer** [comment]
@markus101 Thanks for taking the time to explain, I was just looking to better understand why it worked in one place but not the other, not asking for a change to be made.
