### ISSUE TITLE
Don't Treat 400 Response as Error for Notifiarr

### ISSUE THREAD

**Issue by austinwbest** [Sonarr/Sonarr#5953]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Many services are not available 100% of the time and throwing them into a completely non working state over that seems aggressive. Even CF can have blips and now users have to go in and manually test connects just to bring them back to a working state.

More importantly though is taking down the connect because of a valid response such as a 400, 409, etc code.

Imagine if a service connected to the api and got a 400, 409, 426, etc, then the app decided sonarr/radarr/etc was not available at all because of that. It is a bit to aggressive and should be implemented to only be triggered by actual unavailable response codes.

### Describe the solution you'd like

Ideally an option to not apply this health check to specific connects instead of forcing every connect to be up and respond with a 200 every time.

Optionally allow valid codes to not throw a connect into an unavailable state when the connect/service is actually available

### Describe alternatives you've considered

Returning a 200 to make the health check happy even though a valid HTTP code of a non 200 should be acceptable.

**Comment by markus101** [comment]
Generally 400 responses are the client making a mistake, not that the service is down, which is either a configuration issue that needs to be addressed or something in the code that isn't accounting for a specific case and it should.

400 - Sonarr uses these all the time in the API to indicate that the request was bad and provides the field(s) that are missing
409 - Likely not worth blocking on, but curious in what circumstances this is occurring
426 - This is almost certainly a configuration issue and likely the config should be upgraded to support HTTPS

I agree that returning a 200 response just to placate Sonarr is bad design, but more information on what responses Sonarr is receiving and why for different services would be valuable in determining what we can do, because I don't think a blanket 4xx response = okay is the right approach.

> Even CF can have blips and now users have to go in and manually test connects just to bring them back to a working state.

What's CF in the context of connections?

**Comment by austinwbest** [comment]
CF in this scenario would be Cloudflare. If a connect reaches out to a service behind it and they are having a temporary issue then the connect goes down.

If a service returns a 400 for a bad setting the connect goes down.

I understand a timeout, 404, 401, 3xx redirects if those are not going to be followed, etc but there are valid 4xx response codes that can be returned but that doesn't mean the service is unavailable completely.

Hopefully that helps?

**Comment by Qstick** [comment]
I'm assuming this really only effects notifiarr connect given the multitude of options related to different triggers? Backoff and shutdown of any other connect provider when we see exceptions seems legit to me.

**Comment by austinwbest** [comment]
Im not entirely sure what all API responses others do but it could very well be an issue that is less likely for services that are not as feature/settings based. I was just trying to speak in general in case others have different API code responses that could one day see similar things happen.

**Comment by markus101** [comment]
Ahh, that CF, yes, they do go now, but very infrequently and for short periods of time until traffic re-routes to another endpoint, generally if CloudFlare is down for an extended period of time it makes headlines and the internet is in rough shape. Unless we're talking about services behind CloudFlare, but that does fall into the service is down and Sonarr shouldn't keep trying bucket I think.

> If they for example do not turn on delete trigger then when sonarr sends it the site returns a 400 for the trigger being disabled. If they dont pick a channel it returns a 400 for a missing channel. This could be temporary or whatever (for the trigger not being enabled) but now that one trigger returns a valid 400 the entire connect is disabled. It returns these valid codes so a user could look in the log files if they think it should be working and find the reason it isn't.

Can these cases be handled during configuration as well so the user can be alerted that something is misconfigured instead of silently failing until they notice?

I think a lot of those example 4xx errors should show an error for the connection and back off accordingly, but if they legitimately come up we can address them on a per-connection basis. Addressing the case for Notifiarr specifically makes sense though.

**Comment by austinwbest** [comment]
To some extent i can work on automation to turn triggers in sonarr/radarr/etc on and off based on settings but that would rely on the local client being installed which not everyone uses.

I am working on adding a visual way to put errors in front of the user on the site as well to help with that "silently failing" issue too.

If you guys decide to do it per connect, that is suitable as well. I was just trying to bring up the potential issues that anything can cause so it doesnt come back up later was all.

**Comment by austinwbest** [comment]
Just an update, since this was swapped to `up-for-grabs` and im not going to keep having users running into issues, i have changed all 400's to 200's to make the starr apps happy and keep it from disabling the connect.

Also a side note, multiple users said that simply testing the connect does not even bring it back to working and they have to delete the connect and re-add it to get it to work again.

Anyhow, I'll keep an eye on this and if/when it is updated to allow 400's i will revert the change.

**Comment by davidnewhall** [comment]
Can you give users the option for "health checks disable my notification agent" ? I'd rather just disable that "feature" so my apps continue to work as I configured them and they don't stop sending my notifications because docker upgraded some containers. This is weird.
