### ISSUE TITLE
Interactive search for all episodes or multiple seasons in the series

### ISSUE THREAD

**Issue by EloToJaa** [Sonarr/Sonarr#5978]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Many times when downloading a series I wanted to download multiple seasons at once. Instead of downloading them one by one I would prefer to be able to download all or some of the seasons at once.

### Describe the solution you'd like

Add Interactive search for multiple seasons in the top bar of series preview.
![here](https://github.com/Sonarr/Sonarr/assets/22549550/cc23fcfa-139a-4721-80f9-159e977454c6)
I have some experience with React and C# and would be happy to help implement a PR that would add this feature.

### Describe alternatives you've considered

An alternative is to do a Manual Import of multiple seasons downloaded manually using the download client.

### Anything else?

I am interested if this feature is possible to implement and if so how hard would it be to implement it.

**Comment by markus101** [comment]
This is already possible with Search Monitored, Sonarr will search for each season and grab appropriate releases. Each season is searched because multi-season packs are not supported and large series could have more results than Sonarr would handle in one big search.

> An alternative is to do a Manual Import of multiple seasons downloaded manually using the download client.

If the download is in Sonarr's category it will try to import it automatically.
