### ISSUE TITLE
Add custom tmdb api

### ISSUE THREAD

**Issue by yjiawqgj** [Sonarr/Sonarr#5998]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some series/movies cannot be searched on tvdb and imdb, so videos cannot be added. There are series/movie information on tmdb, but you cannot use tmdb. I wonder if users can use their own API to use TMDB. data.

### Describe the solution you'd like

Add custom tmdb api

### Describe alternatives you've considered

no

**Comment by Thirrian** [comment]
https://github.com/Sonarr/Sonarr/issues?q=is%3Aissue+is%3Aclosed+tmdb

**Comment by augustuen** [comment]
This has been requested and discussed countless times before (including the issues Thirrian linked) It's not going to be added in the foreseeable future. Your best bet is to add that information to TVDB.

Also, movies aren't handled by Sonarr, so if you're looking to add that information by adding TMDB, you're out of luck anyways. Radarr is the movie one and already uses TMDB.

**Comment by yjiawqgj** [comment]
> This has been requested and discussed countless times before (including the issues Thirrian linked) It's not going to be added in the foreseeable future. Your best bet is to add that information to TVDB.
> 
> Also, movies aren't handled by Sonarr, so if you're looking to add that information by adding TMDB, you're out of luck anyways. Radarr is the movie one and already uses TMDB.

I know that sonarr and radarr are developed by the same team. My question is just not subdivided. What I want to express is that sonarr adds a personal tmdb. But my native language is Chinese, and I can’t understand why the addition of tmdb is refused even when I use Google Web Translate.

**Comment by augustuen** [comment]
Sonarr and Radarr aren't developed by the same team. Radarr is based on Sonarr so code and contributions are shared between the two, but the actual dev teams are separate. 

There's loads of previous discussion for you to read, but just to name a few points:
1. Adding TMDB would be a lot of effort which wouldn't really benefit a lot of people.
2. Following up on that, maintaining TMDB support would take a lot of resources away from other issues. 
3. Sonarr doesn't just use TVDB metadata, it mixes it with other sources, like TheXEM, to make the automation work. 
4. In Skyhook (Sonarr's metadata system) there's also built-in caching from TVDB, to avoid hitting their APIs too hard and getting banned. Because of that (and the previous point), we can't have users use their own API connections.

**Comment by yjiawqgj** [comment]
> Sonarr 和 Radarr 不是由同一团队开发的。Radarr 基于 Sonarr，因此两者之间共享代码和贡献，但实际的开发团队是分开的。
> 
> 之前有很多讨论供您阅读，但仅举几点：
> 
> 1. 添加 TMDB 需要花费大量精力，而且不会真正让很多人受益。
> 2. 接下来，维持 TMDB 支持将占用处理其他问题的大量资源。
> 3. Sonarr 不仅使用 TVDB 元数据，还将其与 TheXEM 等其他来源混合，以实现自动化。
> 4. Skyhook（Sonarr 的元数据系统）还内置了 TVDB 的缓存，以避免对其 API 造成太大影响而被禁止。因此（以及前一点），我们不能让用户使用他们自己的 API 连接。

I thought these two tools were developed by one team.
Regarding your first reply: I don’t understand why you say it won’t “really” benefit many people? Adding this feature will benefit those who need it. Even if it doesn’t benefit many people, the fact is that it does benefit some people. And I proposed to add tmdb because there are databases and some TV series cannot be added. This is not actually a feature suggestion! This is an obvious flaw.
Second: I can understand if there are other more urgent matters or plans that need to be addressed. But I'd also like to reiterate that this is considered a bug rather than a feature suggestion.
Third: No matter how much metadata support is added, the fact remains that maximum support cannot be achieved. Even with the addition of TheXEM.
Fourth: I don't understand what you mean by "caching with built-in TVDB". What is it caching? Maybe it's a translation problem, but I don't understand what you mean.
Ultimately, if the truth is number two: tmdb can't be added because there are other more urgent things, I can understand that.
Maybe the fourth point you mentioned is the key point. Unfortunately, due to Google’s automatic translation or maybe my understanding, I still don’t know the core reason why TMDB support for tmdb individual users cannot be added.

**Comment by yjiawqgj** [comment]
> Sonarr and Radarr aren't developed by the same team. Radarr is based on Sonarr so code and contributions are shared between the two, but the actual dev teams are separate.
> 
> There's loads of previous discussion for you to read, but just to name a few points:
> 
> 1. Adding TMDB would be a lot of effort which wouldn't really benefit a lot of people.
> 2. Following up on that, maintaining TMDB support would take a lot of resources away from other issues.
> 3. Sonarr doesn't just use TVDB metadata, it mixes it with other sources, like TheXEM, to make the automation work.
> 4. In Skyhook (Sonarr's metadata system) there's also built-in caching from TVDB, to avoid hitting their APIs too hard and getting banned. Because of that (and the previous point), we can't have users use their own API connections.

I thought these two tools were developed by one team.
Regarding your first reply: I don’t understand why you say it won’t “really” benefit many people? Adding this feature will benefit those who need it. Even if it doesn’t benefit many people, the fact is that it does benefit some people. And I proposed to add tmdb because there are databases and some TV series cannot be added. This is not actually a feature suggestion! This is an obvious flaw.
Second: I can understand if there are other more urgent matters or plans that need to be addressed. But I'd also like to reiterate that this is considered a bug rather than a feature suggestion.
Third: No matter how much metadata support is added, the fact remains that maximum support cannot be achieved. Even with the addition of TheXEM.
Fourth: I don't understand what you mean by "caching with built-in TVDB". What is it caching? Maybe it's a translation problem, but I don't understand what you mean.
Ultimately, if the truth is number two: tmdb can't be added because there are other more urgent things, I can understand that.
Maybe the fourth item you mentioned is the key point. Unfortunately, due to the automatic translation of Google's machine or the problem of my understanding ability, I still don't know the core reason why the data support of tmdb cannot be added.

**Comment by augustuen** [comment]
>Second: I can understand if there are other more urgent matters or plans that need to be addressed. But I'd also like to reiterate that this is considered a bug rather than a feature suggestion.

It's not a bug, because Sonarr isn't supposed to be working in this way. It could be called a limitation, but it's not a bug. This is definitely a feature request. And whenever the limited development resources need to be focused somewhere, it's always a cost-vs-reward thing. If it will benefit few people, it might be worth it if it's quick and easy to do. If it's hard to do, it needs to be important to many people, otherwise it will be put on hold until a time there's less to do (this is just in general. For this issue, I don't expect we'd get to a point where it makes sense to focus on it for a good while)


>Fourth: I don't understand what you mean by "caching with built-in TVDB". What is it caching? Maybe it's a translation problem, but I don't understand what you mean.

When Sonarr looks for metadata, it doesn't go and ask TVDB directly. It asks Skyhook, which saves the data from TVDB for a period. This means that Sonarr needs to ask TVDB more rarely, and so we're not as big a load on their systems. If users were to use their own API keys, it would either have to be passed to Skyhook (bad security), or Sonarr would have to contact TVDB/TMDB directly, without caching.

**Comment by yjiawqgj** [comment]
> > Second: I can understand if there are other more urgent matters or plans that need to be addressed. But I'd also like to reiterate that this is considered a bug rather than a feature suggestion.
> 
> It's not a bug, because Sonarr isn't supposed to be working in this way. It could be called a limitation, but it's not a bug. This is definitely a feature request. And whenever the limited development resources need to be focused somewhere, it's always a cost-vs-reward thing. If it will benefit few people, it might be worth it if it's quick and easy to do. If it's hard to do, it needs to be important to many people, otherwise it will be put on hold until a time there's less to do (this is just in general. For this issue, I don't expect we'd get to a point where it makes sense to focus on it for a good while)
> 
> > Fourth: I don't understand what you mean by "caching with built-in TVDB". What is it caching? Maybe it's a translation problem, but I don't understand what you mean.
> 
> When Sonarr looks for metadata, it doesn't go and ask TVDB directly. It asks Skyhook, which saves the data from TVDB for a period. This means that Sonarr needs to ask TVDB more rarely, and so we're not as big a load on their systems. If users were to use their own API keys, it would either have to be passed to Skyhook (bad security), or Sonarr would have to contact TVDB/TMDB directly, without caching.

The error I am talking about is not the error of the development team, but the error of sonarr function, that is to say, the functional defect.
My feature request is to add an API for user's personal tmdb. I don't understand what role the sonarr cache you mentioned plays in this problem. I don't discuss how sonarr works, I need tmdb's metadata to add some TV series that I can't. If you don't want users to use the API to increase the burden on the tmdb website, you can use the caching mechanism you mentioned. If I subscribe to a drama, I can directly cache all the metadata of the entire drama so that it can be added when the latest episode is updated. There is no need to ask tmdb for data.

**Comment by markus101** [comment]
Supporting TMDb or another metadata provider is not something we currently have plans to support. Supporting another metadata provider instead of or in addition to TheTVDB is not a small undertaking and and would have an on going support and development impact.

If series/episode information is missing from TheTVDB then TheTVDB can be updated to include that information so long as it follows their rules.
