### ISSUE TITLE
If Show In Multiple Lists Upgrade Monitor Type to Broadest

### ISSUE THREAD

**Issue by richardgetz** [Sonarr/Sonarr#6010]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have multiple lists used by different users and some automated processes. I'd like to be able to have one list that only downloads the first episode of a series but if it gets added to any other list with the broader "All Episodes" options that takes precedent and upgrades the monitor option for the show.

### Describe the solution you'd like

I would like shows that are in multiple lists to automaticlaly use the "broader" monitor option.

### Describe alternatives you've considered

One potential alternative is to give an allow override option within the import lists to allow people to prevent/allow what I am suggesting.

**Comment by thezoggy** [comment]
there are "request" software out there that can micromanage how your wanting to add stuff to sonarr. this is not really in scope of sonarr itself as its not setup for multi-user

**Comment by richardgetz** [comment]
I'm less worried about micromanaging and more just thinking the list functionality itself. You don't think priority of list should be taken into account of which settings to use? Welcome any software that you think may overlap though.

**Comment by markus101** [comment]
Once the series is added Sonarr has no knowledge on whether the series was added by monitoring the first episode or all episodes, this is because that can be changed on a per episode or season basis afterwards and tracking something like `Future Only` would effectively mean everything would get unmonitored within a day of an episode airing.

At best this would have to resync every series after list processing to the value selected in that list, which would mean if you manually changed from the first episode to all episodes it'd change it back. At this time it's not something we're going to implement.
