### ISSUE TITLE
Add Option when removing torrent to change to post-import category

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#6023]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When removing a torrent from queue, it may be wished to move the torrent to the post import cat as its uneeded for organization. E.g. even with delay profiles a situation may exist where preferred 720p is grabbed after 1080p is grabbed and the user must then go ignore the 1080p release

### Describe the solution you'd like

Add a checkbox upon removing a release from queue (ignore)  that is dependent on remove from client being false to say "change to post import cat" that would ignore the release and move it to the post import cat.

It should also be possible to simply move the release to the post-import cat from queue without ignoring and without removing from client using the existing ignore functionality

### Describe alternatives you've considered

Manual cat change in client 

### Anything else?

N/a

**Comment by markus101** [comment]
I don't think it makes sense to add another checkbox. but would could make sense to convert the remove checkbox to a dropdown with a few options:

- Remove: Same as the current behaviour when remove is checked
- Ignore: Same as we currently do when `Remove` is unchecked
- Move to Post-Import Category: If configured, moves to post-import category, if not set then it would no-op

My concern with this is not everyone is using post import categories and because they are configured on a per-download client basis the UI wouldn't know whether it is supported so for some download clients/configurations it'd do nothing.

**Comment by bakerboy448** [comment]
It already knows the client based on the queue info? How difficult is it to add in the client.settings details at that point in time?

perhaps it can be options of Ignore / Remove / Ignore & Try Move Post Import logging at warn or debug if not found and with appropriate helptext to keep it simple and avoid additional calls?

Keeping the redownload bool checkbox of course

**Comment by markus101** [comment]
Actually looks like it should be easier to track whether a post import category is supported, no need to ignore and try to set the post import category at the same time.
