### ISSUE TITLE
Series type anime not searching indexer with absolute episode number

### ISSUE THREAD

**Issue by HatboyWonder** [Sonarr/Sonarr#6025]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When searching the configured indexers for an anime episode (Jujutsu Kaisen S02E08, 32) the search request on the indexer only does the SxxExx search which leads to no results:

![image](https://github.com/Sonarr/Sonarr/assets/26897610/10d1fa9b-5d78-43eb-b7d0-85cd22695fb4)

### Expected Behavior

Indexer needs to be searched with absolute format for series type anime per default.

### Environment

```markdown
- OS: Linux
- Sonarr: 3.0.10.1567
- Docker Install: yes
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Main

### Trace Logs?

[trace.txt](https://github.com/Sonarr/Sonarr/files/12640329/trace.txt)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

https://thexem.info/xem/show/5671

Looks like those are aliases for the series.

**Comment by HatboyWonder** [comment]
To me this seems like a clear bug in sonarr as the series type is not honored.

What are you implying with the aliases for the series?

**Comment by markus101** [comment]
The aliases contain the The XEM:

```
Jujutsu Kaisen 2nd Season
Jujutsu Kaisen S2
```

The 2023 one is coming from our own mappings, though that's wrong and has been removed. Since the alias for the series contains `2nd Season` and `S2` they are used when searching, which is not a bug it is required or you wouldn't get the correct results. Additionally these requests are made without `season=2` or `episode=8` which is what is used for _most_ torznab/newznab indexers.

The series type is being honored, if you have further questions please use one of the support channels.
