### ISSUE TITLE
Folder quality should be used if file quality was determined by extension

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#603]
If the extension is `.mkv` and the folder is a lesser quality (IE: WEBDL-480p) and the quality was determined by the extension, not the filename we should use the quality from the folder. Currently we use the folder quality only when it is a better quality than the file.

**Comment by otoolejp** [comment]
Just another example of folder quality that might be taken into consideration for parsing quality:
Gintama 82 Rumbel-sMi 640x480 H264 CBR Vorbis 2 0 eng softsub MKV - Gintama 82 H\[Rumbel-sMi]_Gintama_-_82_[H264][3BEED028].mkv

The above parses as HDTV-720, which seems to be expected behavior based on this issue. Seems to come up often enough, but I've only seen it in anime thus far.

**Comment by markus101** [comment]
If the quality parser was able to say how it decided on the quality (file name or extension) then we could use that to decide whether or not to use the folder quality instead.
