### ISSUE TITLE
After downloading season pack, some episodes are marked as missing

### ISSUE THREAD

**Issue by Terebi42** [Sonarr/Sonarr#604]
I downloaded season 2 of a series using the season automatic search.

I have uTorrent 3.0 configured to download to c:\downloads, and then move to \\WDMyCloud\downloads\sonarr  (the sonarr is added automatically via the tag configuration) This is done because I want to store things long term on my NAS, but download to regular disk, because if I have to restart or something, doing recheck on the NAS takes forever. 

After everything is done, about 1/2 the episodes are marked as missing in sonarr. In the log it said it looked for them in c:\ and was unable to find them.

This appears to be a race condition involving when sonarr checks the client, vs when uTorrent is done moving the files.  (In this case, it appears it checked after those files had already been moved, but the opposite condition seems equally likely)

To compound the issue, there does not appear to be a way to trigger sonarr to recheck the files in the download client to reconfirm if they are there, or what their expected location is.

**Comment by markus101** [comment]
I think what you're seeing is uTorrent telling Sonarr they're in one location, but in reality its somewhere in the middle of moving, because IIRC its because uTorrent tells Sonarr that the download is complete but meanwhile its still moving the files (or running a post-download script).

Once Sonarr imports the files it was aware of it will stop waiting to import files for that release (and stops showing it in the queue). Offhand I can't think of anything that we can do to improve this behavior as ultimately uTorrent is misleading Sonarr, but maybe @Taloth has an idea.

Please use the forums for support next time.

**Comment by Terebi42** [comment]
sorry, I will post stuff on the forums first.

Presumably at some point uTorrent will have the correct info in it, when it is done with the processing. Can we add a button somewhere to try and reprocess it?

**Comment by Taloth** [comment]
if it's reproducible try get a sonarr tracelog. that way we should be able to see what torrent reports as time progresses.
