### ISSUE TITLE
The Pirate Bay added new 4K/UHD, Sonarr Indexer unable to be updated due to Category Mismatch

### ISSUE THREAD

**Issue by stry8993** [Sonarr/Sonarr#6043]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Whereupon adjusting the categories to match the newly added UHD/4K - TV Shows specific category added to thepiratebay.org both Sonarr, in the Indexer sections, is unable to save the category, even though it is present in the options there.

Specific issue test - "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings."

### Expected Behavior

Click the TPB Indexer, change from TV->UHD to UHD/4K - TV Shows categories, test/save.

### Steps To Reproduce

1. In Sonarr have TV -> TV, and/or TVHD, and/or TVUHD selected.
2. Deselect categories, test and/or save.

### Environment

```markdown
- OS: Synology DS7.2
- Sonarr: 4.0.0.682 (4.0.0.682-ls578 by linuxserver.io)
- Docker Install: Yes
- Using Reverse Proxy: No 
- Browser: Edge
- Database: Sqlite 3.41.2
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/12686840/sonarr.txt)

### Anything else?

![Screenshot 2023-09-21 100442](https://github.com/Sonarr/Sonarr/assets/8879559/1810d868-630c-455e-9b1d-27b7e48dab51)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

As the error mentions, no results were returned for that category and Sonarr is preventing the saving because it appears to be misconfigured.
