### ISSUE TITLE
Manual Import Option to Copy or Hardlink

### ISSUE THREAD

**Issue by TheDeathly** [Sonarr/Sonarr#606]
I noticed when i had to manually import a few episodes it didn't follow that option, it seems to always copy which isnt exactly ideal sometimes. Would it be possible to have it follow that option, or add another set of options for the manual import?

**Comment by markus101** [comment]
If you use manual import from the queue for a torrent it should respect the Hardlinking option and will either copy or hardlink if the torrent is still seeding. In all other cases it will import by moving the file(s) (Importing from usenet or by picking a folder manually).

I was thinking it would be good to have the option to copy instead of move though.

**Comment by TheDeathly** [comment]
Oh you know what, it had moved the seeding files not copied which messed my torrents up. Thats why I didn't like manual import. I wouldn't have cared too much if it had copied, but hard linking should be the highest priority if its enabled i feel.

**Comment by Taloth** [comment]
@markus101 Are you sure it respects the IsReadOnly flag on Manual Import via Queue?

**Comment by markus101** [comment]
Without diving in too much, it should as the tracked download is passed.

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs#L228

**Comment by waldnercharles** [comment]
I've run into this same issue. It would be nice to have an option to always copy / hardlink regardless of seeding status. I'm not sure how accurate Sonarr's detection of whether a file is being seeded or not is.

**Comment by TheDeathly** [comment]
The issue is that when you do a Manual Import it isn't looking at any download clients, so it just always moves. It would be really nice to have a checkbox or something that lets you choose different moving methods; copy, hard/soft link, move.

**Comment by markus101** [comment]
Manual Import has two entry points, one from the wanted page and another from the queue, if you start manual import from the queue the seeding status is captured and if its still seeding then its hardlinked or copied.

We should probably add a message in the UI that says whether or not it will copy/hardlink or move though.

**Comment by NMe84** [comment]
If you're making a message out of it, might as well add a checkbox and make it customizable. :) I've run into this problem a few times today, where I have downloaded some season manually because Sonarr couldn't understand the release name, but when I wanted to keep seeding, I noticed all the files were gone. It would be very helpful to have the option to hardlink rather than move.

**Comment by Blackkatt** [comment]
"Manual Import has two entry points, one from the wanted page and another from the queue, if you start manual import from the queue the seeding status is captured and if its still seeding then its hardlinked or copied."

yes, but that would only work if sonarr was the one that sent the torrent to the client. so not really usefull (at least not for me)

I need an option to tell sonarr that its a torrent and rules how to handle that.

so If I manually download something with my torrent client, it would be nice to be able to have sonarr import that when its done, just like it does if sonarr would have sent it.

**Comment by NMe84** [comment]
> so If I manually download something with my torrent client, it would be nice to be able to have sonarr import that when its done, just like it does if sonarr would have sent it.

It already does that. Just add the torrent to your client using the same category that you configured Sonarr to use. If the download's name is in a format that Sonarr understands it will pick it up just fine.

**Comment by Blackkatt** [comment]
Yeah, my bad. Totally works. Dunno what I did wrong the first time...

**Comment by beeblebrox** [comment]
+1 for always having the option to explicitly set hardlink/copy while importing.

+1 with a message indicating how the import will be accomplished if there is no explicit option. 

It would be very beneficial if there was a confirmation before an import will move files to prevent unexpected data lost (misplacement?). 

Perhaps this is a different issue, but I've only seen an option to import from the 'wanted' section and never from the queue (version 2.0.0.3732). With no indication a manual import from 'wanted' would move the files catching the situation later is very frustrating to deal with and correct.

**Comment by some-guy-23** [comment]
I also think it would be a good idea to indicate what method Sonarr will use for file import.

Then you could give an option to override and use a specific method instead.

**Comment by Magic815** [comment]
+1 to have an indicator of what method Sonarr will use before commencing import. Just got dinged with a HnR on my private torrent site account because Sonarr did a move instead of hardlink during a manual import. I unfortunately assumed that having the setting of 'hardlink instead of copy' would protect me in all import methods.

**Comment by gabo77** [comment]
It seems not all use cases are covered by the actual implementation. Right now, I have a torrent that has been grabbed by sonarr, sent to rtorrent and has been imported properly, but something else broke the files sonarr imported. Now that the download is complete and sonarr thinks it has been imported, I want sonarr to handle those files again, so I deleted them at the destination. When I hit import (manual, automatic, dronefac, etc.), it will always move them, which breaks my seeding or obliges me to copy them. I want to hardlink them. 

Now, they are no longer in the queue (rtorrent is seeding them), so I would I tell sonarr to grab those files again and hardlink them to the destination? Hopefully my explanations are clear enough so you can understand (not fluent in english). In the "manual import" of the "wanted" section, if I could check a box to tell sonarr to hardlink instead of moving or copying, that would be awesome :)

**Comment by markus101** [comment]
This has been implemented already.

**Comment by mtr2014** [comment]
When has this been implanted? I still only have "Move or Copy" as options.

**Comment by markus101** [comment]
The linked PR says: `Taloth merged commit 9fbe06a into develop on Nov 2, 2016`

And also makes a note about how Copy operates. https://github.com/Sonarr/Sonarr/pull/1513#issuecomment-266931780

**Comment by Magic815** [comment]
Apologies as I'm away from my computer to try Sonarr until tomorrow, but is there a way to have a confirmation box on manual import appear if hardlinking fails? I get that it will try to hardlink instead of copy (if the setting to do so is checked), but it'd be nice to have the option to cancel the import entirely if the hardlink fails - instead of just defaulting to copy.

Any time I'm using the manual import, its because I'm importing a torrent from a private tracker. Hardlinking ensures that torrent continues seeding with no further hit to my hard drive space. Should I just make a new feature request?

**Comment by markus101** [comment]
There isn't a confirmation, it's the same as an automatic import with Completed Download Handling, if the hardlinking fails because the setup doesn't support it (different volumes, not supported by the filesystem, etc), it will fallback to Copy.

I'm sure we'd implement a feature where it wouldn't automatically fallback to copying,, but feel free to file an issue as it's better than discussing it's merits in a closed issue.

**Comment by matthewdias** [comment]
I'm a bit confused, on manual import from the wanted page, is it supposed to respect the hardlink setting? Because the behavior im seeing is that it just moves the files, even tho i have it set to hardlink for normal automatic imports.

**Comment by markus101** [comment]
Did you select `Copy`?

![image](https://cloud.githubusercontent.com/assets/413544/26498755/f7765050-41e4-11e7-8f6c-24ccf4ddf940.png)

(`Copy` will attempt to hardlink if that is enabled and fallback to copy if the hardlink fails), the default action is `Move`.

If you're having a specific problem please open a thread on the forums for support.

**Comment by matthewdias** [comment]
I did yes. Will open a forum topic.

**Comment by super94i** [comment]
the only solution is to be in the destination folder then: ln -sf /source/folder/* .
hardlink them all to this folder

**Comment by drew7721** [comment]
It seem that even with the Importing setting set to use hard links, when you manually import a file and select copy it will still copy the file over instead of making a hard link to it.

For now the workaround is manually making a hard link in the destination folder `ln /source/file.mkv` and then update series and scan disk then do a rename.

<img width="584" alt="patial" src="https://user-images.githubusercontent.com/9411699/31453130-0c2516a6-ae7f-11e7-8863-f4cb524c9d2c.png">
<img width="491" alt="hardlinks" src="https://user-images.githubusercontent.com/9411699/31453174-393a4ee0-ae7f-11e7-8004-e6a2ac6dd3c5.png">

**Comment by Dnkhatri** [comment]
Something might be wrong with your settings as manual import if copy is selected hard links. I have recently imported about 30 series and over 600 episode manually using copy with hardlinked enabled and they all were hard-linked properly.

**Comment by drew7721** [comment]
@Dnkhatri you are right! I figured what was causing the issue. It was behaving like that because of the way my drives are fused. The downloader was saving them on the main drive but the sonarr library is on a fused drive. Since hard-links don't work between drives it was copying the files over. I changed the default download location to be relevant to the fused drive and now it all works as it should 💯 !
