### ISSUE TITLE
Prefer same release group as others in season

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#614]
Especially with anime it might help if we 'prefer' the same subgroup/releasegroup as other episodes in the season.
It might even be preferable to do that without config option. I think some ppl would really like that coz it might save them setting up complicated custom tags.

Somewhat related to https://github.com/Sonarr/Sonarr/issues/385 but a different approach.

**Comment by SAKUJ0** [comment]
That works with P2P releases but it would not work with scene ones. Unless Sonarr could tell whether a release is scene or not using a pre-db (which might be desirable?).

**Comment by markus101** [comment]
Would we just base this off of whats available while we are checking? If the less-preferred release group comes out first and there isn't a delay its not going to change the behaviour as its preferred not mandatory.

Sounds like we need a scoring system.

**Comment by Taloth** [comment]
Yes, it will only work with backlog searches or delayed queue. It only affects prioritization logic.

**Comment by kxzaon** [comment]
More than five years later, it is still an issue for me as a release maniac guy. I really don't like to have releases from different teams in a single season. I would also like to have the same behaviour with all the seasons of a TV show but it is less important on the scale on my cleanliness issue.
For instance today I grabbed a release from "3VO" even though the last previous episodes are from "N7G". And yeah the release quality is the same and yeah these two teams are in my preferred list because in other TV shows I've entire seasons of "3VO" releases. So I add +50 to this two keywords, "3VO" and "N7G".
So five years later, is it possible to prioritize the release of the same team as the rest of the season ?
Thanks a lot.

**Comment by markus101** [comment]
5 years later you can use preferred words, which will require manual intervention to achieve, but will do it.

Given the low number of requests for this and the complexity to do it, we're not going to do it for the foreseeable future, maybe one day.

**Comment by tomkimberlin** [comment]
I haven't wanted this for 5 years, but I would still really appreciate this feature. I shouldn't have to go through my shows and identify which release groups to prefer. As far as implementing it goes, avoiding grabbing releases until the entire season/show is searched would allow for easier analysis and comparison between potential release groups. Another idea which would minimize the need for this feature is some sort of preference towards files of a similar size. Many times Sonarr will be consistently choosing files with similar sizes but randomly choose a file out of left field which is twice as large as the other files for the same season. At the very least I think the logic in this area could use some tweaking for more consistency.
