### ISSUE TITLE
Paper cut in Sonarr

### ISSUE THREAD

**Issue by rnjohnson18** [Sonarr/Sonarr#620]
I have no idea how to describe this, so view this screenshot:

![screen shot on 2015-06-14 at 15-59-49](https://cloud.githubusercontent.com/assets/2603556/8150237/662b2b98-12a7-11e5-9673-326bcb829187.png)

Notice how the episodes currently being downloaded do not end with "Ne..." Why is this? There looks like  there is enough room for that line to fit despite the progress circle. 

Yes it's not really a big deal but at least it'll make the interface look a little more consistent, right?

**Comment by rfgamaral** [comment]
Since I don't have an active download right now can't really confirm this... But it's most likely the way the UI was built. The progress circle container is probably going all the way from the top border to the bottom one, despite that it's only being displayed in the top-right corner.

This is probably not that hard to fix.

**Comment by rnjohnson18** [comment]
Thanks for the quick (and nice) reply rfgamaral.

**Comment by rfgamaral** [comment]
You're welcome. But please note that I'm no maintainer of this project, just a regular user like you. I'm sure someone else will have something to say.

**Comment by thezoggy** [comment]
yes, just the indicator icon eating up some of the space, hence you see the cut off for the name reflect it.
