### ISSUE TITLE
PWA app installs Improperly named on Android.

### ISSUE THREAD

**Issue by ltomes** [Sonarr/Sonarr#6263]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If sonarr is installed with Firefox nightly the app is installed with the name "website".

![Screenshot_20231219_201127_Firefox Nightly](https://github.com/Sonarr/Sonarr/assets/4184677/738392b9-315f-44a2-aa6b-0d636c4bfe27)
![Screenshot_20231219_201145_One UI Home](https://github.com/Sonarr/Sonarr/assets/4184677/d782f9be-2fd2-4be7-92a5-4890e4f71598)

### Expected Behavior

The app should be installed with the name "Sonarr".

### Steps To Reproduce

Have Firefox on android
Go to sonarr
Install as app
Observe incorrect name on home screen.

### Environment

```markdown
- OS: Android 13
- Sonarr: latest 
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: Firefox Nightly
- Database:
```

### What branch are you running?

Main

### Trace Logs?

Na

### Anything else?

I glanced at the manifest files, and the name appears properly set, but I might be overlooking something.

If someone provides some guidance I can put out an MR to update the manifestsl files.

**Comment by markus101** [comment]
> - Sonarr: latest 

This isn't a version, specifically which version do you have installed from System: About?

**Comment by markus101** [comment]
Not sure what browsers default to when the name is empty, but that's what it is in v3 and already fixed in the v4 beta.

V3: https://github.com/Sonarr/Sonarr/blob/v3/frontend/src/Content/Images/Icons/manifest.json#L2
V4 Beta: https://github.com/Sonarr/Sonarr/blob/develop/frontend/src/Content/Images/Icons/manifest.json#L2

Closing since this appears to already be addressed or Firefox Nightly is having issues.
