### ISSUE TITLE
[BUG] UnauthorisedAccessException when opening v4.0.0.748

### ISSUE THREAD

**Issue by trumpy81** [Sonarr/Sonarr#6318]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Installed Sonaar v4.0.0.478. When attempting to open Sonaar, I am presented with an Epic Fail! message that states: UnauthorisedAcessException: Access to the path 'C:\ProgramData\Sonaar\config.xml'

Question is, where and how do I correct the permissions?

### Expected Behavior

I expected the program to open without issue.

### Steps To Reproduce

Edition	Windows 11 Pro
Version	23H2
Installed on	14/07/2023
OS build	22631.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0

Install Sonarr.main.4.0.0.748.win-x64-installer.exe downloaded from https://sonarr.tv/#download
After installation, attempt to open Sonaar by double clicking on the desktop icon.

See this error message:
![image](https://github.com/Sonarr/Sonarr/assets/12381786/5093cb72-4896-4110-b86f-daad645fca2a)

### Environment

```markdown
- OS: Windows 11 Pro
- Sonarr: 4.0.0.478
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox 121.0 x64
- Database: N/A
```

### What branch are you running?

Main

### Trace Logs?

Unable to get trace logs.

**Comment by thezoggy** [comment]
did you run sonarr once as admin?

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Sonarr uses very relaxed permissions when creating the DB and config file (IIRC it's everyone), if those were changed then running Sonarr once as admin may resolve it, otherwise you'll need to change them at the path listed in the error.

**Comment by trumpy81** [comment]
@thezoggy
No I did not, I simply clicked on the desktop icon.

@markus101 Thanks for the tips regarding the support forums etc. I didn't know they existed and I didn't search for them either :(
I will try running 'As Administrator' to see if that makes a difference, if not then I will hit the path and add appropriate permissions.

Thanks Guys.
