### ISSUE TITLE
Sonarr mistaking release title for release language

### ISSUE THREAD

**Issue by flexyboooy** [Sonarr/Sonarr#6326]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Possibly an edge case, but "1080p" and "x265" matched the search criteria for this release but it got rejected (ignored) because it has "Italian" in the title, although the release is in fact in English language.

![Sonarr-confused](https://github.com/Sonarr/Sonarr/assets/102152250/b867d404-6ad2-439f-97bd-4597359ef05f)

What to do to avoid this?

### Expected Behavior

Be smarter about it?

### Steps To Reproduce

Add the show to Sonarr, grab a cold one and wait ...

### Environment

```markdown
- OS: Raspbian GNU/Linux 11 (bullseye) armv7l
- Sonarr: 2.0.0.5344
- Docker Install: No
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Main

### Trace Logs?

none

### Anything else?

nope

**Comment by markus101** [comment]
You're still running Sonarr v2, this was already fixed in v3, but v4 was just released, time to upgrade.

**Comment by markus101** [comment]
This particular issue was about the language in the series title, which has been solved for a very long time.

The parser will always parse Japanese from that title because it doesn't know that `Returning Japanese` is part of the episode title. Normally languages in episode titles are stripped out during the aggregation/augmentation process (at a point when Sonarr knows the series and episode(s) in the release), but in this particular instance it's a multi-part episode so when Sonarr compares whether `Returning Japanese Part One` contains the episode's title of `Returning Japanese (1)` it fails because it doesn't.

Definitely an issue, just not the same issue as this thread was about, but we'll get it fixed.
