### ISSUE TITLE
Sonarr is duplicating downloads

### ISSUE THREAD

**Issue by TheNetworkLair** [Sonarr/Sonarr#6345]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sonarr is duplicating downloads in the root of my torrent client download directory.

- I use filebot for post processing, not sonarr. and recently sonarr has decided to create its own post processed folder containing the name of the tv shows into torrent download folder, duplicating my content in my torrent client downloads folder.

- I noticed this has started happening after upgrading to version 3.0.10.1567. my setup has not changed, previously sonarr did not behave like this. I also have sonarr "rename episodes" disabled but it still "takes over" anything it downloads making duplicates files in its own folder.

### Describe the solution you'd like

Option to actually disable sonarr post download file handling.

### Describe alternatives you've considered

Unable to find a solution.

**Comment by markus101** [comment]
Sonarr has an option to disable Completed Handling already. V4 has been out for a couple weeks now as well.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by TheNetworkLair** [comment]
Interesting. The setting somehow reverted when i upgraded. Unchecked completed download handling in torrent client config and its fixed now. Thank you

**Comment by augustuen** [comment]
This sounds like you've set your root folder to your downloads folder, which isn't compatible with how Sonarr works.

Disabling "Rename Epsiode" means Sonarr will use the original filename instead of a more sensible and prettier one defined by you. It will still need to import the file.

Using an import-script was added as a feature in V4. Though I suspect your setup will require some more fixing before you can really utilise it. Since it's a support issue, I suggest you join us over on discord or on the Sonarr forums.

**Comment by TheNetworkLair** [comment]
Correct. However It works 100% now. I just didn't want it making its own folder, just to use it for scraping downloads. I do my own processing from my clients downloads folder
