### ISSUE TITLE
Complete download handling broken with Transmission 4.0.x

### ISSUE THREAD

**Issue by carlflash** [Sonarr/Sonarr#6418]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

With reference to https://github.com/transmission/transmission/issues/6528

Sonarr removes torrents from Transmission 3.0 but not 4.0.x

I don't know if Transmission or Sonarr needs to change the way they talk to each other.

### Expected Behavior

To remove torrents.

### Steps To Reproduce

Tested with linuxserver/transmission docker images.

Sonarr removes torrent from Transmission 3.0 once seeding finishes with these settings.

Set to 1 min for testing, behavior is the same with days/weeks/months.

![1](https://github.com/transmission/transmission/assets/47334163/6be5f1f8-4d39-4bfe-be23-94051bc9a374)
![Screenshot 2024-01-14 at 20 47 24](https://github.com/transmission/transmission/assets/47334163/a5ff8606-79c5-458e-bc24-0b1e4d431135)

**With Transmission 4.0.0 torrent remains in client like this:**

![Screenshot 2024-01-14 at 20 49 53](https://github.com/transmission/transmission/assets/47334163/e15ba5d5-db94-4d1b-98e2-4668d5b98d1f)

**With Transmission 4.0.1 torrent remains in client like this:**

![Screenshot 2024-01-14 at 20 51 09](https://github.com/transmission/transmission/assets/47334163/a0fb8066-5320-4663-a7fa-abafa2d0e50f)

**With Transmission 4.0.2 and forward torrent remains in client like this:**

![Screenshot 2024-01-14 at 20 51 47](https://github.com/transmission/transmission/assets/47334163/ab239b29-fa97-4dfe-81d1-d493d02c66b8)

### Environment

```markdown
- Sonarr: https://github.com/linuxserver/docker-sonarr
```

### What branch are you running?

Main

### Trace Logs?

I can't access these at the moment.

**Comment by bakerboy448** [comment]
Trace logs are required and not optional.

as mentioned on the referenced transmission issue, Trace logs will have transmissions response and details from there - it appears transmission made a material breaking change

**Comment by markus101** [comment]
Please update the environment to include all the requested information, not just the a link to the container you're using.

We absolutely need trace logs for this to determine what could be causing this.

**Comment by salomj** [comment]
I have occasional issues with sonarr not removing downloads, like 1 in every 20 times, but it typically seems to do a good job. I'm using a custom docker images for transmission, so maybe it has to do with the linuxserver docker image?

**Comment by bbsixzz** [comment]
I followed this issue from my initial report over at https://github.com/transmission/transmission/issues/6528

I did a fresh install on a clean debian system with the latest linuxserver/transmission:4.0.5

- OS: Debian GNU/Linux 12 (bookworm) Kernel: Linux 6.1.0-17-amd64
- Sonarr: 4.0.1.929 (docker pull linuxserver/sonarr:latest)
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Safari Version 17.3 (19617.2.4.11.8)
- Database:  n/a

Here is the trace log from downloading True.Detective.S04E01.Part.1.HMAX.WEB-DL.AAC2.0.x264-BTW.mkv

https://hastebin.skyra.pw/yuxudojube.yaml

Hope this helps, please let me know if you need anything else.

Cheers

**Comment by bakerboy448** [comment]
```
2024-01-31 04:54:34.6|Trace|HttpClient|Response content (457 bytes): {"arguments":{"torrents":[{"downloadDir":"/data/.sonarr","downloadedEver":0,"errorString":"","eta":-1,"hashString":"ca10d70624d9797df628c1f04ee965a4f03e92e3","id":1,"isFinished":true,"leftUntilDone":0,"name":"True.Detective.S04E01.Part.1.HMAX.WEB-DL.AAC2.0.x264-BTW.mkv","secondsDownloading":0,"secondsSeeding":0,"seedIdleLimit":1,"seedIdleMode":1,"seedRatioLimit":2,"seedRatioMode":0,"status":0,"totalSize":847459920,"uploadedEver":0}]},"result":"success"}
```

transmission completed torrent response snippet

**Comment by bbsixzz** [comment]
![Screenshot 2024-01-31 at 05 18 40](https://github.com/Sonarr/Sonarr/assets/47334163/0224156d-69bc-4cfe-8d0e-b87cf224addf)

This is how it looks with linuxserver/transmission:4.0.5

If I switch to linuxserver/transmission:version-3.00-r8 the file is removed.

**Comment by carlflash** [comment]
> Here is the trace log

Thanks for this! 

I have the same results and have since downgraded to linuxserver/transmission:version-3.00-r8 which works correctly.

Is there something Sonarr team can do to fix this or is it up to Transmission?

**Comment by markus101** [comment]
@bbsixzz looks like your log expired, Baker pulled out the completed torrent from the log, but I also need to see the config values.

In this case `seedRatioMode: 0`, so then it checks `seedRatioLimited` from the config.

**Comment by markus101** [comment]
I've tested against transmission 4.0.2 and 4.0.5 (linuxserver's docker container) and I'm unable to reproduce any issues with seeding goals, I set the seed ratio goal in Transmission to 1, grabbed a torrent, let it download and after importing it was removed.

From the snippet of the response from transmission from bbsixzz I see that both `downloadedEver` and `uploadedEver` are both 0, which will result in Sonarr seeing the ratio being 0 (since you can't divide by 0). In my tests I saw valid values for those same properties. Once the download was complete, imported and met it's seeding goal it was removed without issue.

If you still have issues it'd be worth reaching out via one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr). Discord is likely best, particularly in this instance.

**Comment by bbsixzz** [comment]
>  I set the seed ratio goal in Transmission to 1

Hey thanks for testing this, I can't provide a new log as I'm away but why do you test a setting I don't have?

The only setting I have in Sonarr is Seed time 1.

Transmission looks like this in both 3 and 4:

![image](https://github.com/Sonarr/Sonarr/assets/47334163/ef9498e5-08d8-4168-af9a-73627a10fd4f)


Again, this is for demonstrative purposes only.

My setup seeds for a month usually then removes the file, I have no ratio set because that rarely gets fulfilled and so torrents would still stick around.

Are you saying I should set ratio goal 1 in Transmission and leave Sonarr as is with Seed time 1 only and it should work?

If you try my setup as presented with no ratio set you will find Transmission 3 to behaves correctly while Transmission 4 chokes.

**Comment by bbsixzz** [comment]
Just to be extra clear, I just want the torrents gone from Transmission after a certain amount of time ratio be damned. What settings do I need to set to make this work?

**Comment by carlflash** [comment]
@markus101 it's strange that you went ahead with completely different settings and closed the issue.

I can easily reproduce it if the settings are followed as presented. Please have a look again.

**Comment by markus101** [comment]
My mistake, but next time make sure you provide all the necessary information to diagnose instead of only screenshots that fill the entire screen.

I've also verified the behaviour with just a time limit and Transmission appears to be retting `secondsSeeding` when stopping seeding (either when manually stopped or automatically stopped when reaching it's idle timeout), which means for torrents that aren't actively seeding it's going to be very difficult for Sonarr to check that it's finished seeding and get it removed (and impossible with a seed time of 1 minute for testing).

According to https://github.com/transmission/transmission/blob/340d0d496639364524642917cefe07f402459962/libtransmission/transmission.h#L1529-L1530 (which is where the API docs point you to), this value should not reset when stopped. If this is an intentional change on the Transmission side we might be able to handle the scenario better, but for now we're leaving it as-is.
