### ISSUE TITLE
Feature request for paused torrent logic

### ISSUE THREAD

**Issue by ac1dburnz** [Sonarr/Sonarr#6423]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Right now you either have a choice to pause a torrent before it downloads or you can automatically have the torrent start once grabbed.

### Describe the solution you'd like

It would be great to have more options than just pausing or not pausing a torrent once they are grabbed and pushed to rtorrent. For instance, it would be helpful to have a logic that determines when a torrent should be paused. One possible approach is to pause only newly added series and automatically approve all series that have already been downloaded. This logic could be customized through custom rules, similar to how Add Custom Format conditions are set. Having the ability to create rules on when a download should be added in a paused state or not would be extremely useful to mitigate unwanted new shows that are added from lists. 

### Describe alternatives you've considered

n/a

**Comment by stevietv** [comment]
Wouldn't just disabling `search for missing episodes` on the import list solve this?

**Comment by ac1dburnz** [comment]
No , these solutions do not work. This is specifically for when recommendations get imported through the lists and are automatically added. I still want to have everything imported but for new items that don't have a previous record did installed eps id like to confirm if I actually want to download it or not.

**Comment by markus101** [comment]
Sonarr only adds items on lists that don't already exist in your library, so not searching for episodes by default then deciding if you want them would let you decide whether you want to search for the series, instead of searching, adding to your client then deciding whether you want them. Also a second client would you add them, search and then decide if you want that workflow for some reason.

Adding customizable rules isn't something we're going to implement at this time.
