### ISSUE TITLE
Allow users to chose the refresh perior on lmport List Sync

### ISSUE THREAD

**Issue by AN1MATEK** [Sonarr/Sonarr#6427]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

If I would like to actively monitor a list, with the refresh period configured manually. This could be an useful feature for many users. 

### Describe the solution you'd like

A dropdown or field on `Settings > Import List > [List]` that allows customization of the refresh period. This could be under Show Advanced too. 

### Describe alternatives you've considered

I've seen that there was a closed issue (https://github.com/Sonarr/Sonarr/issues/4123) where it was said that this can be accomplished with an API script. I think that can apply to most of the Feature Requests too. I do have many scripts in my setup (not for any arr API) but I still have no idea how to do it. This would allow this setting for every user with just a few clicks.

**Comment by markus101** [comment]
> If I would like to actively monitor a list

What exactly do you mean by this?

Outside of Sonarr to Sonarr syncing almost real time syncing is not the intention because most providers would see Sonarr hammering their services, and either impose rate heavy rate limits or outright block Sonarr from syncing. This is quite similar to the reasoning that Sonarr doesn't go off and search missing episodes constantly and RSS Syncs have a minimum time, since most indexers expect them not to refresh more than every 15 minutes or so.

The comment in #4123 no longer applies because each list is refreshed independently instead of whenever any list is refreshed.

It's possible we reduce the interval between refreshes some, but allowing people to customize it is unlikely and allowing it to be near realtime syncing is not something we plan to do.

**Comment by bakerboy448** [comment]
> Outside of Sonarr to Sonarr syncing almost real time syncing is not the intention

Lists are always "add this eventually" and never "add this right now" tools.

**Comment by AN1MATEK** [comment]
Hey thanks for the quick answers. I understand the settings are due to prevent hammering the services every 10 minutes, that makes sense.
<img width="278" alt="Screenshot 2024-01-26 at 17 51 21" src="https://github.com/Sonarr/Sonarr/assets/15142596/4165cc9e-b45c-4813-99e0-5287de9c1b53">
Nevertheless, a 1h or 2h interval is reasonable, not spam, specially considering services like trakt.tv that offer a premium subscription, which I am personally seeing if I could get enough value out of it to justify the purchase.

See and do as you see fit, I will not pressure the issue further.

**Comment by markus101** [comment]
The issue is it's a problem of scale, at 6-12x the number of attempts in the same period would be pretty impactful on these services, especially when a lot of the time nothing has been added.

We've discussed a bit further on Discord with the conclusion that we're not going to make it variable or decrease the times right now.
