### ISSUE TITLE
sonarr v4 cannot recognize the episode number correctly

### ISSUE THREAD

**Issue by Kelcoin** [Sonarr/Sonarr#6472]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If torrent title have S01 without episode number but in the file only have S01E01, sonarr will still try to import it as season pack and then stuck.
I dont know it's bug or new feature, but sonarr v3 does not have this problem
example:
![image](https://github.com/Sonarr/Sonarr/assets/10922375/7726e8eb-fbe6-4ae0-9791-16ab7ec3c887)
![image](https://github.com/Sonarr/Sonarr/assets/10922375/6a9fd834-c189-4b4b-81f1-5f07588f9690)

### Expected Behavior

recognize the episode number correctly from file

### Environment

```markdown
- OS: Windows
- Sonarr: 4.0.1.929
- Docker Install: no
- Using Reverse Proxy: no
- Browser: edge
- Database: Sqlite 3.36.0
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/14155623/sonarr.trace.txt)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

If the season pack only has one file Sonarr will be unable to import all the files and you'll need to manually clean it up because it expects to import them all.

**Comment by AtomBoyC** [comment]
I got the same problem. That bothers me.
The indexer site's single episode release title is fine, such as "One Piece S01E01 ....".
But the torrent file's structure is always in this way : "One.Piece.S01.... /One.Piece.S01.E01....". 
Yes, the single episode is in a full season pack name folder when releasing.
I guess sonarr using the folder name rather than indexer site's relese title when importing that file. That causes this issue.

This is a seriors problem, because many trackers prefer release single episode in that way for the convinence to cross-seed and no need to re-download when season finale repacking.
