### ISSUE TITLE
Files become "stuck" in download client when a better download is queued while original file is downloading

### ISSUE THREAD

**Issue by asherbig** [Sonarr/Sonarr#6641]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes, an initial download (A) is grabbed. While A is downloading but before A has been imported, a second, better download (B), is grabbed. What ends up happening is B gets imported, and A is stuck in a state where it's downloaded, but unable to import, and unable to be deleted. `Not a Custom Format upgrade for existing episode file(s)`

![image](https://github.com/Sonarr/Sonarr/assets/9668239/adb5fccc-1a07-433e-b5d2-f05aca17fd11)

### Describe the solution you'd like

I imagine that Sonarr already has auto-deletion logic that looks something like:
```
if download.paused and download.imported:
  download.delete()
```
I am suggesting that logic be added to like so:
```
if download.paused and download.imported:
  download.delete()
elif download.paused and download.queued_before_current_imported_file: # new logic
  download.delete()
```

I think this would solve the problem that I'm having, since download A was queued before download B. It makes sense that download B was queued, since Sonarr thinks it's an upgrade over download A. But that also means that download A should now be in a "ready to be deleted" state, since download B is now the "primary download".

I still believe that paused logic should be respected. Downloads should not be deleted if they are not paused in the download client. This should help prevent deleting downloads before seeding requirements are met.

I also don't believe that this logic will lead to download loops, though I am likely not aware of all the possible edge cases that this code will run through that might lead to unwanted behavior.

### Describe alternatives you've considered

Adding a delay to the download grabs.

Cons:
* missing "swarm" downloads
* adding X amount of time to the new content cycle
* Still not guaranteed to fix the problem, only aims to reduce the probability of it happening

Pros:
* It is currently possible to do

**Comment by markus101** [comment]
Similar to https://github.com/Sonarr/Sonarr/issues/5515, but https://github.com/Sonarr/Sonarr/issues/4324 is likely the closest duplicate, as mentioned there hit and runs make this a complicated endeavor, no short term plans to implement queue management at this level, but as mentioned in #5515 you could do it with a custom script, either on grab or import.

**Comment by asherbig** [comment]
What are hit and runs?

**Comment by markus101** [comment]
Yes, only deleting when paused would overcome the H&R aspect of it.

Just being paused and grabbed before another download could still remove something that the user didn't want it to though, so there needs to be more safeguards than that, especially when we're talking about data that hasn't been imported.

**Comment by asherbig** [comment]
Ah, thanks for the response! What's a scenario where something might be removed that the user didn't want removed?

If the first download had just completed and imported before the second download started, then the end state after download 2 finishes and imports would be the same as the change I'm proposing.

**Comment by markus101** [comment]
I'm not sure offhand, but there are many reasons why something could be rejected that aren't "not an upgrade".

https://github.com/Sonarr/Sonarr/tree/develop/src/NzbDrone.Core/MediaFiles/EpisodeImport/Specifications

You could also potentially have the reverse problem, a file is grabbed because it's seen as an upgrade (usually because the indexer says it's X), but at import time it get stuck because it's actually Y.

Moving to trash could work, but in a seedbox scenario that could take a considerable amount of time and block other imports.

There are a lot of edge cases that could arise and lead to issues.

**Comment by markus101** [comment]
Perhaps an option for "removing" for torrents is having a removal category (like post import), that way it's not stuck in Sonarr's queue, but Sonarr doesn't force the deletion either.


For Usenet moving to a different folder and removing from history could be viable.

**Comment by asherbig** [comment]
> You could also potentially have the reverse problem, a file is grabbed because it's seen as an upgrade (usually because the indexer says it's X), but at import time it get stuck because it's actually Y.

I agree, this is a real issue and is annoying. And it's similar to the scenario in the post, but I think it's different enough to not need to be addressed by the solution to this specific problem where queueing time leads to stuck downloads

**Comment by asherbig** [comment]
> but Sonarr doesn't force the deletion either

What do you mean? Like Sonarr will not auto-delete ever? Or Sonarr will not auto-delete until certain conditions are met (paused, etc)?

**Comment by markus101** [comment]
Two things:

1. Some people perma seed everything, so they'd never want things deleted, but a different category would work for them
2. It's a lot safer to test things without removing them, so to start just changing the category would be a good start it's stop Sonarr from seeing them in queue and also prevent it from deleting something while all the kinks are worked out

**Comment by markus101** [comment]
Closing as this isn't something we have current plans to tackle.

**Comment by chrisfosterelli** [comment]
Sorry to necro an older issue but I was considering creating a new issue when I came across this. 

@markus101 I wonder if the discussion in this issue is conflating a couple things:

1. the desire to delete / trump in progress or older downloads, and 
2. the desire to not have sonarr get stuck in an import error state when an upgrade imports before the lower scored version

The linked duplicates and reason for closing this issue seem to be for the first point, and I totally follow that logic with respect to HnRs so I think that makes sense, but I think the second point is potentially still a legitimate issue by itself.

If the following situation happens, sonarr handles everything great:

1. Sonarr finds release A with CF score of 1000, begins download of release A
2. Sonarr finds release B with CF score of 2000, begins download of release B
3. Download completes for release A, Sonarr imports release A
4. Download completes for release B, Sonarr imports release B because 2000 > 1000

In this case both torrents are left in the client until their respective seed goals are met, in which case sonarr then cleans them up (or if they're moved to a post-import category it's something else's job to deal with it). No issue with HnR here.

If the following situation happens, sonarr borks:

1. Sonarr finds release A with CF score of 1000, begins download of release A
2. Sonarr finds release B with CF score of 2000, begins download of release B
3. Download completes for release B, Sonarr imports release B
4. Download completes for release A, Sonarr errors on import for release A because 1000 < 2000

In this case there is no issue with HnR (good), but sonarr is stuck in an error state. I think some of the issues linked and discussion in this thread is a request that, at step 3, sonarr should stop and delete the download for release A. I completely agree this would cause issues with HnR and should not be done. However, my suggestion is that, at step 4, sonarr could at least be smart enough to realize that download A was requested by sonarr before download B and therefore download A having a lower score is expected and should not replace the existing file. It should still do the same thing as the current situation with respect to torrent handling: leave both of them there until their respective seed goals are met, in which case sonarr cleans them up, or move them to a post-import category if configured to do so. There'd be no issue with HnR here. Essentially, I'm not trying to request that sonarr does something different so much as request it does the same thing it already does even in edge cases where DLs finish out of order. 

This situation is fairly common to occur with some shows that have releases from both scene and P2P groups, if you use autobrr and if you use scene trackers because scene releases usually come out before P2P releases, but the P2P releases are usually unpacked so they can import before unpackarr finishes unpacking the scene release. This causes both unpackerr and sonarr to get stuck until I manually go clean things up. I could use delay profiles to try to reduce the occurrence of this but it would not be a guarantee against the situation and would mean I lose out on any opportunity to participate in the initial swarm.

If you feel this reasoning makes sense and is fundamentally different from the issue here I would be happy to open a new issue. But I didn't want to do so preemptively if you think this is the same as the other issues as I recognize there's already been three issues closed about this.
