### ISSUE TITLE
DVD Order

### ISSUE THREAD

**Issue by TechD87** [Sonarr/Sonarr#6648]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I already know that this is a current open issue and in turn will likely make this ticket moot. 

However, I'm generally curious regarding the difficulties retrieving this request via Skyhook. Is there able to be a separate API per format? 

### Describe the solution you'd like

An update to T/T #255 on the current standings on it. Maybe having some kind of transparency so that the end-customers can see the progress and possibly give advice. 

### Describe alternatives you've considered

N/A

### Anything else?

Keep up the great work. Ya'll are awesome.

**Comment by Krandor1** [comment]
When there is an update the open issue will be updated.  On Mar 23, 2024, at 20:48, TechD87 ***@***.***> wrote:﻿
Is there an existing issue for this?

 I have searched the existing open and closed issues

Is your feature request related to a problem? Please describe
I already know that this is a current open issue and in turn will likely make this ticket moot.
However, I'm generally curious regarding the difficulties retrieving this request via Skyhook. Is there able to be a separate API per format?
Describe the solution you'd like
An update to T/T #255 on the current standings on it. Maybe having some kind of transparency so that the end-customers can see the progress and possibly give advice.
Describe alternatives you've considered
N/A
Anything else?
Keep up the great work. Ya'll are awesome.

**Comment by markus101** [comment]
Please don't open duplicate issues. When we have information to provide the original issue will be updated. If you'd like to ask a question about block issue please use on of the support channels.

[forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr)
