### ISSUE TITLE
Move to using Redux toolkit (and React-redux hooks)

### ISSUE THREAD

**Issue by joshka** [Sonarr/Sonarr#6719]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'm re-learning redux in so I can implement the multi-user stuff (having not touched it since ~2016). I noticed that they introduced the redux toolkit in 2019, which changed a bunch of things. Have you considered simplifying a bunch of the redux / react code by moving over to that and  the newer versions of react-redux which use hooks instead of connect.

### Describe the solution you'd like

Follow the migration steps documented on the redux site for this.
- https://redux.js.org/tutorials/fundamentals/part-8-modern-redux
- https://redux.js.org/usage/migrating-to-modern-redux
- https://redux.js.org/usage/migrations/migrating-rtk-2

Change to using hooks instead of connect:
https://react-redux.js.org/api/hooks

Perhaps wait until after the .NET 8.0 upgrade lands to avoid changing too many things at once.

### Describe alternatives you've considered

NA

### Anything else?

Note - this is more just looking to understand whether his has been tried / proposed / thought about before. I didn't see any obvious issues about it / messages in the discord.

**Comment by markus101** [comment]
If we were writing the frontend again starting now then, redux toolkit would be quite appealing, but at this time it seems like an unnecessary rewrite as a lot of the boilerplate for updating the state already exists.

I'd also really consider not using redux at all and use zustand or another state management tool instead. Zustand + SWR is a pretty nice combination for managing state with caching and not having to do everything you need to do with redux.

We already use hooks for some state operations with redux, mostly in `.tsx` files where we've rewritten things, eventually things will get migrated over (and most new things are done in TS instead of JS), but converting everything to TS and functional components isn't really a priority at this time.

**Comment by joshka** [comment]
Thanks for the context. Makes sense.

**Comment by joshka** [comment]
> I'd also really consider not using redux at all and use zustand or another state management tool instead. Zustand + SWR is a pretty nice combination for managing state with caching and not having to do everything you need to do with redux.

You just non-ironically channeled this (at 3:05) :)
https://youtu.be/aWfYxg-Ypm4?si=ynWVWznfBWtFSjiq&t=185
