### ISSUE TITLE
Manual import UI improvements

### ISSUE THREAD

**Issue by ghost** [Sonarr/Sonarr#673]
I generally import a folders containing a single tv show and this can be painful where it does not match.
1. When searching for a unmatched series it should auto focus to the series name search so I do not have to click before I type to search.
2. A button to open the add new series page in a new tab would be nice.
3. Setting multiple episodes to to a single series or season should be possible (checkboxes?) nothing like searching for the same series 40 times to drive you mad!
4. Same as above but for setting seasons (This presents a few technical challenges I think). 
5. When selecting a season or episode It would be nice if I could just type a number such as 1 and it selects season 1.

**Comment by markus101** [comment]
1. It was doing this, might have broken in the Bootstrap upgrade

2. Multiple tabs are not a good thing for Sonarr, the end result is too many ajax calls that get hung out especially around signalR.

3. Leaving this out was intentional, but something we want to do, similarly we could do better at falling back to the folder for more info to avoid this

4. For episodes? We'd need a way to fill the range, pick the starting episode and fill up from there, users picking a range that we couldn't complete would be an issue.

5. Maybe via a filter we could narrow it down? The current view would be tough to use with lots of seasons or episodes, but I don't click typing a 1 and getting episode 1 would be a good thing, any 2 or 3 digit numbers would be impossible to choose with a single key press and timing out would result in frustration I think, either they were too slow or there is a lag while we wait for the timeout.

**Comment by markus101** [comment]
Bulk editing of manual import items will be addressed via https://github.com/Sonarr/Sonarr/issues/1643
