### ISSUE TITLE
Feature Request: Add "Cutoff Unmet" option to Series Monitoring

### ISSUE THREAD

**Issue by edrock200** [Sonarr/Sonarr#6742]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

To add an ability to edit per show or in bulk, and enable monitoring for episodes in which cutoff is unmet.

### Describe the solution you'd like

Add a "cutoff unmet" in the Monitoring dropdown selection box of the "Series Monitoring" dialogue box which selects items in which cutoff is unmet.

### Describe alternatives you've considered

Select "Missing", then manually enable monitoring for remaining episodes that exist but cutoff is unmet.

### Anything else?

Appreciate the consideration.

**Comment by markus101** [comment]
Since you didn't really explain the problem and just explained the solution a couple times, what exactly is the problem you're trying to solve with this request?

If the cutoff is already met why do you need to unmonitor them?
This sounds like a roundabout way (via manually changing things) to get the behaviour of unmonitoring things when the cutoff is met.

**Comment by edrock200** [comment]
> Since you didn't really explain the problem and just explained the solution a couple times, what exactly is the problem you're trying to solve with this request?
> 
> If the cutoff is already met why do you need to unmonitor them? This sounds like a roundabout way (via manually changing things) to get the behaviour of unmonitoring things when the cutoff is met.

Yes, my apologies, I said it backwards. When going into a show, I want to unmonitor items in which cutoff is met. Presently, there doesn't appear to be a way to do this unless I'm missing it.

**Comment by markus101** [comment]
It's not that they're backwards, it's about explaining the problem.
Why would this be useful to your workflow?
Since the cutoff is met nothing would be downloaded for those episodes, but why do you want to no longer monitor those episodes?

**Comment by edrock200** [comment]
> It's not that they're backwards, it's about explaining the problem. Why would this be useful to your workflow? Since the cutoff is met nothing would be downloaded for those episodes, but why do you want to no longer monitor those episodes?

Primarily because when I have a bunch of randomly missing episodes in a show, today, I will click Series Monitoring, then missing, to unmonitor the episodes that exist, then I will click Search Monitored on the show. Because I've unmonitored existing, it won't use up api hits/queries for shows that already exist, only the missing ones. I would like to expand this to query for items that exist but cutoff isn't met as well in an automated manner.

**Comment by markus101** [comment]
Search monitored episodes at a series level has two different behaviours:

1. If no seasons are monitored, episodes are searched for individually
2. If at least one season is monitored then season searches are performed for those monitored seasons

Most of the time the second method applies, because most people don't unmonitor seasons then monitor a couple scattered episodes.

If you ended up invoking multiple searches after toggling the monitored state a couple times (missing then cutoff unmet) you'd likely end up using more API requests.

I don't think a cutoff unmet monitoring option makes a lot of sense, but it may make sense to improve how this search behaves to optimize results.

**Comment by edrock200** [comment]
Thanks for taking the time to explain.
