### ISSUE TITLE
Feature request - easier language priority settings

### ISSUE THREAD

**Issue by ianlot** [Sonarr/Sonarr#6762]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The current language settings with custom profiles is not easy and user friendly, especially if the user doesn't speak well English, and can't understand the Servarr wiki. 

### Describe the solution you'd like

It would be nice if a user could add a language list to a quality profile. 
For example, I create a new quality profile, I select 720p webdl, 720p bluray. Then I add the languages I want, for example I add English, and German, and Multi language. Then I can drag and drop the list items to prioritize them, just like with the qualities. 

### Describe alternatives you've considered

Alternative can be and "easy" setup, that I described above, and an "advanced" setup. Advanced setup can be the current custom profiles.

**Comment by ianlot** [comment]
Sorry, that's what I meant, the trash guide.

**Comment by markus101** [comment]
We have no plans to add languages back to quality profiles.

**Comment by gudvinr** [comment]
> We have no plans to add languages back to quality profiles.

It should be reconsidered, honestly. Right now, if you want different profile that only changes language, you need to add EVERYTHING one by one:
- each source
- each quality type

In comparison, Radarr only requires you to:
- duplicate profile
- select language

So, if you want to filter "decent HD" videos in single languages, you will need to play checkers with these checkboxes.  
And you probably will need to copy some regexes from another site (because that's what official wiki says).

Even though you already have profile but you can't import "standard" profile so you really need to do that from scratch or import obscure jsons that might not even do what you want.

Sure, once you've done it (if you were brave enough) you can export and import that custom profile if you want to only change the language.

But if you ever change your "standard" quality profile, you will need to also go through the same process again.

So, unless you if only consume content in English (because search for releases in other languages is pretty bad anyway) or watch anime, this impacts UX heavily.
