### ISSUE TITLE
Add custom indexer

### ISSUE THREAD

**Issue by lucad87** [Sonarr/Sonarr#6833]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I need to add custom indexers that are not showed in the default Jackett indexers list.

### Describe the solution you'd like

I'd like to have a dedicated page in the frontend to achieve this goal, giving us also the possibility to add private custom indexers that use credentials.

### Describe alternatives you've considered

At least, give us the possibility to encrypt a password value in order to add custom indexers json files manually in the /Indexers folder.

**Comment by stevietv** [comment]
You can add a custom torznab or newznab indexer no problem to sonarr.
Indexers need to follow this sort of standard in order to be parsable with Sonarr.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
