### ISSUE TITLE
FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jdfalk** [Sonarr/Sonarr#689]
I am getting repeated crashes in Sonarr on Ubuntu. I have a full crash log, and GDB crash dump also, but didn't want to upload it without anyone actually caring the issue.

Log:
Jul 14 22:50:33 theark mono[4882]: at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
Jul 14 22:50:33 theark mono[4882]: at System.Threading.Timer+Scheduler.SchedulerThread () [0x00000] in <filename unknown>:0
Jul 14 22:50:33 theark mono[4882]: [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
Jul 14 22:50:33 theark mono[4882]: at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
Jul 14 22:50:33 theark mono[4882]: at System.Threading.Timer+Scheduler.SchedulerThread () [0x00000] in <filename unknown>:0
Jul 14 22:50:33 theark mono[4882]: System.NullReferenceException: Object reference not set to an instance of an object
Jul 14 22:50:33 theark mono[4882]: [Fatal] GlobalExceptionHandlers: EPIC FAIL: Object reference not set to an instance of an object
Jul 14 22:50:33 theark mono[4882]: at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
Jul 14 22:50:33 theark mono[4882]: at System.Threading.Timer+Scheduler.SchedulerThread () [0x00000] in <filename unknown>:0
Jul 14 22:50:33 theark mono[4882]: EPIC FAIL: System.NullReferenceException: Object reference not set to an instance of an object

System:
ProblemType: Crash
Architecture: amd64
Date: Sun Jul 12 21:48:35 2015
DistroRelease: Ubuntu 15.04
ExecutablePath: /opt/NzbDrone/NzbDrone.exe
ExecutableTimestamp: 1434652511
InterpreterPath: /usr/bin/mono-sgen
ProcCmdline: /usr/bin/mono /opt/NzbDrone/NzbDrone.exe -nobrowser
ProcCwd: /
ProcEnviron:
 LANG=en_US.UTF-8
 PATH=(custom, no user)
 SHELL=/bin/bash

root@theark:/var/crash# lspci -nn
00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor DRAM Controller [8086:0150] (rev 09)
00:02.0 VGA compatible controller [0300]: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller [8086:0152] (rev 09)
00:14.0 USB controller [0c03]: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller [8086:1e31] (rev 04)
00:16.0 Communication controller [0780]: Intel Corporation 7 Series/C210 Series Chipset Family MEI Controller #1 [8086:1e3a] (rev 04)
00:1a.0 USB controller [0c03]: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2 [8086:1e2d] (rev 04)
00:1b.0 Audio device [0403]: Intel Corporation 7 Series/C210 Series Chipset Family High Definition Audio Controller [8086:1e20] (rev 04)
00:1c.0 PCI bridge [0604]: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 1 [8086:1e10] (rev c4)
00:1c.1 PCI bridge [0604]: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 2 [8086:1e12] (rev c4)
00:1c.4 PCI bridge [0604]: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 5 [8086:1e18] (rev c4)
00:1c.5 PCI bridge [0604]: Intel Corporation 82801 PCI Bridge [8086:244e] (rev c4)
00:1c.6 PCI bridge [0604]: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 7 [8086:1e1c] (rev c4)
00:1c.7 PCI bridge [0604]: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 8 [8086:1e1e] (rev c4)
00:1d.0 USB controller [0c03]: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1 [8086:1e26] (rev 04)
00:1f.0 ISA bridge [0601]: Intel Corporation Z77 Express Chipset LPC Controller [8086:1e44] (rev 04)
00:1f.2 SATA controller [0106]: Intel Corporation 7 Series/C210 Series Chipset Family 6-port SATA Controller [AHCI mode] [8086:1e02] (rev 04)
00:1f.3 SMBus [0c05]: Intel Corporation 7 Series/C210 Series Chipset Family SMBus Controller [8086:1e22] (rev 04)
01:00.0 RAID bus controller [0104]: LSI Logic / Symbios Logic MegaRAID SAS 2108 [Liberator] [1000:0079] (rev 05)
02:00.0 Ethernet controller [0200]: Intel Corporation 82572EI Gigabit Ethernet Controller (Copper) [8086:107d] (rev 06)
03:00.0 USB controller [0c03]: VIA Technologies, Inc. VL80x xHCI USB 3.0 Controller [1106:3432] (rev 03)
04:00.0 PCI bridge [0604]: Intel Corporation 82801 PCI Bridge [8086:244e] (rev 41)
07:00.0 SATA controller [0106]: Marvell Technology Group Ltd. 88SE9172 SATA 6Gb/s Controller [1b4b:9172] (rev 11)

**Comment by Taloth** [comment]
Read the sticky on the forum.

**Comment by jdfalk** [comment]
It's stuff like that that causes me not to contribute feedback or anything
useful to projects.

I looked through the open listed bugs specifically listed to Ubuntu at the
beginning and none of them were references to my kernel version or anything
specific to my instance.

Learn to use GitHub properly for triaging issues. Instead of pointing users
to some 90 page long forum to parse through. It is embarrassing and
unprofessional.

**Comment by Taloth** [comment]
You looked through the _open_ listed bugs, did you consider that there may be closed issues on the subject?
Like [this query](https://github.com/Sonarr/Sonarr/issues?q=is%3Aissue+nullreferenceexception+is%3Aclosed), which gives you https://github.com/Sonarr/Sonarr/issues/579 and https://github.com/Sonarr/Sonarr/issues/586.

I pointed you to the thread which describes your issue, and where the first post has been edited to with the likely solution. The only reason why I didn't post a direct link was because I was on my phone, ow, and at work... so you're welcome.

I have to give you some credit though, you at least tried searching.

It's a pity that github doesn't allow us to add a banner to the new issue page to have ppl search the forum as well. Coz that's where most support requests go.

**Comment by jdfalk** [comment]
A forum is not a bug tracker.

**Comment by markus101** [comment]
I think our first response could have been a bit more courteous, but we've had countless threads on this subject (on github and our forums) so our patience is thinning on this subject.

> It's stuff like that that causes me not to contribute feedback or anything useful to projects.

Unfortunately this goes both ways, we do take time out of our busy lives to work on it. We don't enjoy weeding through and triaging the same issue repeatedly or dealing with hostility when someone doesn't like our tone or response.

> Learn to use GitHub properly for triaging issues. Instead of pointing users
to some 90 page long forum to parse through. It is embarrassing and
unprofessional.

I think thats a little of the pot calling the kettle black, telling us we're doing it wrong isn't professional either. If we're being completely honest, pointing you to the stickied thread is triaging though (bonus points for providing a link?). Would a 90 page github issue be any better?

> I looked through the open listed bugs specifically listed to Ubuntu at the beginning and none of them were references to my kernel version or anything specific to my instance.

This is actually quite important to us, at first look we both concluded your issue was the same as the issues we've diagnosed and have a resolution for.

> A forum is not a bug tracker.

No, but its a damn good place to have a discussion and gather information before determining if there is an bug to track or further work for us to do, we use GHIs as a source of things to work on, filling it with support requests (which is a high percentage of our overall requests doesn't add value for anyone). If there was a closed issue that contained information on this issue would you have seen it?


Not sure if this needs to be said, but I'm not trying to defend @Taloth or pile on hate towards you, I'm trying to explain where we're coming from and why we do things the way we're doing it. In the end I think we all want the same thing, Sonarr to be the best it can be, so we do value constructive criticism and suggestions.

**Comment by jdfalk** [comment]
Same on my side so apologies all around. .Net/Mono is specialness so
understandable.

However, as someone who has worked with very good bug trackers, and very
bad bug trackers and is now very accustomed to using a excellent bug
tracker, it is second nature to see the bugs in the actual bug tracker. So
I am biased towards using that in professional environments and obviously
this is a side project so there are massive differences but it creates gaps
in my brain when I can't see bugs in a bug tracker like normal. So once
again apologies for that.

Having clients automatically submit bugs (on github would most likely
require the user to be logged in), and a good triage system that
effectively groups feature requests, potential issues, requirements
gathering, dupes the bugs as necessary, applies tags, and attempts to
minimize the impact to actual development time is critical so I do
understand that as well. I don't think a forum fits but again, could be my
blinders and absolute hate of forums.

The first thing I did was search the bug tracker before I even submitted an
issue. I then looked at the project guidelines and it said to go look at a
90 page forum post that made me want to stab myself. So then I started
looking through the ubuntu specific bugs on the forum post relating to the
kernel issues as this only started occuring after I upgraded my kernel from
v4.1-rc3-unstable/
<http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.1-rc3-unstable/> to
v4.1-unstable/
<http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.1-unstable/> as I am on a
mainline kernel for btrfs reasons and was submitting issues to the ubuntu
team. After I found references to most issues occurring with older kernels,
I had a full GDB crash dump and as you had stated you had spent a good time
trying to solve these issues. I had hoped to assist where I could by
actually providing a full crash dump on a later kernel to see if it's a
kernel issue in this case that was causing my particular issue. If so then
it's possible that it needs to be escalated now to the ubuntu team to get
resolved higher up in the kernel.

So all of that thought went in before I posted the bug. Now granted, I can
understand why the team didn't want to do anything and mark it as closed.
However, I have a real issue that when I actually tried somewhat to follow
your steps and honestly found them to be pretty obnoxious in regards to
someone attempting to fix their issue and contribute meaningful data.

Everyone has the right to their own opinions and attitudes, in technology
we all get frustrated and angry that's why we go and make something better.
That's also why we rage quit :). I am perfectly happy with anyone pointing
out what an idiot I am because it let's me grow as a person, and if I
disagree I often say so (in horrible bursts of memes, rants, and something
reflecting pictionary but drawn worse and angrier :p) but I always consider
what they say.

Have a great day and thanks for a reasoned, rational, and well thought out
response.

**Comment by Taloth** [comment]
So kernel 4.1.x... then I have this nice thread for you: https://forums.sonarr.tv/t/native-mono-crash-on-linux-kernel-4-1-2/6330 Just posted yesterday.
Obviously still an external cause.

**Comment by jdfalk** [comment]
OK Taloth, are you always an asshole? Honestly? Your response in the forum makes me believe in real life you just really are an asshole all the time. "That's what you get with new kernels smile"  I am answering here so that others can see when searching in github. I will also use your forum but I wanted to make sure that others saw the fact that you just don't really care about user issues. Kudos to others in the team who obviously do want to fix issues and make the project better.

**Comment by kayone** [comment]
We definitely have an asshole in this thread and its not @taloth.

**Comment by jdfalk** [comment]
Sigh... Now I have to address this publicly in every way I can which isn't
something that I had originally planned on doing.

**Comment by Taloth** [comment]
C'mon guys, this isn't what any of us wanted. At this point we're all biased toward interpreting everything ppl say negatively, even if they didn't mean it that way. We're aggravated and that's not going to end well.

@jdfalk. I briefly mentioned before that I was at work when replying to you initially using my cellphone. This unfortunately meant that I redirected you to the forum thread in a way that was too short to properly convey my intention. I never meant that you 'should've read the forum' , I merely wanted to point you to the existing discussion to help you along. I apologise for the way this happened.

This bias in interpretation also happened on the forum. my sentence with regard to new kernels can be interpreted as 'you're stupid for using new kernels' or as 'shit like this happens with new kernels, so lets go figure it out'. If I meant the first I wouldn't have used the smiley.
In the rest of the thread I continued to assist him in investigating the matter. With the ultimate conclusion that the code that fixed the problem in earlier kernel versions was removed again in 4.1, causing a regression, but that we don't yet know if it's something mono can fix or whether it's truly a kernel regression and should be fixed by the kernel team.
I wish you had focused on that part of the conversation since that was about addressing the issue.

I do however have to mention my surprise (of whatever the correct english word is) when you said that you explicitly posted you reply on github to make sure everybody could see what happened. I assume you did that because you're angry and isn't your standard modus operandi, it doesn't exactly reflect well on yourself. (I believe this is what kayone commented on)
But personally, I think they'll look at this and take it as an example of a conversation initially gone horribly wrong and (hopefully) subsequently settled in a fair manner.

Neither of us has been particularly tactful in our responses. I sincerely hope we can leave this behind us and continue addressing the kernel issue on better terms.

**Comment by jdfalk** [comment]
Absolutely, and a completely fair response. Yes I was frustrated with that
and understanding that English isn't your first language helps. I was
preparing a G+ post (which as its G+ no one would see it anyways ha!) Ohh I
will get nasty looks for that one at work tomorrow.
https://plus.google.com/u/0/+JohnathanFalk/about

But absolutely with that under the bridge and done.
