### ISSUE TITLE
Anime packs/batches not showing

### ISSUE THREAD

**Issue by Seoyne** [Sonarr/Sonarr#696]
The only time packs show up in searches is when its listed as 
* [CBM] Psycho-Pass 1-22 Complete (Dual Audio) [BDRip-1080p-8bit-AC3]

When most are listed as:

* [Commie] Psycho-Pass [BD 1080p FLAC]

**Comment by markus101** [comment]
Please use our forums for support.

Results shown in manual search are whats returned by your indexer, likely an issue because Sonarr is looking for a specific episode and your indexer isn't returning the full pack. In the event it was returned Sonarr would reject it because it wouldn't be able to determine the series (no episode information to parse).
