### ISSUE TITLE
Search for upgrades when adding series

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#712]
Instead of searching for just missing, should we search for all episodes that could use an upgrade? We'd need to figure out which episodes are missing plus the list that hasn't met the cutoff and do a search. Use season searches when appropriate (more than one episode is going to be searched for is the current criteria).

Perhaps this should rely on changes to quality profiles to default to not upgrading? https://github.com/Sonarr/Sonarr/issues/426

**Comment by thezoggy** [comment]
should also maybe warn people about adding with full backlog / upgrade on how that may hammer providers...   seen people lately come over from sb where 720p bluray is better than 1080p web-dl.. where sonarr views the opposite.. thus they see their bluray's get nuked or see a bunch of stuff queued because of the quality difference between the two apps.
