### ISSUE TITLE
Filter Queue by State

### ISSUE THREAD

**Issue by ObviousViking** [Sonarr/Sonarr#7196]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Lack of filtering on the que page for when a large number of items are being dealt with. When there is a large number of items dealt with the que can get pretty laggy. So filtering to just complete might make this easier to deal with.

### Describe the solution you'd like

I would like to be able to filter on the status of a download. i.e complete, failed, in progress. This would also make mass clean up easier too 

### Describe alternatives you've considered

Downloading less at a time...... but thats not possible with it being automated. So no other process that i know of

**Comment by darylf** [comment]
I was about to request a similar feature! My queue has grown to over 1500 items, and I often need to manually interact with over 25 of them at once. Unfortunately, the queue page constantly jumps around due to sorting changes, making it difficult to manage. I was hoping for a filter that would allow me to view only items requiring manual interaction, making the cleanup process more manageable. This would greatly improve usability when handling large queues. Filtering by states like "manual interaction required," or "in progress" would be a game-changer for managing high-volume queues more efficiently.
