### ISSUE TITLE
Migration Required for qualitydefinition validations

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#7272]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

```json
    {
        "id": 2,
        "maxSize": 0,
        "minSize": 0,
        "preferredSize": 0,
        "quality": {
            "id": 1,
            "name": "SDTV",
            "resolution": 480,
            "source": "television"
        },
        "title": "SDTV",
        "weight": 2
    },
```

or similar entries for existing quality definitions fail the new validation and should have a forced database migration to migrate to meet requirements

### Expected Behavior

Existing Values should not be invalid with migration

### Steps To Reproduce

n/a

### Environment

```markdown
- OS: n/a
- Sonarr: 4.0.9.2457
- Docker Install:  n/a
- Using Reverse Proxy: n/a 
- Browser: n/a
- Database: n/a
```

### What branch are you running?

Develop

### Trace Logs?

```
Invalid request Validation failed: 
 -- MinSize: 'Min Size' must be less than or equal to '0'.
 -- PreferredSize: 'Preferred Size' must be greater than or equal to '10'.
```

**Comment by markus101** [comment]
For validation changes we don't run a separate migration, values will need to be updated when saved if they fall outside the bounds.

**Comment by austinwbest** [comment]
I would suggest correcting the API responses when this happens since it wont be fixed. The user also said they used the reset in sonarr its self and it did not fix the problem which means it is possible the reset is not even using the min required values to pass validation either.

When sending Preferred of 0 this is the response:
```
Invalid request Validation failed: 
 -- MinSize: 'Min Size' must be less than or equal to '0'.
 -- PreferredSize: 'Preferred Size' must be greater than or equal to '10'.
```

MinSize must be less than or equal to 0??

When sending Max of 0 this is the response:
```
Invalid request Validation failed: 
-- PreferredSize: 'Preferred Size' must be less than or equal to '0'. 
-- MaxSize: 'Max Size' must be greater than or equal to '95'.
```

PreferredSize must be less than or equal to 0??

this one is even more problematic as 10 was sent in the payload but it still says it needs to be less than or equal to 0 when it should be greater than or equal to 10.

Based on this, hopefully this tldr helps
- Seems one error is triggering a second to show up incorrectly
- Seems the wording is less than instead of greater than
- Seems the error responses are not using the validation minimums in those extra errors
- Seems the UI reset is not using the minimums that this new validation requires (did not confirm this one, just based on user explanation on what they tried)

**Comment by markus101** [comment]
The logic for the validation is in https://github.com/Sonarr/Sonarr/blob/develop/src/Sonarr.Api.V3/Qualities/QualityDefinitionResourceValidator.cs

but effectively:

- Min must be greater than or equal to 0
- Min must be less than or equal to the preferred value
- Preferred must be greater than or equal to the minimum value
- Preferred must be less than or equal to the maximum value
- Maximum must be greater than the preferred value
- Maximum must be less than the max value
- All values must either be null or >= 0 <= 1000


Min: 10
Preferred: 0
Max: ?
```
Invalid request Validation failed: 
 -- MinSize: 'Min Size' must be less than or equal to '0'.
 -- PreferredSize: 'Preferred Size' must be greater than or equal to '10'.
```

Min fails being less than preferred and thus preferred fails because it's less than 10.


Min: 0
Preferred: 95
Max: 0
```
Invalid request Validation failed: 
-- PreferredSize: 'Preferred Size' must be less than or equal to '0'. 
-- MaxSize: 'Max Size' must be greater than or equal to '95'.
```

Same-ish issue, preferred fails because it's greater than the max of 0 and max fails because it's less than 95.

The only way to capture all possible errors is to check all the cases and doing so conditionally would be a pain. Ultimately we opted to not try and guard the checks from expecting certain ranges and just throw back all possible errors.

The validation cannot make changes to the resource, but we may be able to improve the messaging to include the quality that is failing so it's easier to adjust in the UI.

I can't reproduce reset not working.
