### ISSUE TITLE
Naming Pattern not being adhered to

### ISSUE THREAD

**Issue by kingy444** [Sonarr/Sonarr#7290]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Using the naming pattern `{Series.Title}.S{season:00}.E{episode:00}...{Episode.CleanTitle}` the `...` is always replaced with a single `.` and not respected
![image](https://github.com/user-attachments/assets/61adf8c3-17d6-41b1-a97b-44ca69d5505d)

### Expected Behavior

Using the naming pattern `{Series.Title}.S{season:00}.E{episode:00}...{Episode.CleanTitle}` would return the `...` as requested

### Environment

```markdown
- OS: Win10
- Sonarr: 4.0.9.2244
- Docker Install: No
- Using Reverse Proxy:  No
- Browser: Edge + Chrome
- Database: Sqlite 3.36.0
```

### What branch are you running?

Main

### Trace Logs?

Can provide if required however seems like a code issue to me

**Comment by kingy444** [comment]
Should have added I see the same occur when I put other characters as the separator too or other text replacements (names without the .)

I want to be able to have the space between episode delimitation and episode name

I don't see why `-_-` or `-.-` or `.,.` should work but `...` or `---` or `___` get replaced with a single version of their character

**Comment by markus101** [comment]
It gets replaced because repeat characters are replaced during the renaming process. `-.-` stays because there aren't multiple of the same character in a row. `--.` should also be replaced with `-.`.

We do maintain `...` in some cases so it's not difficult for us to support that here as well when part of the naming format and not a result duplicates due to other tokens being replaced. This will only apply to `...` and not other cases.
