### ISSUE TITLE
Prioritize Download Decisions

### ISSUE THREAD

**Issue by waldnercharles** [Sonarr/Sonarr#733]
In `PrioritizeDecisions` inside of the `DownloadDecisionPriorizationService `, number of seeds has a lower priority than number of episodes & average episode size. Shouldn't this be the other way around? Or weighted?

I'm also not sure why we order by the lowest episode number either. Correct me if I'm wrong, but won't this always force a season pack to have higher priority?

Or even better yet, why not allow the user to decide the order of importance? Something like:
-- Priority
:: # Of Seeds ::
:: Season Packs     ::
:: Average Episode Size ::
:: Age of Torrent ::

(Those :: are handles for users to drag to specify the order.)

**Comment by markus101** [comment]
Yes, season packs are prioritized, I don't see that changing, though the option to exclude season packs entirely might be something we consider.

I don't see a customizable order being viable, its useful for 1% of the users, adds a lot of complexity and keeps a strict order, a weighted system would be more flexible and useful for usenet and torrents.

We've had some internal discussions about how we'd want to handle this scenario, though nothing concrete has been decided.

**Comment by waldnercharles** [comment]
I guess my question is: If I am looking for s01e03 and i find a season pack with 1 seed, it will prefer the season pack over the single episode, even if that episode has 1,000 seeds. This seems incorrect to me.

**Comment by Taloth** [comment]
Define 'looking'. Did you do an Automatic Search, or a Manual Search.
Did Sonarr actually grab that season pack?

**Comment by waldnercharles** [comment]
Automatic Search. Even if it finds 2 single episode torrents, the one with the smaller size (given a 200mb difference) will be chosen over one with more seeds.

**Comment by Taloth** [comment]
We were talking about it grabbing season packs over single eps. Not grabbing one single episode over another.

**Comment by waldnercharles** [comment]
I'm confused. The logic used for both is the same isn't it? Contained within `DownloadDecisionPriorizationService.PrioritizeDecisions`.

**Comment by Taloth** [comment]
Yes and No, the logic isn't limited to that function. That function merely prioritizes it, the rejection logic is performed elsewhere.

A season pack will only be grabbed during a season search when that season pack is an upgrade for all episodes in the season. Otherwise it will be rejected, regardless of prioritization.
It always takes precedence over single episodes for this very reason. Otherwise Sonarr might grab one  single episode which would cause the season pack to be rejected entirely, with you ending up with a single episode in your collection instead of all of them.

This is why I was asking about your example, the scenario you painted is not possible. Since I couldn't preclude a bug, I needed to know what you were doing exactly.
If you have even one episode unmonitored in the season, no season pack will ever be grabbed.
If you automatically searched for a single episode, no season pack will ever be grabbed.
If you manually searched for a single episode, you get to pick the desired release.

So if you ran into the situation where Sonarr incorrectly grabbed a season pack, you'll have to come with specifics.

Atm Sonarr will reject any torrent without seeds (if that information is provided by the indexer), there is a Github issue with the proposal to make that limit configurable. There's also a suggestion to turn the size, seed and age into a weighted system. But as markus mentioned, we're still discussing that.

**Comment by waldnercharles** [comment]
My apologies; I couldn't find the issue / suggestion for the weighted system. I also incorrectly assumed that Sonarr would pick and choose the correct files from a season pack. Thank you for the explanation.

My situation was I had an empty show that I just added (Not add & search). Then I selected it and did an automatic season search.It chose to download a season pack with 1 seeder. When I looked for the episodes myself (using my good old fashioned web browser) I found all of the episodes were uploaded individually with an average of 5-6 seeders per episode.
