### ISSUE TITLE
Series refresh triggered too often if Sonarr crashes

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#735]
Basically, if Sonarr crashes (repeatedly) it will at fairly high frequency refresh stuff, and thus hit skyhook and thexem way more often that desired. Talking about 500+ full refreshes in 24h.

A few proposed changes:
- During Scheduled refresh check the LastSync time of continuing series. This will prevent high-frequency series refreshes.
- During startup, check Command queue to orphaned tasks to detect a crash, postpone any schedule task related to that command by at least an hour. This prevents tasks such as Scene mapping updates from running too quickly.

CC: @markus101

**Comment by markus101** [comment]
I like the idea of checking the tasks table to see what was aborted and using that to offset the next schedule.

As long as a user can still force it to recheck, skipping it during an automatic one would be okay, but the drawback I see is if they update TheTVDB, then try to update a series in Sonarr that shows no changes since the skyhook cache is still active it would be skipped if the automatic refresh was triggered shortly after (which might have been long enough to have it update automatically).

**Comment by thezoggy** [comment]
but if their sonarr is crashing..they prob arent too worried about if they get delayed data.... if they want it to work as it should.. fix the crashing? seems like a fair trade.. at least better than someone banning their ip for abuse (tvdb/xem/skyhook/etc)

**Comment by markus101** [comment]
My concern is the majority of users that isn't crashing, don't let a few problematic users ruin it for everyone. I'm saying if someone refreshes manually don't punish them for that, it seems less likely that they are the ones updating one series manually, if all of them are refreshed (or at least the user tries to refresh them all), we should store the last updated, if they ask for one to refresh don't store that value.

**Comment by thezoggy** [comment]
right, forced updates is one thing.. but the problem is that your never setting your value that stuff was synced..thus each crash it starts updating.. thus the same shows get updated over and over... you could somewhat solve this by doing what we did in sb.. store the last updated at the series level.. so even if it crashes and some shows were updated.. those arent updated blindly.. thus eventually post crash.. they would all get updated.. just may be staggered.

**Comment by Taloth** [comment]
@markus101 Fixed part 1. But that's only helping us for Skyhook, not xem.

But part 2 is giving me troubles, not sure how to do that cleanly.
Atm I see this convoluted chain of events: Have TaskManager fetch the Queued and Orphaned items from CommandRepository during AppStart event (need to fetch both, coz the AppStart handler in CommandRepository may or may not have run yet) and update the ScheduleTaskRepository as needed.
It feels ugly.
