### ISSUE TITLE
Treat Downloads with Executable Files as Failed

### ISSUE THREAD

**Issue by majorrowe** [Sonarr/Sonarr#7369]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Undesirable files being downloaded eg .zipx and .lnk files

### Describe the solution you'd like

Looking for the ablility to define a list of file extensions e.g "*.zipx, *.lnk"to be blacklisted from being downloaded by the client. Recent spike in dodgy releases would make this very handy.

### Describe alternatives you've considered

Have looked at handling this at p2p client level but seems nothing avalible there either.

**Comment by bakerboy448** [comment]
Per prior comment from Markus, appears no plans for this per the issue B linked.

> Sonarr does not remove downloads that it does not handle importing for. You may be able to set something up in your download client to automatically cancel them when files with that extension are found.

**Comment by Thirrian** [comment]
Feels like something you can do in a post-process script in a download client. Or pre-process in sonarr. Just my €0.02

**Comment by Zerauskire** [comment]
> Feels like something you can do in a post-process script in a download client. Or pre-process in sonarr. Just my €0.02

Yes and no. Currently I handle this by having my torrent client ignore specific file types. In my case, the current popular thing going around are these ".lnk" files that are actually malware. They are handled by my torrent client to make sure they do not get downloaded but that only prevents it from being saved to my server. The torrent client itself still has them as an active download and Sonarr still sees it as being in progress of downloading. So it just sits there until I manually intervene. 

I could write some sort of script possibly to say that if all files are unselected for download and the torrent is just sitting there idle not really doing anything, remove the torrent. The problem here is that this only really solves half of the issue. The next time Sonarr runs through to check for missing episodes, it just goes right back and grabs all those same torrents again and the process starts over.

There really needs to be some solution within Sonarr to make sure that these are not grabbed again. I really wish I had the answer for how this could be approached but I do not.

The only method I can think of personally would be to check what files are contained in the torrent. If there are no valid video formats like mkv, avi, mpg, etc... then there really isn't any reason to download that torrent and it should be blocked from downloading again. At least for a short period of time. 

Maybe as part of that option there could be a secondary option to allow or disallow compressed files. Maybe in your personal use, you don't run across files being compressed so you don't even want those file types to be seen as valid. I can't speak for that part though. In my personal experience I just don't come across compressed video files. I'm fully aware that others do though. So this could by an option to just allow them or not based on your use case.

Another potential apporach to curb some of these might be to implement an option to have Sonarr only search for episodes within so many hours or so after an episode was scheduled to be released. What i'm seeing as a common trend for this is that people are uploading these malware torrents using episodes that haven't even aired yet. Sonarr then grabs them because they are really the only option. Then the next day, they are again the only option so they get grabbed again.

**Comment by klueman** [comment]
@Zerauskire According to other posts on this topic, the response to this seems to be that if you're using a public tracker, they don't care if it breaks Sonarr for you. Which is, to say the _very_ least, disappointing. It's unlikely they'll do anything.

There's a few people working on tools to address this issue.  [cleanuperr](https://github.com/flmorg/cleanuperr) is one. That's probably the best bet going forward.

**Comment by markus101** [comment]
This issue was triaged and remains open, if this was something we weren't going to do it would already be closed.

**Comment by sdembis** [comment]
@markus101  This has been showing up for quite some time now, so a solution incorporated into Sonarr or a how-to workaround for download clients, etc., would be greatly appreciated.  Interesting enough, these particular downloads show as 'shortcut' and the shortcut links to 'command' (cmd) in Windows System 32.   Thanks for all your great work.

**Comment by polaroidkidd** [comment]
I've started noticing that some downloads are folders, which then contain the `.lnk` files, but the folder name itself ends in a `.mp4`, or some other commonly valid ending.

```
some-documentary.mp4
    some-documentary.mp4.lnk
```

unfortunately the current block-list assumes the folder is a valid file and doesn't check the contents any further. Has anyone else been able to mitigate this somehow?
