### ISSUE TITLE
Add ability to move&continue seeding torrents instead of copy/hardlink

### ISSUE THREAD

**Issue by gurabli** [Sonarr/Sonarr#738]
I recently migrated from Flexget to Sonarr, and now with Jackett, it is doing the job very nice.
Flexget is really powerful when it comes to customization, but now Sonarr is keeping up nicely with major functions already supported. What is really missing is the move downloaded torrent and continue seeding, without copy or hardlinking. 

As series name and season number are available for Sonarr with adding a tv show, it could be done the way like this, and pass these to the download client (I think Deluge is the best choice here, it handles these things exceptionally good).

An option like: Move downloaded torrents to 'download location{Series_name (from rage or tvdb)}{Season ## (from rage or tvdb)}

Example.Show.S02E02 would be moved and continued seeding at 'custom path'\Example Show\Season 2'

It is working excellent in flexget with Deluge the best, and in Transmission too. It doesn't need to be available for all download clients, if Deluge and Transmission is supported, it is already great. 

Lot's of us would like have this implemented, I'm sure, and woul also let us have proper folder structures (without hardlinks) and keeping torrents alive as they could be left to seed infinite time.

**Comment by markus101** [comment]
I don't see this being something we want to support, it only works for people that aren't renaming files, which I suspect is a lower percentage of our overall users, a 1% feature as we call it as well as people with a remote torrent client (seedboxes).

Obviously copying isn't ideal for long term seeding, but what is the concern with hard linking? Why isn't it sufficient?

**Comment by gurabli** [comment]
Hardlinking is fine, no problems with that, and on Linux it is working really nice. 
What I suggested is a great feature imho, but really not necessary one. I though it is rather easy to implement, as getting the series name and season number from rage/tvdb is something actually Sonarr already does, the move when done (downloading) could be just a slider to turn on or off, Deluge is very flexible with this.

Interesting to see that renaming is so frequent, as most of us I believe are using scene releases for tv shows, in that case I don't see the point of renaming, as Kodi, Plex, Emby, etc fully support proper scene naming. Obviously, I was wrong with my assumption. 

Just curios: if Deluge stops seeding the torrent, as it reached the seeding goal/time, and hardlinking is used, will it move after seeding is over, and do this automatically?

**Comment by markus101** [comment]
> Just curios: if Deluge stops seeding the torrent, as it reached the seeding goal/time, and hardlinking is used, will it move after seeding is over, and do this automatically?

It doesn't need to move it if its already hardlinked. If you have Remove Completed Downloads enabled in Sonarr it will tell your client to delete it.

**Comment by gurabli** [comment]
Thanks markus101 for clarifying this. If you think, you can assign a low priority feature request to this, and if someone feels later on to implement moving&seeding, maybe we will see this feature once in Sonarr.

**Comment by Terebi42** [comment]
@markus101 Could you elaborate on why this is a 1% issue?  I'm not sure I understand why people are using the rename feature so much. plex/kodi/etc all seem to handle scene and p2p naming just fine? other than OCD types, what is the use case for renaming? Are you collecting telemetry on how many users are actually using the rename feature? 

The problem with hardlinking is that there is no way to delete all the hardlink copies in one go. You have to delete it from the download directory, and go delete it from the sorted directories too.

Also, the download directory becomes huge, so any interaction you are doing with it becomes a PITA because you are filtering through many hundreds of files. 

Perhaps a different way to solve this issue would be when sonarr detects that the copy has been deleted (which is already in place and in use for stop monitoring) then an option to remove from client and delete from the original download location?

**Comment by markus101** [comment]
Its based on the number of people that have requested this feature/interaction with users, we don't have any specific numbers (though its something we'd love to have). Inconsistency in how files are named is a big reason, when things don't sort in

> The problem with hardlinking is that there is no way to delete all the hardlink copies in one go. You have to delete it from the download directory, and go delete it from the sorted directories too.

That probably depends on the OS, quick search for Ubuntu resulted in: http://linuxcommando.blogspot.ca/2008/09/how-to-find-and-delete-all-hard-links.html

> Also, the download directory becomes huge, so any interaction you are doing with it becomes a PITA because you are filtering through many hundreds of files.

Wouldn't you just do that in the client? Transmission has a basic filter for torrent names that makes it trivial to find it.

> Perhaps a different way to solve this issue would be when sonarr detects that the copy has been deleted (which is already in place and in use for stop monitoring) then an option to remove from client and delete from the original download location?

I see this being a source of pain to troubleshoot, the people that understand what it really does vs the people that enable it because they can is probably quite different.

**Comment by bobbintb** [comment]
I think it would be interesting to get some data on the number of users that use renaming vs the number of users that don't because I would really think the number of users that actually use the renaming feature is in the minority.

Personally, I would like this feature as hard linking is not an option for me due to technical limitations of my server and as I seed many things indefinitely, I either have to waste a huge amount of drive space (I'm talking TB) or a huge amount of time babysitting and cleaning up after an automated system. I get that that the renaming issue would pretty much make this impossible. A solution to that could be simply notifying the user that renaming will be automatically disabled when the feature is turned on and doing so. Then implementing the move command to the supported client would be all that is needed.

**Comment by Taloth** [comment]
https://www.reddit.com/r/sonarr/comments/4lsk6k/finished_file_handling_question

**Comment by murbancic** [comment]
I just set up Sonarr this week coming from Flexget and would love this feature.  I am not concerned with my file name syntax being 100% identical as long as Plex can grab it all which I have yet to have an issue with.  Avoiding duplicating files and wasting space while still maintaining the seed is very useful, especially when downloading from a private tracker and trying to maintain a higher ratio.
The advantage I see over the hard link as after I reach my desired ratio, the torrent pauses or deletes and the show is already where it needs to be keeping my downloads folder organized and my torrent downloader display less cluttered.

**Comment by bobbintb** [comment]
Thankfully my NAS now supports hard links so this isn't an issue for me anymore. I still thinks it useful though. I can achieve the same result but it requires a lot of effort and scripting from the torrent client.

**Comment by jeramie72** [comment]
yea i just installed sonarr today and was disappointed to find out that it didn't either download to the correct folder initially (what i thought it would do (or am i doing something wrong?)) or move it (not copy, thats silly imho) and keep seeding. i use plex as well, no need to rename.

**Comment by christofferb** [comment]
+1 for this feature. Only thing stopping me from leaving Flexget.

**Comment by fent** [comment]
> hard linking is not an option for me due to technical limitations of my server and as I seed many things indefinitely

What's the issue here? I usually seed things indefinitely too and have had no trouble with hardlinks.

> I don't see this being something we want to support, it only works for people that aren't renaming files

I think torrent clients, at least Deluge and Transmission, allow renaming, even for individual files in multi-file torrents.

**Comment by bobbintb** [comment]
> > hard linking is not an option for me due to technical limitations of my server and as I seed many things indefinitely

> What's the issue here? I usually seed things indefinitely too and have had no trouble with hardlinks.

My NAS didn't support hard links at the time I wrote that but it has since been added.

**Comment by bagobones** [comment]
Current flexget user who has used both Transmission and Deluge. Both support move and renaming without breaking seeding via their APIs. Not underlying file system or OS dependency on linking etc or need to shift data around you just download into your ideal path and your done, if a file is poorly named you correct it via the client, and it still continues to seed.

**Comment by qtv** [comment]
I am surprised this has not been implemented yet. Would be immensely beneficial in cleaning up directories by not requiring a pointless downloads folder that's only used for seeding. Plenty of people don't rename.

**Comment by Cr4zyy** [comment]
Would also love this feature to be added, All my TV media gets stored on another drive from where I download, so hardlinking isnt an option and having to store stuff on the drive that i download too wont work out as it's a smaller and fuller drive.

**Comment by Cr4zyy** [comment]
I made a simple Bash script to do this for me with Sonarr and Transmission on Ubuntu, maybe it will help others out if they come across this issue. https://github.com/Cr4zyy/Sonarr-Transmission-Fixer

**Comment by Jeremydavisvt** [comment]
+1'ing this feature. I use plex with this, and constantly am running into duplicate episodes/lots of wasted space, and I'd rather have completed tv show episodes not clogging up my Downloads folder. The devs seem to cater to those that like organization, but in my opinion, _not_ having this feature makes folders more disorganized.

**Comment by Karmalakas** [comment]
I have same duplicates problem on Windows. Have read https://forums.sonarr.tv/t/sonarr-keeps-copying-files/6536, but no help at all. Also can't figure out where to find this "Downloaded files handler" to turn it off. Was thinking why Sonarr can't have hardlinks the other way around? Not trying to change the seeded files so these would link to copies, but create hardlinks in Series folder to link to downloaded/seeded files?

**Comment by markus101** [comment]
Due the complications of supporting this for all clients as well as dealing with RAR releases/upgrades/etc this is not something we're planning to support at this time, tagging for a possible reevaluation later.

**Comment by Arzte** [comment]
Would a feature like this need to support all clients to be added? (asking for clarification, as @gurabli originally only asked for deluge/transmission)

**Comment by gertab** [comment]
+1 for this feature.

**Comment by markus101** [comment]
We've revaluated this issue and determined it is not something we have plans to add. Upgrades (propers, qualities, languages, preferred words, etc) along with being unable to rename files (which has impacts on other apps consuming the files) make this extremely complicated. Custom Scripts can be used to achieve this behaviour if someone is inclined to do so.
