### ISSUE TITLE
Duplicate downloads with different download clients

### ISSUE THREAD

**Issue by ipsq** [Sonarr/Sonarr#748]
I recently noticed that my Sonarr was sending the same episode multiple times to Deluge. This resulted in a lot of unmanaged downloads:
https://www.dropbox.com/s/09o726zms49sdfw/Schermafdruk%202015-08-18%2012.52.58.png?dl=0

This is what my deluge looks like:
https://www.dropbox.com/s/45k9nmzt3iho2qq/Schermafdruk%202015-08-18%2012.53.13.png?dl=0

Both are completely out of sync.

In the logs it keeps saying:

```
Message
Couldn't add report to download queue. The Simpsons S26E03 Super Franchise Me 720p WEB-DL x264 AAC: The request timed out

Exception
System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
  at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) [0x00000] in <filename unknown>:0 
```

**Comment by ipsq** [comment]
It's easy to spot the ones not managed by Sonarr since they all have no label assigned to them.

**Comment by ipsq** [comment]
Is it better to use Blackhole for now?

**Comment by ipsq** [comment]
I did some research and it seems the connection between Sonarr and Deluge is not really reliable. When Sonarr makes a call to a Deluge endpoint and times out, Sonarr marks that as a fail whilst Deluge did in fact pick it up. Maybe a check afterwards or something similar will do the job. As it is now, I'm trying to get Blackhole to work.

**Comment by markus101** [comment]
Please use the forums for support.

> When Sonarr makes a call to a Deluge endpoint and times out, Sonarr marks that as a fail whilst Deluge did in fact pick it up. Maybe a check afterwards or something similar will do the job. 

That appears to be the case, Deluge should respond instead of letting the call timeout. Checking to see if the torrent really went through when Deluge fails to respond shouldn't be something Sonarr ever needs to do and something I don't see us doing.

> Is it better to use Blackhole for now?

I wouldn't recommend it, I would recommend troubleshooting deluge further to see why its failing to respond or switching to another supported client. Blackhole isn't designed for continued seeding after import (it moves the files instead of copying or hardlinking).

If you have any more issues please open a thread on our forums.
