### ISSUE TITLE
Allow symlinks in addition to hard links to add downloaded files to media library

### ISSUE THREAD

**Issue by GNUGradyn** [Sonarr/Sonarr#7505]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I seed my downloads indefinitely, so I am currently forced to pick from the following options:
* Default (just copy, no hard links):
This results in 2 copies of my entire massive library
* Hard link on, rename on:
This option honestly may as well not exist. The rename may fail due to filesystem locks, and even if it works it will stop the file from seeding since the name has changed, at which point you may as well just have moved the file because the download server no longer knows where it is
* Hard link on, rename off:
This option sorta makes hard links make sense, but you're stuck with the default file name for the media which may confuse your media server and sucks if you are a nut about organizing your library

It's kinda a lose-lose-lose situation so I propose a fourth situation that is the best of all the worlds. 

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/5e3aa0af-6ca4-4882-a27b-851c314e6092)
Add an option here to do symlinks. I'm not entirely sure what the UI would look like because it would need to be either of the checkboxes or neither, not both. Maybe a [Copy | Hard Link | Symlink] dropdown and a warning under the rename setting that just mentions it will do nothing in symlink mode. 

This would be the optimal solution because it would allow you to just download the file to your downloads folder like normal and create a link with another name back to the downloads folder. This is the best of all 3 worlds - you only have 1 copy of every file, it is named as the download client expects it, and the link is named as the media server expects it (or however you want it to be named).

### Describe alternatives you've considered

Most download servers support downloading directly to a different destination. This would be better then having 2 copies but you'd still be stuck with the original directory structure and file names. Having an option to just move the file instead of copying would also make sense if you don't intend to seed but for those of us who intend to seed it's really the only good answer

### Anything else?

Not sure how many people are running sonarr on windows but there should probably be a check for windows users to make sure symlink support is enabled as it is disabled by default to this day

**Comment by markus101** [comment]
> Hard link on, rename on:
> This option honestly may as well not exist. The rename may fail due to filesystem locks, and even if it works it will stop the file from seeding since the name has changed, at which point you may as well just have moved the file because the download server no longer knows where it is

If you think there is no reason for this to exist then I don't think you understand how hardlinks actually work. Yes, filesystem locks can prevent the hardlink from being created, but this is largely a Windows-only problem where locks actually exist. 

Renaming a hardlinked file does not alter the original file/name in any way shape or form, if you alter the contents of the file then yes the file is altered, but altering the source of the symlink would do the same thing. "This option honestly may as well not exist." is co

> Hard link on, rename off:
> This option sorta makes hard links make sense

Only if you want to keep original file names for some reason, because renaming has no impact on hardlinks.

The one downside of hardlinks is they must be on the same volume, but with disk merging software that supports hardlinks it works across physical disk boundaries.

But in a proper setup that allows for hardlinks there is zero downside to them, whereas symlinks would only have downsides in comparison because maintaining the original file with a symlink, with the same name is vital for its functionality.

> Most download servers support downloading directly to a different destination. This would be better then having 2 copies but you'd still be stuck with the original directory structure and file names. Having an option to just move the file instead of copying would also make sense if you don't intend to seed but for those of us who intend to seed it's really the only good answer

People already do this, Sonarr will not download to the directory for the show for many reasons, but being stuck with the original structure is one of them.

> Not sure how many people are running sonarr on windows but there should probably be a check for windows users to make sure symlink support is enabled as it is disabled by default to this day

Prior to Windows 10 Insiders build 14972 administrator access was required to create them, but for the majority of users prior to that it likely involved a UAC prompt as they were granted it through the Administrators group.

We have no plans to support importing via symlinks because it introduces another level of complexity that many users do not understand and we'll continue to strongly suggest users operate with a system that supports hardlinks and atomic moves.

To understand hardlinks and set up your system we suggest following Trash's guide on the subject https://trash-guides.info/File-and-Folder-Structure/Hardlinks-and-Instant-Moves/

If there is a reason you can't use hardlinks and absolutely want symlinks (and understand the caveats) then maybe an Import Script (Settings: Media Management: Import Using Script), would be more appropriate for your setup, but there are only a handful of people using that functionality so support/documentation is severely limited.

**Comment by fryfrog** [comment]
As someone who [used to do symlinks](https://gist.github.com/fryfrog/65e3e0e9ae45af694aa86c1e713fa889), they're awful. But if they're your one true love, you can make it work by adapting my old script for it.

Fair warning, there's no *good* way to do them. If you let the real file live in the library and the *link* in the torrent folder, when sonarr/radarr upgrade it breaks the link and the torrent. If you go the other way and put the real file in the torrent folder and the link in the library, you won't know when the torrent isn't needed anymore.

A hard link setup solves all of this and is worth re-working your system to support them, I know because I used symlinks for *years* and finally bit the bullet and re-worked my setup of zfs datasets to do it "right". Good luck, hopefully we see you on Discord to get help fixing yours!
