### ISSUE TITLE
Non-recursive or direct manual import of series

### ISSUE THREAD

**Issue by Pavlogal** [Sonarr/Sonarr#7507]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sonarr failed to import some files upon torrent completion, so I went to do it manually. The problem is that currently the only way to do it is to go to Missing and scan the whole folder that the files are stored in, **recursively**. This is not a problem if it's a whole season download since you can just select that folder instead, but for single episodes it's an issue because those files are all getting placed in the same downloads directory, so scanning it means also scanning basically everything you ever downloaded...

### Describe the solution you'd like

I would like to have a toggle for manual imports that says "non-recursive" so that it would only scan the directory I chose and none of the subdirectories. Obviously if I have a lot of single-episode downloads it would still take a while but it would still be way quicker. Also the ability to just import a single file instead of having to scan a whole folder would be very welcome. Maybe even place such a button next to each episode in the series, next to search and interactive search.

### Describe alternatives you've considered

A different solution would be to autocreate a folder for each series in the downloads folder. So then every single episode will be downloaded to that subdirectory and thus segregated from everything else. I am not sure if there is a way to do this in qBittorrent natively, currently I can only select one directory per category.

**Comment by augustuen** [comment]
>A different solution would be to autocreate a folder for each series in the downloads folder. So then every single episode will be downloaded to that subdirectory and thus segregated from everything else. I am not sure if there is a way to do this in qBittorrent natively, currently I can only select one directory per category.

Sonarr doesn't touch your downloads folder, so that would have to be done by qBittorrent. qBittorrent can do that by setting `Torrent content layout` to `Create Subfolder`. 

Alternatively, you can use a post-import category, with different folders set for the two categories. Then the un-imported folder would be basically empty.

**Comment by markus101** [comment]
In this case Sonarr doesn’t process all files because there are more than 50 (IIRC) files in the folder it’s processing and they do not belong to the same series, but it would still display them.

At this time we’re not going to add an option, but I would suggest that you follow @augustuen’s suggestions
