### ISSUE TITLE
Use English Alias when searching newznab indexers

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#753]
Mostly an anime problem, but if there are aliases for other languages we should only use the english alias when searching newznab indexers (since we only use one).

**Comment by thezoggy** [comment]
per xem chat, apparently that its not so black and white which name to use.. `you need the japanese name on top to find the japanese release names`

**Comment by NMe84** [comment]
Using the English alias would be a bad idea. Most anime in XEM uses the English title that TVDB uses as a main name and a main Japanese alias for making releases work. If anything, anime should use the Japanese name instead, but that would in turn break the non-anime shows or those anime shows that happen to have been made differently.

If you can't search on all different names, using the first alias like you do now is probably a lot safer because I can't remember the last time I've seen the most important alias not being at the top.

**Comment by markus101** [comment]
Meant to close this before.. searching by multiple aliases is still valid.
