### ISSUE TITLE
Season Search for daily shows

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#755]
Doesn't appear to work and may be searching for the actual season number, which would be obviously wrong. Need to determine why its not working and see what we can do to fix it.

We may be able to search for a full season on newznab using partial episode matches, but mileage may vary.

**Comment by thezoggy** [comment]
yeah, 'daily' shows are searching by season using the wrong data.. tries to do season # instead of the YYYY. 

auto/manual search works:
`https://api.dognzb.cr/api?t=tvsearch&cat=5030,5040&extended=1&apikey=<removed>&offset=0&limit=100&rid=5714&season=2014&ep=09/25`

season search doesnt:
`https://api.dognzb.cr/api?t=tvsearch&cat=5030,5040&extended=1&apikey=<removed>&offset=200&limit=100&rid=5714&season=19`

now there is the issue when a season spans across multiple years.. which year do you use/search for each year?

its been awhile since ive used sb with daily shows.. so im just going off reading the source code / memory.. will have to spin up an instance to confirm.. 
when sb does its season search, it does `&season=2010&q=2010.03` so you get stuff for that 'season' but limit the scope to the month.. thus it can fit within the 100 limit result (x limited pages needed to go through).
