### ISSUE TITLE
Series update info & scan disk

### ISSUE THREAD

**Issue by jamesfairhurst** [Sonarr/Sonarr#765]
I sometimes delete an entire show folder after watching if I don't want to keep the files but still want Sonarr to grab future episodes (i.e. the next season). 

After deleting a show folder and clicking the "Update series info & scan disk" I expected the series to be updated and reflect the fact the files are no longer there. Instead the episodes remain green and the log shows:

    MetadataService - Series folder does not exist, skipping metadata creation

Not a bug per se but thought I'd report it. Thanks for the great app!

**Comment by markus101** [comment]
This is intentional behaviour, if the root folder (parent of the series folder) or the series folder is missing, Sonarr will not rescan the directory, this is to deal with volumes that have been unmounted temporarily as Sonarr would treat all the files as missing. A few options to work around this:

1. Delete the contents of the folder, not the folder
2. Delete the files from Sonarr (from the series details page)
3. Enable Create Empty Series folders in Sonarr (Advanced Media Management option) - this will have Sonarr recreate the folders and subsequently scan the contents.

**Comment by CaptainRewind** [comment]
I'd call this a bug. Sonarr should mark any episodes as missing when the parent folder does not exist. None of the 3 options you propose solve the problem of Sonarr misreporting that a file exists when in fact it and its parent folder have been deleted.
