### ISSUE TITLE
Ability to execute a script before import (Pre-import script)

### ISSUE THREAD

**Issue by sea3pea0** [Sonarr/Sonarr#791]
Would be great if sonarr was able to use Syncthing's API to determine when a synced folder has finished so it can scan for files to import at that time. It seems both Syncthing's and BTSync's api could be used to easily determine that info. Since Syncthing is open source it would probably be better to go that route over BTSync. Could there just be an option to have sonarr make an api call to syncthing before running downloaded episodes scan to see if files are still syncing or not? [Here](http://docs.syncthing.net/dev/events.html) is Syncthing's API.

This would be great for those systems that don't support an SSHFS mount.

**Comment by markus101** [comment]
Not the first time this idea has come to mind, but if we allowed a custom script to be executed before import then the user could check the file for issues (like nzb2media) and in this case check the progress of another app.

We'd need to return a couple different possible values to determine whether or not it should be imported, something like:

- Okay
- Failed
- Wait

**Comment by ptr727** [comment]
This would be useful to me as well, see https://forums.sonarr.tv/t/processing-media-file-after-download-but-before-import/16133

**Comment by l3uddz** [comment]
**Describe the problem**

When using docker, hard linking becomes problematic, this would provide a possible solution to that.

Ofcourse this is only beneficial to users who are not able to have their download/import folders on the same volume.

**Describe any solutions you think might work**

Add another web hook event, OnDownloadCompleted.
This web hook would send everything the onDownload event sends (e.g. sourceFilePath of the file that WOULD/WILL be imported, the relativeImportPath of where the file should be imported).

The web hook receiver running on the host system, would then hardline the file to the destination and send a response to the web hook request, e.g.

HTTP 200 = File was hard linked, this would allow sonar to check for that response from the web hook event, if it was 200 response, check if the import destination exists, if it does, consider the import complete.

HTTP 501 = Hardlink failed, thus telling sonar to act normally and try to import as it usually would.

**Comment by RyanEwen** [comment]
I've been looking for a way to automatically FTP or SCP files from a remote download server upon completion. Seems like this is the feature needed to do this. 

Currently I mount the remote download directory using curlftpfs (sshfs was slow), but I don't like this much, especially since sonarr is running locally from within docker and the FTP mount directory may go down or may not be connected before the container is up, causing weirdness.

**Comment by drgroot** [comment]
a preimport script will be very useful. I need to do special prep work on the target directory before sonarr imports it. it becomes problematic with unionfs and what not without this.

**Comment by JeWe37** [comment]
> Not the first time this idea has come to mind, but if we allowed a custom script to be executed before import then the user could check the file for issues (like nzb2media) and in this case check the progress of another app.
> 
> We'd need to return a couple different possible values to determine whether or not it should be imported, something like:
> 
>     * Okay
> 
>     * Failed
> 
>     * Wait

So I took a look at the code and going by how webhooks are implemented as an entirely parallel process with no current way of signalling back to Sonarr what to do, it might be more practical to simply add another import type, alongside move, copy and hardlink(shown a little differently in the UI, but that's what it amounts to internally), which instead calls a script with whatever data it has at that point(might be best to make it an advanced option). No other hooks return values matter so far, having one where it does seems rather inconsistent.

Effectively you would have a checkbox in the UI to do custom imports and then be able to specify a command to run. That would be provided with the required environment variables, similar to script integrations, and take care of the import instead of Sonarr. Nonzero return codes would amount to an import failure, during the scripts runtime it shows as importing.

I might look into doing a PR for that at some point, but I'd like to gauge whether that approach would be viable and if the core team(@markus101) agrees, as I don't exactly have an overview of the code base as it stands.

**Comment by markus101** [comment]
Nothing exists currently for hooking back to Sonarr because so far nothing has needed that functionality, but what you're saying makes sense, it's outside of the scope of other connections, though could potentially live in the same area of the UI.

As described I think your approach seems reasonable for the most part, but a few things things to consider
- supporting multiple scripts
- allowing the script to tell Sonarr to deal with it, either via a specific exit code or environment variable (the latter being able to communicate errors more effectively)

@Taloth and @Qstick might have their own thoughts.

**Comment by JeWe37** [comment]
So I've been working on this a bit. The config/frontend side should be done and I have a plan for what to do. Basically `EpisodeFileMovingService` and `ExtraFileManager` have all the information that needs to be provided to the scripts and access to the config, therefore they would be the logical place to integrate this. In order to actually execute the script though, I need a reference to the `ProcessProvider` that's created all the way up in `NzbDroneRunner`. I have been digging through references, but in all honesty, I have not been able to find how to pass it down the object graph into the `EpisodeFileMovingService`/`ExtraFileManager`. Do you happen to have a hint as to how these variables are passed down?

One potential concern I have come across: If one uses the script to do a remux whilst copying(as would be a natural application) it is possible that a rescan and rename is required afterwards in order to get everything into sync. Should I consider that out of scope(seeing as the script could always just call these via the API if it needs to) or should support be directly integrated into Sonarr itself? Say via a special return code, similar to the return code for telling Sonarr to handle the file that has already been proposed.
