### ISSUE TITLE
unable to parse episode from filename -- cartoons

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#866]
unable to parse ep from filename s##.e##:

![sonarr138](http://zoggy.net/sonarr138.png)

ep are out of tvdb's ep range.. thus was expecting a different error.. not one it couldnt parse.

**Comment by thezoggy** [comment]
some more anime/kid shows bad naming:
![sonarr137](http://zoggy.net/sonarr137.png)

**Comment by thezoggy** [comment]
and more
![sonarr136](http://zoggy.net/sonarr136.png)

**Comment by Taloth** [comment]
First one already fixed earlier.
Second one is picked up by anime regex due to [Pixar], don't think we can fix that without the advanced parser.
Last one is problematic, coz atm Sonarr doesn't support this format (without series title) at all. (see https://github.com/Sonarr/Sonarr/issues/585 for something similar)

Can we close this?

**Comment by thezoggy** [comment]
sure
