### ISSUE TITLE
Duplicate Download

### ISSUE THREAD

**Issue by supick** [Sonarr/Sonarr#888]
Hello, I'm new user and I'm sorry if this is noob question. Could you please check below log, I have no idea why Sonarr delete good quality episode and grab low quality episode instead

RssSyncService	Starting RSS Sync	2:30pm
SceneMappingService	Updating Scene mappings	2:28pm
RssSyncService	RSS Sync Completed. Reports found: 110, Reports grabbed: 1	2:15pm
DownloadService	Report sent to UTorrent. Arrow S04E04 720p HDTV X264 322MB PAHE	2:15pm
DownloadDecisionMaker	Processing 110 releases	2:15pm
RssSyncService	Starting RSS Sync	2:15pm
RecycleBinProvider	Recycling Bin has not been configured, deleting permanently. C:\TV\Arrow\Arrow.S04E03.720p.HDTV.X264-DIMENSION[rarbg].mkv	2:04pm
RssSyncService	RSS Sync Completed. Reports found: 11, Reports grabbed: 1
DownloadService	Report sent to UTorrent. Arrow S04E04 720p HDTV X264 322MB PAHE	2:00pm
DownloadDecisionMaker	Processing 11 releases	2:00pm
Rarbg	Rarbg The request was aborted: Could not create SSL/TLS secure channel.	2:00pm
RssSyncService	Starting RSS Sync

![untitled](https://cloud.githubusercontent.com/assets/8292690/10668313/e82f6734-7905-11e5-9345-61bfd2d8aa07.jpg)

**Comment by markus101** [comment]
Please use the forums for support.

Based on the logs Sonarr didn't grab S04E03, but S04E04, but given the number mismatch it shouldn't have been imported automatically (assuming you're on the latest version of Sonarr). Without debug logs of the grab and import we can't say why it was grabbed (though I suspect the grab is because there wasn't an existing file).
