### ISSUE TITLE
All migrations are executed when testing a lower migration

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#902]
Right now if you're testing migration 75 the data in injected before migration 75 runs (as we want), then the migration runs, but all remaining migrations run, if there is an expectation in migration 80 that the data in test 75 didn't add migration 80 will fail and the test will fail due to the migration failure.

We should try to prevent any further migrations from running in this case.

**Comment by vawen** [comment]
I modified DBTest to stop migration in a given version, but still the test fails due to required attributes missing on the Series table (TvMazeID, migration 94).

This point is harder to solve in since I don't see a way to preserve DataObjects to the state in a given version.

I only see two possible solutions:
- Check DB directly with SQL (don't know if it is even possible).
- Modify initial DB to a valid state.
