### ISSUE TITLE
Support using season number from season folder when renaming/importing

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#903]
We should be able to parse this format: `Season {season:0}/{episode:00}` (iTunes style), so we should allow users to be able to set it as their naming pattern and then they can disable Season Folders at the series level.

**Comment by i-c** [comment]
It might also be useful to have an advanced option to use something other than 0 (e.g. "treat season 99 as specials" or whatever).

This would be for people who organize their files by putting them into iTunes, since it specifically doesn't let you you use 0 for a season number. (If you set that it just saves it as a blank and dumps the given files into the series folder.)

**Comment by markus101** [comment]
I think the usefulness of that is far out weighed by it being an ugly work around. I don't see that being something that we would want to support, I think thats an issue that iTunes should support if they choose to, but thats outside of what Sonarr should handle.

**Comment by markus101** [comment]
Similarly Sonarr should be able to import from a release that excludes the season number in the file name.

**Comment by Lonli-Lokli** [comment]
So is there any ETA for this feature? Thanks!

**Comment by markus101** [comment]
You're almost never going to get an ETA, it'll be done when it's done. In the mean time use manual import.

**Comment by Kedryn** [comment]
@markus101  i think you misunderstood the problem in #5749, when you closed it.
It has a little to do with this issue. It was about epside mapping that changes when new episodes without season number are downloaded.
