### ISSUE TITLE
Poorly named multi episode file not properly imported

### ISSUE THREAD

**Issue by M0UL** [Sonarr/Sonarr#905]
multiepisodes file names like RWBY.S01E02E03.1080p.BluRay.x264-DeBTViD are geting imported as a single episodes.
http://prntscr.com/8x0m1e
http://prnt.sc/8x0lps

**Comment by markus101** [comment]
Could you post the full `Source Path` from the import event, I suspect that will help us most in determining the cause.

**Comment by M0UL** [comment]
here is the source path: http://prntscr.com/8yvjkn

**Comment by markus101** [comment]
`rwbys01e02e031080-debt.mkv` is one terribly named episode, it failed because there is no separation between `e03` and `1080`. This is a challenging issue because while we will fallback to using the folder name when there is only one episode in the release, falling back in this case could cause issue if there is more than one valid (non-sample) file.

**Comment by markus101** [comment]
The actual file name is too shitty to deal with, but parsing/processing improvements overall will likely help here.
