### ISSUE TITLE
Add Series with implicit year in name

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#918]
If the directory name has an year appended we should search tvdb without the year, and filter the results based on premiere year.
That way we can automatically import existing series when the user likes to keep the year appended to the folder even if the series title is unique.

On a second note, consistency would suggest that we also add an renaming option that forces the year to be appended to series title in the the renamer. perhaps {Series TitleYear}

**Comment by markus101** [comment]
Should we do this in Skyhook? We probably want to support searching fallback to using the Skyhook DB, which this would fit quite well in as well.

**Comment by h0bd0b1in** [comment]
Ignore me if I'm being silly but surely this should be something easy to implement? A simple if statement could handle this, right? Search as normal, if results return nothing, omit the year, search again.

Or is it more complex than that?

(Asking because all of my series have years appended to the folder name :P)

**Comment by joshgx** [comment]
Just wanted to bump this. Awesome work fellas. I use implicit names in my series names as well. Its the OCD in me :D

**Comment by Foebik** [comment]
I wouldn't mind seeing the option to add the year into the series folder name as part of the renamer process. I can think of 3 shows of the top of my head ( I know there are others) that if this was an available option I wouldn't have to manually fix them every time they got imported into Plex.

Doctor Who 2005
Travelers 2016
Poldark 2015

When the series folder has the year, it finds the correct meta data no problem in Plex. But if it doesn't, I have to fix it for every show.

**Comment by markus101** [comment]
@Foebik there is a separate issue for that https://github.com/Sonarr/Sonarr/issues/393

**Comment by voltagex** [comment]
I actually need the reverse, where the series year is *not* in the path.

**Comment by markus101** [comment]
Skyhook will also look for the series without the year, filtering out any duplicate results.

**Comment by aaronth07** [comment]
I'm having the same issue, all of my TV show folders are named "TV Show Name (Release Year)", but I cannot find a way to have sonarr create the TV show folder with the release year in the title. "{Series Title} ({Release Year})" does not work because instead of it showing up as "TV Show Name (Release Year)", it instead shows up as "TV Show Name ()". The only fix I have found is to add the TV show in with the incorrect naming scheme (and let it create a folder with the incorrect name), then correct the TV show path to the correct TV show folder (with the correct name). This however is not a solution and I would like to see a way to add the release year into the folder name.
