### ISSUE TITLE
Language parsing misinterprets release as French

### ISSUE THREAD

**Issue by Halfwalker** [Sonarr/Sonarr#938]
Some releases being blocked because they're misinterpreted as French when English is wanted.  For example :

 Manhattan.S01E13.VOSTFR.720p.BluRay.x264-PR0

**Comment by delphiactual** [comment]
VOSTFR is english with hardcoded french subs...

**Comment by Halfwalker** [comment]
French subs are there, but can be disabled just fine.  Checked in VLC and XBMC/Kodi.

**Comment by markus101** [comment]
Some discussion here: https://github.com/Sonarr/Sonarr/issues/280

This is because Sonarr has no way of knowing whether its hardcoded or not and errs on the side of it being hardcoded, this behaviour won't be changing unless Sonarr treats subtitled languages separately from audio languages and has a reliable way to do so.
