### ISSUE TITLE
Files/Folders leftover after download and move process occurs

### ISSUE THREAD

**Issue by Drewster727** [Sonarr/Sonarr#982]
I'm regularly running into an issue where randomly sonarr will leave behind files/folders even after it has moved the video file over to the proper television series location. It does not *always* happen, it seems to be somewhat random. Sometimes the folder contains samples and that's all that is leftover, but I've since fixed that by having SABNZBD remove samples. However, this issue still regularly occurs. I'll see the show/file in the series folder, but the "Completed" folder and video file are still sitting there and don't get removed.

I've turned on debug logging and tried to see if I could find anything out of place but I don't see it complaining about being unable to delete the folder/files after copying.

Any ideas? Thanks.

**Comment by markus101** [comment]
Please use the forums for support.

We'll need to know more details about your setup, which version of Sonarr, which OS and how files are stored when downloading and moved to.

Sonarr won't remove a download that still has a valid video file or a RAR file, but moves the video video instead of copying for usenet downloads.

**Comment by Drewster727** [comment]
Gotcha. I will post on the forums. Thanks!
